In [1]:
import pandas as pd
from pathlib import Path

POSITION_PATH = Path("../data/processed/9558/position.parquet")

position = pd.read_parquet(POSITION_PATH)

print("Shape:", position.shape)
print("\nColumns:")
print(position.columns.tolist())

print("\nFirst 10 rows:")
display(position.head(10))

print("\nUnique drivers:", position["driver_number"].nunique())

print("\nRows per driver:")
display(
    position.groupby("driver_number")
    .size()
    .sort_values()
)

print("\nTimestamp range:")
print("Start:", position["date"].min())
print("End:  ", position["date"].max())

Shape: (252, 5)

Columns:
['date', 'session_key', 'driver_number', 'position', 'meeting_key']

First 10 rows:

,date,session_key,driver_number,position,meeting_key
0,2024-07-07 13:05:02.926000+00:00,9558,1,4,1240
1,2024-07-07 13:05:02.926000+00:00,9558,2,12,1240
2,2024-07-07 13:05:02.926000+00:00,9558,3,15,1240
3,2024-07-07 13:05:02.926000+00:00,9558,4,3,1240
4,2024-07-07 13:05:02.926000+00:00,9558,10,19,1240
5,2024-07-07 13:05:02.926000+00:00,9558,11,20,1240
6,2024-07-07 13:05:02.926000+00:00,9558,14,10,1240
7,2024-07-07 13:05:02.926000+00:00,9558,16,11,1240
8,2024-07-07 13:05:02.926000+00:00,9558,18,8,1240
9,2024-07-07 13:05:02.926000+00:00,9558,20,17,1240

Unique drivers: 20

Rows per driver:

driver_number
10     2
14    10
44    10
22    10
77    10
31    11
4     11
24    11
23    12
3     12
55    12
27    13
1     13
11    14
18    14
2     15
20    15
16    17
81    17
63    23
dtype: int64

Timestamp range:
Start: 2024-07-07 13:05:02.926000+00:00
End:   2024-07-07 15:24:33.149000+00:00

In [2]:
print("Unique drivers:", position["driver_number"].nunique())

print("Rows per driver:")
display(
    position.groupby("driver_number")
    .size()
    .sort_values()
)
print("Timestamp range:")
print("Start:", position["date"].min())
print("End:  ", position["date"].max())

Unique drivers: 20
Rows per driver:

driver_number
10     2
14    10
44    10
22    10
77    10
31    11
4     11
24    11
23    12
3     12
55    12
27    13
1     13
11    14
18    14
2     15
20    15
16    17
81    17
63    23
dtype: int64

Timestamp range:
Start: 2024-07-07 13:05:02.926000+00:00
End:   2024-07-07 15:24:33.149000+00:00

In [3]:
display(
    position[
        ["date", "driver_number", "position"]
    ].sort_values("date").head(30)
)
print(position.dtypes)

print("\nPosition values:")
print(sorted(position["position"].dropna().unique()))

print("\nMissing values:")
print(position[["date", "driver_number", "position"]].isna().sum())

                               date  driver_number  position
0  2024-07-07 13:05:02.926000+00:00              1         4
19 2024-07-07 13:05:02.926000+00:00             81         5
18 2024-07-07 13:05:02.926000+00:00             77        16
17 2024-07-07 13:05:02.926000+00:00             63         1
16 2024-07-07 13:05:02.926000+00:00             55         7
14 2024-07-07 13:05:02.926000+00:00             31        18
13 2024-07-07 13:05:02.926000+00:00             27         6
12 2024-07-07 13:05:02.926000+00:00             24        14
11 2024-07-07 13:05:02.926000+00:00             23         9
10 2024-07-07 13:05:02.926000+00:00             22        13
15 2024-07-07 13:05:02.926000+00:00             44         2
8  2024-07-07 13:05:02.926000+00:00             18         8
7  2024-07-07 13:05:02.926000+00:00             16        11
6  2024-07-07 13:05:02.926000+00:00             14        10
5  2024-07-07 13:05:02.926000+00:00             11        20
4  2024-07-07 13:05:02.926000+00:00             10        19
3  2024-07-07 13:05:02.926000+00:00              4         3
2  2024-07-07 13:05:02.926000+00:00              3        15
1  2024-07-07 13:05:02.926000+00:00              2        12
9  2024-07-07 13:05:02.926000+00:00             20        17
21 2024-07-07 14:03:24.443000+00:00             55         6
20 2024-07-07 14:03:24.443000+00:00             27         7
22 2024-07-07 14:03:25.230000+00:00             14         9
23 2024-07-07 14:03:25.230000+00:00             23        10
24 2024-07-07 14:03:25.320000+00:00             16        10
25 2024-07-07 14:03:25.320000+00:00             23        11
26 2024-07-07 14:03:26.193000+00:00             20        18
27 2024-07-07 14:03:26.193000+00:00             31        17
28 2024-07-07 14:03:29.174000+00:00              2        13
29 2024-07-07 14:03:29.174000+00:00             22        12

date             datetime64[us, UTC]
session_key                    int64
driver_number                  int64
position                       int64
meeting_key                    int64
dtype: object

Position values:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20)]

Missing values:
date             0
driver_number    0
position         0
dtype: int64

In [4]:
position_events = (
    position.sort_values("date").groupby("date").agg(
        cars_reporting=("driver_number", "nunique"),
        min_position=("position", "min"),
        max_position=("position", "max")
    ).reset_index()
)

display(position_events.head(20))
print("Total position events:", len(position_events))
print("Cars report per event:")

display(
    position_events["cars_reporting"].value_counts().sort_index()
)

display(
    position_events.sort_values("cars_reporting").head(20)
)

,date,cars_reporting,min_position,max_position
0,2024-07-07 13:05:02.926000+00:00,20,1,20
1,2024-07-07 14:03:24.443000+00:00,2,6,7
2,2024-07-07 14:03:25.230000+00:00,2,9,10
3,2024-07-07 14:03:25.320000+00:00,2,10,11
4,2024-07-07 14:03:26.193000+00:00,2,17,18
5,2024-07-07 14:03:29.174000+00:00,2,12,13
6,2024-07-07 14:03:31.245000+00:00,2,3,4
7,2024-07-07 14:03:31.254000+00:00,2,3,4
8,2024-07-07 14:03:32.535000+00:00,2,7,8
9,2024-07-07 14:03:32.612000+00:00,2,19,20
10,2024-07-07 14:03:32.979000+00:00,3,8,10
11,2024-07-07 14:03:33.449000+00:00,3,11,13
12,2024-07-07 14:03:37.140000+00:00,2,3,4
13,2024-07-07 14:03:39.792000+00:00,3,11,13
14,2024-07-07 14:03:44.739000+00:00,2,16,17
15,2024-07-07 14:03:45.314000+00:00,2,17,18
16,2024-07-07 14:03:55.649000+00:00,2,14,15
17,2024-07-07 14:04:01.043000+00:00,2,14,15
18,2024-07-07 14:04:10.669000+00:00,2,14,15
19,2024-07-07 14:04:38.592000+00:00,2,14,15

Total position events: 113
Cars report per event:

cars_reporting
1     12
2     86
3     12
6      2
20     1
Name: count, dtype: int64

,date,cars_reporting,min_position,max_position
53,2024-07-07 14:34:03.188000+00:00,1,2,2
52,2024-07-07 14:33:59.306000+00:00,1,3,3
43,2024-07-07 14:33:05.835000+00:00,1,9,9
63,2024-07-07 14:45:23.367000+00:00,1,3,3
47,2024-07-07 14:33:08.145000+00:00,1,8,8
69,2024-07-07 14:46:09.164000+00:00,1,5,5
68,2024-07-07 14:46:07.046000+00:00,1,6,6
64,2024-07-07 14:45:23.382000+00:00,1,2,2
80,2024-07-07 14:56:14.125000+00:00,1,6,6
96,2024-07-07 15:03:55.362000+00:00,1,12,12
95,2024-07-07 15:03:51.034000+00:00,1,13,13
81,2024-07-07 14:56:14.905000+00:00,1,5,5
15,2024-07-07 14:03:45.314000+00:00,2,17,18
1,2024-07-07 14:03:24.443000+00:00,2,6,7
3,2024-07-07 14:03:25.320000+00:00,2,10,11
2,2024-07-07 14:03:25.230000+00:00,2,9,10
24,2024-07-07 14:13:35.084000+00:00,2,17,18
25,2024-07-07 14:14:46.609000+00:00,2,15,16
26,2024-07-07 14:15:08.611000+00:00,2,16,17
27,2024-07-07 14:15:36.067000+00:00,2,17,18

In [5]:
position_times = (
    position[["date"]].drop_duplicates().sort_values("date").reset_index(drop=True)
)

print("Unique position timestamps:", len(position_times))
display(position_times.head(10))

Unique position timestamps: 113

                              date
0 2024-07-07 13:05:02.926000+00:00
1 2024-07-07 14:03:24.443000+00:00
2 2024-07-07 14:03:25.230000+00:00
3 2024-07-07 14:03:25.320000+00:00
4 2024-07-07 14:03:26.193000+00:00
5 2024-07-07 14:03:29.174000+00:00
6 2024-07-07 14:03:31.245000+00:00
7 2024-07-07 14:03:31.254000+00:00
8 2024-07-07 14:03:32.535000+00:00
9 2024-07-07 14:03:32.612000+00:00

In [6]:
drivers = (
    position["driver_number"].drop_duplicates().sort_values().tolist()
)

position_timeline = pd.MultiIndex.from_product(
    [position_times["date"], drivers],
    names=["date", "driver_number"]
).to_frame(index=False)

print("Timeline shape:", position_timeline.shape)
display(position_timeline.head(20))

Timeline shape: (2260, 2)

                               date  driver_number
0  2024-07-07 13:05:02.926000+00:00              1
1  2024-07-07 13:05:02.926000+00:00              2
2  2024-07-07 13:05:02.926000+00:00              3
3  2024-07-07 13:05:02.926000+00:00              4
4  2024-07-07 13:05:02.926000+00:00             10
5  2024-07-07 13:05:02.926000+00:00             11
6  2024-07-07 13:05:02.926000+00:00             14
7  2024-07-07 13:05:02.926000+00:00             16
8  2024-07-07 13:05:02.926000+00:00             18
9  2024-07-07 13:05:02.926000+00:00             20
10 2024-07-07 13:05:02.926000+00:00             22
11 2024-07-07 13:05:02.926000+00:00             23
12 2024-07-07 13:05:02.926000+00:00             24
13 2024-07-07 13:05:02.926000+00:00             27
14 2024-07-07 13:05:02.926000+00:00             31
15 2024-07-07 13:05:02.926000+00:00             44
16 2024-07-07 13:05:02.926000+00:00             55
17 2024-07-07 13:05:02.926000+00:00             63
18 2024-07-07 13:05:02.926000+00:00             77
19 2024-07-07 13:05:02.926000+00:00             81

In [7]:
position_timeline = position_timeline.merge(
    position[["date", "driver_number", "position"]],
    on=["date","driver_number"],
    how="left"
)

print("Shape:", position_timeline.shape)

display(
    position_timeline.head(25)
)

Shape: (2260, 3)

                               date  driver_number  position
0  2024-07-07 13:05:02.926000+00:00              1       4.0
1  2024-07-07 13:05:02.926000+00:00              2      12.0
2  2024-07-07 13:05:02.926000+00:00              3      15.0
3  2024-07-07 13:05:02.926000+00:00              4       3.0
4  2024-07-07 13:05:02.926000+00:00             10      19.0
5  2024-07-07 13:05:02.926000+00:00             11      20.0
6  2024-07-07 13:05:02.926000+00:00             14      10.0
7  2024-07-07 13:05:02.926000+00:00             16      11.0
8  2024-07-07 13:05:02.926000+00:00             18       8.0
9  2024-07-07 13:05:02.926000+00:00             20      17.0
10 2024-07-07 13:05:02.926000+00:00             22      13.0
11 2024-07-07 13:05:02.926000+00:00             23       9.0
12 2024-07-07 13:05:02.926000+00:00             24      14.0
13 2024-07-07 13:05:02.926000+00:00             27       6.0
14 2024-07-07 13:05:02.926000+00:00             31      18.0
15 2024-07-07 13:05:02.926000+00:00             44       2.0
16 2024-07-07 13:05:02.926000+00:00             55       7.0
17 2024-07-07 13:05:02.926000+00:00             63       1.0
18 2024-07-07 13:05:02.926000+00:00             77      16.0
19 2024-07-07 13:05:02.926000+00:00             81       5.0
20 2024-07-07 14:03:24.443000+00:00              1       NaN
21 2024-07-07 14:03:24.443000+00:00              2       NaN
22 2024-07-07 14:03:24.443000+00:00              3       NaN
23 2024-07-07 14:03:24.443000+00:00              4       NaN
24 2024-07-07 14:03:24.443000+00:00             10       NaN

In [8]:
position_timeline = (
    position_timeline.sort_values(["driver_number", "date"]).copy()
)

position_timeline["position"] = (
    position_timeline.groupby("driver_number")["position"].ffill()
)

display(
    position_timeline.head(25)
)

                                date  driver_number  position
0   2024-07-07 13:05:02.926000+00:00              1       4.0
20  2024-07-07 14:03:24.443000+00:00              1       4.0
40  2024-07-07 14:03:25.230000+00:00              1       4.0
60  2024-07-07 14:03:25.320000+00:00              1       4.0
80  2024-07-07 14:03:26.193000+00:00              1       4.0
100 2024-07-07 14:03:29.174000+00:00              1       4.0
120 2024-07-07 14:03:31.245000+00:00              1       3.0
140 2024-07-07 14:03:31.254000+00:00              1       4.0
160 2024-07-07 14:03:32.535000+00:00              1       4.0
180 2024-07-07 14:03:32.612000+00:00              1       4.0
200 2024-07-07 14:03:32.979000+00:00              1       4.0
220 2024-07-07 14:03:33.449000+00:00              1       4.0
240 2024-07-07 14:03:37.140000+00:00              1       3.0
260 2024-07-07 14:03:39.792000+00:00              1       3.0
280 2024-07-07 14:03:44.739000+00:00              1       3.0
300 2024-07-07 14:03:45.314000+00:00              1       3.0
320 2024-07-07 14:03:55.649000+00:00              1       3.0
340 2024-07-07 14:04:01.043000+00:00              1       3.0
360 2024-07-07 14:04:10.669000+00:00              1       3.0
380 2024-07-07 14:04:38.592000+00:00              1       3.0
400 2024-07-07 14:04:51.385000+00:00              1       3.0
420 2024-07-07 14:08:42.843000+00:00              1       3.0
440 2024-07-07 14:12:58.996000+00:00              1       3.0
460 2024-07-07 14:13:12.204000+00:00              1       3.0
480 2024-07-07 14:13:35.084000+00:00              1       3.0

In [9]:
print("Missing positions:", position_timeline["position"].isna().sum())

print("\nRows per timestamp:")
display(
    position_timeline
    .groupby("date")
    .size()
    .value_counts()
    .sort_index()
)

Missing positions: 0

Rows per timestamp:

20    113
Name: count, dtype: int64

In [10]:
position_timeline["position_update"] = (
    position_timeline["position"].ne(
        position_timeline.groupby("driver_number")["position"].shift()
    )
)
position_timeline["last_position_update"] = (
    position_timeline["date"].where(position_timeline["position_update"])
    .groupby(position_timeline["driver_number"]).ffill()

)

position_timeline["seconds_since_position_update"] = (
    position_timeline["date"] - position_timeline["last_position_update"]
).dt.total_seconds()

display(
    position_timeline[
        [
            "date",
            "driver_number",
            "position",
            "last_position_update",
            "seconds_since_position_update"
        ]
    ].head(30)
)

,date,driver_number,position,last_position_update,seconds_since_position_update
0,2024-07-07 13:05:02.926000+00:00,1,4.0,2024-07-07 13:05:02.926000+00:00,0.000
20,2024-07-07 14:03:24.443000+00:00,1,4.0,2024-07-07 13:05:02.926000+00:00,3501.517
40,2024-07-07 14:03:25.230000+00:00,1,4.0,2024-07-07 13:05:02.926000+00:00,3502.304
60,2024-07-07 14:03:25.320000+00:00,1,4.0,2024-07-07 13:05:02.926000+00:00,3502.394
80,2024-07-07 14:03:26.193000+00:00,1,4.0,2024-07-07 13:05:02.926000+00:00,3503.267
100,2024-07-07 14:03:29.174000+00:00,1,4.0,2024-07-07 13:05:02.926000+00:00,3506.248
120,2024-07-07 14:03:31.245000+00:00,1,3.0,2024-07-07 14:03:31.245000+00:00,0.000
140,2024-07-07 14:03:31.254000+00:00,1,4.0,2024-07-07 14:03:31.254000+00:00,0.000
160,2024-07-07 14:03:32.535000+00:00,1,4.0,2024-07-07 14:03:31.254000+00:00,1.281
180,2024-07-07 14:03:32.612000+00:00,1,4.0,2024-07-07 14:03:31.254000+00:00,1.358
200,2024-07-07 14:03:32.979000+00:00,1,4.0,2024-07-07 14:03:31.254000+00:00,1.725
220,2024-07-07 14:03:33.449000+00:00,1,4.0,2024-07-07 14:03:31.254000+00:00,2.195
240,2024-07-07 14:03:37.140000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,0.000
260,2024-07-07 14:03:39.792000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,2.652
280,2024-07-07 14:03:44.739000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,7.599
300,2024-07-07 14:03:45.314000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,8.174
320,2024-07-07 14:03:55.649000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,18.509
340,2024-07-07 14:04:01.043000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,23.903
360,2024-07-07 14:04:10.669000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,33.529
380,2024-07-07 14:04:38.592000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,61.452
400,2024-07-07 14:04:51.385000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,74.245
420,2024-07-07 14:08:42.843000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,305.703
440,2024-07-07 14:12:58.996000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,561.856
460,2024-07-07 14:13:12.204000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,575.064
480,2024-07-07 14:13:35.084000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,597.944
500,2024-07-07 14:14:46.609000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,669.469
520,2024-07-07 14:15:08.611000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,691.471
540,2024-07-07 14:15:36.067000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,718.927
560,2024-07-07 14:18:44.117000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,906.977
580,2024-07-07 14:23:06.887000+00:00,1,3.0,2024-07-07 14:03:37.140000+00:00,1169.747

In [11]:
stale_position = (
    position_timeline[
        [
            "driver_number",
            "date",
            "position",
            "seconds_since_position_update"
        ]
    ].sort_values("seconds_since_position_update", ascending=False)
)
display(stale_position.head(30))

,driver_number,date,position,seconds_since_position_update
697,63,2024-07-07 14:29:31.044000+00:00,1.0,5068.118
695,44,2024-07-07 14:29:31.044000+00:00,2.0,5068.118
675,44,2024-07-07 14:29:05.679000+00:00,2.0,5042.753
677,63,2024-07-07 14:29:05.679000+00:00,1.0,5042.753
657,63,2024-07-07 14:27:09.820000+00:00,1.0,4926.894
659,81,2024-07-07 14:27:09.820000+00:00,5.0,4926.894
655,44,2024-07-07 14:27:09.820000+00:00,2.0,4926.894
2244,10,2024-07-07 15:24:33.149000+00:00,20.0,4860.537
639,81,2024-07-07 14:25:59.612000+00:00,5.0,4856.686
637,63,2024-07-07 14:25:59.612000+00:00,1.0,4856.686
635,44,2024-07-07 14:25:59.612000+00:00,2.0,4856.686
619,81,2024-07-07 14:24:57.776000+00:00,5.0,4794.850
615,44,2024-07-07 14:24:57.776000+00:00,2.0,4794.850
617,63,2024-07-07 14:24:57.776000+00:00,1.0,4794.850
2224,10,2024-07-07 15:22:29.285000+00:00,20.0,4736.673
595,44,2024-07-07 14:23:06.887000+00:00,2.0,4683.961
597,63,2024-07-07 14:23:06.887000+00:00,1.0,4683.961
599,81,2024-07-07 14:23:06.887000+00:00,5.0,4683.961
2204,10,2024-07-07 15:19:28.852000+00:00,20.0,4556.240
579,81,2024-07-07 14:18:44.117000+00:00,5.0,4421.191
575,44,2024-07-07 14:18:44.117000+00:00,2.0,4421.191
577,63,2024-07-07 14:18:44.117000+00:00,1.0,4421.191
2184,10,2024-07-07 15:16:02.782000+00:00,20.0,4350.170
2164,10,2024-07-07 15:14:40.746000+00:00,20.0,4268.134
557,63,2024-07-07 14:15:36.067000+00:00,1.0,4233.141
555,44,2024-07-07 14:15:36.067000+00:00,2.0,4233.141
559,81,2024-07-07 14:15:36.067000+00:00,5.0,4233.141
539,81,2024-07-07 14:15:08.611000+00:00,5.0,4205.685
535,44,2024-07-07 14:15:08.611000+00:00,2.0,4205.685
537,63,2024-07-07 14:15:08.611000+00:00,1.0,4205.685

In [12]:
position_events= position[
    ["date", "driver_number", "position"]
].copy()

position_events["position_event"] = True

display(position_events.head(20))

                               date  driver_number  position  position_event
0  2024-07-07 13:05:02.926000+00:00              1         4            True
1  2024-07-07 13:05:02.926000+00:00              2        12            True
2  2024-07-07 13:05:02.926000+00:00              3        15            True
3  2024-07-07 13:05:02.926000+00:00              4         3            True
4  2024-07-07 13:05:02.926000+00:00             10        19            True
5  2024-07-07 13:05:02.926000+00:00             11        20            True
6  2024-07-07 13:05:02.926000+00:00             14        10            True
7  2024-07-07 13:05:02.926000+00:00             16        11            True
8  2024-07-07 13:05:02.926000+00:00             18         8            True
9  2024-07-07 13:05:02.926000+00:00             20        17            True
10 2024-07-07 13:05:02.926000+00:00             22        13            True
11 2024-07-07 13:05:02.926000+00:00             23         9            True
12 2024-07-07 13:05:02.926000+00:00             24        14            True
13 2024-07-07 13:05:02.926000+00:00             27         6            True
14 2024-07-07 13:05:02.926000+00:00             31        18            True
15 2024-07-07 13:05:02.926000+00:00             44         2            True
16 2024-07-07 13:05:02.926000+00:00             55         7            True
17 2024-07-07 13:05:02.926000+00:00             63         1            True
18 2024-07-07 13:05:02.926000+00:00             77        16            True
19 2024-07-07 13:05:02.926000+00:00             81         5            True

In [13]:
position_timeline = position_timeline.drop(
    columns=["position_event", "last_position_update", "seconds_since_position_update"],
    errors="ignore"
)

position_timeline = position_timeline.merge(
    position_events,
    on=["date", "driver_number", "position"],
    how="left"
)

position_timeline["position_event"] = (
    position_timeline["position_event"].fillna(False)
)

print("Actual position events:", position_timeline["position_event"].sum())

display(
    position_timeline[
        ["date", "driver_number", "position", "position_event"]
    ].head(30)
)

Actual position events: 252

                               date  driver_number  position position_event
0  2024-07-07 13:05:02.926000+00:00              1       4.0           True
1  2024-07-07 14:03:24.443000+00:00              1       4.0          False
2  2024-07-07 14:03:25.230000+00:00              1       4.0          False
3  2024-07-07 14:03:25.320000+00:00              1       4.0          False
4  2024-07-07 14:03:26.193000+00:00              1       4.0          False
5  2024-07-07 14:03:29.174000+00:00              1       4.0          False
6  2024-07-07 14:03:31.245000+00:00              1       3.0           True
7  2024-07-07 14:03:31.254000+00:00              1       4.0           True
8  2024-07-07 14:03:32.535000+00:00              1       4.0          False
9  2024-07-07 14:03:32.612000+00:00              1       4.0          False
10 2024-07-07 14:03:32.979000+00:00              1       4.0          False
11 2024-07-07 14:03:33.449000+00:00              1       4.0          False
12 2024-07-07 14:03:37.140000+00:00              1       3.0           True
13 2024-07-07 14:03:39.792000+00:00              1       3.0          False
14 2024-07-07 14:03:44.739000+00:00              1       3.0          False
15 2024-07-07 14:03:45.314000+00:00              1       3.0          False
16 2024-07-07 14:03:55.649000+00:00              1       3.0          False
17 2024-07-07 14:04:01.043000+00:00              1       3.0          False
18 2024-07-07 14:04:10.669000+00:00              1       3.0          False
19 2024-07-07 14:04:38.592000+00:00              1       3.0          False
20 2024-07-07 14:04:51.385000+00:00              1       3.0          False
21 2024-07-07 14:08:42.843000+00:00              1       3.0          False
22 2024-07-07 14:12:58.996000+00:00              1       3.0          False
23 2024-07-07 14:13:12.204000+00:00              1       3.0          False
24 2024-07-07 14:13:35.084000+00:00              1       3.0          False
25 2024-07-07 14:14:46.609000+00:00              1       3.0          False
26 2024-07-07 14:15:08.611000+00:00              1       3.0          False
27 2024-07-07 14:15:36.067000+00:00              1       3.0          False
28 2024-07-07 14:18:44.117000+00:00              1       3.0          False
29 2024-07-07 14:23:06.887000+00:00              1       3.0          False

In [14]:
position_timeline["last_position_update"] = (
    position_timeline["date"]
    .where(position_timeline["position_event"])
    .groupby(position_timeline["driver_number"])
    .ffill()
)

position_timeline["seconds_since_position_update"] = (
    position_timeline["date"]
    - position_timeline["last_position_update"]
).dt.total_seconds()

display(
    position_timeline[
        [
            "driver_number",
            "date",
            "position",
            "position_event",
            "seconds_since_position_update"
        ]
    ]
    .sort_values("seconds_since_position_update", ascending=False)
    .head(30)
)

,driver_number,date,position,position_event,seconds_since_position_update
1955,63,2024-07-07 14:29:31.044000+00:00,1.0,False,5068.118
1729,44,2024-07-07 14:29:31.044000+00:00,2.0,False,5068.118
1728,44,2024-07-07 14:29:05.679000+00:00,2.0,False,5042.753
1954,63,2024-07-07 14:29:05.679000+00:00,1.0,False,5042.753
1953,63,2024-07-07 14:27:09.820000+00:00,1.0,False,4926.894
2179,81,2024-07-07 14:27:09.820000+00:00,5.0,False,4926.894
1727,44,2024-07-07 14:27:09.820000+00:00,2.0,False,4926.894
564,10,2024-07-07 15:24:33.149000+00:00,20.0,False,4860.537
2178,81,2024-07-07 14:25:59.612000+00:00,5.0,False,4856.686
1952,63,2024-07-07 14:25:59.612000+00:00,1.0,False,4856.686
1726,44,2024-07-07 14:25:59.612000+00:00,2.0,False,4856.686
2177,81,2024-07-07 14:24:57.776000+00:00,5.0,False,4794.850
1725,44,2024-07-07 14:24:57.776000+00:00,2.0,False,4794.850
1951,63,2024-07-07 14:24:57.776000+00:00,1.0,False,4794.850
563,10,2024-07-07 15:22:29.285000+00:00,20.0,False,4736.673
1724,44,2024-07-07 14:23:06.887000+00:00,2.0,False,4683.961
1950,63,2024-07-07 14:23:06.887000+00:00,1.0,False,4683.961
2176,81,2024-07-07 14:23:06.887000+00:00,5.0,False,4683.961
562,10,2024-07-07 15:19:28.852000+00:00,20.0,False,4556.240
2175,81,2024-07-07 14:18:44.117000+00:00,5.0,False,4421.191
1723,44,2024-07-07 14:18:44.117000+00:00,2.0,False,4421.191
1949,63,2024-07-07 14:18:44.117000+00:00,1.0,False,4421.191
561,10,2024-07-07 15:16:02.782000+00:00,20.0,False,4350.170
560,10,2024-07-07 15:14:40.746000+00:00,20.0,False,4268.134
1948,63,2024-07-07 14:15:36.067000+00:00,1.0,False,4233.141
1722,44,2024-07-07 14:15:36.067000+00:00,2.0,False,4233.141
2174,81,2024-07-07 14:15:36.067000+00:00,5.0,False,4233.141
2173,81,2024-07-07 14:15:08.611000+00:00,5.0,False,4205.685
1721,44,2024-07-07 14:15:08.611000+00:00,2.0,False,4205.685
1947,63,2024-07-07 14:15:08.611000+00:00,1.0,False,4205.685

In [15]:
from pathlib import Path
import pandas as pd

LAP_PATH = Path("../data/processed/9558/lap_performance.parquet")

lap_performance = pd.read_parquet(LAP_PATH)

print("Shape:", lap_performance.shape)
print("Columns:")
print(lap_performance.columns.tolist())

Shape: (962, 19)
Columns:
['meeting_key', 'session_key', 'driver_number', 'lap_number', 'date_start', 'duration_sector_1', 'duration_sector_2', 'duration_sector_3', 'i1_speed', 'i2_speed', 'is_pit_out_lap', 'lap_duration', 'segments_sector_1', 'segments_sector_2', 'segments_sector_3', 'st_speed', 'stint_number', 'compound', 'tyre_age']

In [16]:
lap_timeline = (
    lap_performance[
        [
            "date_start",
            "driver_number",
            "lap_number",
        ]
    ]
    .dropna(subset=["date_start"])
    .sort_values(["driver_number","date_start"])
    .reset_index(drop=True)
)
print("Shape:", lap_timeline.shape)
print(lap_timeline.head(10))

Shape: (961, 3)
                        date_start  driver_number  lap_number
0 2024-07-07 14:03:12.540000+00:00              1           1
1 2024-07-07 14:04:49.750000+00:00              1           2
2 2024-07-07 14:06:21.461000+00:00              1           3
3 2024-07-07 14:07:53.675000+00:00              1           4
4 2024-07-07 14:09:25.527000+00:00              1           5
5 2024-07-07 14:10:57.353000+00:00              1           6
6 2024-07-07 14:12:29.113000+00:00              1           7
7 2024-07-07 14:14:01.043000+00:00              1           8
8 2024-07-07 14:15:33.002000+00:00              1           9
9 2024-07-07 14:17:04.948000+00:00              1          10

In [17]:
position_events = (
    position[
        [
            "date",
            "driver_number",
            "position",
        ]
    ]
    .dropna(subset=["date", "position"])
    .sort_values(["driver_number", "date"])
    .reset_index(drop=True)
)

print("Shape:", position_events.shape)
print(position_events.head(20))

Shape: (252, 3)
                               date  driver_number  position
0  2024-07-07 13:05:02.926000+00:00              1         4
1  2024-07-07 14:03:31.245000+00:00              1         3
2  2024-07-07 14:03:31.254000+00:00              1         4
3  2024-07-07 14:03:37.140000+00:00              1         3
4  2024-07-07 14:25:59.612000+00:00              1         4
5  2024-07-07 14:29:05.679000+00:00              1         5
6  2024-07-07 14:31:13.305000+00:00              1         4
7  2024-07-07 14:31:15.050000+00:00              1         5
8  2024-07-07 14:45:51.799000+00:00              1         4
9  2024-07-07 14:47:33.122000+00:00              1         3
10 2024-07-07 15:04:40.696000+00:00              1         4
11 2024-07-07 15:06:24.058000+00:00              1         3
12 2024-07-07 15:19:28.852000+00:00              1         2
13 2024-07-07 13:05:02.926000+00:00              2        12
14 2024-07-07 14:03:29.174000+00:00              2        13
15 2024-07-07 14:03:33.449000+00:00              2        11
16 2024-07-07 14:03:39.792000+00:00              2        12
17 2024-07-07 14:04:51.385000+00:00              2        13
18 2024-07-07 14:33:09.055000+00:00              2        12
19 2024-07-07 14:39:04.248000+00:00              2        13

In [18]:
lap_timeline_asof = (
    lap_timeline.sort_values(["date_start", "driver_number"]).reset_index(drop=True)
)

position_events_asof = (
    position_events
    .rename(columns={"date":"position_event_time"})
    .sort_values(["position_event_time","driver_number"])
    .reset_index(drop=True)
)

lap_with_position = pd.merge_asof(
    lap_timeline_asof,
    position_events_asof,
    left_on="date_start",
    right_on="position_event_time",
    by="driver_number",
    direction="backward"
)

print("Shape:", lap_with_position.shape)
print(lap_with_position.head(20))

Shape: (961, 5)
                         date_start  driver_number  lap_number  \
0  2024-07-07 14:03:12.540000+00:00              1           1
1  2024-07-07 14:03:12.540000+00:00              2           1
2  2024-07-07 14:03:12.540000+00:00              3           1
3  2024-07-07 14:03:12.540000+00:00              4           1
4  2024-07-07 14:03:12.540000+00:00             10           1
5  2024-07-07 14:03:12.540000+00:00             14           1
6  2024-07-07 14:03:12.540000+00:00             16           1
7  2024-07-07 14:03:12.540000+00:00             18           1
8  2024-07-07 14:03:12.540000+00:00             20           1
9  2024-07-07 14:03:12.540000+00:00             22           1
10 2024-07-07 14:03:12.540000+00:00             23           1
11 2024-07-07 14:03:12.540000+00:00             24           1
12 2024-07-07 14:03:12.540000+00:00             27           1
13 2024-07-07 14:03:12.540000+00:00             31           1
14 2024-07-07 14:03:12.540000+00:00             44           1
15 2024-07-07 14:03:12.540000+00:00             55           1
16 2024-07-07 14:03:12.540000+00:00             63           1
17 2024-07-07 14:03:12.540000+00:00             77           1
18 2024-07-07 14:03:12.540000+00:00             81           1
19 2024-07-07 14:04:48.099000+00:00             63           2

                position_event_time  position
0  2024-07-07 13:05:02.926000+00:00         4
1  2024-07-07 13:05:02.926000+00:00        12
2  2024-07-07 13:05:02.926000+00:00        15
3  2024-07-07 13:05:02.926000+00:00         3
4  2024-07-07 13:05:02.926000+00:00        19
5  2024-07-07 13:05:02.926000+00:00        10
6  2024-07-07 13:05:02.926000+00:00        11
7  2024-07-07 13:05:02.926000+00:00         8
8  2024-07-07 13:05:02.926000+00:00        17
9  2024-07-07 13:05:02.926000+00:00        13
10 2024-07-07 13:05:02.926000+00:00         9
11 2024-07-07 13:05:02.926000+00:00        14
12 2024-07-07 13:05:02.926000+00:00         6
13 2024-07-07 13:05:02.926000+00:00        18
14 2024-07-07 13:05:02.926000+00:00         2
15 2024-07-07 13:05:02.926000+00:00         7
16 2024-07-07 13:05:02.926000+00:00         1
17 2024-07-07 13:05:02.926000+00:00        16
18 2024-07-07 13:05:02.926000+00:00         5
19 2024-07-07 13:05:02.926000+00:00         1

In [19]:
lap_with_position["position_age_seconds"] = (
    lap_with_position["date_start"]
    - lap_with_position["position_event_time"]
).dt.total_seconds()

print(
    lap_with_position[
        [
            "driver_number",
            "lap_number",
            "date_start",
            "position_event_time",
            "position",
            "position_age_seconds",
        ]
    ].head(30)
)

print(lap_with_position["position_age_seconds"].describe())

    driver_number  lap_number                       date_start  \
0               1           1 2024-07-07 14:03:12.540000+00:00
1               2           1 2024-07-07 14:03:12.540000+00:00
2               3           1 2024-07-07 14:03:12.540000+00:00
3               4           1 2024-07-07 14:03:12.540000+00:00
4              10           1 2024-07-07 14:03:12.540000+00:00
5              14           1 2024-07-07 14:03:12.540000+00:00
6              16           1 2024-07-07 14:03:12.540000+00:00
7              18           1 2024-07-07 14:03:12.540000+00:00
8              20           1 2024-07-07 14:03:12.540000+00:00
9              22           1 2024-07-07 14:03:12.540000+00:00
10             23           1 2024-07-07 14:03:12.540000+00:00
11             24           1 2024-07-07 14:03:12.540000+00:00
12             27           1 2024-07-07 14:03:12.540000+00:00
13             31           1 2024-07-07 14:03:12.540000+00:00
14             44           1 2024-07-07 14:03:12.540000+00:00
15             55           1 2024-07-07 14:03:12.540000+00:00
16             63           1 2024-07-07 14:03:12.540000+00:00
17             77           1 2024-07-07 14:03:12.540000+00:00
18             81           1 2024-07-07 14:03:12.540000+00:00
19             63           2 2024-07-07 14:04:48.099000+00:00
20             44           2 2024-07-07 14:04:48.941000+00:00
21              1           2 2024-07-07 14:04:49.750000+00:00
22              4           2 2024-07-07 14:04:50.260000+00:00
23             81           2 2024-07-07 14:04:50.898000+00:00
24             55           2 2024-07-07 14:04:51.615000+00:00
25             18           2 2024-07-07 14:04:52.007000+00:00
26             16           2 2024-07-07 14:04:52.522000+00:00
27             27           2 2024-07-07 14:04:53.072000+00:00
28             14           2 2024-07-07 14:04:53.522000+00:00
29             22           2 2024-07-07 14:04:53.977000+00:00

                position_event_time  position  position_age_seconds
0  2024-07-07 13:05:02.926000+00:00         4              3489.614
1  2024-07-07 13:05:02.926000+00:00        12              3489.614
2  2024-07-07 13:05:02.926000+00:00        15              3489.614
3  2024-07-07 13:05:02.926000+00:00         3              3489.614
4  2024-07-07 13:05:02.926000+00:00        19              3489.614
5  2024-07-07 13:05:02.926000+00:00        10              3489.614
6  2024-07-07 13:05:02.926000+00:00        11              3489.614
7  2024-07-07 13:05:02.926000+00:00         8              3489.614
8  2024-07-07 13:05:02.926000+00:00        17              3489.614
9  2024-07-07 13:05:02.926000+00:00        13              3489.614
10 2024-07-07 13:05:02.926000+00:00         9              3489.614
11 2024-07-07 13:05:02.926000+00:00        14              3489.614
12 2024-07-07 13:05:02.926000+00:00         6              3489.614
13 2024-07-07 13:05:02.926000+00:00        18              3489.614
14 2024-07-07 13:05:02.926000+00:00         2              3489.614
15 2024-07-07 13:05:02.926000+00:00         7              3489.614
16 2024-07-07 13:05:02.926000+00:00         1              3489.614
17 2024-07-07 13:05:02.926000+00:00        16              3489.614
18 2024-07-07 13:05:02.926000+00:00         5              3489.614
19 2024-07-07 13:05:02.926000+00:00         1              3585.173
20 2024-07-07 13:05:02.926000+00:00         2              3586.015
21 2024-07-07 14:03:37.140000+00:00         3                72.610
22 2024-07-07 14:03:37.140000+00:00         4                73.120
23 2024-07-07 13:05:02.926000+00:00         5              3587.972
24 2024-07-07 14:03:24.443000+00:00         6                87.172
25 2024-07-07 14:03:32.535000+00:00         7                79.472
26 2024-07-07 14:03:32.979000+00:00         8                79.543
27 2024-07-07 14:03:32.979000+00:00         9                80.093
28 2024-07-07 14:03:32.979000+00:00        10                80.543
29 2024-07-07 14:03:39.792000+00:00        11                74.185
count     961.000000
mean      809.536048
std      1029.913742
min         0.078000
25%       201.709000
50%       465.242000
75%       933.878000
max      5054.845000
Name: position_age_seconds, dtype: float64

In [20]:
race_start = lap_performance["date_start"].min()

print("Race start:", race_start)

lap_with_position["is_race_started"] = (
    lap_with_position["date_start"] >= race_start
)

lap_with_position["position_age_seconds"] = (
    lap_with_position["date_start"]
    - lap_with_position["position_event_time"]
).dt.total_seconds()

print(
    lap_with_position[
        [
            "driver_number",
            "lap_number",
            "position",
            "position_event_time",
            "position_age_seconds",
            "is_race_started",
        ]
    ].head(20)
)

Race start: 2024-07-07 14:03:12.540000+00:00
    driver_number  lap_number  position              position_event_time  \
0               1           1         4 2024-07-07 13:05:02.926000+00:00
1               2           1        12 2024-07-07 13:05:02.926000+00:00
2               3           1        15 2024-07-07 13:05:02.926000+00:00
3               4           1         3 2024-07-07 13:05:02.926000+00:00
4              10           1        19 2024-07-07 13:05:02.926000+00:00
5              14           1        10 2024-07-07 13:05:02.926000+00:00
6              16           1        11 2024-07-07 13:05:02.926000+00:00
7              18           1         8 2024-07-07 13:05:02.926000+00:00
8              20           1        17 2024-07-07 13:05:02.926000+00:00
9              22           1        13 2024-07-07 13:05:02.926000+00:00
10             23           1         9 2024-07-07 13:05:02.926000+00:00
11             24           1        14 2024-07-07 13:05:02.926000+00:00
12             27           1         6 2024-07-07 13:05:02.926000+00:00
13             31           1        18 2024-07-07 13:05:02.926000+00:00
14             44           1         2 2024-07-07 13:05:02.926000+00:00
15             55           1         7 2024-07-07 13:05:02.926000+00:00
16             63           1         1 2024-07-07 13:05:02.926000+00:00
17             77           1        16 2024-07-07 13:05:02.926000+00:00
18             81           1         5 2024-07-07 13:05:02.926000+00:00
19             63           2         1 2024-07-07 13:05:02.926000+00:00

    position_age_seconds  is_race_started
0               3489.614             True
1               3489.614             True
2               3489.614             True
3               3489.614             True
4               3489.614             True
5               3489.614             True
6               3489.614             True
7               3489.614             True
8               3489.614             True
9               3489.614             True
10              3489.614             True
11              3489.614             True
12              3489.614             True
13              3489.614             True
14              3489.614             True
15              3489.614             True
16              3489.614             True
17              3489.614             True
18              3489.614             True
19              3585.173             True

In [21]:
driver_activity = (
    lap_performance
    .groupby("driver_number")
    .agg(
        first_lap=("lap_number", "min"),
        last_lap=("lap_number", "max"),
        last_lap_time=("date_start", "max"),
        laps_recorded=("lap_number", "count"),
    )
    .reset_index()
)

print(driver_activity)

    driver_number  first_lap  last_lap                    last_lap_time  \
0               1          1        52 2024-07-07 15:24:12.328000+00:00
1               2          1        52 2024-07-07 15:25:36.918000+00:00
2               3          1        51 2024-07-07 15:24:15.174000+00:00
3               4          1        52 2024-07-07 15:24:16.709000+00:00
4              10          1         1 2024-07-07 14:03:12.540000+00:00
5              11          1        50 2024-07-07 15:24:28.289000+00:00
6              14          1        52 2024-07-07 15:25:12.203000+00:00
7              16          1        51 2024-07-07 15:24:48.817000+00:00
8              18          1        52 2024-07-07 15:25:06.631000+00:00
9              20          1        52 2024-07-07 15:25:38.167000+00:00
10             22          1        52 2024-07-07 15:25:27.234000+00:00
11             23          1        52 2024-07-07 15:25:18.725000+00:00
12             24          1        50 2024-07-07 15:25:02.816000+00:00
13             27          1        52 2024-07-07 15:25:04.989000+00:00
14             31          1        50 2024-07-07 15:24:19.110000+00:00
15             44          1        52 2024-07-07 15:24:09.955000+00:00
16             55          1        52 2024-07-07 15:24:59.135000+00:00
17             63          1        34 2024-07-07 14:56:04.669000+00:00
18             77          1        51 2024-07-07 15:24:49.652000+00:00
19             81          1        52 2024-07-07 15:24:22.700000+00:00

    laps_recorded
0              52
1              52
2              51
3              52
4               1
5              50
6              52
7              51
8              52
9              52
10             52
11             52
12             50
13             52
14             50
15             52
16             52
17             34
18             51
19             52

In [22]:
lap_with_position = lap_with_position.merge(
    driver_activity[
        [
            "driver_number",
            "last_lap",
            "last_lap_time",
        ]
    ],
    on="driver_number",
    how="left"
)

lap_with_position["seconds_from_last_lap"] = (
    lap_with_position["last_lap_time"]
    - lap_with_position["date_start"]
).dt.total_seconds()

print(
    lap_with_position[
        [
            "driver_number",
            "lap_number",
            "date_start",
            "last_lap",
            "last_lap_time",
            "seconds_from_last_lap",
        ]
    ].tail(20)
)

     driver_number  lap_number                       date_start  last_lap  \
941              2          51 2024-07-07 15:24:05.184000+00:00        52
942             20          51 2024-07-07 15:24:06.717000+00:00        52
943             44          52 2024-07-07 15:24:09.955000+00:00        52
944              1          52 2024-07-07 15:24:12.328000+00:00        52
945              3          51 2024-07-07 15:24:15.174000+00:00        51
946              4          52 2024-07-07 15:24:16.709000+00:00        52
947             31          50 2024-07-07 15:24:19.110000+00:00        50
948             81          52 2024-07-07 15:24:22.700000+00:00        52
949             11          50 2024-07-07 15:24:28.289000+00:00        50
950             16          51 2024-07-07 15:24:48.817000+00:00        51
951             77          51 2024-07-07 15:24:49.652000+00:00        51
952             55          52 2024-07-07 15:24:59.135000+00:00        52
953             24          50 2024-07-07 15:25:02.816000+00:00        50
954             27          52 2024-07-07 15:25:04.989000+00:00        52
955             18          52 2024-07-07 15:25:06.631000+00:00        52
956             14          52 2024-07-07 15:25:12.203000+00:00        52
957             23          52 2024-07-07 15:25:18.725000+00:00        52
958             22          52 2024-07-07 15:25:27.234000+00:00        52
959              2          52 2024-07-07 15:25:36.918000+00:00        52
960             20          52 2024-07-07 15:25:38.167000+00:00        52

                       last_lap_time  seconds_from_last_lap
941 2024-07-07 15:25:36.918000+00:00                 91.734
942 2024-07-07 15:25:38.167000+00:00                 91.450
943 2024-07-07 15:24:09.955000+00:00                  0.000
944 2024-07-07 15:24:12.328000+00:00                  0.000
945 2024-07-07 15:24:15.174000+00:00                  0.000
946 2024-07-07 15:24:16.709000+00:00                  0.000
947 2024-07-07 15:24:19.110000+00:00                  0.000
948 2024-07-07 15:24:22.700000+00:00                  0.000
949 2024-07-07 15:24:28.289000+00:00                  0.000
950 2024-07-07 15:24:48.817000+00:00                  0.000
951 2024-07-07 15:24:49.652000+00:00                  0.000
952 2024-07-07 15:24:59.135000+00:00                  0.000
953 2024-07-07 15:25:02.816000+00:00                  0.000
954 2024-07-07 15:25:04.989000+00:00                  0.000
955 2024-07-07 15:25:06.631000+00:00                  0.000
956 2024-07-07 15:25:12.203000+00:00                  0.000
957 2024-07-07 15:25:18.725000+00:00                  0.000
958 2024-07-07 15:25:27.234000+00:00                  0.000
959 2024-07-07 15:25:36.918000+00:00                  0.000
960 2024-07-07 15:25:38.167000+00:00                  0.000

In [23]:
lap_with_position["position_status"] = "ACTIVE"

lap_with_position.loc[
    lap_with_position["position_event_time"] < race_start,
    "position_status"
] = "PRE_RACE"

print(
    lap_with_position[
        [
            "driver_number",
            "lap_number",
            "date_start",
            "position",
            "position_event_time",
            "position_age_seconds",
            "position_status",
        ]
    ].head(30)
)

    driver_number  lap_number                       date_start  position  \
0               1           1 2024-07-07 14:03:12.540000+00:00         4
1               2           1 2024-07-07 14:03:12.540000+00:00        12
2               3           1 2024-07-07 14:03:12.540000+00:00        15
3               4           1 2024-07-07 14:03:12.540000+00:00         3
4              10           1 2024-07-07 14:03:12.540000+00:00        19
5              14           1 2024-07-07 14:03:12.540000+00:00        10
6              16           1 2024-07-07 14:03:12.540000+00:00        11
7              18           1 2024-07-07 14:03:12.540000+00:00         8
8              20           1 2024-07-07 14:03:12.540000+00:00        17
9              22           1 2024-07-07 14:03:12.540000+00:00        13
10             23           1 2024-07-07 14:03:12.540000+00:00         9
11             24           1 2024-07-07 14:03:12.540000+00:00        14
12             27           1 2024-07-07 14:03:12.540000+00:00         6
13             31           1 2024-07-07 14:03:12.540000+00:00        18
14             44           1 2024-07-07 14:03:12.540000+00:00         2
15             55           1 2024-07-07 14:03:12.540000+00:00         7
16             63           1 2024-07-07 14:03:12.540000+00:00         1
17             77           1 2024-07-07 14:03:12.540000+00:00        16
18             81           1 2024-07-07 14:03:12.540000+00:00         5
19             63           2 2024-07-07 14:04:48.099000+00:00         1
20             44           2 2024-07-07 14:04:48.941000+00:00         2
21              1           2 2024-07-07 14:04:49.750000+00:00         3
22              4           2 2024-07-07 14:04:50.260000+00:00         4
23             81           2 2024-07-07 14:04:50.898000+00:00         5
24             55           2 2024-07-07 14:04:51.615000+00:00         6
25             18           2 2024-07-07 14:04:52.007000+00:00         7
26             16           2 2024-07-07 14:04:52.522000+00:00         8
27             27           2 2024-07-07 14:04:53.072000+00:00         9
28             14           2 2024-07-07 14:04:53.522000+00:00        10
29             22           2 2024-07-07 14:04:53.977000+00:00        11

                position_event_time  position_age_seconds position_status
0  2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
1  2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
2  2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
3  2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
4  2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
5  2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
6  2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
7  2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
8  2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
9  2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
10 2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
11 2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
12 2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
13 2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
14 2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
15 2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
16 2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
17 2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
18 2024-07-07 13:05:02.926000+00:00              3489.614        PRE_RACE
19 2024-07-07 13:05:02.926000+00:00              3585.173        PRE_RACE
20 2024-07-07 13:05:02.926000+00:00              3586.015        PRE_RACE
21 2024-07-07 14:03:37.140000+00:00                72.610          ACTIVE
22 2024-07-07 14:03:37.140000+00:00                73.120          ACTIVE
23 2024-07-07 13:05:02.926000+00:00              3587.972        PRE_RACE
24 2024-07-07 14:03:24.443000+00:00                87.172          ACTIVE
25 2024-07-07 14:03:32.535000+00:00                79.472          ACTIVE
26 2024-07-07 14:03:32.979000+00:00                79.543          ACTIVE
27 2024-07-07 14:03:32.979000+00:00                80.093          ACTIVE
28 2024-07-07 14:03:32.979000+00:00                80.543          ACTIVE
29 2024-07-07 14:03:39.792000+00:00                74.185          ACTIVE

In [24]:
race_position_events = position_events[
    position_events["date"] >= race_start
].copy()

race_position_events["seconds_since_position_update"] = (
    race_position_events
    .groupby("driver_number")["date"]
    .diff()
    .dt.total_seconds()
)

print(
    race_position_events["seconds_since_position_update"].describe()
)

count     212.000000
mean      339.505759
std       487.451380
min         0.009000
25%         6.343000
50%       108.541500
75%       531.914250
max      2558.012000
Name: seconds_since_position_update, dtype: float64

In [25]:
largest_gaps = (
    race_position_events
    .dropna(subset=["seconds_since_position_update"])
    .sort_values("seconds_since_position_update", ascending=False)
    [
        [
            "driver_number",
            "date",
            "position",
            "seconds_since_position_update",
        ]
    ]
    .head(20)
)

print(largest_gaps)

     driver_number                             date  position  \
192             55 2024-07-07 14:46:02.455000+00:00         5
155             24 2024-07-07 14:59:17.237000+00:00        18
176             31 2024-07-07 14:58:32.979000+00:00        17
70              14 2024-07-07 14:33:06.309000+00:00         9
127             22 2024-07-07 14:33:06.829000+00:00        10
160             27 2024-07-07 14:32:10.763000+00:00         8
18               2 2024-07-07 14:33:09.055000+00:00        12
139             23 2024-07-07 14:33:07.683000+00:00        11
234             77 2024-07-07 15:24:33.149000+00:00        15
93              16 2024-07-07 15:24:33.149000+00:00        14
37               3 2024-07-07 14:57:00.990000+00:00        13
44               4 2024-07-07 14:25:59.612000+00:00         3
4                1 2024-07-07 14:25:59.612000+00:00         4
233             77 2024-07-07 14:57:23.523000+00:00        14
96              18 2024-07-07 14:23:06.887000+00:00         8
80              16 2024-07-07 14:23:06.887000+00:00         7
132             22 2024-07-07 15:16:02.782000+00:00        10
144             23 2024-07-07 15:16:02.782000+00:00         9
49               4 2024-07-07 15:06:20.850000+00:00         2
187             44 2024-07-07 15:04:44.001000+00:00         3

     seconds_since_position_update
192                       2558.012
155                       2433.120
176                       2015.203
70                        1773.330
127                       1767.037
160                       1717.784
18                        1697.670
139                       1696.298
234                       1629.626
93                        1585.507
37                        1424.820
44                        1342.472
4                         1342.472
233                       1328.995
96                        1174.352
80                        1173.908
132                       1155.419
144                       1151.925
49                        1134.711
187                       1034.666

In [26]:
race_position_events = position_events[
    position_events["date"] >= race_start
].copy()

race_position_events["seconds_since_position_update"] = (
    race_position_events
    .groupby("driver_number")["date"]
    .diff()
    .dt.total_seconds()
)

print(
    race_position_events[
        race_position_events["seconds_since_position_update"] > 600
    ][
        [
            "driver_number",
            "date",
            "position",
            "seconds_since_position_update",
        ]
    ]
    .sort_values("seconds_since_position_update", ascending=False)
    .to_string(index=False)
)

 driver_number                             date  position  seconds_since_position_update
            55 2024-07-07 14:46:02.455000+00:00         5                       2558.012
            24 2024-07-07 14:59:17.237000+00:00        18                       2433.120
            31 2024-07-07 14:58:32.979000+00:00        17                       2015.203
            14 2024-07-07 14:33:06.309000+00:00         9                       1773.330
            22 2024-07-07 14:33:06.829000+00:00        10                       1767.037
            27 2024-07-07 14:32:10.763000+00:00         8                       1717.784
             2 2024-07-07 14:33:09.055000+00:00        12                       1697.670
            23 2024-07-07 14:33:07.683000+00:00        11                       1696.298
            77 2024-07-07 15:24:33.149000+00:00        15                       1629.626
            16 2024-07-07 15:24:33.149000+00:00        14                       1585.507
             3 2024-07-07 14:57:00.990000+00:00        13                       1424.820
             4 2024-07-07 14:25:59.612000+00:00         3                       1342.472
             1 2024-07-07 14:25:59.612000+00:00         4                       1342.472
            77 2024-07-07 14:57:23.523000+00:00        14                       1328.995
            18 2024-07-07 14:23:06.887000+00:00         8                       1174.352
            16 2024-07-07 14:23:06.887000+00:00         7                       1173.908
            22 2024-07-07 15:16:02.782000+00:00        10                       1155.419
            23 2024-07-07 15:16:02.782000+00:00         9                       1151.925
             4 2024-07-07 15:06:20.850000+00:00         2                       1134.711
            44 2024-07-07 15:04:44.001000+00:00         3                       1034.666
             1 2024-07-07 15:04:40.696000+00:00         4                       1027.574
            11 2024-07-07 15:22:29.285000+00:00        17                        918.510
            31 2024-07-07 15:22:29.285000+00:00        16                        918.510
             1 2024-07-07 14:45:51.799000+00:00         4                        876.749
            11 2024-07-07 14:29:31.044000+00:00        15                        862.433
            11 2024-07-07 14:47:39.903000+00:00        16                        854.845
             3 2024-07-07 14:27:09.820000+00:00        15                        837.616
             4 2024-07-07 15:19:28.852000+00:00         3                        788.002
             1 2024-07-07 15:19:28.852000+00:00         2                        784.794
            63 2024-07-07 14:45:51.799000+00:00         5                        770.401
             4 2024-07-07 14:45:31.552000+00:00         2                        769.968
            16 2024-07-07 14:47:39.903000+00:00        17                        745.375
            20 2024-07-07 14:27:09.820000+00:00        14                        743.211
            44 2024-07-07 14:45:23.382000+00:00         2                        684.076
            81 2024-07-07 14:45:23.367000+00:00         3                        680.179
            27 2024-07-07 14:44:14.818000+00:00         8                        670.191
            23 2024-07-07 14:44:17.535000+00:00         9                        669.852
            22 2024-07-07 14:44:16.342000+00:00         8                        669.513
             2 2024-07-07 14:56:58.961000+00:00        12                        644.478
            20 2024-07-07 14:56:55.993000+00:00        11                        641.510
            23 2024-07-07 14:56:50.857000+00:00        10                        636.374
            22 2024-07-07 14:56:47.363000+00:00         9                        632.880
            14 2024-07-07 14:56:43.890000+00:00         8                        629.407
            18 2024-07-07 14:56:35.390000+00:00         7                        620.907
            27 2024-07-07 14:56:32.077000+00:00         6                        618.517
            77 2024-07-07 14:18:44.117000+00:00        18                        601.274

In [27]:
lap_with_position["driver_active"] = (
    lap_with_position["lap_number"]
    <= lap_with_position["last_lap"]
)

print(
    lap_with_position[
        [
            "driver_number",
            "lap_number",
            "last_lap",
            "driver_active",
        ]
    ].tail(20)
)

     driver_number  lap_number  last_lap  driver_active
941              2          51        52           True
942             20          51        52           True
943             44          52        52           True
944              1          52        52           True
945              3          51        51           True
946              4          52        52           True
947             31          50        50           True
948             81          52        52           True
949             11          50        50           True
950             16          51        51           True
951             77          51        51           True
952             55          52        52           True
953             24          50        50           True
954             27          52        52           True
955             18          52        52           True
956             14          52        52           True
957             23          52        52           True
958             22          52        52           True
959              2          52        52           True
960             20          52        52           True

In [28]:
lap_with_position = (
    lap_with_position
    .sort_values(["driver_number", "lap_number"])
    .reset_index(drop=True)
)

lap_with_position["position_change"] = (
    lap_with_position
    .groupby("driver_number")["position"]
    .diff()
)

lap_with_position["positions_gained"] = (
    -lap_with_position["position_change"]
).clip(lower=0)

lap_with_position["positions_lost"] = (
    lap_with_position["position_change"]
).clip(lower=0)

max_position = lap_with_position[
    lap_with_position["driver_number"] == 1
][
    [
        "lap_number",
        "date_start",
        "position",
        "position_change",
        "positions_gained",
        "positions_lost",
        "position_event_time",
        "position_age_seconds"
    ]
]

print(max_position.to_string(index=False))

 lap_number                       date_start  position  position_change  positions_gained  positions_lost              position_event_time  position_age_seconds
          1 2024-07-07 14:03:12.540000+00:00         4              NaN               NaN             NaN 2024-07-07 13:05:02.926000+00:00              3489.614
          2 2024-07-07 14:04:49.750000+00:00         3             -1.0               1.0             0.0 2024-07-07 14:03:37.140000+00:00                72.610
          3 2024-07-07 14:06:21.461000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:03:37.140000+00:00               164.321
          4 2024-07-07 14:07:53.675000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:03:37.140000+00:00               256.535
          5 2024-07-07 14:09:25.527000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:03:37.140000+00:00               348.387
          6 2024-07-07 14:10:57.353000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:03:37.140000+00:00               440.213
          7 2024-07-07 14:12:29.113000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:03:37.140000+00:00               531.973
          8 2024-07-07 14:14:01.043000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:03:37.140000+00:00               623.903
          9 2024-07-07 14:15:33.002000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:03:37.140000+00:00               715.862
         10 2024-07-07 14:17:04.948000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:03:37.140000+00:00               807.808
         11 2024-07-07 14:18:36.554000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:03:37.140000+00:00               899.414
         12 2024-07-07 14:20:08.433000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:03:37.140000+00:00               991.293
         13 2024-07-07 14:21:40.221000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:03:37.140000+00:00              1083.081
         14 2024-07-07 14:23:12.105000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:03:37.140000+00:00              1174.965
         15 2024-07-07 14:24:43.737000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:03:37.140000+00:00              1266.597
         16 2024-07-07 14:26:15.941000+00:00         4              1.0               0.0             1.0 2024-07-07 14:25:59.612000+00:00                16.329
         17 2024-07-07 14:27:48.466000+00:00         4              0.0              -0.0             0.0 2024-07-07 14:25:59.612000+00:00               108.854
         18 2024-07-07 14:29:23.894000+00:00         5              1.0               0.0             1.0 2024-07-07 14:29:05.679000+00:00                18.215
         19 2024-07-07 14:31:00.053000+00:00         5              0.0              -0.0             0.0 2024-07-07 14:29:05.679000+00:00               114.374
         20 2024-07-07 14:32:42.464000+00:00         5              0.0              -0.0             0.0 2024-07-07 14:31:15.050000+00:00                87.414
         21 2024-07-07 14:34:19.699000+00:00         5              0.0              -0.0             0.0 2024-07-07 14:31:15.050000+00:00               184.649
         22 2024-07-07 14:35:53.074000+00:00         5              0.0              -0.0             0.0 2024-07-07 14:31:15.050000+00:00               278.024
         23 2024-07-07 14:37:25.010000+00:00         5              0.0              -0.0             0.0 2024-07-07 14:31:15.050000+00:00               369.960
         24 2024-07-07 14:38:57.270000+00:00         5              0.0              -0.0             0.0 2024-07-07 14:31:15.050000+00:00               462.220
         25 2024-07-07 14:40:30.085000+00:00         5              0.0              -0.0             0.0 2024-07-07 14:31:15.050000+00:00               555.035
         26 2024-07-07 14:42:06.267000+00:00         5              0.0              -0.0             0.0 2024-07-07 14:31:15.050000+00:00               651.217
         27 2024-07-07 14:43:47.712000+00:00         5              0.0              -0.0             0.0 2024-07-07 14:31:15.050000+00:00               752.662
         28 2024-07-07 14:45:46.850000+00:00         5              0.0              -0.0             0.0 2024-07-07 14:31:15.050000+00:00               871.800
         29 2024-07-07 14:47:27.944000+00:00         4             -1.0               1.0             0.0 2024-07-07 14:45:51.799000+00:00                96.145
         30 2024-07-07 14:49:09.592000+00:00         3             -1.0               1.0             0.0 2024-07-07 14:47:33.122000+00:00                96.470
         31 2024-07-07 14:50:51.654000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:47:33.122000+00:00               198.532
         32 2024-07-07 14:52:33.677000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:47:33.122000+00:00               300.555
         33 2024-07-07 14:54:16.219000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:47:33.122000+00:00               403.097
         34 2024-07-07 14:55:58.844000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:47:33.122000+00:00               505.722
         35 2024-07-07 14:57:41.224000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:47:33.122000+00:00               608.102
         36 2024-07-07 14:59:24.402000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:47:33.122000+00:00               711.280
         37 2024-07-07 15:01:06.361000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:47:33.122000+00:00               813.239
         38 2024-07-07 15:02:45.144000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:47:33.122000+00:00               912.022
         39 2024-07-07 15:04:21.179000+00:00         3              0.0              -0.0             0.0 2024-07-07 14:47:33.122000+00:00              1008.057
         40 2024-07-07 15:06:19.420000+00:00         4              1.0               0.0             1.0 2024-07-07 15:04:40.696000+00:00                98.724
         41 2024-07-07 15:07:49.775000+00:00         3             -1.0               1.0             0.0 2024-07-07 15:06:24.058000+00:00                85.717
         42 2024-07-07 15:09:19.236000+00:00         3              0.0              -0.0             0.0 2024-07-07 15:06:24.058000+00:00               175.178
         43 2024-07-07 15:10:48.675000+00:00         3              0.0              -0.0             0.0 2024-07-07 15:06:24.058000+00:00               264.617
         44 2024-07-07 15:12:17.680000+00:00         3              0.0              -0.0             0.0 2024-07-07 15:06:24.058000+00:00               353.622
         45 2024-07-07 15:13:47.096000+00:00         3              0.0              -0.0             0.0 2024-07-07 15:06:24.058000+00:00               443.038
         46 2024-07-07 15:15:16.171000+00:00         3              0.0              -0.0             0.0 2024-07-07 15:06:24.058000+00:00               532.113
         47 2024-07-07 15:16:45.763000+00:00         3              0.0              -0.0             0.0 2024-07-07 15:06:24.058000+00:00               621.705
         48 2024-07-07 15:18:15.134000+00:00         3              0.0              -0.0             0.0 2024-07-07 15:06:24.058000+00:00               711.076
         49 2024-07-07 15:19:44.252000+00:00         2             -1.0               1.0             0.0 2024-07-07 15:19:28.852000+00:00                15.400
         50 2024-07-07 15:21:13.702000+00:00         2              0.0              -0.0             0.0 2024-07-07 15:19:28.852000+00:00               104.850
         51 2024-07-07 15:22:42.993000+00:00         2              0.0              -0.0             0.0 2024-07-07 15:19:28.852000+00:00               194.141
         52 2024-07-07 15:24:12.328000+00:00         2              0.0              -0.0             0.0 2024-07-07 15:19:28.852000+00:00               283.476

In [29]:
lap_with_position["position_change"] = (
    lap_with_position["position_change"]
    .fillna(0)
)

lap_with_position["positions_gained"] = (
    lap_with_position["positions_gained"]
    .fillna(0)
)

lap_with_position["positions_lost"] = (
    lap_with_position["positions_lost"]
    .fillna(0)
)

lap_with_position["position_change_last_lap"] = (
    lap_with_position
    .groupby("driver_number")["position_change"]
    .shift(1)
)

lap_with_position["positions_gained_last_lap"] = (
    lap_with_position
    .groupby("driver_number")["positions_gained"]
    .shift(1)
)

lap_with_position["positions_lost_last_lap"] = (
    lap_with_position
    .groupby("driver_number")["positions_lost"]
    .shift(1)
)

print(
    lap_with_position[
        [
            "driver_number",
            "lap_number",
            "position",
            "position_change",
            "positions_gained",
            "positions_lost",
            "position_change_last_lap",
            "positions_gained_last_lap",
            "positions_lost_last_lap",
        ]
    ].head(25)
)

    driver_number  lap_number  position  position_change  positions_gained  \
0               1           1         4              0.0               0.0
1               1           2         3             -1.0               1.0
2               1           3         3              0.0              -0.0
3               1           4         3              0.0              -0.0
4               1           5         3              0.0              -0.0
5               1           6         3              0.0              -0.0
6               1           7         3              0.0              -0.0
7               1           8         3              0.0              -0.0
8               1           9         3              0.0              -0.0
9               1          10         3              0.0              -0.0
10              1          11         3              0.0              -0.0
11              1          12         3              0.0              -0.0
12              1          13         3              0.0              -0.0
13              1          14         3              0.0              -0.0
14              1          15         3              0.0              -0.0
15              1          16         4              1.0               0.0
16              1          17         4              0.0              -0.0
17              1          18         5              1.0               0.0
18              1          19         5              0.0              -0.0
19              1          20         5              0.0              -0.0
20              1          21         5              0.0              -0.0
21              1          22         5              0.0              -0.0
22              1          23         5              0.0              -0.0
23              1          24         5              0.0              -0.0
24              1          25         5              0.0              -0.0

    positions_lost  position_change_last_lap  positions_gained_last_lap  \
0              0.0                       NaN                        NaN
1              0.0                       0.0                        0.0
2              0.0                      -1.0                        1.0
3              0.0                       0.0                       -0.0
4              0.0                       0.0                       -0.0
5              0.0                       0.0                       -0.0
6              0.0                       0.0                       -0.0
7              0.0                       0.0                       -0.0
8              0.0                       0.0                       -0.0
9              0.0                       0.0                       -0.0
10             0.0                       0.0                       -0.0
11             0.0                       0.0                       -0.0
12             0.0                       0.0                       -0.0
13             0.0                       0.0                       -0.0
14             0.0                       0.0                       -0.0
15             1.0                       0.0                       -0.0
16             0.0                       1.0                        0.0
17             1.0                       0.0                       -0.0
18             0.0                       1.0                        0.0
19             0.0                       0.0                       -0.0
20             0.0                       0.0                       -0.0
21             0.0                       0.0                       -0.0
22             0.0                       0.0                       -0.0
23             0.0                       0.0                       -0.0
24             0.0                       0.0                       -0.0

    positions_lost_last_lap
0                       NaN
1                       0.0
2                       0.0
3                       0.0
4                       0.0
5                       0.0
6                       0.0
7                       0.0
8                       0.0
9                       0.0
10                      0.0
11                      0.0
12                      0.0
13                      0.0
14                      0.0
15                      0.0
16                      1.0
17                      0.0
18                      1.0
19                      0.0
20                      0.0
21                      0.0
22                      0.0
23                      0.0
24                      0.0

In [30]:
lap_with_position["driver_ahead"] = (
    lap_with_position["position"] - 1
)

lap_with_position["driver_behind"] = (
    lap_with_position["position"] + 1
)

print(
    lap_with_position[
        [
            "driver_number",
            "lap_number",
            "position",
            "driver_ahead",
            "driver_behind"
        ]
    ].head(10)
)

   driver_number  lap_number  position  driver_ahead  driver_behind
0              1           1         4             3              5
1              1           2         3             2              4
2              1           3         3             2              4
3              1           4         3             2              4
4              1           5         3             2              4
5              1           6         3             2              4
6              1           7         3             2              4
7              1           8         3             2              4
8              1           9         3             2              4
9              1          10         3             2              4

In [31]:
ahead_lookup = (
    lap_with_position[
        [
            "driver_number",
            "lap_number",
            "position"
        ]
    ]
    .rename(
        columns={
            "driver_number": "driver_ahead_number",
            "position": "driver_ahead_position"
        }
    )
)
lap_with_position = lap_with_position.merge(
    ahead_lookup,
    left_on=["lap_number", "driver_ahead"],
    right_on=["lap_number", "driver_ahead_position"],
    how="left"
)

lap_with_position = lap_with_position.drop(
    columns=["driver_ahead_position"]
)

print(
    lap_with_position[
        [
            "driver_number",
            "lap_number",
            "position",
            "driver_ahead",
            "driver_ahead_number",
            "driver_behind"
        ]
    ].head(10)
)

   driver_number  lap_number  position  driver_ahead  driver_ahead_number  \
0              1           1         4             3                  4.0
1              1           2         3             2                 44.0
2              1           3         3             2                 44.0
3              1           4         3             2                 44.0
4              1           5         3             2                 44.0
5              1           6         3             2                 44.0
6              1           7         3             2                 44.0
7              1           8         3             2                 44.0
8              1           9         3             2                 44.0
9              1          10         3             2                 44.0

   driver_behind
0              5
1              4
2              4
3              4
4              4
5              4
6              4
7              4
8              4
9              4

In [32]:
# Remove previously added traffic-performance columns
traffic_columns = [
    "ahead_lap_duration",
    "ahead_compound",
    "ahead_tyre_age",
    "ahead_stint_number",
    "behind_lap_duration",
    "behind_compound",
    "behind_tyre_age",
    "behind_stint_number",
    "driver_behind_number",
]

lap_with_position = lap_with_position.drop(
    columns=traffic_columns,
    errors="ignore"
)

ahead_performance = (
    lap_performance[
        [
            "driver_number",
            "lap_number",
            "lap_duration",
            "compound",
            "tyre_age",
            "stint_number"
        ]
    ]
    .rename(
        columns={
            "driver_number": "driver_ahead_number",
            "lap_duration": "ahead_lap_duration",
            "compound": "ahead_compound",
            "tyre_age": "ahead_tyre_age",
            "stint_number": "ahead_stint_number"
        }
    )
)

behind_performance = (
    lap_performance[
        [
            "driver_number",
            "lap_number",
            "lap_duration",
            "compound",
            "tyre_age",
            "stint_number"
        ]
    ]
    .rename(
        columns={
            "driver_number": "driver_behind_number",
            "lap_duration": "behind_lap_duration",
            "compound": "behind_compound",
            "tyre_age": "behind_tyre_age",
            "stint_number": "behind_stint_number"
        }
    )
)

lap_with_position = lap_with_position.merge(
    ahead_performance,
    on=["driver_ahead_number", "lap_number"],
    how="left"
)

lap_with_position = lap_with_position.merge(
    behind_performance,
    left_on=["lap_number", "driver_behind"],
    right_on=["lap_number", "driver_behind_number"],
    how="left"
)

print(
    lap_with_position[
        [
            "driver_number",
            "lap_number",
            "position",
            "driver_ahead_number",
            "ahead_lap_duration",
            "ahead_compound",
            "ahead_tyre_age",
            "driver_behind_number",
            "behind_lap_duration",
            "behind_compound",
            "behind_tyre_age"
        ]
    ].head(25)
)

    driver_number  lap_number  position  driver_ahead_number  \
0               1           1         4                  4.0
1               1           2         3                 44.0
2               1           3         3                 44.0
3               1           4         3                 44.0
4               1           5         3                 44.0
5               1           6         3                 44.0
6               1           7         3                 44.0
7               1           8         3                 44.0
8               1           9         3                 44.0
9               1          10         3                 44.0
10              1          11         3                 44.0
11              1          12         3                 44.0
12              1          13         3                 44.0
13              1          14         3                 44.0
14              1          15         3                 44.0
15              1          16         4                  4.0
16              1          17         4                  4.0
17              1          18         5                 81.0
18              1          19         5                 81.0
19              1          20         5                 81.0
20              1          21         5                 63.0
21              1          22         5                 63.0
22              1          23         5                 63.0
23              1          24         5                 63.0
24              1          25         5                 63.0

    ahead_lap_duration ahead_compound  ahead_tyre_age  driver_behind_number  \
0               97.721         MEDIUM             0.0                   NaN
1               91.420         MEDIUM             1.0                   4.0
2               91.716         MEDIUM             2.0                   4.0
3               91.988         MEDIUM             3.0                   4.0
4               91.677         MEDIUM             4.0                   4.0
5               91.746         MEDIUM             5.0                   4.0
6               91.675         MEDIUM             6.0                   4.0
7               91.760         MEDIUM             7.0                   4.0
8               91.564         MEDIUM             8.0                   4.0
9               91.515         MEDIUM             9.0                   4.0
10              91.487         MEDIUM            10.0                   4.0
11              91.563         MEDIUM            11.0                   4.0
12              91.881         MEDIUM            12.0                   4.0
13              91.609         MEDIUM            13.0                   4.0
14              91.563         MEDIUM            14.0                   4.0
15              91.690         MEDIUM            15.0                   NaN
16              94.304         MEDIUM            16.0                   NaN
17              94.269         MEDIUM            17.0                   NaN
18             100.728         MEDIUM            18.0                   NaN
19              97.348         MEDIUM            19.0                   NaN
20              92.753         MEDIUM            20.0                   NaN
21              91.344         MEDIUM            21.0                   NaN
22              91.497         MEDIUM            22.0                   NaN
23              91.968         MEDIUM            23.0                   NaN
24              94.781         MEDIUM            24.0                   NaN

    behind_lap_duration behind_compound  behind_tyre_age
0                   NaN             NaN              NaN
1                92.188          MEDIUM              1.0
2                91.991          MEDIUM              2.0
3                91.976          MEDIUM              3.0
4                91.716          MEDIUM              4.0
5                91.896          MEDIUM              5.0
6                92.071          MEDIUM              6.0
7                92.018          MEDIUM              7.0
8                91.976          MEDIUM              8.0
9                91.830          MEDIUM              9.0
10               91.748          MEDIUM             10.0
11               91.718          MEDIUM             11.0
12               91.472          MEDIUM             12.0
13               91.407          MEDIUM             13.0
14               90.946          MEDIUM             14.0
15                  NaN             NaN              NaN
16                  NaN             NaN              NaN
17                  NaN             NaN              NaN
18                  NaN             NaN              NaN
19                  NaN             NaN              NaN
20                  NaN             NaN              NaN
21                  NaN             NaN              NaN
22                  NaN             NaN              NaN
23                  NaN             NaN              NaN
24                  NaN             NaN              NaN

In [33]:
max_traffic = lap_with_position[
    lap_with_position["driver_number"] == 1
][
    [
        "lap_number",
        "position",
        "driver_ahead",
        "driver_ahead_number",
        "driver_behind",
        "driver_behind_number"
    ]
]

print(max_traffic.to_string(index=False))

 lap_number  position  driver_ahead  driver_ahead_number  driver_behind  driver_behind_number
          1         4             3                  4.0              5                   NaN
          2         3             2                 44.0              4                   4.0
          3         3             2                 44.0              4                   4.0
          4         3             2                 44.0              4                   4.0
          5         3             2                 44.0              4                   4.0
          6         3             2                 44.0              4                   4.0
          7         3             2                 44.0              4                   4.0
          8         3             2                 44.0              4                   4.0
          9         3             2                 44.0              4                   4.0
         10         3             2                 44.0              4                   4.0
         11         3             2                 44.0              4                   4.0
         12         3             2                 44.0              4                   4.0
         13         3             2                 44.0              4                   4.0
         14         3             2                 44.0              4                   4.0
         15         3             2                 44.0              4                   4.0
         16         4             3                  4.0              5                   NaN
         17         4             3                  4.0              5                   NaN
         18         5             4                 81.0              6                   NaN
         19         5             4                 81.0              6                   NaN
         20         5             4                 81.0              6                   NaN
         21         5             4                 63.0              6                   NaN
         22         5             4                 63.0              6                   NaN
         23         5             4                 63.0              6                   NaN
         24         5             4                 63.0              6                   NaN
         25         5             4                 63.0              6                   NaN
         26         5             4                 63.0              6                   NaN
         27         5             4                 63.0              6                   NaN
         28         5             4                 63.0              6                   NaN
         29         4             3                 44.0              5                   NaN
         30         3             2                 44.0              4                   4.0
         31         3             2                 44.0              4                   4.0
         32         3             2                 44.0              4                   4.0
         33         3             2                 44.0              4                   4.0
         34         3             2                 44.0              4                   4.0
         35         3             2                 44.0              4                   4.0
         36         3             2                 44.0              4                   4.0
         37         3             2                 44.0              4                   4.0
         38         3             2                 44.0              4                   4.0
         39         3             2                 44.0              4                   4.0
         40         4             3                 44.0              5                   NaN
         41         3             2                  4.0              4                   4.0
         42         3             2                  4.0              4                   4.0
         43         3             2                  4.0              4                   4.0
         44         3             2                  4.0              4                   4.0
         45         3             2                  4.0              4                   4.0
         46         3             2                  4.0              4                   4.0
         47         3             2                  4.0              4                   4.0
         48         3             2                  4.0              4                   4.0
         49         2             1                 44.0              3                   3.0
         50         2             1                 44.0              3                   3.0
         51         2             1                 44.0              3                   3.0
         52         2             1                 44.0              3                   NaN

In [34]:
print("lap_with_position shape:", lap_with_position.shape)
print("Columns")
for col in lap_with_position.columns:
    print(col)

lap_with_position shape: (962, 30)
Columns
date_start
driver_number
lap_number
position_event_time
position
position_age_seconds
is_race_started
last_lap
last_lap_time
seconds_from_last_lap
position_status
driver_active
position_change
positions_gained
positions_lost
position_change_last_lap
positions_gained_last_lap
positions_lost_last_lap
driver_ahead
driver_behind
driver_ahead_number
ahead_lap_duration
ahead_compound
ahead_tyre_age
ahead_stint_number
driver_behind_number
behind_lap_duration
behind_compound
behind_tyre_age
behind_stint_number

In [35]:
# Inspect Max Verstappen's traffic-related data

max_traffic_check = lap_with_position[
    lap_with_position["driver_number"] == 1
]

print(
    max_traffic_check[
        [
            "lap_number",
            "position",
            "driver_ahead",
            "driver_ahead_number",
            "driver_behind",
            "driver_behind_number"
        ]
    ].head(20).to_string(index=False)
)

 lap_number  position  driver_ahead  driver_ahead_number  driver_behind  driver_behind_number
          1         4             3                  4.0              5                   NaN
          2         3             2                 44.0              4                   4.0
          3         3             2                 44.0              4                   4.0
          4         3             2                 44.0              4                   4.0
          5         3             2                 44.0              4                   4.0
          6         3             2                 44.0              4                   4.0
          7         3             2                 44.0              4                   4.0
          8         3             2                 44.0              4                   4.0
          9         3             2                 44.0              4                   4.0
         10         3             2                 44.0              4                   4.0
         11         3             2                 44.0              4                   4.0
         12         3             2                 44.0              4                   4.0
         13         3             2                 44.0              4                   4.0
         14         3             2                 44.0              4                   4.0
         15         3             2                 44.0              4                   4.0
         16         4             3                  4.0              5                   NaN
         17         4             3                  4.0              5                   NaN
         18         5             4                 81.0              6                   NaN
         19         5             4                 81.0              6                   NaN
         20         5             4                 81.0              6                   NaN

In [36]:
gap_columns = [
    col for col in lap_with_position.columns
    if "gap" in col.lower()
]
print("Gap related columns:")
print(gap_columns)

Gap related columns:
[]

In [37]:
traffic_features = lap_with_position[
    [
        "driver_number",
        "lap_number",
        "position",
        "driver_ahead_number",
        "driver_behind_number",
        "position_change"
    ]
].copy()

traffic_features["traffic_ahead"] = (
    traffic_features["driver_ahead_number"].notna()
).astype(int)

traffic_features["traffic_behind"] = (
    traffic_features["driver_behind_number"].notna()
).astype(int)

traffic_features = traffic_features[
    [
        "driver_number",
        "lap_number",
        "position",
        "traffic_ahead",
        "traffic_behind",
        "position_change"
    ]
]

print("Traffic features shape:", traffic_features.shape)

print(
    traffic_features.head(20).to_string(index=False)
)

Traffic features shape: (962, 6)
 driver_number  lap_number  position  traffic_ahead  traffic_behind  position_change
             1           1         4              1               0              0.0
             1           2         3              1               1             -1.0
             1           3         3              1               1              0.0
             1           4         3              1               1              0.0
             1           5         3              1               1              0.0
             1           6         3              1               1              0.0
             1           7         3              1               1              0.0
             1           8         3              1               1              0.0
             1           9         3              1               1              0.0
             1          10         3              1               1              0.0
             1          11         3              1               1              0.0
             1          12         3              1               1              0.0
             1          13         3              1               1              0.0
             1          14         3              1               1              0.0
             1          15         3              1               1              0.0
             1          16         4              1               0              1.0
             1          17         4              1               0              0.0
             1          18         5              1               0              1.0
             1          19         5              1               0              0.0
             1          20         5              1               0              0.0

In [38]:
print("\nMissing values:")
print(traffic_features.isna().sum())

print("\nTraffic ahead distribution:")
print(traffic_features["traffic_ahead"].value_counts())

print("\nTraffic behind distribution:")
print(traffic_features["traffic_behind"].value_counts())

print("\nPosition change distribution:")
print(traffic_features["position_change"].value_counts().sort_index())

Missing values:
driver_number      0
lap_number         0
position           0
traffic_ahead      0
traffic_behind     0
position_change    0
dtype: int64

Traffic ahead distribution:
traffic_ahead
1    908
0     54
Name: count, dtype: int64

Traffic behind distribution:
traffic_behind
0    569
1    393
Name: count, dtype: int64

Position change distribution:
position_change
-5.0      2
-3.0      2
-2.0     13
-1.0     65
 0.0    824
 1.0     39
 2.0      9
 3.0      4
 5.0      3
 8.0      1
Name: count, dtype: int64

In [39]:
traffic_features.to_parquet(
    "pitwall/data/processed/9558/traffic_features.parquet",
    index=False
)

print("Shape:", traffic_features.shape)

OSError: Cannot save file into a non-existent directory: 'pitwall\data\processed\9558'

In [40]:
from pathlib import Path

output_dir = Path("../data/processed/9558")
output_dir.mkdir(parents=True, exist_ok=True)

traffic_features.to_parquet(
    output_dir / "traffic_features.parquet",
    index=False
)

print("Saved:", (output_dir / "traffic_features.parquet").resolve())

Saved: C:\Users\Nihan\.vscode\pitwall\data\processed\9558\traffic_features.parquet