In [3]:
import pandas as pd
import numpy as np

from pathlib import Path

DATA_DIR = Path("../data/processed/9558")

lap_data = pd.read_parquet(DATA_DIR / "lap_performance.parquet")

print("Shape:", lap_data.shape)
print("\nColumns:")
print(lap_data.columns.tolist())

print("\nFirst 5 rows:")
display(lap_data.head())

Shape: (962, 19)

Columns:
['meeting_key', 'session_key', 'driver_number', 'lap_number', 'date_start', 'duration_sector_1', 'duration_sector_2', 'duration_sector_3', 'i1_speed', 'i2_speed', 'is_pit_out_lap', 'lap_duration', 'segments_sector_1', 'segments_sector_2', 'segments_sector_3', 'st_speed', 'stint_number', 'compound', 'tyre_age']

First 5 rows:

   meeting_key  session_key  driver_number  ...  stint_number compound  tyre_age
0         1240         9558              1  ...           1.0   MEDIUM       0.0
1         1240         9558              1  ...           1.0   MEDIUM       1.0
2         1240         9558              1  ...           1.0   MEDIUM       2.0
3         1240         9558              1  ...           1.0   MEDIUM       3.0
4         1240         9558              1  ...           1.0   MEDIUM       4.0

[5 rows x 19 columns]

In [4]:
print("Tyre age summary:")
display(
    lap_data["tyre_age"].describe()
)

print("\nTyre age by compound:")
display(
    lap_data.groupby("compound")["tyre_age"]
    .agg(["count", "min", "median", "mean", "max"])
)

print("\nNumber of observations by compound:")
display(
    lap_data["compound"].value_counts()
)

Tyre age summary:

count    960.000000
mean       8.736458
std        6.808441
min        0.000000
25%        3.000000
50%        7.000000
75%       12.000000
max       27.000000
Name: tyre_age, dtype: float64

Tyre age by compound:

              count  min  median       mean   max
compound
HARD             44  0.0     7.0   7.204545  18.0
INTERMEDIATE    234  0.0     5.0   4.888889  12.0
MEDIUM          508  0.0    11.0  11.417323  27.0
SOFT            174  0.0     6.0   6.471264  18.0

Number of observations by compound:

compound
MEDIUM          508
INTERMEDIATE    234
SOFT            174
HARD             44
Name: count, dtype: int64

In [5]:
for compound in ["SOFT", "MEDIUM", "HARD"]:
    subset = lap_data[lap_data["compound"] == compound]

    print(f"\n{compound}")
    print("-" * 40)

    display(
        subset.groupby("tyre_age")["lap_duration"]
        .agg(["count", "mean", "median"])
        .head(20)
    )

SOFT
----------------------------------------

          count        mean    median
tyre_age
0.0          14  117.528786  117.6000
1.0          14   92.537286   92.5070
2.0          13   91.592692   90.8780
3.0          12   90.997667   90.4645
4.0          12   90.914000   90.3105
5.0          12   90.984583   90.6680
6.0          12   91.361417   91.1785
7.0          12   91.589750   91.1575
8.0          12   91.397333   91.0565
9.0          12   91.456500   91.1185
10.0         12   91.468500   91.0945
11.0         12   91.746583   91.3280
12.0         11   91.730455   91.5290
13.0          8   92.473875   92.0890
14.0          2   93.433000   93.4330
15.0          1   96.522000   96.5220
16.0          1   98.735000   98.7350
17.0          1   98.497000   98.4970
18.0          1  101.731000  101.7310

MEDIUM
----------------------------------------

          count        mean    median
tyre_age
0.0          24  105.869875  102.0065
1.0          24   92.572917   92.7025
2.0          24   92.425667   92.3380
3.0          24   92.834083   92.3040
4.0          24   93.248417   92.2730
5.0          23   92.250783   92.0620
6.0          23   92.568043   92.6620
7.0          22   91.881409   92.2050
8.0          22   91.895955   92.3085
9.0          22   92.078909   92.4005
10.0         21   91.855143   92.1230
11.0         21   91.861048   92.2360
12.0         20   91.923000   92.1200
13.0         19   91.978158   92.3830
14.0         16   92.302375   92.4040
15.0         16   92.881250   93.0070
16.0         16   94.922500   94.9435
17.0         16   95.438312   95.5905
18.0         16  104.101625  104.2885
19.0         15   97.383667   97.3300

HARD
----------------------------------------

          count        mean    median
tyre_age
0.0           2  117.532000  117.5320
1.0           3   91.157667   90.4750
2.0           3   90.605333   89.8720
3.0           3   90.638000   89.8720
4.0           3   90.318333   89.7390
5.0           3   90.403667   89.5890
6.0           3   90.679333   89.5880
7.0           3   90.834333   89.5530
8.0           3   90.542000   89.4150
9.0           3   90.366667   89.4390
10.0          3   90.495000   89.5600
11.0          2   90.897500   90.8975
12.0          2   91.107500   91.1075
13.0          2   90.788500   90.7885
14.0          1   92.702000   92.7020
15.0          1   94.231000   94.2310
16.0          1   94.829000   94.8290
17.0          1   95.384000   95.3840
18.0          1  101.868000  101.8680

In [6]:
stint_check = (
    lap_data[
        lap_data["compound"].isin(["SOFT", "MEDIUM", "HARD"])
    ].sort_values(
        ["driver_number","stint_number","lap_number"]
    )
)

display(
    stint_check[
        [
            "driver_number",
            "stint_number",
            "lap_number",
            "compound",
            "tyre_age",
            "lap_duration"
        ]
    ].head(40)
)

    driver_number  stint_number  lap_number compound  tyre_age  lap_duration
0               1           1.0           1   MEDIUM       0.0        97.211
1               1           1.0           2   MEDIUM       1.0        91.773
2               1           1.0           3   MEDIUM       2.0        92.200
3               1           1.0           4   MEDIUM       3.0        91.933
4               1           1.0           5   MEDIUM       4.0        91.778
5               1           1.0           6   MEDIUM       5.0        91.711
6               1           1.0           7   MEDIUM       6.0        91.935
7               1           1.0           8   MEDIUM       7.0        92.038
8               1           1.0           9   MEDIUM       8.0        91.883
9               1           1.0          10   MEDIUM       9.0        91.661
10              1           1.0          11   MEDIUM      10.0        91.810
11              1           1.0          12   MEDIUM      11.0        91.894
12              1           1.0          13   MEDIUM      12.0        91.759
13              1           1.0          14   MEDIUM      13.0        91.700
14              1           1.0          15   MEDIUM      14.0        92.249
15              1           1.0          16   MEDIUM      15.0        92.504
16              1           1.0          17   MEDIUM      16.0        95.359
17              1           1.0          18   MEDIUM      17.0        96.172
18              1           1.0          19   MEDIUM      18.0       102.485
19              1           1.0          20   MEDIUM      19.0        97.108
20              1           1.0          21   MEDIUM      20.0        93.488
21              1           1.0          22   MEDIUM      21.0        91.904
22              1           1.0          23   MEDIUM      22.0        92.143
23              1           1.0          24   MEDIUM      23.0        93.020
24              1           1.0          25   MEDIUM      24.0        96.063
25              1           1.0          26   MEDIUM      25.0       101.491
38              1           3.0          39     HARD       0.0       118.311
39              1           3.0          40     HARD       1.0        90.056
40              1           3.0          41     HARD       2.0        89.604
41              1           3.0          42     HARD       3.0        89.472
42              1           3.0          43     HARD       4.0        89.105
43              1           3.0          44     HARD       5.0        89.372
44              1           3.0          45     HARD       6.0        89.137
45              1           3.0          46     HARD       7.0        89.543
46              1           3.0          47     HARD       8.0        89.411
47              1           3.0          48     HARD       9.0        88.952
48              1           3.0          49     HARD      10.0        89.560
49              1           3.0          50     HARD      11.0        89.286
50              1           3.0          51     HARD      12.0        89.443
51              1           3.0          52     HARD      13.0        89.089

In [7]:
stint_progression = (
    stint_check.groupby(
        ["driver_number","stint_number","compound"]
    )
    .agg(
        laps=("lap_number", "count"),
        first_lap=("lap_number", "min"),
        last_lap=("lap_number", "max"),
        min_tyre_age=("tyre_age", "min"),
        max_tyre_age=("tyre_age", "max")
    ).reset_index()
)
display(stint_progression.head(30))

    driver_number  stint_number compound  ...  last_lap  min_tyre_age  max_tyre_age
0               1           1.0   MEDIUM  ...        26           0.0          25.0
1               1           3.0     HARD  ...        52           0.0          13.0
2               2           1.0   MEDIUM  ...        27           0.0          26.0
3               2           3.0     SOFT  ...        52           0.0          13.0
4               3           1.0   MEDIUM  ...        26           0.0          25.0
5               3           3.0     SOFT  ...        51           0.0          13.0
6               4           1.0   MEDIUM  ...        27           0.0          26.0
7               4           3.0     SOFT  ...        52           0.0          12.0
8              11           1.0     HARD  ...        19           0.0          18.0
9              11           4.0   MEDIUM  ...        47           0.0           9.0
10             11           5.0     SOFT  ...        50           0.0           2.0
11             14           1.0   MEDIUM  ...        27           0.0          26.0
12             14           3.0   MEDIUM  ...        52           0.0          13.0
13             16           1.0   MEDIUM  ...        19           0.0          18.0
14             16           4.0     SOFT  ...        51           0.0          13.0
15             18           1.0   MEDIUM  ...        26           0.0          25.0
16             18           3.0   MEDIUM  ...        52           0.0          12.0
17             20           1.0   MEDIUM  ...        27           0.0          26.0
18             20           3.0     SOFT  ...        52           0.0          14.0
19             22           1.0   MEDIUM  ...        27           0.0          26.0
20             22           3.0     SOFT  ...        52           0.0          13.0
21             23           1.0   MEDIUM  ...        27           0.0          26.0
22             23           3.0   MEDIUM  ...        52           0.0          13.0
23             24           1.0     SOFT  ...        12           0.0          11.0
24             24           2.0   MEDIUM  ...        19           0.0           6.0
25             24           5.0     SOFT  ...        50           0.0          12.0
26             27           1.0   MEDIUM  ...        26           0.0          25.0
27             27           3.0     SOFT  ...        52           0.0          12.0
28             31           1.0     SOFT  ...        19           0.0          18.0
29             31           3.0   MEDIUM  ...        26           0.0           4.0

[30 rows x 8 columns]

In [8]:
degradation_data = lap_data[
    lap_data["compound"].isin(["SOFT","MEDIUM","HARD"])
].copy()

degradation_data = degradation_data[
    degradation_data["tyre_age"] >= 1
].copy()

print("Candidate degradation dataset shape:")
print(degradation_data.shape)
print("\nRows by compound:")
print(
    degradation_data["compound"].value_counts()
)

print("\nTyre-age coverage:")
display(
    degradation_data
    .groupby("compound")["tyre_age"]
    .agg(
        count="count",
        min="min",
        median="median",
        mean="mean",
        max="max"
    )
)

Candidate degradation dataset shape:
(685, 19)

Rows by compound:
compound
MEDIUM    484
SOFT      160
HARD       41
Name: count, dtype: int64

Tyre-age coverage:

          count  min  median       mean   max
compound
HARD         41  1.0     7.0   7.731707  18.0
MEDIUM      484  1.0    11.0  11.983471  27.0
SOFT        160  1.0     7.0   7.037500  18.0

In [9]:
degradation_summary = (
    degradation_data.groupby(["compound", "tyre_age"])["lap_duration"]
    .agg(
        count="count",
        mean="mean",
        median="median",
        std="std"
    ).reset_index()
)

for compound in ["SOFT", "MEDIUM", "HARD"]:
    print(f"{compound}")

    display(
        degradation_summary[
            (degradation_summary["compound"] == compound) & (degradation_summary["count"] >= 3)
        ]
    )

SOFT

   compound  tyre_age  count       mean   median       std
45     SOFT       1.0     14  92.537286  92.5070  2.530658
46     SOFT       2.0     13  91.592692  90.8780  1.388789
47     SOFT       3.0     12  90.997667  90.4645  1.501193
48     SOFT       4.0     12  90.914000  90.3105  1.304096
49     SOFT       5.0     12  90.984583  90.6680  1.431136
50     SOFT       6.0     12  91.361417  91.1785  1.764778
51     SOFT       7.0     12  91.589750  91.1575  1.987143
52     SOFT       8.0     12  91.397333  91.0565  1.631132
53     SOFT       9.0     12  91.456500  91.1185  1.720455
54     SOFT      10.0     12  91.468500  91.0945  1.532484
55     SOFT      11.0     12  91.746583  91.3280  1.407992
56     SOFT      12.0     11  91.730455  91.5290  1.454493
57     SOFT      13.0      8  92.473875  92.0890  1.726039

MEDIUM

   compound  tyre_age  count        mean    median       std
18   MEDIUM       1.0     24   92.572917   92.7025  1.384402
19   MEDIUM       2.0     24   92.425667   92.3380  1.662960
20   MEDIUM       3.0     24   92.834083   92.3040  3.388307
21   MEDIUM       4.0     24   93.248417   92.2730  5.691730
22   MEDIUM       5.0     23   92.250783   92.0620  2.029553
23   MEDIUM       6.0     23   92.568043   92.6620  3.246345
24   MEDIUM       7.0     22   91.881409   92.2050  1.238738
25   MEDIUM       8.0     22   91.895955   92.3085  1.266463
26   MEDIUM       9.0     22   92.078909   92.4005  1.492294
27   MEDIUM      10.0     21   91.855143   92.1230  1.112550
28   MEDIUM      11.0     21   91.861048   92.2360  0.984157
29   MEDIUM      12.0     20   91.923000   92.1200  1.246850
30   MEDIUM      13.0     19   91.978158   92.3830  0.929209
31   MEDIUM      14.0     16   92.302375   92.4040  0.650227
32   MEDIUM      15.0     16   92.881250   93.0070  0.810968
33   MEDIUM      16.0     16   94.922500   94.9435  0.627178
34   MEDIUM      17.0     16   95.438312   95.5905  0.807274
35   MEDIUM      18.0     16  104.101625  104.2885  2.060566
36   MEDIUM      19.0     15   97.383667   97.3300  1.313078
37   MEDIUM      20.0     15   93.241200   93.4840  0.990864
38   MEDIUM      21.0     15   92.288933   92.4950  0.879801
39   MEDIUM      22.0     15   92.635467   92.6120  1.127888
40   MEDIUM      23.0     15   93.597600   93.6250  1.702777
41   MEDIUM      24.0     15   95.826400   95.4730  1.510135
42   MEDIUM      25.0     15  102.972667  102.4810  2.487021
43   MEDIUM      26.0      9  108.377556  108.1260  2.485486

HARD

  compound  tyre_age  count       mean  median       std
0     HARD       1.0      3  91.157667  90.475  1.559415
1     HARD       2.0      3  90.605333  89.872  1.508230
2     HARD       3.0      3  90.638000  89.872  1.685072
3     HARD       4.0      3  90.318333  89.739  1.584528
4     HARD       5.0      3  90.403667  89.589  1.602649
5     HARD       6.0      3  90.679333  89.588  2.291942
6     HARD       7.0      3  90.834333  89.553  2.228000
7     HARD       8.0      3  90.542000  89.415  1.955486
8     HARD       9.0      3  90.366667  89.439  2.043083
9     HARD      10.0      3  90.495000  89.560  1.729734

In [10]:
fuel_features = pd.read_parquet(
    DATA_DIR / "fuel_features.parquet"
)

print("Fuel featues:")
print(fuel_features.head())

print(fuel_features.shape)

degradation_data = degradation_data.merge(
    fuel_features,
    on=["driver_number", "lap_number"],
    how="left",
    validate="one_to_one"
)

print("Merged shape:", degradation_data.shape)
print("Missing fuel effects:")
print(degradation_data["fuel_effect"].isna().sum())

display(
    degradation_data[
        [
            "driver_number",
            "lap_number",
            "compound",
            "tyre_age",
            "lap_duration",
            "fuel_effect"
        ]
    ].head(20)
)

Fuel featues:
   driver_number  lap_number  fuel_effect
0              1           1    -0.000000
1              1           2    -0.084122
2              1           3    -0.168244
3              1           4    -0.252366
4              1           5    -0.336488
(692, 3)
Merged shape: (685, 20)
Missing fuel effects:
11

    driver_number  lap_number compound  tyre_age  lap_duration  fuel_effect
0               1           2   MEDIUM       1.0        91.773    -0.084122
1               1           3   MEDIUM       2.0        92.200    -0.168244
2               1           4   MEDIUM       3.0        91.933    -0.252366
3               1           5   MEDIUM       4.0        91.778    -0.336488
4               1           6   MEDIUM       5.0        91.711    -0.420610
5               1           7   MEDIUM       6.0        91.935    -0.504732
6               1           8   MEDIUM       7.0        92.038    -0.588854
7               1           9   MEDIUM       8.0        91.883    -0.672976
8               1          10   MEDIUM       9.0        91.661    -0.757098
9               1          11   MEDIUM      10.0        91.810    -0.841220
10              1          12   MEDIUM      11.0        91.894    -0.925342
11              1          13   MEDIUM      12.0        91.759    -1.009464
12              1          14   MEDIUM      13.0        91.700    -1.093586
13              1          15   MEDIUM      14.0        92.249    -1.177708
14              1          16   MEDIUM      15.0        92.504    -1.261830
15              1          17   MEDIUM      16.0        95.359    -1.345952
16              1          18   MEDIUM      17.0        96.172    -1.430074
17              1          19   MEDIUM      18.0       102.485    -1.514196
18              1          20   MEDIUM      19.0        97.108    -1.598317
19              1          21   MEDIUM      20.0        93.488    -1.682439

In [11]:
degradation_data["fuel_adjusted_lap_duration"] = (
    degradation_data["lap_duration"] - degradation_data["fuel_effect"]
)

display(
    degradation_data[
        [
            "driver_number",
            "lap_number",
            "compound",
            "tyre_age",
            "lap_duration",
            "fuel_effect",
            "fuel_adjusted_lap_duration"
        ]
    ].head(20)
)

    driver_number  lap_number  ... fuel_effect  fuel_adjusted_lap_duration
0               1           2  ...   -0.084122                   91.857122
1               1           3  ...   -0.168244                   92.368244
2               1           4  ...   -0.252366                   92.185366
3               1           5  ...   -0.336488                   92.114488
4               1           6  ...   -0.420610                   92.131610
5               1           7  ...   -0.504732                   92.439732
6               1           8  ...   -0.588854                   92.626854
7               1           9  ...   -0.672976                   92.555976
8               1          10  ...   -0.757098                   92.418098
9               1          11  ...   -0.841220                   92.651220
10              1          12  ...   -0.925342                   92.819342
11              1          13  ...   -1.009464                   92.768464
12              1          14  ...   -1.093586                   92.793586
13              1          15  ...   -1.177708                   93.426708
14              1          16  ...   -1.261830                   93.765830
15              1          17  ...   -1.345952                   96.704952
16              1          18  ...   -1.430074                   97.602074
17              1          19  ...   -1.514196                  103.999196
18              1          20  ...   -1.598317                   98.706317
19              1          21  ...   -1.682439                   95.170439

[20 rows x 7 columns]

In [12]:
adjusted_degradation_summary = (
    degradation_data
    .groupby(["compound","tyre_age"])["fuel_adjusted_lap_duration"]
    .agg(
        count="count",
        mean="mean",
        median="median",
        std="std"
    ).reset_index()
)
for compound in ["SOFT", "MEDIUM", "HARD"]:
    print(f"{compound} - FUEL ADJUSTED")
    display(
        adjusted_degradation_summary[
            (adjusted_degradation_summary["compound"] == compound) &
            (adjusted_degradation_summary["count"] >= 3)
        ]
    )

SOFT - FUEL ADJUSTED

   compound  tyre_age  count       mean     median       std
45     SOFT       1.0     14  95.469537  94.655696  2.570462
46     SOFT       2.0     13  94.504607  94.158757  1.060506
47     SOFT       3.0     12  93.892865  93.520866  1.037022
48     SOFT       4.0     12  93.893320  93.651305  0.710402
49     SOFT       5.0     12  94.048025  94.011866  0.627803
50     SOFT       6.0     12  94.508980  94.795745  0.761068
51     SOFT       7.0     12  94.821436  94.633928  1.185942
52     SOFT       8.0     12  94.713141  94.743050  0.676677
53     SOFT       9.0     12  94.856430  94.755111  0.753237
54     SOFT      10.0     12  94.952552  94.984733  0.654801
55     SOFT      11.0     12  95.314757  95.078342  0.824748
56     SOFT      12.0     11  95.623008  95.500464  1.104784
57     SOFT      13.0      8  96.322455  96.379221  1.280100

MEDIUM - FUEL ADJUSTED

   compound  tyre_age  count        mean      median       std
18   MEDIUM       1.0     24   93.571865   93.292122  1.459615
19   MEDIUM       2.0     24   93.508737   93.328744  1.739798
20   MEDIUM       3.0     24   94.001276   93.362366  3.436105
21   MEDIUM       4.0     23   93.355674   93.104488  1.515283
22   MEDIUM       5.0     23   93.549187   93.208610  1.791909
23   MEDIUM       6.0     23   93.950570   93.321732  3.098003
24   MEDIUM       7.0     22   93.342072   93.388854  0.628302
25   MEDIUM       8.0     22   93.440740   93.247476  1.068632
26   MEDIUM       9.0     22   93.707816   93.441098  1.540726
27   MEDIUM      10.0     21   93.461472   93.389220  0.744796
28   MEDIUM      11.0     21   93.551499   93.456342  0.795048
29   MEDIUM      12.0     20   93.575997   93.637964  0.679193
30   MEDIUM      13.0     19   93.576475   93.631586  0.756281
31   MEDIUM      14.0     16   93.480083   93.581708  0.650227
32   MEDIUM      15.0     16   94.143080   94.268830  0.810968
33   MEDIUM      16.0     16   96.268452   96.289452  0.627178
34   MEDIUM      17.0     16   96.868386   97.020574  0.807274
35   MEDIUM      18.0     16  105.615821  105.802696  2.060566
36   MEDIUM      19.0     15   98.981984   98.928317  1.313078
37   MEDIUM      20.0     15   94.923639   95.166439  0.990864
38   MEDIUM      21.0     15   94.055495   94.261561  0.879801
39   MEDIUM      22.0     15   94.486150   94.462683  1.127888
40   MEDIUM      23.0     15   95.532405   95.559805  1.702777
41   MEDIUM      24.0     15   97.845327   97.491927  1.510135
42   MEDIUM      25.0     15  105.075716  104.584049  2.487021

HARD - FUEL ADJUSTED

  compound  tyre_age  count       mean     median       std
0     HARD       1.0      3  93.400919  93.336757  0.410655
1     HARD       2.0      3  92.932708  92.968879  0.407584
2     HARD       3.0      3  93.049497  92.921001  0.311905
3     HARD       4.0      3  92.813952  92.638123  0.479215
4     HARD       5.0      3  92.983407  92.989245  0.309920
5     HARD       6.0      3  93.343196  93.373489  0.490385
6     HARD       7.0      3  93.582318  93.422611  0.361212
7     HARD       8.0      3  93.374106  93.368733  0.096295
8     HARD       9.0      3  93.282895  93.466098  0.326676
9     HARD      10.0      3  93.495350  93.555977  0.142819

In [13]:

for compound in ["SOFT", "MEDIUM", "HARD"]:

    subset = degradation_data[
        degradation_data["compound"] == compound
    ]["fuel_adjusted_lap_duration"]

    q1 = subset.quantile(0.25)
    q3 = subset.quantile(0.75)
    iqr = q3 - q1

    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    outliers = subset[
        (subset < lower) | (subset > upper)
    ]

    print(f"\n===== {compound} =====")
    print(f"Q1: {q1:.3f}")
    print(f"Q3: {q3:.3f}")
    print(f"IQR: {iqr:.3f}")
    print(f"Lower bound: {lower:.3f}")
    print(f"Upper bound: {upper:.3f}")
    print(f"Potential outliers: {len(outliers)}")
    print(f"Total observations: {len(subset)}")

===== SOFT =====
Q1: 93.823
Q3: 95.515
IQR: 1.692
Lower bound: 91.285
Upper bound: 98.052
Potential outliers: 7
Total observations: 160

===== MEDIUM =====
Q1: 93.119
Q3: 95.560
IQR: 2.441
Lower bound: 89.458
Upper bound: 99.221
Potential outliers: 44
Total observations: 484

===== HARD =====
Q1: 93.026
Q3: 93.598
IQR: 0.572
Lower bound: 92.169
Upper bound: 94.455
Potential outliers: 4
Total observations: 41

In [14]:
for compound in ["SOFT","MEDIUM", "HARD"]:
    subset = degradation_data[
        degradation_data["compound"] == compound
    ].copy()

    q1 = subset["fuel_adjusted_lap_duration"].quantile(0.25)
    q3 = subset["fuel_adjusted_lap_duration"].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5*iqr
    upper = q3 + 1.5*iqr
    suspicious = subset[
        (subset["fuel_adjusted_lap_duration"] < lower) |
        (subset["fuel_adjusted_lap_duration"] > upper)
    ]

    print(f"\n===== {compound} suspicious laps =====")

    display(
        suspicious[
            [
                "driver_number",
                "lap_number",
                "stint_number",
                "compound",
                "tyre_age",
                "lap_duration",
                "fuel_effect",
                "fuel_adjusted_lap_duration"
            ]
        ]
        .sort_values("fuel_adjusted_lap_duration", ascending=False)
    )

===== SOFT suspicious laps =====

     driver_number  lap_number  ...  fuel_effect fuel_adjusted_lap_duration
490             31          19  ...    -1.514196                 103.245196
180             11          49  ...    -4.037855                 101.397855
632             77          39  ...    -3.196635                 100.310635
488             31          17  ...    -1.345952                 100.080952
489             31          18  ...    -1.430074                  99.927074
114              3          51  ...    -4.206099                  99.020099
113              3          50  ...    -4.121977                  98.271977

[7 rows x 8 columns]

===== MEDIUM suspicious laps =====

     driver_number  lap_number  ...  fuel_effect fuel_adjusted_lap_duration
631             77          26  ...    -2.103049                 111.636049
493             31          25  ...    -2.018927                 109.450927
269             18          19  ...    -1.514196                 109.082196
199             14          19  ...    -1.514196                 108.784196
423             24          19  ...    -1.514196                 107.827196
313             20          26  ...    -2.103049                 107.569049
238             16          19  ...    -1.514196                 107.382196
453             27          19  ...    -1.514196                 107.266196
101              3          26  ...    -2.103049                 106.916049
62               2          26  ...    -2.103049                 106.745049
94               3          19  ...    -1.514196                 106.436196
385             23          19  ...    -1.514196                 106.133196
346             22          19  ...    -1.514196                 106.099196
624             77          19  ...    -1.514196                 105.940196
392             23          26  ...    -2.103049                 105.874049
206             14          26  ...    -2.103049                 105.721049
598             63          19  ...    -1.514196                 105.665196
55               2          19  ...    -1.514196                 105.604196
353             22          26  ...    -2.103049                 105.363049
523             44          19  ...    -1.514196                 105.225196
306             20          19  ...    -1.514196                 105.019196
569             55          26  ...    -2.103049                 104.584049
17               1          19  ...    -1.514196                 103.999196
460             27          26  ...    -2.103049                 103.956049
139              4          26  ...    -2.103049                 103.618049
24               1          26  ...    -2.103049                 103.594049
132              4          19  ...    -1.514196                 102.950196
530             44          26  ...    -2.103049                 102.895049
276             18          26  ...    -2.103049                 102.887049
669             81          26  ...    -2.103049                 102.725049
662             81          19  ...    -1.514196                 102.242196
605             63          26  ...    -2.103049                 102.052049
562             55          19  ...    -1.514196                 102.024196
630             77          25  ...    -2.018927                 101.779927
524             44          20  ...    -1.598317                 101.619317
599             63          20  ...    -1.598317                 101.560317
422             24          18  ...    -1.430074                 101.067074
100              3          25  ...    -2.018927                 100.743927
625             77          20  ...    -1.598317                 100.140317
492             31          24  ...    -1.934805                  99.939805
503             31          48  ...    -3.953733                  99.884733
421             24          17  ...    -1.345952                  99.451952
133              4          20  ...    -1.598317                  99.302317
629             77          24  ...    -1.934805                  99.284805

[44 rows x 8 columns]

===== HARD suspicious laps =====

     driver_number  lap_number  ...  fuel_effect fuel_adjusted_lap_duration
170             11          19  ...    -1.514196                 103.382196
169             11          18  ...    -1.430074                  96.814074
168             11          17  ...    -1.345952                  96.174952
167             11          16  ...    -1.261830                  95.492830

[4 rows x 8 columns]

In [15]:
traffic_features = pd.read_parquet(
    DATA_DIR / "traffic_features.parquet"
)

traffic_features.head()
traffic_features[
    traffic_features.duplicated(
        subset=["driver_number", "lap_number"],
        keep=False
    )
].sort_values(
    ["driver_number", "lap_number"]
).head(30)

traffic_features.groupby(
    ["driver_number", "lap_number"]
).size().describe()

count    961.000000
mean       1.001041
std        0.032258
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        2.000000
dtype: float64

In [16]:
duplicates = traffic_features[
    traffic_features.duplicated(
        subset=["driver_number", "lap_number"],
        keep=False
    )
].sort_values(
    ["driver_number", "lap_number"]
)

duplicates

     driver_number  lap_number  ...  traffic_behind  position_change
895             77          38  ...               0              0.0
896             77          38  ...               0              0.0

[2 rows x 6 columns]

In [17]:
traffic_features = traffic_features.drop_duplicates(
    subset=[
        "driver_number", "lap_number"
    ]
).copy()

print(traffic_features.shape)

print(
    traffic_features.groupby(
        ["driver_number", "lap_number"]
    ).size().max()
)

(961, 6)
1

In [18]:
suspicious_laps = degradation_data[
    degradation_data["fuel_adjusted_lap_duration"] >= 100
].copy()

suspicious_laps = suspicious_laps.merge(
    traffic_features,
    on=["driver_number", "lap_number"],
    how="left",
    validate="one_to_one"
)

suspicious_laps[
    [
        "driver_number",
        "lap_number",
        "stint_number",
        "compound",
        "tyre_age",
        "fuel_adjusted_lap_duration",
        "traffic_ahead",
        "traffic_behind",
        "position_change"
    ]
].sort_values(
    "fuel_adjusted_lap_duration",
    ascending=False
)

    driver_number  lap_number  ...  traffic_behind position_change
40             77          26  ...               1             0.0
28             31          25  ...               0             0.0
14             18          19  ...               0             0.0
11             14          19  ...               1             0.0
23             24          19  ...               1             0.0
17             20          26  ...               0             0.0
13             16          19  ...               0             0.0
24             27          19  ...               0             0.0
6               3          26  ...               0             0.0
3               2          26  ...               1             0.0
4               3          19  ...               0             0.0
20             23          19  ...               0             0.0
18             22          19  ...               0             0.0
37             77          19  ...               1             0.0
21             23          26  ...               0             0.0
12             14          26  ...               0             0.0
34             63          19  ...               1             1.0
2               2          19  ...               1             0.0
19             22          26  ...               1             0.0
29             44          19  ...               1            -1.0
16             20          19  ...               0             0.0
33             55          26  ...               0             0.0
0               1          19  ...               0             0.0
25             27          26  ...               0             0.0
8               4          26  ...               1             0.0
1               1          26  ...               0             0.0
9              11          19  ...               1             0.0
27             31          19  ...               0             0.0
7               4          19  ...               1             0.0
31             44          26  ...               1             0.0
15             18          26  ...               0             0.0
43             81          26  ...               1             0.0
42             81          19  ...               0             0.0
36             63          26  ...               0             0.0
32             55          19  ...               0             0.0
39             77          25  ...               1             0.0
30             44          20  ...               1             0.0
35             63          20  ...               1             1.0
10             11          49  ...               1             1.0
22             24          18  ...               1             0.0
5               3          25  ...               0             0.0
41             77          39  ...               0             0.0
38             77          20  ...               1             0.0
26             31          17  ...               0             0.0

[44 rows x 9 columns]

In [19]:
race_control = pd.read_parquet(
    DATA_DIR / "race_control.parquet"
)
print(race_control.columns.tolist())
print(race_control.shape)

race_control[
    race_control["lap_number"].isin([18, 19, 20, 25, 26, 27])
][
    [
        "date",
        "lap_number",
        "category",
        "flag",
        "scope",
        "sector",
        "message"
    ]
].sort_values(
    ["lap_number", "date"]
)

['meeting_key', 'session_key', 'date', 'driver_number', 'lap_number', 'category', 'flag', 'scope', 'sector', 'qualifying_phase', 'message']
(110, 11)

                        date  ...                                            message
11 2024-07-07 14:31:20+00:00  ...                                       DRS DISABLED
12 2024-07-07 14:31:23+00:00  ...                                LOW GRIP CONDITIONS
13 2024-07-07 14:32:40+00:00  ...  CAR 44 (HAM) TIME 1:43.711 DELETED - TRACK LIM...
14 2024-07-07 14:32:41+00:00  ...  CAR 63 (RUS) TIME 1:44.151 DELETED - TRACK LIM...
46 2024-07-07 14:40:24+00:00  ...  WAVED BLUE FLAG FOR CAR 11 (PER) TIMED AT 15:4...
47 2024-07-07 14:40:33+00:00  ...  WAVED BLUE FLAG FOR CAR 24 (ZHO) TIMED AT 15:4...
48 2024-07-07 14:40:36+00:00  ...  WAVED BLUE FLAG FOR CAR 11 (PER) TIMED AT 15:4...
49 2024-07-07 14:41:00+00:00  ...  WAVED BLUE FLAG FOR CAR 16 (LEC) TIMED AT 15:4...
50 2024-07-07 14:41:01+00:00  ...  WAVED BLUE FLAG FOR CAR 11 (PER) TIMED AT 15:4...
51 2024-07-07 14:41:22+00:00  ...  WAVED BLUE FLAG FOR CAR 16 (LEC) TIMED AT 15:4...
52 2024-07-07 14:41:45+00:00  ...                                       DRS DISABLED
53 2024-07-07 14:41:47+00:00  ...                                LOW GRIP CONDITIONS
54 2024-07-07 14:41:49+00:00  ...  WAVED BLUE FLAG FOR CAR 11 (PER) TIMED AT 15:4...
55 2024-07-07 14:42:29+00:00  ...  WAVED BLUE FLAG FOR CAR 16 (LEC) TIMED AT 15:4...
56 2024-07-07 14:42:59+00:00  ...  CAR 16 (LEC) TIME 1:51.732 DELETED - TRACK LIM...
57 2024-07-07 14:44:15+00:00  ...  WAVED BLUE FLAG FOR CAR 31 (OCO) TIMED AT 15:4...
58 2024-07-07 14:44:36+00:00  ...  WAVED BLUE FLAG FOR CAR 31 (OCO) TIMED AT 15:4...
59 2024-07-07 14:44:42+00:00  ...          TRACK SURFACE SLIPPERY IN TRACK SECTOR 17
60 2024-07-07 14:44:43+00:00  ...                           CLEAR IN TRACK SECTOR 17
61 2024-07-07 14:44:44+00:00  ...  WAVED BLUE FLAG FOR CAR 31 (OCO) TIMED AT 15:4...
62 2024-07-07 14:44:45+00:00  ...  CAR 77 (BOT) LAP DELETED - TRACK LIMITS AT TUR...
63 2024-07-07 14:44:52+00:00  ...  WAVED BLUE FLAG FOR CAR 31 (OCO) TIMED AT 15:4...

[22 rows x 7 columns]

In [20]:
low_grip_laps = race_control[
    race_control["message"].str.contains(
        "LOW GRIP CONDITIONS",
        case=False,
        na=False
    )
]["lap_number"].dropna().unique()

print("Low-grip laps:", low_grip_laps)

degradation_data["low_grip_condition"] = (
    degradation_data["lap_number"]
    .isin(low_grip_laps)
    .astype(int)
)

print(
    degradation_data["low_grip_condition"].value_counts()
)

print(
    degradation_data[
        degradation_data["low_grip_condition"] == 1
    ][
        [
            "driver_number",
            "lap_number",
            "compound",
            "tyre_age",
            "fuel_adjusted_lap_duration",
            "low_grip_condition"
        ]
    ].sort_values(["lap_number", "driver_number"]).head(50)
)

Low-grip laps: [19 25]
low_grip_condition
0    650
1     35
Name: count, dtype: int64
     driver_number  lap_number  ... fuel_adjusted_lap_duration  low_grip_condition
17               1          19  ...                 103.999196                   1
55               2          19  ...                 105.604196                   1
94               3          19  ...                 106.436196                   1
132              4          19  ...                 102.950196                   1
170             11          19  ...                 103.382196                   1
199             14          19  ...                 108.784196                   1
238             16          19  ...                 107.382196                   1
269             18          19  ...                 109.082196                   1
306             20          19  ...                 105.019196                   1
346             22          19  ...                 106.099196                   1
385             23          19  ...                 106.133196                   1
423             24          19  ...                 107.827196                   1
453             27          19  ...                 107.266196                   1
490             31          19  ...                 103.245196                   1
523             44          19  ...                 105.225196                   1
562             55          19  ...                 102.024196                   1
598             63          19  ...                 105.665196                   1
624             77          19  ...                 105.940196                   1
662             81          19  ...                 102.242196                   1
23               1          25  ...                  98.081927                   1
61               2          25  ...                  98.184927                   1
100              3          25  ...                 100.743927                   1
138              4          25  ...                  96.325927                   1
205             14          25  ...                  97.705927                   1
275             18          25  ...                  97.369927                   1
312             20          25  ...                  97.168927                   1
352             22          25  ...                  97.491927                   1
391             23          25  ...                  97.630927                   1
459             27          25  ...                  97.936927                   1
493             31          25  ...                 109.450927                   1
529             44          25  ...                  97.006927                   1
568             55          25  ...                  97.161927                   1
604             63          25  ...                  96.799927                   1
630             77          25  ...                 101.779927                   1
668             81          25  ...                  96.289927                   1

[35 rows x 6 columns]

In [21]:
traffic_features = pd.read_parquet(
    DATA_DIR / "traffic_features.parquet"
)

traffic_features[
    traffic_features.duplicated(
        subset=["driver_number", "lap_number"],
        keep=False
    )
].sort_values(
    ["driver_number", "lap_number"]
)

traffic_features = traffic_features.drop_duplicates(
    subset=["driver_number", "lap_number"]
).copy()

print(
    traffic_features.groupby(
        ["driver_number", "lap_number"]
    ).size().max()
)

1

In [22]:
degradation_data = degradation_data.merge(
    traffic_features[
        [
            "driver_number",
            "lap_number",
            "traffic_ahead",
            "traffic_behind",
            "position_change"
        ]
    ],
    on=["driver_number", "lap_number"],
    how="left",
    validate="one_to_one"
)

In [23]:
traffic_condition_check = degradation_data[
    degradation_data["fuel_adjusted_lap_duration"] >= 100
][
    [
        "driver_number",
        "lap_number",
        "compound",
        "tyre_age",
        "fuel_adjusted_lap_duration",
        "low_grip_condition",
        "traffic_ahead",
        "traffic_behind",
        "position_change"
    ]
].sort_values(
    ["lap_number", "fuel_adjusted_lap_duration"],
    ascending=[True, False]
)

traffic_condition_check

     driver_number  lap_number  ... traffic_behind  position_change
488             31          17  ...              0              0.0
422             24          18  ...              1              0.0
269             18          19  ...              0              0.0
199             14          19  ...              1              0.0
423             24          19  ...              1              0.0
238             16          19  ...              0              0.0
453             27          19  ...              0              0.0
94               3          19  ...              0              0.0
385             23          19  ...              0              0.0
346             22          19  ...              0              0.0
624             77          19  ...              1              0.0
598             63          19  ...              1              1.0
55               2          19  ...              1              0.0
523             44          19  ...              1             -1.0
306             20          19  ...              0              0.0
17               1          19  ...              0              0.0
170             11          19  ...              1              0.0
490             31          19  ...              0              0.0
132              4          19  ...              1              0.0
662             81          19  ...              0              0.0
562             55          19  ...              0              0.0
524             44          20  ...              1              0.0
599             63          20  ...              1              1.0
625             77          20  ...              1              0.0
493             31          25  ...              0              0.0
630             77          25  ...              1              0.0
100              3          25  ...              0              0.0
631             77          26  ...              1              0.0
313             20          26  ...              0              0.0
101              3          26  ...              0              0.0
62               2          26  ...              1              0.0
392             23          26  ...              0              0.0
206             14          26  ...              0              0.0
353             22          26  ...              1              0.0
569             55          26  ...              0              0.0
460             27          26  ...              0              0.0
139              4          26  ...              1              0.0
24               1          26  ...              0              0.0
530             44          26  ...              1              0.0
276             18          26  ...              0              0.0
669             81          26  ...              1              0.0
605             63          26  ...              0              0.0
632             77          39  ...              0              0.0
180             11          49  ...              1              1.0

[44 rows x 9 columns]

In [24]:
race_control["message_lower"] = (
    race_control["message"].fillna("").str.lower()
)

abnormal_keywords = (
    "low grip",
    "drs disabled",
    "slippery",
    "track limits",
    "blue flag",
    "yellow flag",
    "red flag",
    "safety car",
    "virtual safety car",
)

race_control["race_condition_event"] = race_control["message_lower"].str.contains(
    "|".join(abnormal_keywords), regex=True, na=False
)

affected_laps = (
    race_control.loc[
        race_control["race_condition_event"],
        "lap_number"
    ].dropna().unique()
)
print("Race-condition affected laps:")
print(sorted(affected_laps))

degradation_data["race_control_affected"] = (
    degradation_data["lap_number"].isin(affected_laps).astype(int)
)

print(
    degradation_data["race_control_affected"].value_counts()
)

Race-condition affected laps:
[np.int64(1), np.int64(17), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(32), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(46), np.int64(49), np.int64(50), np.int64(51), np.int64(52)]
race_control_affected
0    392
1    293
Name: count, dtype: int64

In [25]:
race_wide_events = race_control[
    race_control["message"].fillna("").str.contains(
        "LOW GRIP CONDITIONS|DRS DISABLED|TRACK SURFACE SLIPPERY",
        case=False,
        na=False
    )
].copy()

print(
    race_wide_events[
        [
            "lap_number",
            "category",
            "flag",
            "message"
        ]
    ].sort_values(
        ["lap_number"]
    )
)

race_wide_laps = (
    race_wide_events["lap_number"]
    .dropna()
    .unique()
)

print(
    "Race-wide condition laps:",
    sorted(race_wide_laps)
)

    lap_number category flag                                    message
4            1      DRS  NaN                               DRS DISABLED
11          19      DRS  NaN                               DRS DISABLED
12          19    OTHER  NaN                        LOW GRIP CONDITIONS
20          21    OTHER  NaN  TRACK SURFACE SLIPPERY IN TRACK SECTOR 17
22          21    OTHER  NaN  TRACK SURFACE SLIPPERY IN TRACK SECTOR 17
24          21    OTHER  NaN  TRACK SURFACE SLIPPERY IN TRACK SECTOR 17
26          22    OTHER  NaN  TRACK SURFACE SLIPPERY IN TRACK SECTOR 11
27          22    OTHER  NaN  TRACK SURFACE SLIPPERY IN TRACK SECTOR 17
30          22    OTHER  NaN  TRACK SURFACE SLIPPERY IN TRACK SECTOR 17
32          22    OTHER  NaN  TRACK SURFACE SLIPPERY IN TRACK SECTOR 17
34          22    OTHER  NaN  TRACK SURFACE SLIPPERY IN TRACK SECTOR 17
36          22    OTHER  NaN  TRACK SURFACE SLIPPERY IN TRACK SECTOR 17
52          25      DRS  NaN                               DRS DISABLED
53          25    OTHER  NaN                        LOW GRIP CONDITIONS
59          27    OTHER  NaN  TRACK SURFACE SLIPPERY IN TRACK SECTOR 17
74          36    OTHER  NaN  TRACK SURFACE SLIPPERY IN TRACK SECTOR 10
Race-wide condition laps: [np.int64(1), np.int64(19), np.int64(21), np.int64(22), np.int64(25), np.int64(27), np.int64(36)]

In [26]:
race_control["low_grip_condition"] = (
    race_control["message"]
    .fillna("")
    .str.contains(
        "LOW GRIP CONDITIONS",
        case=False,
        na=False
    )
)

race_control["slippery_sector"] = (
    race_control["message"]
    .fillna("")
    .str.contains(
        "TRACK SURFACE SLIPPERY",
        case=False,
        na=False
    )
)

race_control["drs_disabled"] = (
    race_control["message"]
    .fillna("")
    .str.contains(
        "DRS DISABLED",
        case=False,
        na=False
    )
)

print(
    "Low grip:",
    sorted(
        race_control.loc[
            race_control["low_grip_condition"],
            "lap_number"
        ].dropna().unique()
    )
)

print(
    "Slippery sector:",
    sorted(
        race_control.loc[
            race_control["slippery_sector"],
            "lap_number"
        ].dropna().unique()
    )
)

print(
    "DRS disabled:",
    sorted(
        race_control.loc[
            race_control["drs_disabled"],
            "lap_number"
        ].dropna().unique()
    )
)

Low grip: [np.int64(19), np.int64(25)]
Slippery sector: [np.int64(21), np.int64(22), np.int64(27), np.int64(36)]
DRS disabled: [np.int64(1), np.int64(19), np.int64(25)]

In [27]:
tyre_model_data = degradation_data[
    ~degradation_data["low_grip_condition"].eq(1)
].copy()
print("Original degradation data:", degradation_data.shape)
print("Tyre model data:", tyre_model_data.shape)
print(
    tyre_model_data["low_grip_condition"].value_counts()
)

Original degradation data: (685, 26)
Tyre model data: (650, 26)
low_grip_condition
0    650
Name: count, dtype: int64

In [28]:
tyre_age_summary = (
    tyre_model_data
    .groupby(["compound", "tyre_age"])["fuel_adjusted_lap_duration"]
    .agg(["count","mean","median"])
    .reset_index()
)
print(tyre_age_summary.to_string(index=False))

compound  tyre_age  count       mean     median
    HARD       1.0      3  93.400919  93.336757
    HARD       2.0      3  92.932708  92.968879
    HARD       3.0      3  93.049497  92.921001
    HARD       4.0      3  92.813952  92.638123
    HARD       5.0      3  92.983407  92.989245
    HARD       6.0      3  93.343196  93.373489
    HARD       7.0      3  93.582318  93.422611
    HARD       8.0      3  93.374106  93.368733
    HARD       9.0      3  93.282895  93.466098
    HARD      10.0      3  93.495350  93.555977
    HARD      11.0      2  93.421159  93.421159
    HARD      12.0      2  93.715281  93.715281
    HARD      13.0      2  93.480403  93.480403
    HARD      14.0      1  93.879708  93.879708
    HARD      15.0      1  95.492830  95.492830
    HARD      16.0      1  96.174952  96.174952
    HARD      17.0      1  96.814074  96.814074
  MEDIUM       1.0     24  93.571865  93.292122
  MEDIUM       2.0     24  93.508737  93.328744
  MEDIUM       3.0     23  93.329552  93.362366
  MEDIUM       4.0     23  93.355674  93.104488
  MEDIUM       5.0     23  93.549187  93.208610
  MEDIUM       6.0     22  93.319814  93.279732
  MEDIUM       7.0     22  93.342072  93.388854
  MEDIUM       8.0     22  93.440740  93.247476
  MEDIUM       9.0     22  93.707816  93.441098
  MEDIUM      10.0     21  93.461472  93.389220
  MEDIUM      11.0     21  93.551499  93.456342
  MEDIUM      12.0     20  93.575997  93.637964
  MEDIUM      13.0     19  93.576475  93.631586
  MEDIUM      14.0     16  93.480083  93.581708
  MEDIUM      15.0     16  94.143080  94.268830
  MEDIUM      16.0     16  96.268452  96.289452
  MEDIUM      17.0     16  96.868386  97.020574
  MEDIUM      19.0     15  98.981984  98.928317
  MEDIUM      20.0     15  94.923639  95.166439
  MEDIUM      21.0     15  94.055495  94.261561
  MEDIUM      22.0     15  94.486150  94.462683
  MEDIUM      23.0     15  95.532405  95.559805
  MEDIUM      25.0     15 105.075716 104.584049
  MEDIUM      26.0      0        NaN        NaN
  MEDIUM      27.0      0        NaN        NaN
    SOFT       1.0     14  95.469537  94.655696
    SOFT       2.0     13  94.504607  94.158757
    SOFT       3.0     12  93.892865  93.520866
    SOFT       4.0     12  93.893320  93.651305
    SOFT       5.0     12  94.048025  94.011866
    SOFT       6.0     12  94.508980  94.795745
    SOFT       7.0     12  94.821436  94.633928
    SOFT       8.0     12  94.713141  94.743050
    SOFT       9.0     12  94.856430  94.755111
    SOFT      10.0     12  94.952552  94.984733
    SOFT      11.0     12  95.314757  95.078342
    SOFT      12.0     11  95.623008  95.500464
    SOFT      13.0      8  96.322455  96.379221
    SOFT      14.0      2  96.166964  96.166964
    SOFT      15.0      1  97.783830  97.783830
    SOFT      16.0      1 100.080952 100.080952
    SOFT      17.0      1  99.927074  99.927074

In [29]:
import statsmodels.formula.api as smf

tyre_baseline_model = smf.ols(
    "fuel_adjusted_lap_duration ~ C(driver_number) + C(compound) + tyre_age",
    data=tyre_model_data
).fit()

print(tyre_baseline_model.summary())

                                OLS Regression Results
======================================================================================
Dep. Variable:     fuel_adjusted_lap_duration   R-squared:                       0.413
Model:                                    OLS   Adj. R-squared:                  0.393
Method:                         Least Squares   F-statistic:                     20.64
Date:                        Fri, 25 Sep 2026   Prob (F-statistic):           5.46e-58
Time:                                15:38:14   Log-Likelihood:                -1279.6
No. Observations:                         639   AIC:                             2603.
Df Residuals:                             617   BIC:                             2701.
Df Model:                                  21
Covariance Type:                    nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 91.3376      0.405    225.294      0.000      90.541      92.134
C(driver_number)[T.2]      0.7492      0.457      1.639      0.102      -0.148       1.647
C(driver_number)[T.3]      1.3591      0.457      2.974      0.003       0.462       2.257
C(driver_number)[T.4]     -0.3910      0.459     -0.851      0.395      -1.293       0.511
C(driver_number)[T.11]     1.2883      0.471      2.738      0.006       0.364       2.212
C(driver_number)[T.14]     0.6163      0.452      1.362      0.174      -0.272       1.505
C(driver_number)[T.16]     0.1280      0.479      0.267      0.790      -0.813       1.069
C(driver_number)[T.18]     0.5412      0.455      1.188      0.235      -0.353       1.435
C(driver_number)[T.20]     0.7773      0.455      1.709      0.088      -0.116       1.670
C(driver_number)[T.22]     0.7414      0.457      1.622      0.105      -0.156       1.639
C(driver_number)[T.23]     0.6917      0.452      1.529      0.127      -0.197       1.580
C(driver_number)[T.24]     1.9074      0.506      3.770      0.000       0.914       2.901
C(driver_number)[T.27]     0.3250      0.459      0.707      0.480      -0.577       1.227
C(driver_number)[T.31]     2.0562      0.484      4.245      0.000       1.105       3.007
C(driver_number)[T.44]    -0.5255      0.457     -1.150      0.251      -1.423       0.372
C(driver_number)[T.55]     0.2015      0.437      0.461      0.645      -0.657       1.060
C(driver_number)[T.63]    -0.5027      0.507     -0.992      0.322      -1.498       0.493
C(driver_number)[T.77]     2.0139      0.457      4.407      0.000       1.116       2.911
C(driver_number)[T.81]    -0.3778      0.452     -0.835      0.404      -1.266       0.511
C(compound)[T.MEDIUM]      0.3334      0.390      0.854      0.393      -0.433       1.100
C(compound)[T.SOFT]        1.1573      0.429      2.697      0.007       0.315       2.000
tyre_age                   0.2105      0.012     17.758      0.000       0.187       0.234
==============================================================================
Omnibus:                      390.375   Durbin-Watson:                   1.305
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3724.510
Skew:                           2.628   Prob(JB):                         0.00
Kurtosis:                      13.595   Cond. No.                         241.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [30]:
tyre_degradation_nonlinear = smf.ols(
    "fuel_adjusted_lap_duration ~ C(driver_number) + C(compound) + tyre_age + I(tyre_age**2)",
    data=tyre_model_data
).fit()

print(tyre_degradation_nonlinear.summary())

                                OLS Regression Results
======================================================================================
Dep. Variable:     fuel_adjusted_lap_duration   R-squared:                       0.527
Model:                                    OLS   Adj. R-squared:                  0.510
Method:                         Least Squares   F-statistic:                     31.21
Date:                        Fri, 25 Sep 2026   Prob (F-statistic):           2.93e-85
Time:                                15:38:14   Log-Likelihood:                -1210.4
No. Observations:                         639   AIC:                             2467.
Df Residuals:                             616   BIC:                             2569.
Df Model:                                  22
Covariance Type:                    nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 93.1976      0.395    236.146      0.000      92.423      93.973
C(driver_number)[T.2]      0.7853      0.410      1.913      0.056      -0.021       1.591
C(driver_number)[T.3]      1.3951      0.410      3.399      0.001       0.589       2.201
C(driver_number)[T.4]     -0.3734      0.413     -0.905      0.366      -1.184       0.437
C(driver_number)[T.11]     1.2365      0.423      2.926      0.004       0.407       2.066
C(driver_number)[T.14]     0.7298      0.406      1.796      0.073      -0.068       1.528
C(driver_number)[T.16]     0.3639      0.431      0.845      0.399      -0.482       1.210
C(driver_number)[T.18]     0.6322      0.409      1.546      0.123      -0.171       1.435
C(driver_number)[T.20]     0.8291      0.408      2.030      0.043       0.027       1.631
C(driver_number)[T.22]     0.7775      0.410      1.894      0.059      -0.029       1.583
C(driver_number)[T.23]     0.8052      0.406      1.981      0.048       0.007       1.603
C(driver_number)[T.24]     1.8104      0.454      3.985      0.000       0.918       2.703
C(driver_number)[T.27]     0.3426      0.413      0.830      0.407      -0.468       1.153
C(driver_number)[T.31]     2.1389      0.435      4.917      0.000       1.285       2.993
C(driver_number)[T.44]    -0.4894      0.410     -1.192      0.234      -1.295       0.317
C(driver_number)[T.55]     0.1085      0.393      0.276      0.782      -0.662       0.879
C(driver_number)[T.63]    -0.4838      0.455     -1.063      0.288      -1.378       0.410
C(driver_number)[T.77]     2.0500      0.410      4.995      0.000       1.244       2.856
C(driver_number)[T.81]    -0.2643      0.406     -0.650      0.516      -1.062       0.534
C(compound)[T.MEDIUM]      0.0191      0.351      0.054      0.957      -0.671       0.709
C(compound)[T.SOFT]        1.0574      0.385      2.744      0.006       0.301       1.814
tyre_age                  -0.2144      0.036     -5.890      0.000      -0.286      -0.143
I(tyre_age ** 2)           0.0182      0.001     12.209      0.000       0.015       0.021
==============================================================================
Omnibus:                      207.862   Durbin-Watson:                   1.391
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1247.237
Skew:                           1.312   Prob(JB):                    1.47e-271
Kurtosis:                       9.321   Cond. No.                     4.28e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.28e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [31]:
import numpy as np
import pandas as pd

ages = np.arange(
    tyre_model_data["tyre_age"].min(),
    tyre_model_data["tyre_age"].max() + 1
)

curve = pd.DataFrame({
    "tyre_age": ages
})

curve["predicted_degradation"] = (
    -0.2144 * curve["tyre_age"]
    + 0.0182 * curve["tyre_age"] ** 2
)

print(curve)

    tyre_age  predicted_degradation
0        1.0                -0.1962
1        2.0                -0.3560
2        3.0                -0.4794
3        4.0                -0.5664
4        5.0                -0.6170
5        6.0                -0.6312
6        7.0                -0.6090
7        8.0                -0.5504
8        9.0                -0.4554
9       10.0                -0.3240
10      11.0                -0.1562
11      12.0                 0.0480
12      13.0                 0.2886
13      14.0                 0.5656
14      15.0                 0.8790
15      16.0                 1.2288
16      17.0                 1.6150
17      18.0                 2.0376
18      19.0                 2.4966
19      20.0                 2.9920
20      21.0                 3.5238
21      22.0                 4.0920
22      23.0                 4.6966
23      24.0                 5.3376
24      25.0                 6.0150
25      26.0                 6.7288
26      27.0                 7.4790

In [32]:
tyre_compound_model = smf.ols(
    "fuel_adjusted_lap_duration ~ C(driver_number) + C(compound) * (tyre_age + I(tyre_age**2))",
    data=tyre_model_data
).fit()

print(tyre_compound_model.summary())

                                OLS Regression Results
======================================================================================
Dep. Variable:     fuel_adjusted_lap_duration   R-squared:                       0.535
Model:                                    OLS   Adj. R-squared:                  0.516
Method:                         Least Squares   F-statistic:                     27.11
Date:                        Fri, 25 Sep 2026   Prob (F-statistic):           1.53e-84
Time:                                15:38:15   Log-Likelihood:                -1204.8
No. Observations:                         639   AIC:                             2464.
Df Residuals:                             612   BIC:                             2584.
Df Model:                                  26
Covariance Type:                    nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                                 93.0071      0.853    109.034      0.000      91.332      94.682
C(driver_number)[T.2]                      0.7938      0.409      1.943      0.052      -0.009       1.596
C(driver_number)[T.3]                      1.4036      0.409      3.436      0.001       0.601       2.206
C(driver_number)[T.4]                     -0.3428      0.411     -0.835      0.404      -1.149       0.464
C(driver_number)[T.11]                     1.2128      0.433      2.800      0.005       0.362       2.064
C(driver_number)[T.14]                     0.7221      0.405      1.785      0.075      -0.072       1.517
C(driver_number)[T.16]                     0.3666      0.429      0.855      0.393      -0.476       1.209
C(driver_number)[T.18]                     0.6216      0.407      1.527      0.127      -0.178       1.421
C(driver_number)[T.20]                     0.8090      0.407      1.990      0.047       0.011       1.607
C(driver_number)[T.22]                     0.7860      0.409      1.924      0.055      -0.016       1.588
C(driver_number)[T.23]                     0.7974      0.405      1.971      0.049       0.003       1.592
C(driver_number)[T.24]                     1.8668      0.453      4.119      0.000       0.977       2.757
C(driver_number)[T.27]                     0.3732      0.411      0.909      0.364      -0.433       1.180
C(driver_number)[T.31]                     1.9019      0.439      4.329      0.000       1.039       2.765
C(driver_number)[T.44]                    -0.4810      0.409     -1.177      0.240      -1.283       0.321
C(driver_number)[T.55]                     0.1165      0.391      0.298      0.766      -0.652       0.885
C(driver_number)[T.63]                    -0.4763      0.453     -1.052      0.293      -1.366       0.413
C(driver_number)[T.77]                     2.0584      0.409      5.038      0.000       1.256       2.861
C(driver_number)[T.81]                    -0.2720      0.405     -0.672      0.502      -1.066       0.522
C(compound)[T.MEDIUM]                      0.4873      0.868      0.562      0.575      -1.217       2.192
C(compound)[T.SOFT]                        1.3121      0.934      1.404      0.161      -0.523       3.147
tyre_age                                  -0.1624      0.223     -0.727      0.468      -0.601       0.276
C(compound)[T.MEDIUM]:tyre_age            -0.1009      0.227     -0.443      0.658      -0.548       0.346
C(compound)[T.SOFT]:tyre_age              -0.2083      0.257     -0.812      0.417      -0.712       0.296
I(tyre_age ** 2)                           0.0157      0.013      1.184      0.237      -0.010       0.042
C(compound)[T.MEDIUM]:I(tyre_age ** 2)     0.0041      0.013      0.309      0.758      -0.022       0.030
C(compound)[T.SOFT]:I(tyre_age ** 2)       0.0187      0.016      1.195      0.233      -0.012       0.050
==============================================================================
Omnibus:                      216.249   Durbin-Watson:                   1.395
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1326.088
Skew:                           1.367   Prob(JB):                    1.11e-288
Kurtosis:                       9.507   Cond. No.                     6.80e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.8e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [34]:

split_lap = 45

train_data = tyre_model_data[
    tyre_model_data["lap_number"] < split_lap
].copy()

test_data = tyre_model_data[
    tyre_model_data["lap_number"] >= split_lap
].copy()

print("Training rows:", len(train_data))
print("Testing rows:", len(test_data))

print(
    "Train lap range:",
    train_data["lap_number"].min(),
    "-",
    train_data["lap_number"].max()
)

print(
    "Test lap range:",
    test_data["lap_number"].min(),
    "-",
    test_data["lap_number"].max()
)

Training rows: 517
Testing rows: 133
Train lap range: 2 - 44
Test lap range: 45 - 52

In [36]:
import statsmodels.formula.api as smf
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

validation_data = tyre_model_data.sort_values("lap_number").copy()

print("Training rows:", len(train_data))
print("Testing rows:", len(test_data))
print("Train lap range:", train_data["lap_number"].min(), "-", train_data["lap_number"].max())
print("Test lap range:", test_data["lap_number"].min(), "-", test_data["lap_number"].max())

linear_model = smf.ols(
    "fuel_adjusted_lap_duration ~ C(driver_number) + C(compound) + tyre_age",
    data=train_data
).fit()


quadratic_model = smf.ols(
    "fuel_adjusted_lap_duration ~ C(driver_number) + C(compound) + tyre_age + I(tyre_age**2)",
    data=train_data
).fit()

linear_pred = linear_model.predict(test_data)
quadratic_pred = quadratic_model.predict(test_data)

actual = test_data["fuel_adjusted_lap_duration"]

linear_r2 = r2_score(actual, linear_pred)
quadratic_r2 = r2_score(actual, quadratic_pred)

linear_rmse = np.sqrt(mean_squared_error(actual, linear_pred))
quadratic_rmse = np.sqrt(mean_squared_error(actual, quadratic_pred))


print("\n===== TEST SET RESULTS =====")

print("\nLinear model:")
print("R²:", round(linear_r2, 3))
print("RMSE:", round(linear_rmse, 3), "seconds")

print("\nQuadratic model:")
print("R²:", round(quadratic_r2, 3))
print("RMSE:", round(quadratic_rmse, 3), "seconds")

Training rows: 520
Testing rows: 130
Train lap range: 2 - 45
Test lap range: 45 - 52

===== TEST SET RESULTS =====

Linear model:
R²: 0.425
RMSE: 1.021 seconds

Quadratic model:
R²: 0.04
RMSE: 1.319 seconds

In [38]:
tyre_piecewise_data = tyre_model_data.copy()

tyre_piecewise_data["tyre_age_phase"] = pd.cut(
    tyre_piecewise_data["tyre_age"],
    bins=[0,5,12,float("inf")],
    labels=["early", "middle", "late"],
    include_lowest=True
)

print(
    tyre_piecewise_data[
        ["tyre_age","tyre_age_phase"]
    ].drop_duplicates().sort_values("tyre_age").to_string(index=False)
)
print("Phase counts:", tyre_piecewise_data["tyre_age_phase"].value_counts().sort_index())

 tyre_age tyre_age_phase
      1.0          early
      2.0          early
      3.0          early
      4.0          early
      5.0          early
      6.0         middle
      7.0         middle
      8.0         middle
      9.0         middle
     10.0         middle
     11.0         middle
     12.0         middle
     13.0           late
     14.0           late
     15.0           late
     16.0           late
     17.0           late
     19.0           late
     20.0           late
     21.0           late
     22.0           late
     23.0           late
     25.0           late
     26.0           late
     27.0           late
Phase counts: tyre_age_phase
early     196
middle    252
late      202
Name: count, dtype: int64

In [40]:
import statsmodels.formula.api as smf
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

train_data = tyre_piecewise_data[
    tyre_piecewise_data["lap_number"] < 45
].copy()

test_data = tyre_piecewise_data[
    tyre_piecewise_data["lap_number"] >= 45
].copy()

linear_model = smf.ols(
    "fuel_adjusted_lap_duration ~ C(driver_number) + C(compound) + tyre_age",
    data=train_data
).fit()

piecewise_model = smf.ols(
    "fuel_adjusted_lap_duration ~ C(driver_number) + C(compound) + tyre_age + C(tyre_age_phase)",
    data=train_data
).fit()

actual = test_data["fuel_adjusted_lap_duration"]

linear_pred = linear_model.predict(test_data)
piecewise_model = piecewise_model.predict(test_data)

linear_r2 = r2_score(actual, linear_pred)
linear_rmse = np.sqrt(mean_squared_error(actual, linear_pred))

piecewise_r2 = r2_score(actual, piecewise_model)
piecewise_rmse = np.sqrt(mean_squared_error(actual, piecewise_model))

print("\nLinear model:")
print("R²:", round(linear_r2, 3))
print("RMSE:", round(linear_rmse, 3), "seconds")

print("\nPiecewise model:")
print("R²:", round(piecewise_r2, 3))
print("RMSE:", round(piecewise_rmse, 3), "seconds")


# --------------------------------------------------
# PIECEWISE MODEL COEFFICIENTS
# --------------------------------------------------

print("\n===== PIECEWISE COEFFICIENTS =====")

print(
    piecewise_model.params[
        piecewise_model.params.index.str.contains("tyre_age_phase")
    ]
)

Linear model:
R²: 0.421
RMSE: 1.014 seconds

Piecewise model:
R²: 0.11
RMSE: 1.256 seconds

===== PIECEWISE COEFFICIENTS =====

AttributeError: 'Series' object has no attribute 'params'

In [41]:
print(type(piecewise_model))

<class 'pandas.Series'>

In [42]:
import statsmodels.formula.api as smf

linear_model = smf.ols(
    "fuel_adjusted_lap_duration ~ C(driver_number) + C(compound) + tyre_age",
    data=train_data
).fit()

piecewise_model = smf.ols(
    "fuel_adjusted_lap_duration ~ C(driver_number) + C(compound) + tyre_age + C(tyre_age_phase)",
    data=train_data
).fit()

print("Linear model type:")
print(type(linear_model))

print("\nPiecewise model type:")
print(type(piecewise_model))

print("\n===== PIECEWISE COEFFICIENTS =====")

print(
    piecewise_model.params[
        piecewise_model.params.index.str.contains("tyre_age_phase")
    ]
)

Linear model type:
<class 'statsmodels.regression.linear_model.RegressionResultsWrapper'>

Piecewise model type:
<class 'statsmodels.regression.linear_model.RegressionResultsWrapper'>

===== PIECEWISE COEFFICIENTS =====
C(tyre_age_phase)[T.middle]   -2.078369
C(tyre_age_phase)[T.late]     -2.544153
dtype: float64

In [43]:
print("===== TEST SET RESULTS =====")

print("\nLinear model:")
print("R²:", round(linear_r2, 3))
print("RMSE:", round(linear_rmse, 3), "seconds")

print("\nPiecewise model:")
print("R²:", round(piecewise_r2, 3))
print("RMSE:", round(piecewise_rmse, 3), "seconds")

===== TEST SET RESULTS =====

Linear model:
R²: 0.421
RMSE: 1.014 seconds

Piecewise model:
R²: 0.11
RMSE: 1.256 seconds

In [45]:
tyre_age_coefficient = linear_model.params["tyre_age"]
print("Tyre age coeff: ", tyre_age_coefficient)

tyre_features = tyre_model_data[
    ["driver_number", "lap_number", "tyre_age"]
].copy()

tyre_features["tyre_degradation_effect"] = (
    tyre_features["tyre_age"] * tyre_age_coefficient
)
print(tyre_features.head())
print("Shape:", tyre_features.shape)

Tyre age coeff:  0.21524441782524095
   driver_number  lap_number  tyre_age  tyre_degradation_effect
0              1           2       1.0                 0.215244
1              1           3       2.0                 0.430489
2              1           4       3.0                 0.645733
3              1           5       4.0                 0.860978
4              1           6       5.0                 1.076222
Shape: (650, 4)

In [46]:
from pathlib import Path

OUTPUT_PATH = Path("../data/processed/9558/tyre_features.parquet")

tyre_features.to_parquet(
    OUTPUT_PATH, 
    index=False
)
print("Saved:", OUTPUT_PATH)

Saved: ..\data\processed\9558\tyre_features.parquet