In [ ]:

from pathlib import Path
import joblib
import pandas as pd

# Find the PITWALL root by locating its expected folders
CURRENT_DIR = Path.cwd()

PROJECT_ROOT = next(
    (
        p for p in [CURRENT_DIR, *CURRENT_DIR.parents]
        if (p / "data").is_dir()
        and (p / "models").is_dir()
    ),
    None
)

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "Could not locate the PITWALL root containing both data/ and models/."
    )

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "9558"
MODEL_PATH = PROJECT_ROOT / "models" / "pace_xgb_weather.joblib"
FEATURES_PATH = PROJECT_ROOT / "models" / "pace_xgb_weather_features.joblib"


print("Project root:", PROJECT_ROOT)
print("Processed data directory exists:", DATA_DIR.exists())
print("Pace model exists:", MODEL_PATH.exists())
print("Model feature list exists:", FEATURES_PATH.exists())

print("\nProcessed Parquet files:")
if DATA_DIR.exists():
    for path in sorted(DATA_DIR.glob("*.parquet")):
        print(f"  {path.name} ({path.stat().st_size / 1024:.1f} KB)")

if MODEL_PATH.exists() and FEATURES_PATH.exists():
    pace_model = joblib.load(MODEL_PATH)
    pace_features = joblib.load(FEATURES_PATH)

    print("\nLoaded pace model:", type(pace_model).__name__)
    print("Number of model features:", len(pace_features))
    print("Model feature list:")
    print(pace_features)

Project root: c:\Users\Nihan\.vscode\pitwall
Processed data directory exists: True
Pace model exists: True
Model feature list exists: True

Processed Parquet files:
  fuel_features.parquet (3.4 KB)
  historical_pit_events.parquet (9.0 KB)
  lap_performance.parquet (50.6 KB)
  laps.parquet (48.2 KB)
  position.parquet (5.0 KB)
  race_control.parquet (9.3 KB)
  race_state.parquet (38.5 KB)
  rolling_temporal_predictions.parquet (126.7 KB)
  stints.parquet (5.6 KB)
  traffic_features.parquet (5.7 KB)
  tyre_features.parquet (4.3 KB)
  weather.parquet (9.3 KB)

Loaded pace model: XGBRegressor
Number of model features: 30
Model feature list:
['tyre_age', 'fuel_effect', 'traffic_ahead', 'traffic_behind', 'position_change', 'track_evolution', 'rainfall', 'humidity', 'air_temperature', 'wind_speed', 'driver_number_2', 'driver_number_3', 'driver_number_4', 'driver_number_11', 'driver_number_14', 'driver_number_16', 'driver_number_18', 'driver_number_20', 'driver_number_22', 'driver_number_23', 'driver_number_24', 'driver_number_27', 'driver_number_31', 'driver_number_44', 'driver_number_55', 'driver_number_63', 'driver_number_77', 'driver_number_81', 'compound_MEDIUM', 'compound_SOFT']

In [2]:
parquet_files = sorted(DATA_DIR.glob("*.parquet"))

if not parquet_files:
    raise FileNotFoundError(
        f"No Parquet files found in {DATA_DIR}"
    )

for path in parquet_files:
    df = pd.read_parquet(path)

    print("\n" + "=" * 80)
    print(f"FILE: {path.name}")
    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())

    print("\nFirst 3 rows:")
    display(df.head(3))

    print("\nMissing values (top 10 columns):")
    print(df.isna().sum().sort_values(ascending=False).head(10))

================================================================================
FILE: fuel_features.parquet
Shape: (692, 3)

Columns:
['driver_number', 'lap_number', 'fuel_effect']

First 3 rows:

   driver_number  lap_number  fuel_effect
0              1           1    -0.000000
1              1           2    -0.084122
2              1           3    -0.168244

Missing values (top 10 columns):
driver_number    0
lap_number       0
fuel_effect      0
dtype: int64

================================================================================
FILE: historical_pit_events.parquet
Shape: (45, 13)

Columns:
['driver_number', 'decision_lap', 'position_before', 'compound_before', 'tyre_age_before', 'rainfall', 'grip_condition', 'next_recorded_lap', 'position_next_recorded_lap', 'compound_after', 'tyre_age_after', 'next_is_pit_out', 'position_change_next_recorded_lap']

First 3 rows:

,driver_number,decision_lap,position_before,compound_before,tyre_age_before,rainfall,grip_condition,next_recorded_lap,position_next_recorded_lap,compound_after,tyre_age_after,next_is_pit_out,position_change_next_recorded_lap
0,1,26,5.0,MEDIUM,25.0,1.0,LOW,27.0,5.0,INTERMEDIATE,0.0,True,0.0
1,1,38,3.0,INTERMEDIATE,11.0,1.0,LOW,39.0,3.0,HARD,0.0,True,0.0
2,2,27,13.0,MEDIUM,26.0,1.0,LOW,28.0,11.0,INTERMEDIATE,0.0,True,2.0

Missing values (top 10 columns):
grip_condition                2
decision_lap                  0
position_before               0
compound_before               0
driver_number                 0
tyre_age_before               0
rainfall                      0
next_recorded_lap             0
position_next_recorded_lap    0
compound_after                0
dtype: int64

================================================================================
FILE: lap_performance.parquet
Shape: (962, 19)

Columns:
['meeting_key', 'session_key', 'driver_number', 'lap_number', 'date_start', 'duration_sector_1', 'duration_sector_2', 'duration_sector_3', 'i1_speed', 'i2_speed', 'is_pit_out_lap', 'lap_duration', 'segments_sector_1', 'segments_sector_2', 'segments_sector_3', 'st_speed', 'stint_number', 'compound', 'tyre_age']

First 3 rows:

,meeting_key,session_key,driver_number,lap_number,date_start,duration_sector_1,duration_sector_2,duration_sector_3,i1_speed,i2_speed,is_pit_out_lap,lap_duration,segments_sector_1,segments_sector_2,segments_sector_3,st_speed,stint_number,compound,tyre_age
0,1240,9558,1,1,2024-07-07 14:03:12.540000+00:00,33.528,37.975,25.708,298.0,256.0,False,97.211,"[nan, 2049.0, 2049.0, 2051.0, 2049.0, 2049.0, ...","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2051, 2049, 2049, 2049]",290.0,1.0,MEDIUM,0.0
1,1240,9558,1,2,2024-07-07 14:04:49.750000+00:00,29.612,37.222,24.939,311.0,260.0,False,91.773,"[2049.0, 2049.0, 2051.0, 2049.0, 2048.0, 2048....","[2049, 2049, 2049, 2048, 2048, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2048, 2049, 2049, 2049]",316.0,1.0,MEDIUM,1.0
2,1240,9558,1,3,2024-07-07 14:06:21.461000+00:00,29.672,37.216,25.312,293.0,256.0,False,92.200,"[2048.0, 2048.0, 2048.0, 2049.0, 2049.0, 2048....","[2048, 2049, 2048, 2048, 2048, 2048, 2048, 204...","[2048, 2048, 2048, 2048, 2049, 2049, 2049, 2048]",294.0,1.0,MEDIUM,2.0

Missing values (top 10 columns):
i1_speed             134
duration_sector_1      3
lap_duration           3
tyre_age               2
st_speed               2
compound               2
duration_sector_3      2
i2_speed               2
stint_number           2
duration_sector_2      2
dtype: int64

================================================================================
FILE: laps.parquet
Shape: (962, 16)

Columns:
['meeting_key', 'session_key', 'driver_number', 'lap_number', 'date_start', 'duration_sector_1', 'duration_sector_2', 'duration_sector_3', 'i1_speed', 'i2_speed', 'is_pit_out_lap', 'lap_duration', 'segments_sector_1', 'segments_sector_2', 'segments_sector_3', 'st_speed']

First 3 rows:

,meeting_key,session_key,driver_number,lap_number,date_start,duration_sector_1,duration_sector_2,duration_sector_3,i1_speed,i2_speed,is_pit_out_lap,lap_duration,segments_sector_1,segments_sector_2,segments_sector_3,st_speed
0,1240,9558,1,1,2024-07-07 14:03:12.540000+00:00,33.528,37.975,25.708,298.0,256.0,False,97.211,"[nan, 2049.0, 2049.0, 2051.0, 2049.0, 2049.0, ...","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2051, 2049, 2049, 2049]",290.0
1,1240,9558,1,2,2024-07-07 14:04:49.750000+00:00,29.612,37.222,24.939,311.0,260.0,False,91.773,"[2049.0, 2049.0, 2051.0, 2049.0, 2048.0, 2048....","[2049, 2049, 2049, 2048, 2048, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2048, 2049, 2049, 2049]",316.0
2,1240,9558,1,3,2024-07-07 14:06:21.461000+00:00,29.672,37.216,25.312,293.0,256.0,False,92.200,"[2048.0, 2048.0, 2048.0, 2049.0, 2049.0, 2048....","[2048, 2049, 2048, 2048, 2048, 2048, 2048, 204...","[2048, 2048, 2048, 2048, 2049, 2049, 2049, 2048]",294.0

Missing values (top 10 columns):
i1_speed             134
duration_sector_1      3
lap_duration           3
duration_sector_2      2
st_speed               2
i2_speed               2
duration_sector_3      2
date_start             1
segments_sector_2      1
segments_sector_1      1
dtype: int64

================================================================================
FILE: position.parquet
Shape: (252, 5)

Columns:
['date', 'session_key', 'driver_number', 'position', 'meeting_key']

First 3 rows:

,date,session_key,driver_number,position,meeting_key
0,2024-07-07 13:05:02.926000+00:00,9558,1,4,1240
1,2024-07-07 13:05:02.926000+00:00,9558,2,12,1240
2,2024-07-07 13:05:02.926000+00:00,9558,3,15,1240

Missing values (top 10 columns):
date             0
session_key      0
driver_number    0
position         0
meeting_key      0
dtype: int64

================================================================================
FILE: race_control.parquet
Shape: (110, 11)

Columns:
['meeting_key', 'session_key', 'date', 'driver_number', 'lap_number', 'category', 'flag', 'scope', 'sector', 'qualifying_phase', 'message']

First 3 rows:

,meeting_key,session_key,date,driver_number,lap_number,category,flag,scope,sector,qualifying_phase,message
0,1240,9558,2024-07-07 13:09:42+00:00,<NA>,1,OTHER,NaN,NaN,<NA>,None,AWNINGS MAY BE USED
1,1240,9558,2024-07-07 13:20:00+00:00,<NA>,1,FLAG,GREEN,TRACK,<NA>,None,GREEN LIGHT - PIT EXIT OPEN
2,1240,9558,2024-07-07 13:30:00+00:00,<NA>,1,OTHER,NaN,NaN,<NA>,None,PIT EXIT CLOSED

Missing values (top 10 columns):
qualifying_phase    110
sector               98
driver_number        53
scope                38
flag                 38
meeting_key           0
session_key           0
date                  0
lap_number            0
category              0
dtype: int64

================================================================================
FILE: race_state.parquet
Shape: (962, 23)

Columns:
['driver_number', 'lap_number', 'date_start', 'lap_duration', 'compound', 'tyre_age', 'stint_number', 'is_pit_out_lap', 'position', 'session_key', 'meeting_key', 'track_temperature', 'wind_speed', 'rainfall', 'humidity', 'pressure', 'air_temperature', 'wind_direction', 'weather_age_seconds', 'drs_available', 'grip_condition', 'blue_flag', 'date']

First 3 rows:

,driver_number,lap_number,date_start,lap_duration,compound,tyre_age,stint_number,is_pit_out_lap,position,session_key,...,rainfall,humidity,pressure,air_temperature,wind_direction,weather_age_seconds,drs_available,grip_condition,blue_flag,date
0,1,1,2024-07-07 14:03:12.540000+00:00,97.211,MEDIUM,0.0,1.0,False,4.0,9558.0,...,0.0,64.0,992.0,16.1,275.0,10.044,False,NaN,False,NaT
1,1,2,2024-07-07 14:04:49.750000+00:00,91.773,MEDIUM,1.0,1.0,False,3.0,9558.0,...,0.0,63.0,992.0,16.2,215.0,47.246,True,NaN,False,NaT
2,1,3,2024-07-07 14:06:21.461000+00:00,92.200,MEDIUM,2.0,1.0,False,3.0,9558.0,...,0.0,62.0,991.9,16.3,235.0,18.957,True,NaN,False,NaT

Missing values (top 10 columns):
date                   962
grip_condition         357
lap_duration             3
stint_number             2
tyre_age                 2
compound                 2
date_start               1
weather_age_seconds      1
humidity                 1
position                 1
dtype: int64

================================================================================
FILE: rolling_temporal_predictions.parquet
Shape: (3155, 12)

Columns:
['fold', 'model', 'row_idx', 'actual', 'predicted', 'lap_number', 'compound', 'rainfall', 'error', 'abs_error', 'squared_error', 'weather_regime']

First 3 rows:

,fold,model,row_idx,actual,predicted,lap_number,compound,rainfall,error,abs_error,squared_error,weather_regime
0,16-24,Training median baseline,15,92.504,92.697,16,MEDIUM,0.0,0.193,0.193,0.037249,No rain
1,16-24,Training median baseline,16,95.359,92.697,17,MEDIUM,0.0,-2.662,2.662,7.086244,No rain
2,16-24,Training median baseline,17,96.172,92.697,18,MEDIUM,0.0,-3.475,3.475,12.075625,No rain

Missing values (top 10 columns):
fold          0
model         0
row_idx       0
actual        0
predicted     0
lap_number    0
compound      0
rainfall      0
error         0
abs_error     0
dtype: int64

================================================================================
FILE: stints.parquet
Shape: (65, 8)

Columns:
['meeting_key', 'session_key', 'stint_number', 'driver_number', 'lap_start', 'lap_end', 'compound', 'tyre_age_at_start']

First 3 rows:

,meeting_key,session_key,stint_number,driver_number,lap_start,lap_end,compound,tyre_age_at_start
0,1240,9558,1,1,1.0,26.0,MEDIUM,0
1,1240,9558,2,1,27.0,38.0,INTERMEDIATE,0
2,1240,9558,3,1,39.0,52.0,HARD,0

Missing values (top 10 columns):
lap_end              1
lap_start            1
meeting_key          0
session_key          0
driver_number        0
stint_number         0
compound             0
tyre_age_at_start    0
dtype: int64

================================================================================
FILE: traffic_features.parquet
Shape: (962, 6)

Columns:
['driver_number', 'lap_number', 'position', 'traffic_ahead', 'traffic_behind', 'position_change']

First 3 rows:

,driver_number,lap_number,position,traffic_ahead,traffic_behind,position_change
0,1,1,4,1,0,0.0
1,1,2,3,1,1,-1.0
2,1,3,3,1,1,0.0

Missing values (top 10 columns):
driver_number      0
lap_number         0
position           0
traffic_ahead      0
traffic_behind     0
position_change    0
dtype: int64

================================================================================
FILE: tyre_features.parquet
Shape: (650, 4)

Columns:
['driver_number', 'lap_number', 'tyre_age', 'tyre_degradation_effect']

First 3 rows:

   driver_number  lap_number  tyre_age  tyre_degradation_effect
0              1           2       1.0                 0.215244
1              1           3       2.0                 0.430489
2              1           4       3.0                 0.645733

Missing values (top 10 columns):
driver_number              0
lap_number                 0
tyre_age                   0
tyre_degradation_effect    0
dtype: int64

================================================================================
FILE: weather.parquet
Shape: (147, 10)

Columns:
['date', 'session_key', 'meeting_key', 'track_temperature', 'wind_speed', 'rainfall', 'humidity', 'pressure', 'air_temperature', 'wind_direction']

First 3 rows:

,date,session_key,meeting_key,track_temperature,wind_speed,rainfall,humidity,pressure,air_temperature,wind_direction
0,2024-07-07 13:05:02.119000+00:00,9558,1240,28.1,2.2,0,67.0,991.8,15.9,226
1,2024-07-07 13:06:02.098000+00:00,9558,1240,27.6,1.5,0,66.0,991.7,15.9,268
2,2024-07-07 13:07:02.122000+00:00,9558,1240,27.0,1.4,0,65.0,991.7,15.9,291

Missing values (top 10 columns):
date                 0
session_key          0
meeting_key          0
track_temperature    0
wind_speed           0
rainfall             0
humidity             0
pressure             0
air_temperature      0
wind_direction       0
dtype: int64

In [3]:
for path in sorted(DATA_DIR.glob("*.parquet")):
    df = pd.read_parquet(path)

    if any("lap" in col.lower() for col in df.columns) and any(
        "driver" in col.lower() for col in df.columns
    ):
        print("\n" + "=" * 70)
        print("Dataset:", path.name)
        print("Shape:", df.shape)
        print("Potential strategy columns:")

        keywords = [
            "driver", "lap", "duration", "time", "compound",
            "tyre", "pit", "stint", "position", "fuel",
            "weather", "track"
        ]

        cols = [
            col for col in df.columns
            if any(keyword in col.lower() for keyword in keywords)
        ]

        print(cols)
        display(df[cols].head(5))

======================================================================
Dataset: fuel_features.parquet
Shape: (692, 3)
Potential strategy columns:
['driver_number', 'lap_number', 'fuel_effect']

   driver_number  lap_number  fuel_effect
0              1           1    -0.000000
1              1           2    -0.084122
2              1           3    -0.168244
3              1           4    -0.252366
4              1           5    -0.336488

======================================================================
Dataset: historical_pit_events.parquet
Shape: (45, 13)
Potential strategy columns:
['driver_number', 'decision_lap', 'position_before', 'compound_before', 'tyre_age_before', 'next_recorded_lap', 'position_next_recorded_lap', 'compound_after', 'tyre_age_after', 'next_is_pit_out', 'position_change_next_recorded_lap']

,driver_number,decision_lap,position_before,compound_before,tyre_age_before,next_recorded_lap,position_next_recorded_lap,compound_after,tyre_age_after,next_is_pit_out,position_change_next_recorded_lap
0,1,26,5.0,MEDIUM,25.0,27.0,5.0,INTERMEDIATE,0.0,True,0.0
1,1,38,3.0,INTERMEDIATE,11.0,39.0,3.0,HARD,0.0,True,0.0
2,2,27,13.0,MEDIUM,26.0,28.0,11.0,INTERMEDIATE,0.0,True,2.0
3,2,38,13.0,INTERMEDIATE,10.0,39.0,11.0,SOFT,0.0,True,2.0
4,3,26,14.0,MEDIUM,25.0,27.0,14.0,INTERMEDIATE,0.0,True,0.0

======================================================================
Dataset: lap_performance.parquet
Shape: (962, 19)
Potential strategy columns:
['driver_number', 'lap_number', 'duration_sector_1', 'duration_sector_2', 'duration_sector_3', 'is_pit_out_lap', 'lap_duration', 'stint_number', 'compound', 'tyre_age']

,driver_number,lap_number,duration_sector_1,duration_sector_2,duration_sector_3,is_pit_out_lap,lap_duration,stint_number,compound,tyre_age
0,1,1,33.528,37.975,25.708,False,97.211,1.0,MEDIUM,0.0
1,1,2,29.612,37.222,24.939,False,91.773,1.0,MEDIUM,1.0
2,1,3,29.672,37.216,25.312,False,92.200,1.0,MEDIUM,2.0
3,1,4,29.626,37.090,25.217,False,91.933,1.0,MEDIUM,3.0
4,1,5,29.608,37.007,25.163,False,91.778,1.0,MEDIUM,4.0

======================================================================
Dataset: laps.parquet
Shape: (962, 16)
Potential strategy columns:
['driver_number', 'lap_number', 'duration_sector_1', 'duration_sector_2', 'duration_sector_3', 'is_pit_out_lap', 'lap_duration']

,driver_number,lap_number,duration_sector_1,duration_sector_2,duration_sector_3,is_pit_out_lap,lap_duration
0,1,1,33.528,37.975,25.708,False,97.211
1,1,2,29.612,37.222,24.939,False,91.773
2,1,3,29.672,37.216,25.312,False,92.200
3,1,4,29.626,37.090,25.217,False,91.933
4,1,5,29.608,37.007,25.163,False,91.778

======================================================================
Dataset: race_control.parquet
Shape: (110, 11)
Potential strategy columns:
['driver_number', 'lap_number']

   driver_number  lap_number
0           <NA>           1
1           <NA>           1
2           <NA>           1
3           <NA>           1
4           <NA>           1

======================================================================
Dataset: race_state.parquet
Shape: (962, 23)
Potential strategy columns:
['driver_number', 'lap_number', 'lap_duration', 'compound', 'tyre_age', 'stint_number', 'is_pit_out_lap', 'position', 'track_temperature', 'weather_age_seconds']

,driver_number,lap_number,lap_duration,compound,tyre_age,stint_number,is_pit_out_lap,position,track_temperature,weather_age_seconds
0,1,1,97.211,MEDIUM,0.0,1.0,False,4.0,33.0,10.044
1,1,2,91.773,MEDIUM,1.0,1.0,False,3.0,33.0,47.246
2,1,3,92.200,MEDIUM,2.0,1.0,False,3.0,33.0,18.957
3,1,4,91.933,MEDIUM,3.0,1.0,False,3.0,24.3,51.154
4,1,5,91.778,MEDIUM,4.0,1.0,False,3.0,24.0,22.990

======================================================================
Dataset: stints.parquet
Shape: (65, 8)
Potential strategy columns:
['stint_number', 'driver_number', 'lap_start', 'lap_end', 'compound', 'tyre_age_at_start']

,stint_number,driver_number,lap_start,lap_end,compound,tyre_age_at_start
0,1,1,1.0,26.0,MEDIUM,0
1,2,1,27.0,38.0,INTERMEDIATE,0
2,3,1,39.0,52.0,HARD,0
3,1,2,1.0,27.0,MEDIUM,0
4,2,2,28.0,38.0,INTERMEDIATE,0

======================================================================
Dataset: traffic_features.parquet
Shape: (962, 6)
Potential strategy columns:
['driver_number', 'lap_number', 'position', 'position_change']

   driver_number  lap_number  position  position_change
0              1           1         4              0.0
1              1           2         3             -1.0
2              1           3         3              0.0
3              1           4         3              0.0
4              1           5         3              0.0

======================================================================
Dataset: tyre_features.parquet
Shape: (650, 4)
Potential strategy columns:
['driver_number', 'lap_number', 'tyre_age', 'tyre_degradation_effect']

   driver_number  lap_number  tyre_age  tyre_degradation_effect
0              1           2       1.0                 0.215244
1              1           3       2.0                 0.430489
2              1           4       3.0                 0.645733
3              1           5       4.0                 0.860978
4              1           6       5.0                 1.076222

In [4]:
race_state = pd.read_parquet(DATA_DIR / "race_state.parquet")

print("Shape:", race_state.shape)
print("\nAll columns:")
print(race_state.columns.tolist())

print("\nData types:")
print(race_state.dtypes)

print("\nUnique drivers:")
print(sorted(race_state["driver_number"].dropna().unique()))

print("\nLap-number range:")
print(race_state["lap_number"].min(), "to", race_state["lap_number"].max())

print("\nWeather-state distribution:")
if "weather_state" in race_state.columns:
    print(race_state["weather_state"].value_counts(dropna=False))
else:
    print("No weather_state column found.")

print("\nSample rows:")
display(race_state.head(10))

Shape: (962, 23)

All columns:
['driver_number', 'lap_number', 'date_start', 'lap_duration', 'compound', 'tyre_age', 'stint_number', 'is_pit_out_lap', 'position', 'session_key', 'meeting_key', 'track_temperature', 'wind_speed', 'rainfall', 'humidity', 'pressure', 'air_temperature', 'wind_direction', 'weather_age_seconds', 'drs_available', 'grip_condition', 'blue_flag', 'date']

Data types:
driver_number                        int64
lap_number                           int64
date_start             datetime64[us, UTC]
lap_duration                       float64
compound                               str
tyre_age                           float64
stint_number                       float64
is_pit_out_lap                        bool
position                           float64
session_key                        float64
meeting_key                        float64
track_temperature                  float64
wind_speed                         float64
rainfall                           float64
humidity                           float64
pressure                           float64
air_temperature                    float64
wind_direction                     float64
weather_age_seconds                float64
drs_available                       object
grip_condition                         str
blue_flag                           object
date                   datetime64[us, UTC]
dtype: object

Unique drivers:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(10), np.int64(11), np.int64(14), np.int64(16), np.int64(18), np.int64(20), np.int64(22), np.int64(23), np.int64(24), np.int64(27), np.int64(31), np.int64(44), np.int64(55), np.int64(63), np.int64(77), np.int64(81)]

Lap-number range:
1 to 52

Weather-state distribution:
No weather_state column found.

Sample rows:

,driver_number,lap_number,date_start,lap_duration,compound,tyre_age,stint_number,is_pit_out_lap,position,session_key,...,rainfall,humidity,pressure,air_temperature,wind_direction,weather_age_seconds,drs_available,grip_condition,blue_flag,date
0,1,1,2024-07-07 14:03:12.540000+00:00,97.211,MEDIUM,0.0,1.0,False,4.0,9558.0,...,0.0,64.0,992.0,16.1,275.0,10.044,False,NaN,False,NaT
1,1,2,2024-07-07 14:04:49.750000+00:00,91.773,MEDIUM,1.0,1.0,False,3.0,9558.0,...,0.0,63.0,992.0,16.2,215.0,47.246,True,NaN,False,NaT
2,1,3,2024-07-07 14:06:21.461000+00:00,92.200,MEDIUM,2.0,1.0,False,3.0,9558.0,...,0.0,62.0,991.9,16.3,235.0,18.957,True,NaN,False,NaT
3,1,4,2024-07-07 14:07:53.675000+00:00,91.933,MEDIUM,3.0,1.0,False,3.0,9558.0,...,0.0,61.0,992.0,16.3,237.0,51.154,True,NaN,False,NaT
4,1,5,2024-07-07 14:09:25.527000+00:00,91.778,MEDIUM,4.0,1.0,False,3.0,9558.0,...,0.0,60.0,992.0,16.2,243.0,22.990,True,NaN,False,NaT
5,1,6,2024-07-07 14:10:57.353000+00:00,91.711,MEDIUM,5.0,1.0,False,3.0,9558.0,...,0.0,60.0,991.9,16.3,209.0,54.814,True,NaN,False,NaT
6,1,7,2024-07-07 14:12:29.113000+00:00,91.935,MEDIUM,6.0,1.0,False,3.0,9558.0,...,0.0,61.0,992.0,16.3,251.0,26.554,True,NaN,False,NaT
7,1,8,2024-07-07 14:14:01.043000+00:00,92.038,MEDIUM,7.0,1.0,False,3.0,9558.0,...,0.0,60.0,992.0,16.4,241.0,58.476,True,NaN,False,NaT
8,1,9,2024-07-07 14:15:33.002000+00:00,91.883,MEDIUM,8.0,1.0,False,3.0,9558.0,...,0.0,61.0,992.0,16.5,320.0,30.422,True,NaN,False,NaT
9,1,10,2024-07-07 14:17:04.948000+00:00,91.661,MEDIUM,9.0,1.0,False,3.0,9558.0,...,0.0,61.0,992.0,16.8,208.0,2.385,True,NaN,False,NaT

In [5]:

# Inspect race-state coverage and data quality

print("Rows:", len(race_state))
print("Unique driver-lap combinations:",
      race_state[["driver_number", "lap_number"]].drop_duplicates().shape[0])

print("\nDuplicate driver-lap rows:",
      race_state.duplicated(["driver_number", "lap_number"]).sum())

print("\nMissing values by column:")
display(
    race_state.isna()
    .sum()
    .sort_values(ascending=False)
    .to_frame("missing_count")
    .query("missing_count > 0")
)

print("\nRows per driver:")
display(
    race_state.groupby("driver_number")
    .agg(
        rows=("lap_number", "size"),
        first_lap=("lap_number", "min"),
        last_lap=("lap_number", "max"),
        observed_lap_times=("lap_duration", "count")
    )
    .sort_values("rows", ascending=False)
)

print("\nAvailable columns relevant to simulation:")
for col in race_state.columns:
    if any(term in col.lower() for term in [
        "compound", "tyre", "stint", "pit", "position",
        "fuel", "weather", "track", "lap", "driver",
        "duration", "rain"
    ]):
        print("-", col)

Rows: 962
Unique driver-lap combinations: 962

Duplicate driver-lap rows: 0

Missing values by column:

                     missing_count
date                           962
grip_condition                 357
lap_duration                     3
stint_number                     2
tyre_age                         2
compound                         2
date_start                       1
weather_age_seconds              1
humidity                         1
position                         1
session_key                      1
rainfall                         1
wind_speed                       1
meeting_key                      1
track_temperature                1
drs_available                    1
wind_direction                   1
pressure                         1
air_temperature                  1
blue_flag                        1

Rows per driver:

               rows  first_lap  last_lap  observed_lap_times
driver_number
1                52          1        52                  52
2                52          1        52                  52
4                52          1        52                  52
14               52          1        52                  52
55               52          1        52                  52
22               52          1        52                  52
20               52          1        52                  52
18               52          1        52                  52
23               52          1        52                  52
81               52          1        52                  52
44               52          1        52                  52
27               52          1        52                  52
3                51          1        51                  51
77               51          1        51                  51
16               51          1        51                  51
11               50          1        50                  49
31               50          1        50                  50
24               50          1        50                  50
63               34          1        34                  33
10                1          1         1                   0

Available columns relevant to simulation:
- driver_number
- lap_number
- lap_duration
- compound
- tyre_age
- stint_number
- is_pit_out_lap
- position
- track_temperature
- rainfall
- weather_age_seconds

In [6]:

# Summarise each driver's observed stint and tyre usage

stint_summary = (
    race_state
    .groupby(
        ["driver_number", "stint_number", "compound"],
        dropna=False
    )
    .agg(
        first_lap=("lap_number", "min"),
        last_lap=("lap_number", "max"),
        rows=("lap_number", "size"),
        valid_lap_times=("lap_duration", "count"),
        starting_tyre_age=("tyre_age", "min"),
        ending_tyre_age=("tyre_age", "max"),
        pit_out_laps=("is_pit_out_lap", "sum")
    )
    .reset_index()
    .sort_values(["driver_number", "first_lap"])
)

print("Observed driver stints:", len(stint_summary))
display(stint_summary)

print("\nObserved compound distribution:")
display(
    race_state["compound"]
    .value_counts(dropna=False)
    .rename_axis("compound")
    .to_frame("lap_rows")
)

print("\nLap-time coverage by compound:")
display(
    race_state.groupby("compound", dropna=False)
    .agg(
        rows=("lap_duration", "size"),
        valid_lap_times=("lap_duration", "count"),
        mean_lap_time=("lap_duration", "mean"),
        median_lap_time=("lap_duration", "median")
    )
)

Observed driver stints: 66

,driver_number,stint_number,compound,first_lap,last_lap,rows,valid_lap_times,starting_tyre_age,ending_tyre_age,pit_out_laps
0,1,1.0,MEDIUM,1,26,26,26,0.0,25.0,0
1,1,2.0,INTERMEDIATE,27,38,12,12,0.0,11.0,1
2,1,3.0,HARD,39,52,14,14,0.0,13.0,1
3,2,1.0,MEDIUM,1,27,27,27,0.0,26.0,0
4,2,2.0,INTERMEDIATE,28,38,11,11,0.0,10.0,1
...,...,...,...,...,...,...,...,...,...,...
61,77,2.0,INTERMEDIATE,27,37,11,11,0.0,10.0,1
62,77,3.0,SOFT,38,51,14,14,0.0,13.0,1
63,81,1.0,MEDIUM,1,28,28,28,0.0,27.0,0
64,81,2.0,INTERMEDIATE,29,38,10,10,0.0,9.0,1
65,81,3.0,MEDIUM,39,52,14,14,0.0,13.0,1

Observed compound distribution:

              lap_rows
compound
MEDIUM             508
INTERMEDIATE       234
SOFT               174
HARD                44
NaN                  2

Lap-time coverage by compound:

              rows  valid_lap_times  mean_lap_time  median_lap_time
compound
HARD            44               43      92.506651          90.0560
INTERMEDIATE   234              234     104.987338         103.2230
MEDIUM         508              508      94.473384          92.7685
SOFT           174              174      93.826454          91.3155
NaN              2                0            NaN              NaN

In [7]:

# Summarise each driver's observed stint and tyre usage

stint_summary = (
    race_state
    .groupby(
        ["driver_number", "stint_number", "compound"],
        dropna=False
    )
    .agg(
        first_lap=("lap_number", "min"),
        last_lap=("lap_number", "max"),
        rows=("lap_number", "size"),
        valid_lap_times=("lap_duration", "count"),
        starting_tyre_age=("tyre_age", "min"),
        ending_tyre_age=("tyre_age", "max"),
        pit_out_laps=("is_pit_out_lap", "sum")
    )
    .reset_index()
    .sort_values(["driver_number", "first_lap"])
)

print("Observed driver stints:", len(stint_summary))
display(stint_summary)

print("\nObserved compound distribution:")
display(
    race_state["compound"]
    .value_counts(dropna=False)
    .rename_axis("compound")
    .to_frame("lap_rows")
)

print("\nLap-time coverage by compound:")
display(
    race_state.groupby("compound", dropna=False)
    .agg(
        rows=("lap_duration", "size"),
        valid_lap_times=("lap_duration", "count"),
        mean_lap_time=("lap_duration", "mean"),
        median_lap_time=("lap_duration", "median")
    )
)

Observed driver stints: 66

,driver_number,stint_number,compound,first_lap,last_lap,rows,valid_lap_times,starting_tyre_age,ending_tyre_age,pit_out_laps
0,1,1.0,MEDIUM,1,26,26,26,0.0,25.0,0
1,1,2.0,INTERMEDIATE,27,38,12,12,0.0,11.0,1
2,1,3.0,HARD,39,52,14,14,0.0,13.0,1
3,2,1.0,MEDIUM,1,27,27,27,0.0,26.0,0
4,2,2.0,INTERMEDIATE,28,38,11,11,0.0,10.0,1
...,...,...,...,...,...,...,...,...,...,...
61,77,2.0,INTERMEDIATE,27,37,11,11,0.0,10.0,1
62,77,3.0,SOFT,38,51,14,14,0.0,13.0,1
63,81,1.0,MEDIUM,1,28,28,28,0.0,27.0,0
64,81,2.0,INTERMEDIATE,29,38,10,10,0.0,9.0,1
65,81,3.0,MEDIUM,39,52,14,14,0.0,13.0,1

Observed compound distribution:

              lap_rows
compound
MEDIUM             508
INTERMEDIATE       234
SOFT               174
HARD                44
NaN                  2

Lap-time coverage by compound:

              rows  valid_lap_times  mean_lap_time  median_lap_time
compound
HARD            44               43      92.506651          90.0560
INTERMEDIATE   234              234     104.987338         103.2230
MEDIUM         508              508      94.473384          92.7685
SOFT           174              174      93.826454          91.3155
NaN              2                0            NaN              NaN

In [8]:
print("Saved model type:", type(pace_model).__name__)
print("Number of expected features:", len(pace_features))

print("\nExpected model features:")
for i, feature in enumerate(pace_features, start=1):
    print(f"{i:02d}. {feature}")

print("\nWhich expected features exist in race_state?")
feature_audit = pd.DataFrame({
    "feature": pace_features,
    "in_race_state": [f in race_state.columns for f in pace_features]
})

display(feature_audit)

print("\nFeatures missing directly from race_state:")
print(feature_audit.loc[~feature_audit["in_race_state"], "feature"].tolist())

print("\nAvailable lap-level data columns:")
print(race_state.columns.tolist())

Saved model type: XGBRegressor
Number of expected features: 30

Expected model features:
01. tyre_age
02. fuel_effect
03. traffic_ahead
04. traffic_behind
05. position_change
06. track_evolution
07. rainfall
08. humidity
09. air_temperature
10. wind_speed
11. driver_number_2
12. driver_number_3
13. driver_number_4
14. driver_number_11
15. driver_number_14
16. driver_number_16
17. driver_number_18
18. driver_number_20
19. driver_number_22
20. driver_number_23
21. driver_number_24
22. driver_number_27
23. driver_number_31
24. driver_number_44
25. driver_number_55
26. driver_number_63
27. driver_number_77
28. driver_number_81
29. compound_MEDIUM
30. compound_SOFT

Which expected features exist in race_state?

             feature  in_race_state
0           tyre_age           True
1        fuel_effect          False
2      traffic_ahead          False
3     traffic_behind          False
4    position_change          False
5    track_evolution          False
6           rainfall           True
7           humidity           True
8    air_temperature           True
9         wind_speed           True
10   driver_number_2          False
11   driver_number_3          False
12   driver_number_4          False
13  driver_number_11          False
14  driver_number_14          False
15  driver_number_16          False
16  driver_number_18          False
17  driver_number_20          False
18  driver_number_22          False
19  driver_number_23          False
20  driver_number_24          False
21  driver_number_27          False
22  driver_number_31          False
23  driver_number_44          False
24  driver_number_55          False
25  driver_number_63          False
26  driver_number_77          False
27  driver_number_81          False
28   compound_MEDIUM          False
29     compound_SOFT          False

Features missing directly from race_state:
['fuel_effect', 'traffic_ahead', 'traffic_behind', 'position_change', 'track_evolution', 'driver_number_2', 'driver_number_3', 'driver_number_4', 'driver_number_11', 'driver_number_14', 'driver_number_16', 'driver_number_18', 'driver_number_20', 'driver_number_22', 'driver_number_23', 'driver_number_24', 'driver_number_27', 'driver_number_31', 'driver_number_44', 'driver_number_55', 'driver_number_63', 'driver_number_77', 'driver_number_81', 'compound_MEDIUM', 'compound_SOFT']

Available lap-level data columns:
['driver_number', 'lap_number', 'date_start', 'lap_duration', 'compound', 'tyre_age', 'stint_number', 'is_pit_out_lap', 'position', 'session_key', 'meeting_key', 'track_temperature', 'wind_speed', 'rainfall', 'humidity', 'pressure', 'air_temperature', 'wind_direction', 'weather_age_seconds', 'drs_available', 'grip_condition', 'blue_flag', 'date']

In [9]:

# Load existing engineered features without rebuilding them

fuel_features = pd.read_parquet(DATA_DIR / "fuel_features.parquet")
traffic_features = pd.read_parquet(DATA_DIR / "traffic_features.parquet")
tyre_features = pd.read_parquet(DATA_DIR / "tyre_features.parquet")

# Inspect the track-evolution dataset location before assuming its filename
print("Fuel features:", fuel_features.shape, fuel_features.columns.tolist())
print("Traffic features:", traffic_features.shape, traffic_features.columns.tolist())
print("Tyre features:", tyre_features.shape, tyre_features.columns.tolist())

print("\nJoin-key uniqueness:")
for name, df in [
    ("race_state", race_state),
    ("fuel_features", fuel_features),
    ("traffic_features", traffic_features),
    ("tyre_features", tyre_features),
]:
    keys = ["driver_number", "lap_number"]
    print(
        f"{name}: rows={len(df)}, "
        f"unique keys={df[keys].drop_duplicates().shape[0]}, "
        f"duplicate keys={df.duplicated(keys).sum()}"
    )

print("\nFeature coverage:")
for name, df in [
    ("fuel_features", fuel_features),
    ("traffic_features", traffic_features),
    ("tyre_features", tyre_features),
]:
    print(f"\n{name}")
    display(df.isna().sum().to_frame("missing_count"))
    display(df.head(3))

Fuel features: (692, 3) ['driver_number', 'lap_number', 'fuel_effect']
Traffic features: (962, 6) ['driver_number', 'lap_number', 'position', 'traffic_ahead', 'traffic_behind', 'position_change']
Tyre features: (650, 4) ['driver_number', 'lap_number', 'tyre_age', 'tyre_degradation_effect']

Join-key uniqueness:
race_state: rows=962, unique keys=962, duplicate keys=0
fuel_features: rows=692, unique keys=692, duplicate keys=0
traffic_features: rows=962, unique keys=961, duplicate keys=1
tyre_features: rows=650, unique keys=650, duplicate keys=0

Feature coverage:

fuel_features

               missing_count
driver_number              0
lap_number                 0
fuel_effect                0

   driver_number  lap_number  fuel_effect
0              1           1    -0.000000
1              1           2    -0.084122
2              1           3    -0.168244

traffic_features

                 missing_count
driver_number                0
lap_number                   0
position                     0
traffic_ahead                0
traffic_behind               0
position_change              0

,driver_number,lap_number,position,traffic_ahead,traffic_behind,position_change
0,1,1,4,1,0,0.0
1,1,2,3,1,1,-1.0
2,1,3,3,1,1,0.0

tyre_features

                         missing_count
driver_number                        0
lap_number                           0
tyre_age                             0
tyre_degradation_effect              0

   driver_number  lap_number  tyre_age  tyre_degradation_effect
0              1           2       1.0                 0.215244
1              1           3       2.0                 0.430489
2              1           4       3.0                 0.645733

In [10]:

# Cell 8: Assemble the simulator's race-state table

keys = ["driver_number", "lap_number"]

# Start with the existing race-state dataset
sim_state = race_state.copy()

# Merge previously engineered features
feature_tables = [
    fuel_features[["driver_number", "lap_number", "fuel_effect"]],
    traffic_features[
        ["driver_number", "lap_number",
         "traffic_ahead", "traffic_behind", "position_change"]
    ].drop_duplicates(subset=keys),
    tyre_features[
        ["driver_number", "lap_number", "tyre_degradation_effect"]
    ],
]

for features in feature_tables:
    sim_state = sim_state.merge(
        features,
        on=keys,
        how="left",
        validate="one_to_one"
    )

# Use the existing race-state tyre age where available.
# The engineered tyre age is only a fallback.
if "tyre_age" in sim_state.columns:
    if "tyre_age_feature" not in sim_state.columns:
        # race_state already contains tyre_age
        pass

# Sort for reliable race progression
sim_state = sim_state.sort_values(keys).reset_index(drop=True)

print("Simulator race-state shape:", sim_state.shape)
print("Drivers:", sim_state["driver_number"].nunique())
print("Lap range:", sim_state["lap_number"].min(), "to",
      sim_state["lap_number"].max())
print("Unique driver-lap keys:",
      sim_state[keys].drop_duplicates().shape[0])
print("Duplicate driver-lap keys:", sim_state.duplicated(keys).sum())

display(
    sim_state[
        ["driver_number", "lap_number", "position", "compound",
         "tyre_age", "lap_duration", "fuel_effect",
         "traffic_ahead", "traffic_behind", "rainfall"]
    ].head(10)
)

Simulator race-state shape: (962, 28)
Drivers: 20
Lap range: 1 to 52
Unique driver-lap keys: 962
Duplicate driver-lap keys: 0

,driver_number,lap_number,position,compound,tyre_age,lap_duration,fuel_effect,traffic_ahead,traffic_behind,rainfall
0,1,1,4.0,MEDIUM,0.0,97.211,-0.000000,1.0,0.0,0.0
1,1,2,3.0,MEDIUM,1.0,91.773,-0.084122,1.0,1.0,0.0
2,1,3,3.0,MEDIUM,2.0,92.200,-0.168244,1.0,1.0,0.0
3,1,4,3.0,MEDIUM,3.0,91.933,-0.252366,1.0,1.0,0.0
4,1,5,3.0,MEDIUM,4.0,91.778,-0.336488,1.0,1.0,0.0
5,1,6,3.0,MEDIUM,5.0,91.711,-0.420610,1.0,1.0,0.0
6,1,7,3.0,MEDIUM,6.0,91.935,-0.504732,1.0,1.0,0.0
7,1,8,3.0,MEDIUM,7.0,92.038,-0.588854,1.0,1.0,0.0
8,1,9,3.0,MEDIUM,8.0,91.883,-0.672976,1.0,1.0,0.0
9,1,10,3.0,MEDIUM,9.0,91.661,-0.757098,1.0,1.0,0.0

In [11]:
race_results = []

for driver, group in sim_state.groupby("driver_number"):
    group = group.sort_values("lap_number")

    valid_times = group["lap_duration"].dropna()
    valid_positions = group["position"].dropna()

    compounds = (
        group.dropna(subset=["compound"])
        .sort_values("lap_number")
        .groupby("stint_number", dropna=False)["compound"]
        .first()
        .tolist()
    )

    race_results.append({
        "driver_number": driver,
        "completed_laps": group["lap_number"].max(),
        "last_recorded_position": (
            valid_positions.iloc[-1] if not valid_positions.empty else None
        ),
        "total_recorded_lap_time_s": valid_times.sum(),
        "valid_lap_times": len(valid_times),
        "observed_stint_sequence": " -> ".join(map(str, compounds)),
        "stints_recorded": len(compounds),
    })

race_results = pd.DataFrame(race_results)

race_results = race_results.sort_values(
    ["last_recorded_position", "driver_number"],
    na_position="last"
).reset_index(drop=True)

display(race_results.round(3))

,driver_number,completed_laps,last_recorded_position,total_recorded_lap_time_s,valid_lap_times,observed_stint_sequence,stints_recorded
0,44,52,1.0,4947.427,52,MEDIUM -> INTERMEDIATE -> SOFT,3
1,1,52,2.0,4949.024,52,MEDIUM -> INTERMEDIATE -> HARD,3
2,4,52,3.0,4954.980,52,MEDIUM -> INTERMEDIATE -> SOFT,3
3,63,34,4.0,3172.026,33,MEDIUM -> INTERMEDIATE,2
4,81,52,4.0,4959.839,52,MEDIUM -> INTERMEDIATE -> MEDIUM,3
5,55,52,5.0,4994.754,52,MEDIUM -> INTERMEDIATE -> HARD -> SOFT,4
6,27,52,6.0,5003.148,52,MEDIUM -> INTERMEDIATE -> SOFT,3
7,18,52,7.0,5003.988,52,MEDIUM -> INTERMEDIATE -> MEDIUM,3
8,14,52,8.0,5011.145,52,MEDIUM -> INTERMEDIATE -> MEDIUM,3
9,23,52,9.0,5015.679,52,MEDIUM -> INTERMEDIATE -> MEDIUM,3
10,22,52,10.0,5026.691,52,MEDIUM -> INTERMEDIATE -> SOFT,3
11,2,52,11.0,5036.439,52,MEDIUM -> INTERMEDIATE -> SOFT,3
12,20,52,12.0,5037.649,52,MEDIUM -> INTERMEDIATE -> SOFT,3
13,3,51,13.0,4957.389,51,MEDIUM -> INTERMEDIATE -> SOFT,3
14,16,51,14.0,4987.852,51,MEDIUM -> INTERMEDIATE -> INTERMEDIATE -> SOFT,4
15,77,51,15.0,4989.334,51,MEDIUM -> INTERMEDIATE -> SOFT,3
16,31,50,16.0,4958.249,50,SOFT -> INTERMEDIATE -> MEDIUM -> INTERMEDIATE...,5
17,11,50,17.0,4855.606,49,HARD -> INTERMEDIATE -> INTERMEDIATE -> MEDIUM...,5
18,24,50,18.0,5001.886,50,SOFT -> MEDIUM -> INTERMEDIATE -> INTERMEDIATE...,5
19,10,1,19.0,0.000,0,,0

In [12]:
TARGET_DRIVER = 63  # George Russell

FOCUS_LAPS = range(28, 35)
RIVAL_DRIVERS = [44, 1, 4]  # Hamilton, Verstappen, Norris

columns = [
    "driver_number",
    "lap_number",
    "position",
    "lap_duration",
    "compound",
    "tyre_age",
    "stint_number",
    "rainfall",
    "track_temperature",
    "traffic_ahead",
    "traffic_behind",
]

available_columns = [c for c in columns if c in sim_state.columns]

focus = sim_state[
    sim_state["driver_number"].isin([TARGET_DRIVER] + RIVAL_DRIVERS)
    & sim_state["lap_number"].isin(FOCUS_LAPS)
][available_columns].copy()


focus["driver_name"] = focus["driver_number"].map({
    63: "George Russell",
    44: "Lewis Hamilton",
    1: "Max Verstappen",
    4: "Lando Norris",
})

focus = focus.sort_values(["lap_number", "position"])

display(
    focus[
        ["lap_number", "driver_name"] +
        [c for c in available_columns if c != "driver_number"]
    ].reset_index(drop=True)
)

print("\nGeorge Russell's final recorded laps:")
display(
    sim_state.loc[
        (sim_state["driver_number"] == TARGET_DRIVER)
        & (sim_state["lap_number"].between(30, 34)),
        available_columns
    ].sort_values("lap_number")
)

,lap_number,driver_name,lap_number,position,lap_duration,compound,tyre_age,stint_number,rainfall,track_temperature,traffic_ahead,traffic_behind
0,28,Lando Norris,28,1.0,120.915,INTERMEDIATE,0.0,2.0,1.0,21.2,0.0,1.0
1,28,Lewis Hamilton,28,2.0,120.866,INTERMEDIATE,0.0,2.0,1.0,21.2,1.0,1.0
2,28,George Russell,28,4.0,124.342,INTERMEDIATE,0.0,2.0,1.0,21.2,1.0,0.0
3,28,Max Verstappen,28,5.0,101.176,INTERMEDIATE,1.0,2.0,1.0,21.2,1.0,0.0
4,29,Lando Norris,29,2.0,100.266,INTERMEDIATE,1.0,2.0,1.0,21.0,1.0,1.0
5,29,Lewis Hamilton,29,3.0,100.420,INTERMEDIATE,1.0,2.0,1.0,21.0,1.0,1.0
6,29,Max Verstappen,29,4.0,101.533,INTERMEDIATE,2.0,2.0,1.0,21.0,1.0,0.0
7,29,George Russell,29,5.0,100.405,INTERMEDIATE,1.0,2.0,1.0,21.0,1.0,0.0
8,30,Lando Norris,30,1.0,100.717,INTERMEDIATE,2.0,2.0,1.0,20.9,0.0,1.0
9,30,Lewis Hamilton,30,2.0,100.467,INTERMEDIATE,2.0,2.0,1.0,20.7,1.0,1.0
10,30,Max Verstappen,30,3.0,102.098,INTERMEDIATE,3.0,2.0,1.0,20.7,1.0,1.0
11,30,George Russell,30,4.0,101.237,INTERMEDIATE,2.0,2.0,1.0,20.7,1.0,0.0
12,31,Lando Norris,31,1.0,101.313,INTERMEDIATE,3.0,2.0,1.0,20.7,0.0,1.0
13,31,Lewis Hamilton,31,2.0,101.538,INTERMEDIATE,3.0,2.0,1.0,20.7,1.0,1.0
14,31,Max Verstappen,31,3.0,102.025,INTERMEDIATE,4.0,2.0,1.0,20.7,1.0,1.0
15,31,George Russell,31,4.0,101.902,INTERMEDIATE,3.0,2.0,1.0,20.7,1.0,0.0
16,32,Lando Norris,32,1.0,102.216,INTERMEDIATE,4.0,2.0,1.0,20.7,0.0,1.0
17,32,Lewis Hamilton,32,2.0,102.475,INTERMEDIATE,4.0,2.0,1.0,20.7,1.0,1.0
18,32,Max Verstappen,32,3.0,102.538,INTERMEDIATE,5.0,2.0,1.0,20.7,1.0,1.0
19,32,George Russell,32,4.0,103.085,INTERMEDIATE,4.0,2.0,1.0,20.7,1.0,0.0
20,33,Lando Norris,33,1.0,102.607,INTERMEDIATE,5.0,2.0,1.0,20.7,0.0,1.0
21,33,Lewis Hamilton,33,2.0,102.435,INTERMEDIATE,5.0,2.0,1.0,20.7,1.0,1.0
22,33,Max Verstappen,33,3.0,102.606,INTERMEDIATE,6.0,2.0,1.0,20.7,1.0,1.0
23,33,George Russell,33,4.0,106.221,INTERMEDIATE,5.0,2.0,1.0,20.7,1.0,0.0
24,34,Lando Norris,34,1.0,103.078,INTERMEDIATE,6.0,2.0,1.0,20.7,0.0,1.0
25,34,Lewis Hamilton,34,2.0,102.757,INTERMEDIATE,6.0,2.0,1.0,20.7,1.0,1.0
26,34,Max Verstappen,34,3.0,102.447,INTERMEDIATE,7.0,2.0,1.0,20.7,1.0,1.0
27,34,George Russell,34,4.0,NaN,NaN,NaN,NaN,1.0,21.0,1.0,0.0

George Russell's final recorded laps:

,driver_number,lap_number,position,lap_duration,compound,tyre_age,stint_number,rainfall,track_temperature,traffic_ahead,traffic_behind
854,63,30,4.0,101.237,INTERMEDIATE,2.0,2.0,1.0,20.7,1.0,0.0
855,63,31,4.0,101.902,INTERMEDIATE,3.0,2.0,1.0,20.7,1.0,0.0
856,63,32,4.0,103.085,INTERMEDIATE,4.0,2.0,1.0,20.7,1.0,0.0
857,63,33,4.0,106.221,INTERMEDIATE,5.0,2.0,1.0,20.7,1.0,0.0
858,63,34,4.0,NaN,NaN,NaN,NaN,1.0,21.0,1.0,0.0

In [13]:

# Debug: inspect the current simulator DataFrame

print("sim_state exists:", "sim_state" in globals())

if "sim_state" in globals():
    print("sim_state shape:", sim_state.shape)
    print("sim_state columns:")
    print(sim_state.columns.tolist())
    display(sim_state.head(3))

sim_state exists: True
sim_state shape: (962, 28)
sim_state columns:
['driver_number', 'lap_number', 'date_start', 'lap_duration', 'compound', 'tyre_age', 'stint_number', 'is_pit_out_lap', 'position', 'session_key', 'meeting_key', 'track_temperature', 'wind_speed', 'rainfall', 'humidity', 'pressure', 'air_temperature', 'wind_direction', 'weather_age_seconds', 'drs_available', 'grip_condition', 'blue_flag', 'date', 'fuel_effect', 'traffic_ahead', 'traffic_behind', 'position_change', 'tyre_degradation_effect']

,driver_number,lap_number,date_start,lap_duration,compound,tyre_age,stint_number,is_pit_out_lap,position,session_key,...,weather_age_seconds,drs_available,grip_condition,blue_flag,date,fuel_effect,traffic_ahead,traffic_behind,position_change,tyre_degradation_effect
0,1,1,2024-07-07 14:03:12.540000+00:00,97.211,MEDIUM,0.0,1.0,False,4.0,9558.0,...,10.044,False,NaN,False,NaT,-0.000000,1.0,0.0,0.0,NaN
1,1,2,2024-07-07 14:04:49.750000+00:00,91.773,MEDIUM,1.0,1.0,False,3.0,9558.0,...,47.246,True,NaN,False,NaT,-0.084122,1.0,1.0,-1.0,0.215244
2,1,3,2024-07-07 14:06:21.461000+00:00,92.200,MEDIUM,2.0,1.0,False,3.0,9558.0,...,18.957,True,NaN,False,NaT,-0.168244,1.0,1.0,0.0,0.430489

In [14]:

# Cell 11: Reconstruct observed strategy timelines (fixed)

drivers_to_compare = {
    63: "George Russell",
    44: "Lewis Hamilton",
    1: "Max Verstappen",
    4: "Lando Norris",
}

strategy_data = sim_state[
    sim_state["driver_number"].isin(drivers_to_compare)
].copy()

strategy_data = strategy_data.sort_values(
    ["driver_number", "lap_number"]
)

strategy_data["previous_stint"] = (
    strategy_data.groupby("driver_number")["stint_number"].shift(1)
)

strategy_data["previous_compound"] = (
    strategy_data.groupby("driver_number")["compound"].shift(1)
)

stint_starts = strategy_data[
    strategy_data["stint_number"].notna()
    & (
        strategy_data["stint_number"].ne(strategy_data["previous_stint"])
        | strategy_data["compound"].ne(strategy_data["previous_compound"])
    )
].copy()

stint_starts["driver_name"] = stint_starts["driver_number"].map(
    drivers_to_compare
)

columns_to_show = [
    "driver_number",
    "driver_name",
    "lap_number",
    "position",
    "stint_number",
    "compound",
    "tyre_age",
    "lap_duration",
    "rainfall",
    "track_temperature",
]

columns_to_show = [
    col for col in columns_to_show
    if col in stint_starts.columns
]

print("OBSERVED STINT STARTS")

display(
    stint_starts.sort_values(
        ["driver_number", "lap_number"]
    )[columns_to_show].reset_index(drop=True)
)

print("\nGEORGE RUSSELL: FINAL RECORDED LAPS")

george_final = strategy_data[
    (strategy_data["driver_number"] == 63)
    & strategy_data["lap_number"].between(28, 34)
]

george_columns = [
    "lap_number",
    "position",
    "lap_duration",
    "compound",
    "tyre_age",
    "rainfall",
    "track_temperature",
]

display(
    george_final[
        [c for c in george_columns if c in george_final.columns]
    ].reset_index(drop=True)
)

OBSERVED STINT STARTS

,driver_number,driver_name,lap_number,position,stint_number,compound,tyre_age,lap_duration,rainfall,track_temperature
0,1,Max Verstappen,1,4.0,1.0,MEDIUM,0.0,97.211,0.0,33.0
1,1,Max Verstappen,27,5.0,2.0,INTERMEDIATE,0.0,119.169,1.0,21.5
2,1,Max Verstappen,39,3.0,3.0,HARD,0.0,118.311,1.0,24.2
3,4,Lando Norris,1,3.0,1.0,MEDIUM,0.0,97.721,0.0,33.0
4,4,Lando Norris,28,1.0,2.0,INTERMEDIATE,0.0,120.915,1.0,21.2
5,4,Lando Norris,40,1.0,3.0,SOFT,0.0,114.840,0.0,24.6
6,44,Lewis Hamilton,1,2.0,1.0,MEDIUM,0.0,96.402,0.0,33.0
7,44,Lewis Hamilton,28,2.0,2.0,INTERMEDIATE,0.0,120.866,1.0,21.2
8,44,Lewis Hamilton,39,2.0,3.0,SOFT,0.0,117.389,1.0,24.2
9,63,George Russell,1,1.0,1.0,MEDIUM,0.0,95.560,0.0,33.0
10,63,George Russell,28,4.0,2.0,INTERMEDIATE,0.0,124.342,1.0,21.2

GEORGE RUSSELL: FINAL RECORDED LAPS

,lap_number,position,lap_duration,compound,tyre_age,rainfall,track_temperature
0,28,4.0,124.342,INTERMEDIATE,0.0,1.0,21.2
1,29,5.0,100.405,INTERMEDIATE,1.0,1.0,21.0
2,30,4.0,101.237,INTERMEDIATE,2.0,1.0,20.7
3,31,4.0,101.902,INTERMEDIATE,3.0,1.0,20.7
4,32,4.0,103.085,INTERMEDIATE,4.0,1.0,20.7
5,33,4.0,106.221,INTERMEDIATE,5.0,1.0,20.7
6,34,4.0,NaN,NaN,NaN,1.0,21.0

In [15]:
drivers_to_compare = {
    63: "George Russell",
    44: "Lewis Hamilton",
    1: "Max Verstappen",
    4: "Lando Norris",
}

window = sim_state[
    sim_state["driver_number"].isin(drivers_to_compare)
    & sim_state["lap_number"].between(25, 30)
].copy()

window["driver_name"] = window["driver_number"].map(
    drivers_to_compare
)

window = window.sort_values(["lap_number", "position"])

# Flag observed changes in tyre stint
window["previous_stint"] = (
    window.groupby("driver_number")["stint_number"].shift(1)
)

window["stint_changed"] = (
    window["stint_number"].notna()
    & window["previous_stint"].notna()
    & window["stint_number"].ne(window["previous_stint"])
)

cols = [
    "lap_number",
    "driver_name",
    "position",
    "lap_duration",
    "compound",
    "tyre_age",
    "stint_number",
    "stint_changed",
    "rainfall",
    "track_temperature",
    "traffic_ahead",
]

cols = [c for c in cols if c in window.columns]

display(window[cols].reset_index(drop=True))

print("\nObserved first intermediate-stint lap:")
for driver, name in drivers_to_compare.items():
    rows = sim_state[
        (sim_state["driver_number"] == driver)
        & (sim_state["compound"] == "INTERMEDIATE")
    ]

    if not rows.empty:
        print(f"{name}: lap {int(rows['lap_number'].min())}")

,lap_number,driver_name,position,lap_duration,compound,tyre_age,stint_number,stint_changed,rainfall,track_temperature,traffic_ahead
0,25,Lando Norris,1.0,94.307,MEDIUM,24.0,1.0,False,1.0,22.0,0.0
1,25,Lewis Hamilton,3.0,94.988,MEDIUM,24.0,1.0,False,1.0,22.0,1.0
2,25,George Russell,4.0,94.781,MEDIUM,24.0,1.0,False,1.0,22.0,1.0
3,25,Max Verstappen,5.0,96.063,MEDIUM,24.0,1.0,False,1.0,22.0,1.0
4,26,Lando Norris,1.0,101.515,MEDIUM,25.0,1.0,False,1.0,22.0,0.0
5,26,Lewis Hamilton,3.0,100.792,MEDIUM,25.0,1.0,False,1.0,22.0,1.0
6,26,George Russell,4.0,99.949,MEDIUM,25.0,1.0,False,1.0,22.0,1.0
7,26,Max Verstappen,5.0,101.491,MEDIUM,25.0,1.0,False,1.0,22.0,1.0
8,27,Lando Norris,1.0,104.806,MEDIUM,26.0,1.0,False,1.0,21.5,0.0
9,27,Lewis Hamilton,3.0,105.183,MEDIUM,26.0,1.0,False,1.0,21.5,1.0
10,27,George Russell,4.0,107.698,MEDIUM,26.0,1.0,False,1.0,21.5,1.0
11,27,Max Verstappen,5.0,119.169,INTERMEDIATE,0.0,2.0,True,1.0,21.5,1.0
12,28,Lando Norris,1.0,120.915,INTERMEDIATE,0.0,2.0,True,1.0,21.2,0.0
13,28,Lewis Hamilton,2.0,120.866,INTERMEDIATE,0.0,2.0,True,1.0,21.2,1.0
14,28,George Russell,4.0,124.342,INTERMEDIATE,0.0,2.0,True,1.0,21.2,1.0
15,28,Max Verstappen,5.0,101.176,INTERMEDIATE,1.0,2.0,False,1.0,21.2,1.0
16,29,Lando Norris,2.0,100.266,INTERMEDIATE,1.0,2.0,False,1.0,21.0,1.0
17,29,Lewis Hamilton,3.0,100.420,INTERMEDIATE,1.0,2.0,False,1.0,21.0,1.0
18,29,Max Verstappen,4.0,101.533,INTERMEDIATE,2.0,2.0,False,1.0,21.0,1.0
19,29,George Russell,5.0,100.405,INTERMEDIATE,1.0,2.0,False,1.0,21.0,1.0
20,30,Lando Norris,1.0,100.717,INTERMEDIATE,2.0,2.0,False,1.0,20.9,0.0
21,30,Lewis Hamilton,2.0,100.467,INTERMEDIATE,2.0,2.0,False,1.0,20.7,1.0
22,30,Max Verstappen,3.0,102.098,INTERMEDIATE,3.0,2.0,False,1.0,20.7,1.0
23,30,George Russell,4.0,101.237,INTERMEDIATE,2.0,2.0,False,1.0,20.7,1.0

Observed first intermediate-stint lap:
George Russell: lap 28
Lewis Hamilton: lap 28
Max Verstappen: lap 27
Lando Norris: lap 28

In [16]:

# Cell 13: Build an all-driver snapshot for any race lap

def get_race_snapshot(data, lap_number):
    snapshot = data.loc[
        data["lap_number"] == lap_number
    ].copy()

    snapshot = snapshot.sort_values(
        ["position", "driver_number"],
        na_position="last"
    ).reset_index(drop=True)

    # Add readable names for the drivers in this race
    driver_names = {
        1: "Max Verstappen",
        2: "Logan Sargeant",
        4: "Lando Norris",
        10: "Pierre Gasly",
        11: "Sergio Perez",
        14: "Fernando Alonso",
        16: "Charles Leclerc",
        18: "Lance Stroll",
        20: "Kevin Magnussen",
        22: "Yuki Tsunoda",
        23: "Alexander Albon",
        24: "Guanyu Zhou",
        27: "Nico Hulkenberg",
        31: "Esteban Ocon",
        44: "Lewis Hamilton",
        55: "Carlos Sainz",
        63: "George Russell",
        77: "Valtteri Bottas",
        81: "Oscar Piastri",
    }

    snapshot["driver_name"] = snapshot["driver_number"].map(
        driver_names
    ).fillna("Unknown")

    columns = [
        "position",
        "driver_number",
        "driver_name",
        "lap_number",
        "lap_duration",
        "compound",
        "tyre_age",
        "stint_number",
        "rainfall",
        "traffic_ahead",
        "traffic_behind",
    ]

    columns = [c for c in columns if c in snapshot.columns]

    return snapshot[columns]


# Inspect the race state immediately before the wet-weather pit window
snapshot_lap = 26

race_snapshot = get_race_snapshot(sim_state, snapshot_lap)

print(f"Race state after recorded lap {snapshot_lap}")
print("Drivers represented:", len(race_snapshot))
display(race_snapshot)

Race state after recorded lap 26
Drivers represented: 19

,position,driver_number,driver_name,lap_number,lap_duration,compound,tyre_age,stint_number,rainfall,traffic_ahead,traffic_behind
0,1.0,4,Lando Norris,26,101.515,MEDIUM,25.0,1.0,1.0,0.0,1.0
1,2.0,81,Oscar Piastri,26,100.622,MEDIUM,25.0,1.0,1.0,1.0,1.0
2,3.0,44,Lewis Hamilton,26,100.792,MEDIUM,25.0,1.0,1.0,1.0,1.0
3,4.0,63,George Russell,26,99.949,MEDIUM,25.0,1.0,1.0,1.0,0.0
4,5.0,1,Max Verstappen,26,101.491,MEDIUM,25.0,1.0,1.0,1.0,0.0
5,6.0,55,Carlos Sainz,26,102.481,MEDIUM,25.0,1.0,1.0,1.0,0.0
6,7.0,27,Nico Hulkenberg,26,101.853,MEDIUM,25.0,1.0,1.0,1.0,0.0
7,8.0,14,Fernando Alonso,26,103.618,MEDIUM,25.0,1.0,1.0,1.0,0.0
8,9.0,18,Lance Stroll,26,100.784,MEDIUM,25.0,1.0,1.0,1.0,0.0
9,10.0,22,Yuki Tsunoda,26,103.260,MEDIUM,25.0,1.0,1.0,1.0,1.0
10,11.0,23,Alexander Albon,26,103.771,MEDIUM,25.0,1.0,1.0,1.0,0.0
11,12.0,20,Kevin Magnussen,26,105.466,MEDIUM,25.0,1.0,1.0,1.0,0.0
12,13.0,2,Logan Sargeant,26,104.642,MEDIUM,25.0,1.0,1.0,1.0,1.0
13,14.0,3,Unknown,26,104.813,MEDIUM,25.0,1.0,1.0,1.0,0.0
14,15.0,77,Valtteri Bottas,26,109.533,MEDIUM,25.0,1.0,1.0,1.0,1.0
15,16.0,16,Charles Leclerc,26,105.655,INTERMEDIATE,6.0,2.0,1.0,1.0,0.0
16,17.0,11,Sergio Perez,26,105.736,INTERMEDIATE,6.0,2.0,1.0,1.0,1.0
17,18.0,31,Esteban Ocon,26,118.710,MEDIUM,4.0,3.0,1.0,1.0,0.0
18,19.0,24,Guanyu Zhou,26,105.113,INTERMEDIATE,6.0,3.0,1.0,1.0,1.0

In [17]:

# Cell 14: Define candidate strategies for George Russell

TARGET_DRIVER = 63
DECISION_LAP = 26
RACE_LAPS = int(sim_state["lap_number"].max())

# Actual first recorded lap on intermediates for George
george_data = sim_state[
    sim_state["driver_number"] == TARGET_DRIVER
].sort_values("lap_number")

actual_intermediate_laps = george_data.loc[
    george_data["compound"] == "INTERMEDIATE",
    "lap_number"
]

if actual_intermediate_laps.empty:
    raise ValueError("No observed intermediate stint found for George.")

ACTUAL_INTERMEDIATE_START = int(actual_intermediate_laps.min())

# Candidate first laps on intermediates.
# These are scenarios to test, not predictions of the best strategy.
candidate_laps = sorted(set([
    max(1, ACTUAL_INTERMEDIATE_START - 2),
    max(1, ACTUAL_INTERMEDIATE_START - 1),
    ACTUAL_INTERMEDIATE_START,
    ACTUAL_INTERMEDIATE_START + 1,
    ACTUAL_INTERMEDIATE_START + 2,
]))

candidate_strategies = pd.DataFrame({
    "strategy_id": [
        f"INTERS_LAP_{lap}" for lap in candidate_laps
    ],
    "first_intermediate_lap": candidate_laps,
})

candidate_strategies["decision_lap"] = (
    candidate_strategies["first_intermediate_lap"] - 1
)

candidate_strategies["laps_remaining_at_decision"] = (
    RACE_LAPS - candidate_strategies["decision_lap"]
)

candidate_strategies["is_historical_timing"] = (
    candidate_strategies["first_intermediate_lap"]
    == ACTUAL_INTERMEDIATE_START
)

print("Race length:", RACE_LAPS, "laps")
print("George's observed first intermediate lap:",
      ACTUAL_INTERMEDIATE_START)
print("\nCandidate strategy scenarios:")
display(candidate_strategies)

# Verify George's position and weather at each proposed decision lap
decision_context = george_data[
    george_data["lap_number"].isin(
        candidate_strategies["decision_lap"]
    )
][[
    "lap_number",
    "position",
    "compound",
    "tyre_age",
    "lap_duration",
    "rainfall",
    "track_temperature",
]].copy()

print("\nHistorical context at candidate decision laps:")
display(decision_context.sort_values("lap_number").reset_index(drop=True))

Race length: 52 laps
George's observed first intermediate lap: 28

Candidate strategy scenarios:

,strategy_id,first_intermediate_lap,decision_lap,laps_remaining_at_decision,is_historical_timing
0,INTERS_LAP_26,26,25,27,False
1,INTERS_LAP_27,27,26,26,False
2,INTERS_LAP_28,28,27,25,True
3,INTERS_LAP_29,29,28,24,False
4,INTERS_LAP_30,30,29,23,False

Historical context at candidate decision laps:

,lap_number,position,compound,tyre_age,lap_duration,rainfall,track_temperature
0,25,4.0,MEDIUM,24.0,94.781,1.0,22.0
1,26,4.0,MEDIUM,25.0,99.949,1.0,22.0
2,27,4.0,MEDIUM,26.0,107.698,1.0,21.5
3,28,4.0,INTERMEDIATE,0.0,124.342,1.0,21.2
4,29,5.0,INTERMEDIATE,1.0,100.405,1.0,21.0

In [18]:
pace_data = sim_state.copy()

# Keep valid timed laps with known tyre compounds
pace_data = pace_data[
    pace_data["lap_duration"].notna()
    & pace_data["compound"].notna()
].copy()

# Exclude pit-out laps from representative running pace
if "is_pit_out_lap" in pace_data.columns:
    pace_data = pace_data[
        ~pace_data["is_pit_out_lap"].fillna(False)
    ].copy()

# Focus on the changing-weather phase around the strategy window
pace_data["race_phase"] = pd.cut(
    pace_data["lap_number"],
    bins=[0, 20, 26, 38, 52],
    labels=["Laps 1-20", "Laps 21-26", "Laps 27-38", "Laps 39-52"]
)

pace_summary = (
    pace_data.groupby(
        ["race_phase", "compound", "rainfall"],
        observed=True
    )
    .agg(
        lap_samples=("lap_duration", "size"),
        median_lap_time=("lap_duration", "median"),
        mean_lap_time=("lap_duration", "mean"),
        median_tyre_age=("tyre_age", "median"),
    )
    .reset_index()
    .sort_values(["race_phase", "compound"])
)

print("Observed pace by race phase, compound, and rainfall")
display(pace_summary.round(3))

print("\nSamples available for each compound:")
display(
    pace_data.groupby("compound", observed=True)
    .agg(
        valid_laps=("lap_duration", "size"),
        drivers=("driver_number", "nunique"),
        median_lap_time=("lap_duration", "median"),
    )
    .reset_index()
    .round(3)
)

Observed pace by race phase, compound, and rainfall

,race_phase,compound,rainfall,lap_samples,median_lap_time,mean_lap_time,median_tyre_age
0,Laps 1-20,HARD,0.0,17,92.709,93.050,9.0
1,Laps 1-20,HARD,1.0,1,101.868,101.868,18.0
2,Laps 1-20,MEDIUM,0.0,292,92.709,93.268,8.0
3,Laps 1-20,MEDIUM,1.0,33,100.510,100.980,18.0
4,Laps 1-20,SOFT,0.0,29,94.071,95.059,7.0
5,Laps 1-20,SOFT,1.0,2,100.114,100.114,17.5
6,Laps 21-26,INTERMEDIATE,1.0,19,106.214,106.540,3.0
7,Laps 21-26,MEDIUM,1.0,94,93.842,95.511,22.0
8,Laps 27-38,INTERMEDIATE,0.0,1,99.440,99.440,11.0
9,Laps 27-38,INTERMEDIATE,1.0,187,102.992,102.809,5.0
10,Laps 27-38,MEDIUM,1.0,10,108.320,108.837,26.0
11,Laps 39-52,HARD,0.0,21,89.472,89.537,7.0
12,Laps 39-52,HARD,1.0,2,89.363,89.363,5.5
13,Laps 39-52,INTERMEDIATE,1.0,4,97.024,97.138,12.0
14,Laps 39-52,MEDIUM,0.0,61,90.148,90.481,7.0
15,Laps 39-52,MEDIUM,1.0,10,90.130,90.206,5.0
16,Laps 39-52,SOFT,0.0,118,90.941,91.112,7.0
17,Laps 39-52,SOFT,1.0,13,90.882,90.648,6.0

Samples available for each compound:

       compound  valid_laps  drivers  median_lap_time
0          HARD          41        3           89.872
1  INTERMEDIATE         211       19          103.029
2        MEDIUM         500       19           92.756
3          SOFT         162       13           91.200

In [19]:
# Cell 16: Build lap-by-lap tyre pace references

pace_window = sim_state[
    sim_state["lap_number"].between(20, 35)
    & sim_state["lap_duration"].notna()
    & sim_state["compound"].notna()
].copy()

# Exclude pit-out laps from representative running pace
if "is_pit_out_lap" in pace_window.columns:
    pace_window = pace_window[
        ~pace_window["is_pit_out_lap"].fillna(False)
    ].copy()

lap_pace_reference = (
    pace_window
    .groupby(
        ["lap_number", "compound", "rainfall"],
        observed=True
    )
    .agg(
        drivers_observed=("driver_number", "nunique"),
        median_lap_time=("lap_duration", "median"),
        median_tyre_age=("tyre_age", "median"),
    )
    .reset_index()
    .sort_values(["lap_number", "rainfall", "compound"])
)

print("Lap-by-lap compound pace references, laps 20-35")
display(lap_pace_reference.round(3))

print("\nCoverage by lap and compound")
display(
    lap_pace_reference.pivot_table(
        index="lap_number",
        columns="compound",
        values="drivers_observed",
        aggfunc="first",
        fill_value=0
    )
)

Lap-by-lap compound pace references, laps 20-35

,lap_number,compound,rainfall,drivers_observed,median_lap_time,median_tyre_age
0,20,MEDIUM,1.0,15,97.330,19.0
1,21,INTERMEDIATE,1.0,4,102.422,1.0
2,21,MEDIUM,1.0,15,93.484,20.0
3,22,INTERMEDIATE,1.0,3,104.936,2.0
4,22,MEDIUM,1.0,15,92.495,21.0
5,23,INTERMEDIATE,1.0,3,106.593,3.0
6,23,MEDIUM,1.0,16,92.752,22.0
7,24,INTERMEDIATE,1.0,3,110.729,4.0
8,24,MEDIUM,1.0,16,93.792,23.0
9,25,INTERMEDIATE,1.0,3,108.245,5.0
10,25,MEDIUM,1.0,16,95.542,24.0
11,26,INTERMEDIATE,1.0,3,105.655,6.0
12,26,MEDIUM,1.0,16,102.870,25.0
13,27,INTERMEDIATE,1.0,2,109.225,7.0
14,27,MEDIUM,1.0,9,108.126,26.0
15,28,INTERMEDIATE,1.0,9,102.187,1.0
16,28,MEDIUM,1.0,1,112.976,27.0
17,29,INTERMEDIATE,1.0,17,102.362,1.0
18,30,INTERMEDIATE,1.0,19,102.577,2.0
19,31,INTERMEDIATE,1.0,19,103.274,3.0
20,32,INTERMEDIATE,1.0,19,104.134,4.0
21,33,INTERMEDIATE,1.0,19,104.641,5.0
22,34,INTERMEDIATE,1.0,18,104.649,6.0
23,35,INTERMEDIATE,1.0,18,103.816,7.0

Coverage by lap and compound

compound    INTERMEDIATE  MEDIUM
lap_number
20                     0      15
21                     4      15
22                     3      15
23                     3      16
24                     3      16
25                     3      16
26                     3      16
27                     2       9
28                     9       1
29                    17       0
30                    19       0
31                    19       0
32                    19       0
33                    19       0
34                    18       0
35                    18       0

In [20]:
# Cell 17: Estimate observed tyre crossover

crossover = lap_pace_reference[
    lap_pace_reference["compound"].isin(["MEDIUM", "INTERMEDIATE"])
].pivot(
    index="lap_number",
    columns="compound",
    values="median_lap_time"
).reset_index()

# Keep only laps where both compounds have observed pace
crossover = crossover.dropna(
    subset=["MEDIUM", "INTERMEDIATE"]
).copy()

crossover["intermediate_minus_medium_sec"] = (
    crossover["INTERMEDIATE"] - crossover["MEDIUM"]
)

crossover["cumulative_gap_sec"] = (
    crossover["intermediate_minus_medium_sec"].cumsum()
)

print("Observed same-lap tyre pace gap")
display(crossover.round(3))

print(
    "\nInterpretation: positive gap = intermediates were slower; "
    "negative gap = intermediates were faster."
)

Observed same-lap tyre pace gap

compound,lap_number,INTERMEDIATE,MEDIUM,intermediate_minus_medium_sec,cumulative_gap_sec
1,21,102.422,93.484,8.938,8.938
2,22,104.936,92.495,12.441,21.379
3,23,106.593,92.752,13.842,35.220
4,24,110.729,93.792,16.937,52.157
5,25,108.245,95.542,12.703,64.859
6,26,105.655,102.870,2.785,67.644
7,27,109.225,108.126,1.099,68.743
8,28,102.187,112.976,-10.789,57.954

Interpretation: positive gap = intermediates were slower; negative gap = intermediates were faster.

In [21]:
# Cell 18: Inspect observed tyre changes and surrounding lap times

transition_data = sim_state.sort_values(
    ["driver_number", "lap_number"]
).copy()

transition_data["previous_compound"] = (
    transition_data.groupby("driver_number")["compound"].shift(1)
)

transition_data["previous_lap_number"] = (
    transition_data.groupby("driver_number")["lap_number"].shift(1)
)

transition_data["compound_changed"] = (
    transition_data["compound"].notna()
    & transition_data["previous_compound"].notna()
    & transition_data["compound"].ne(
        transition_data["previous_compound"]
    )
)

transitions = transition_data[
    transition_data["compound_changed"]
].copy()

transitions["driver_lap_label"] = (
    transitions["driver_number"].astype(str)
    + " | lap "
    + transitions["lap_number"].astype(str)
)

print("Observed compound changes")
display(
    transitions[
        [
            "driver_number",
            "previous_lap_number",
            "lap_number",
            "previous_compound",
            "compound",
            "lap_duration",
            "is_pit_out_lap",
            "position",
        ]
    ]
    .sort_values(["lap_number", "driver_number"])
    .round(3)
)

# Inspect laps immediately around each driver's compound change
near_transition = transition_data[
    transition_data.apply(
        lambda row: any(
            (
                transitions["driver_number"].eq(row["driver_number"])
                & (transitions["lap_number"] - row["lap_number"]).abs().le(1)
            )
        ),
        axis=1,
    )
].copy()

print("\nLap times around observed compound changes")
display(
    near_transition[
        [
            "driver_number",
            "lap_number",
            "compound",
            "lap_duration",
            "is_pit_out_lap",
            "position",
        ]
    ]
    .sort_values(["driver_number", "lap_number"])
    .round(3)
)

Observed compound changes

,driver_number,previous_lap_number,lap_number,previous_compound,compound,lap_duration,is_pit_out_lap,position
581,24,12.0,13,SOFT,MEDIUM,115.049,True,19.0
227,11,19.0,20,HARD,INTERMEDIATE,119.150,True,15.0
329,16,19.0,20,MEDIUM,INTERMEDIATE,120.269,True,7.0
588,24,19.0,20,MEDIUM,INTERMEDIATE,125.955,True,19.0
690,31,19.0,20,SOFT,INTERMEDIATE,121.025,True,18.0
692,31,21.0,22,INTERMEDIATE,MEDIUM,115.208,True,18.0
26,1,26.0,27,MEDIUM,INTERMEDIATE,119.169,True,5.0
130,3,26.0,27,MEDIUM,INTERMEDIATE,122.788,True,14.0
387,18,26.0,27,MEDIUM,INTERMEDIATE,121.611,True,8.0
645,27,26.0,27,MEDIUM,INTERMEDIATE,122.727,True,7.0
697,31,26.0,27,MEDIUM,INTERMEDIATE,122.736,True,18.0
799,55,26.0,27,MEDIUM,INTERMEDIATE,121.664,True,6.0
885,77,26.0,27,MEDIUM,INTERMEDIATE,125.367,True,15.0
79,2,27.0,28,MEDIUM,INTERMEDIATE,125.981,True,11.0
182,4,27.0,28,MEDIUM,INTERMEDIATE,120.915,True,1.0
285,14,27.0,28,MEDIUM,INTERMEDIATE,124.427,True,7.0
440,20,27.0,28,MEDIUM,INTERMEDIATE,125.299,True,10.0
492,22,27.0,28,MEDIUM,INTERMEDIATE,123.448,True,8.0
544,23,27.0,28,MEDIUM,INTERMEDIATE,128.459,True,9.0
748,44,27.0,28,MEDIUM,INTERMEDIATE,120.866,True,2.0
852,63,27.0,28,MEDIUM,INTERMEDIATE,124.342,True,4.0
938,81,28.0,29,MEDIUM,INTERMEDIATE,121.184,True,1.0
141,3,37.0,38,INTERMEDIATE,SOFT,123.328,True,13.0
245,11,37.0,38,INTERMEDIATE,MEDIUM,120.171,True,16.0
347,16,37.0,38,INTERMEDIATE,SOFT,117.811,True,15.0
450,20,37.0,38,INTERMEDIATE,SOFT,123.931,True,11.0
606,24,37.0,38,INTERMEDIATE,SOFT,126.729,True,18.0
896,77,37.0,38,INTERMEDIATE,SOFT,126.628,True,14.0
38,1,38.0,39,INTERMEDIATE,HARD,118.311,True,3.0
90,2,38.0,39,INTERMEDIATE,SOFT,116.256,True,11.0
296,14,38.0,39,INTERMEDIATE,MEDIUM,119.234,True,8.0
503,22,38.0,39,INTERMEDIATE,SOFT,118.637,True,9.0
555,23,38.0,39,INTERMEDIATE,MEDIUM,117.678,True,10.0
709,31,38.0,39,INTERMEDIATE,MEDIUM,120.130,True,16.0
759,44,38.0,39,INTERMEDIATE,SOFT,117.389,True,2.0
948,81,38.0,39,INTERMEDIATE,MEDIUM,114.658,True,4.0
194,4,39.0,40,INTERMEDIATE,SOFT,114.840,True,1.0
400,18,39.0,40,INTERMEDIATE,MEDIUM,116.032,True,7.0
658,27,39.0,40,INTERMEDIATE,SOFT,115.659,True,6.0
812,55,39.0,40,INTERMEDIATE,HARD,116.753,True,2.0
255,11,47.0,48,MEDIUM,SOFT,125.507,True,16.0
823,55,50.0,51,HARD,SOFT,112.546,True,5.0

Lap times around observed compound changes

,driver_number,lap_number,compound,lap_duration,is_pit_out_lap,position
25,1,26,MEDIUM,101.491,False,5.0
26,1,27,INTERMEDIATE,119.169,True,5.0
27,1,28,INTERMEDIATE,101.176,False,5.0
37,1,38,INTERMEDIATE,95.963,False,3.0
38,1,39,HARD,118.311,True,3.0
...,...,...,...,...,...,...
938,81,29,INTERMEDIATE,121.184,True,1.0
939,81,30,INTERMEDIATE,100.492,False,6.0
947,81,38,INTERMEDIATE,97.106,False,5.0
948,81,39,MEDIUM,114.658,True,4.0
949,81,40,MEDIUM,89.913,False,5.0

In [22]:
# Cell 19: Estimate pit-out lap excess versus same-lap running pace

pit_data = sim_state[
    sim_state["lap_duration"].notna()
    & sim_state["compound"].notna()
].copy()

pit_data["is_pit_out_lap"] = (
    pit_data["is_pit_out_lap"].fillna(False).astype(bool)
)

# Reference pace: non-pit-out laps on the same lap and compound
running_reference = (
    pit_data[~pit_data["is_pit_out_lap"]]
    .groupby(["lap_number", "compound"], observed=True)
    .agg(
        running_median=("lap_duration", "median"),
        running_drivers=("driver_number", "nunique"),
    )
    .reset_index()
)

pit_out_laps = pit_data[pit_data["is_pit_out_lap"]].merge(
    running_reference,
    on=["lap_number", "compound"],
    how="left",
    validate="many_to_one",
)

pit_out_laps["pit_out_excess_sec"] = (
    pit_out_laps["lap_duration"] - pit_out_laps["running_median"]
)

print("Pit-out laps compared with same-lap, same-compound running pace")
display(
    pit_out_laps[
        [
            "driver_number",
            "lap_number",
            "compound",
            "lap_duration",
            "running_median",
            "running_drivers",
            "pit_out_excess_sec",
        ]
    ]
    .sort_values(["lap_number", "driver_number"])
    .round(3)
)

print("\nSummary of usable pit-out excess estimates")
display(
    pit_out_laps["pit_out_excess_sec"]
    .dropna()
    .describe()
    .round(3)
    .to_frame("pit_out_excess_sec")
)

Pit-out laps compared with same-lap, same-compound running pace

,driver_number,lap_number,compound,lap_duration,running_median,running_drivers,pit_out_excess_sec
25,24,13,MEDIUM,115.049,92.492,16.0,22.556
8,11,20,INTERMEDIATE,119.150,NaN,NaN,NaN
14,16,20,INTERMEDIATE,120.269,NaN,NaN,NaN
26,24,20,INTERMEDIATE,125.955,NaN,NaN,NaN
31,31,20,INTERMEDIATE,121.025,NaN,NaN,NaN
32,31,22,MEDIUM,115.208,92.495,15.0,22.713
0,1,27,INTERMEDIATE,119.169,109.225,2.0,9.944
4,3,27,INTERMEDIATE,122.788,109.225,2.0,13.563
17,18,27,INTERMEDIATE,121.611,109.225,2.0,12.386
27,24,27,INTERMEDIATE,124.515,109.225,2.0,15.290
29,27,27,INTERMEDIATE,122.727,109.225,2.0,13.502
33,31,27,INTERMEDIATE,122.736,109.225,2.0,13.511
37,55,27,INTERMEDIATE,121.664,109.225,2.0,12.439
41,77,27,INTERMEDIATE,125.367,109.225,2.0,16.142
2,2,28,INTERMEDIATE,125.981,102.187,9.0,23.794
6,4,28,INTERMEDIATE,120.915,102.187,9.0,18.728
12,14,28,INTERMEDIATE,124.427,102.187,9.0,22.240
15,16,28,INTERMEDIATE,123.138,102.187,9.0,20.951
19,20,28,INTERMEDIATE,125.299,102.187,9.0,23.112
21,22,28,INTERMEDIATE,123.448,102.187,9.0,21.261
23,23,28,INTERMEDIATE,128.459,102.187,9.0,26.272
35,44,28,INTERMEDIATE,120.866,102.187,9.0,18.679
40,63,28,INTERMEDIATE,124.342,102.187,9.0,22.155
9,11,29,INTERMEDIATE,124.385,102.362,17.0,22.023
43,81,29,INTERMEDIATE,121.184,102.362,17.0,18.822
5,3,38,SOFT,123.328,NaN,NaN,NaN
10,11,38,MEDIUM,120.171,NaN,NaN,NaN
16,16,38,SOFT,117.811,NaN,NaN,NaN
20,20,38,SOFT,123.931,NaN,NaN,NaN
28,24,38,SOFT,126.729,NaN,NaN,NaN
42,77,38,SOFT,126.628,NaN,NaN,NaN
1,1,39,HARD,118.311,NaN,NaN,NaN
3,2,39,SOFT,116.256,93.138,5.0,23.118
13,14,39,MEDIUM,119.234,92.722,1.0,26.512
22,22,39,SOFT,118.637,93.138,5.0,25.499
24,23,39,MEDIUM,117.678,92.722,1.0,24.956
34,31,39,MEDIUM,120.130,92.722,1.0,27.408
36,44,39,SOFT,117.389,93.138,5.0,24.251
44,81,39,MEDIUM,114.658,92.722,1.0,21.936
7,4,40,SOFT,114.840,92.194,8.0,22.646
18,18,40,MEDIUM,116.032,91.146,5.0,24.886
30,27,40,SOFT,115.659,92.194,8.0,23.464
38,55,40,HARD,116.753,90.056,1.0,26.697
11,11,48,SOFT,125.507,91.031,10.0,34.476
39,55,51,SOFT,112.546,91.529,9.0,21.017

Summary of usable pit-out excess estimates

       pit_out_excess_sec
count              34.000
mean               21.087
std                 5.278
min                 9.944
25%                18.691
50%                22.198
75%                24.137
max                34.476

In [23]:
# Cell 20: Strategy sensitivity analysis for George Russell

import numpy as np
import pandas as pd

# Observed same-lap pace differences from Cell 17
observed_gaps = crossover.set_index("lap_number")[
    "intermediate_minus_medium_sec"
].to_dict()

# Scenarios for the missing counterfactual:
# positive = mediums are slower than intermediates after lap 27
# These are assumptions to test, not learned facts.
post_crossover_scenarios = {
    "Mediums equal to inters": 0.0,
    "Mediums 2s slower per lap": 2.0,
    "Mediums 5s slower per lap": 5.0,
}

candidate_laps = [26, 27, 28, 29, 30]
last_lap = int(sim_state["lap_number"].max())

results = []

for scenario_name, medium_disadvantage in post_crossover_scenarios.items():
    for pit_lap in candidate_laps:
        total_delta = 0.0
        unsupported_laps = 0

        for lap in range(21, last_lap + 1):
            if lap < pit_lap:
                # George stays on mediums
                if lap in observed_gaps:
                    total_delta += 0.0
                elif lap > 27:
                    # No reliable observed medium/intermediate comparison
                    total_delta += 0.0
                    unsupported_laps += 1

            else:
                # George has switched to intermediates
                if lap in observed_gaps:
                    total_delta += observed_gaps[lap]
                elif lap > 27:
                    # Scenario assumption for the unobserved medium alternative
                    total_delta -= medium_disadvantage
                    unsupported_laps += 1

        results.append({
            "scenario": scenario_name,
            "intermediate_start_lap": pit_lap,
            "assumed_medium_disadvantage_sec_per_lap": medium_disadvantage,
            "estimated_delta_sec": round(total_delta, 2),
            "unsupported_laps": unsupported_laps,
        })

strategy_sensitivity = pd.DataFrame(results)

print("Sensitivity results (exploratory, not a validated race prediction)")
display(
    strategy_sensitivity.pivot(
        index="intermediate_start_lap",
        columns="scenario",
        values="estimated_delta_sec",
    ).round(2)
)

print(
    "\nImportant: these totals are scenario comparisons, not predicted finishing "
    "times or win probabilities. The unsupported-lap count shows where "
    "counterfactual pace assumptions enter the calculation."
)

Sensitivity results (exploratory, not a validated race prediction)

scenario,Mediums 2s slower per lap,Mediums 5s slower per lap,Mediums equal to inters
intermediate_start_lap,,,
26,-54.91,-126.91,-6.91
27,-57.69,-129.69,-9.69
28,-58.79,-130.79,-10.79
29,-48.00,-120.00,0.00
30,-46.00,-115.00,0.00

Important: these totals are scenario comparisons, not predicted finishing times or win probabilities. The unsupported-lap count shows where counterfactual pace assumptions enter the calculation.

In [24]:
def build_decision_state(sim_state, driver_number, decision_lap):
    required_columns = [
        "driver_number",
        "lap_number",
        "position",
        "compound",
        "tyre_age",
    ]

    missing_columns = [
        col for col in required_columns
        if col not in sim_state.columns
    ]

    if missing_columns:
        raise ValueError(
            f"Missing required columns: {missing_columns}"
        )
    if decision_lap < 1:
        raise ValueError("decision_lap must be at least 1.")

    # Latest available state for every driver at this lap
    field_state = (
        sim_state.loc[
            sim_state["lap_number"].eq(decision_lap)
        ]
        .sort_values("position", na_position="last")
        .copy()
        .reset_index(drop=True)
    )

    if field_state.empty:
        raise ValueError(
            f"No race-state data available for lap {decision_lap}."
        )

    # Find the selected driver
    target_rows = field_state.loc[
        field_state["driver_number"].eq(driver_number)
    ]

    if target_rows.empty:
        available_drivers = sorted(
            field_state["driver_number"].dropna().unique().tolist()
        )

        raise ValueError(
            f"Driver {driver_number} has no recorded state "
            f"on lap {decision_lap}. "
            f"Drivers available: {available_drivers}"
        )

    target_state = target_rows.iloc[0].copy()

    # Automatically collect the useful state fields already available
    context_columns = [
        "driver_number",
        "lap_number",
        "position",
        "compound",
        "tyre_age",
        "stint_number",
        "lap_duration",
        "is_pit_out_lap",
        "fuel_effect",
        "tyre_degradation_effect",
        "traffic_ahead",
        "traffic_behind",
        "position_change",
        "rainfall",
        "humidity",
        "air_temperature",
        "track_temperature",
        "wind_speed",
        "grip_condition",
        "blue_flag",
    ]

    context_columns = [
        col for col in context_columns
        if col in field_state.columns
    ]

    field_context = field_state[context_columns].copy()

    # Flag missing information for the selected driver
    important_fields = [
        "position",
        "compound",
        "tyre_age",
        "fuel_effect",
        "tyre_degradation_effect",
        "traffic_ahead",
        "traffic_behind",
        "rainfall",
        "air_temperature",
    ]

    important_fields = [
        col for col in important_fields
        if col in target_state.index
    ]

    missing_features = [
        col for col in important_fields
        if pd.isna(target_state[col])
    ]

    decision_context = {
        "driver_number": int(driver_number),
        "decision_lap": int(decision_lap),
        "next_lap": int(decision_lap + 1),
        "race_laps_in_dataset": int(
            sim_state["lap_number"].max()
        ),
        "drivers_observed": int(
            field_state["driver_number"].nunique()
        ),
        "target_state": target_state,
        "field_state": field_context,
        "missing_target_features": missing_features,
    }

    return decision_context


# First test: George Russell after lap 26
decision_state = build_decision_state(
    sim_state=sim_state,
    driver_number=63,
    decision_lap=26,
)

print("PITWALL DECISION STATE")
print("=" * 45)
print("Selected driver:", decision_state["driver_number"])
print("State after lap:", decision_state["decision_lap"])
print("Next lap to strategize:", decision_state["next_lap"])
print("Drivers observed:", decision_state["drivers_observed"])
print(
    "Missing important features:",
    decision_state["missing_target_features"]
)

print("\nSELECTED DRIVER STATE")
display(
    decision_state["target_state"]
    .to_frame("value")
)

print("\nFIELD STATE")
display(decision_state["field_state"])

PITWALL DECISION STATE
=============================================
Selected driver: 63
State after lap: 26
Next lap to strategize: 27
Drivers observed: 19
Missing important features: []

SELECTED DRIVER STATE

                                                    value
driver_number                                          63
lap_number                                             26
date_start               2024-07-07 14:41:59.699000+00:00
lap_duration                                       99.949
compound                                           MEDIUM
tyre_age                                             25.0
stint_number                                          1.0
is_pit_out_lap                                      False
position                                              4.0
session_key                                        9558.0
meeting_key                                        1240.0
track_temperature                                    22.0
wind_speed                                            0.8
rainfall                                              1.0
humidity                                             69.0
pressure                                            992.2
air_temperature                                      15.1
wind_direction                                      267.0
weather_age_seconds                                56.971
drs_available                                       False
grip_condition                                        LOW
blue_flag                                           False
date                                                  NaT
fuel_effect                                     -2.103049
traffic_ahead                                         1.0
traffic_behind                                        0.0
position_change                                       0.0
tyre_degradation_effect                           5.38111

FIELD STATE

,driver_number,lap_number,position,compound,tyre_age,stint_number,lap_duration,is_pit_out_lap,fuel_effect,tyre_degradation_effect,traffic_ahead,traffic_behind,position_change,rainfall,humidity,air_temperature,track_temperature,wind_speed,grip_condition,blue_flag
0,4,26,1.0,MEDIUM,25.0,1.0,101.515,False,-2.103049,5.381110,0.0,1.0,0.0,1.0,69.0,15.1,22.0,0.8,LOW,False
1,81,26,2.0,MEDIUM,25.0,1.0,100.622,False,-2.103049,5.381110,1.0,1.0,0.0,1.0,69.0,15.1,22.0,0.8,LOW,False
2,44,26,3.0,MEDIUM,25.0,1.0,100.792,False,-2.103049,5.381110,1.0,1.0,0.0,1.0,69.0,15.1,22.0,0.8,LOW,False
3,63,26,4.0,MEDIUM,25.0,1.0,99.949,False,-2.103049,5.381110,1.0,0.0,0.0,1.0,69.0,15.1,22.0,0.8,LOW,False
4,1,26,5.0,MEDIUM,25.0,1.0,101.491,False,-2.103049,5.381110,1.0,0.0,0.0,1.0,67.0,15.1,22.0,1.0,LOW,False
5,55,26,6.0,MEDIUM,25.0,1.0,102.481,False,-2.103049,5.381110,1.0,0.0,0.0,1.0,67.0,15.1,22.0,1.0,LOW,False
6,27,26,7.0,MEDIUM,25.0,1.0,101.853,False,-2.103049,5.381110,1.0,0.0,0.0,1.0,67.0,15.1,22.0,1.0,LOW,False
7,14,26,8.0,MEDIUM,25.0,1.0,103.618,False,-2.103049,5.381110,1.0,0.0,0.0,1.0,67.0,15.1,22.0,1.0,LOW,False
8,18,26,9.0,MEDIUM,25.0,1.0,100.784,False,-2.103049,5.381110,1.0,0.0,0.0,1.0,67.0,15.1,22.0,1.0,LOW,False
9,22,26,10.0,MEDIUM,25.0,1.0,103.260,False,-2.103049,5.381110,1.0,1.0,0.0,1.0,67.0,15.1,22.0,1.0,LOW,False
10,23,26,11.0,MEDIUM,25.0,1.0,103.771,False,-2.103049,5.381110,1.0,0.0,0.0,1.0,67.0,15.1,22.0,1.0,LOW,False
11,20,26,12.0,MEDIUM,25.0,1.0,105.466,False,-2.103049,5.381110,1.0,0.0,0.0,1.0,67.0,15.1,22.0,1.0,LOW,False
12,2,26,13.0,MEDIUM,25.0,1.0,104.642,False,-2.103049,5.381110,1.0,1.0,0.0,1.0,67.0,15.1,22.0,1.0,LOW,False
13,3,26,14.0,MEDIUM,25.0,1.0,104.813,False,-2.103049,5.381110,1.0,0.0,0.0,1.0,67.0,15.1,22.0,1.0,LOW,False
14,77,26,15.0,MEDIUM,25.0,1.0,109.533,False,-2.103049,5.381110,1.0,1.0,0.0,1.0,67.0,15.1,22.0,1.0,LOW,False
15,16,26,16.0,INTERMEDIATE,6.0,2.0,105.655,False,NaN,NaN,1.0,0.0,0.0,1.0,68.0,15.1,21.5,0.9,LOW,False
16,11,26,17.0,INTERMEDIATE,6.0,2.0,105.736,False,NaN,NaN,1.0,1.0,0.0,1.0,68.0,15.1,21.5,0.9,LOW,False
17,31,26,18.0,MEDIUM,4.0,3.0,118.710,False,NaN,0.860978,1.0,0.0,0.0,1.0,68.0,15.1,21.4,0.7,LOW,True
18,24,26,19.0,INTERMEDIATE,6.0,3.0,105.113,False,NaN,NaN,1.0,1.0,0.0,1.0,68.0,15.1,21.4,0.7,LOW,False

In [25]:


def generate_strategy_candidates(
    decision_state,
    sim_state,
    pit_window=5,
):
    target = decision_state["target_state"]
    decision_lap = decision_state["decision_lap"]
    next_lap = decision_state["next_lap"]
    driver_number = decision_state["driver_number"]

    current_compound = target["compound"]

    if pd.isna(current_compound):
        raise ValueError(
            f"Driver {driver_number} has no recorded compound "
            f"at lap {decision_lap}."
        )

    current_compound = str(current_compound).upper()

    last_race_lap = int(sim_state["lap_number"].max())

    # Candidate pit laps must be after the completed decision lap
    candidate_pit_laps = list(
        range(
            next_lap,
            min(decision_lap + pit_window, last_race_lap - 1) + 1,
        )
    )

    # Compounds actually observed around this decision window
    observed_window = sim_state[
        sim_state["lap_number"].between(
            max(1, decision_lap - 2),
            min(last_race_lap, decision_lap + pit_window),
        )
        & sim_state["compound"].notna()
    ].copy()

    available_compounds = sorted(
        observed_window["compound"]
        .astype(str)
        .str.upper()
        .unique()
        .tolist()
    )

    # Use observed weather to prioritize sensible compound choices.
    rainfall = target.get("rainfall", np.nan)
    grip = str(target.get("grip_condition", "")).upper()

    wet_conditions = (
        (pd.notna(rainfall) and float(rainfall) > 0)
        or grip in {"LOW", "WET"}
    )

    wet_compounds = {"INTERMEDIATE", "WET"}
    dry_compounds = {"SOFT", "MEDIUM", "HARD"}

    if wet_conditions:
        eligible_compounds = [
            compound for compound in available_compounds
            if compound in wet_compounds
        ]
    else:
        eligible_compounds = [
            compound for compound in available_compounds
            if compound in dry_compounds
        ]

    # Always include the option to remain on the current tyres
    # through the candidate window as a baseline.
    candidates = [{
        "driver_number": driver_number,
        "decision_lap": decision_lap,
        "strategy_type": "HOLD",
        "pit_lap": None,
        "target_compound": current_compound,
        "description": (
            f"Stay on {current_compound} through the candidate window"
        ),
    }]

    # Generate all feasible pit-lap / eligible-compound combinations
    for pit_lap in candidate_pit_laps:
        for compound in eligible_compounds:
            if compound == current_compound:
                continue

            candidates.append({
                "driver_number": driver_number,
                "decision_lap": decision_lap,
                "strategy_type": "PIT",
                "pit_lap": pit_lap,
                "target_compound": compound,
                "description": (
                    f"Switch to {compound} on lap {pit_lap}"
                ),
            })

    candidates_df = pd.DataFrame(candidates)

    if candidates_df.empty:
        raise ValueError(
            "No feasible strategy candidates were generated. "
            "Check compound availability and the decision lap."
        )

    candidates_df.insert(
        0,
        "strategy_id",
        [
            f"S{i + 1:03d}"
            for i in range(len(candidates_df))
        ],
    )

    candidates_df["is_hold_baseline"] = (
        candidates_df["strategy_type"] == "HOLD"
    )

    return candidates_df


# Generate strategies for George after lap 26
strategy_candidates = generate_strategy_candidates(
    decision_state=decision_state,
    sim_state=sim_state,
    pit_window=5,
)

print("Selected driver:", decision_state["driver_number"])
print("Decision lap:", decision_state["decision_lap"])
print("Candidate strategies:", len(strategy_candidates))

display(strategy_candidates)

Selected driver: 63
Decision lap: 26
Candidate strategies: 6

,strategy_id,driver_number,decision_lap,strategy_type,pit_lap,target_compound,description,is_hold_baseline
0,S001,63,26,HOLD,NaN,MEDIUM,Stay on MEDIUM through the candidate window,True
1,S002,63,26,PIT,27.0,INTERMEDIATE,Switch to INTERMEDIATE on lap 27,False
2,S003,63,26,PIT,28.0,INTERMEDIATE,Switch to INTERMEDIATE on lap 28,False
3,S004,63,26,PIT,29.0,INTERMEDIATE,Switch to INTERMEDIATE on lap 29,False
4,S005,63,26,PIT,30.0,INTERMEDIATE,Switch to INTERMEDIATE on lap 30,False
5,S006,63,26,PIT,31.0,INTERMEDIATE,Switch to INTERMEDIATE on lap 31,False

In [26]:

pace_check_columns = [
    "lap_duration",
    "compound",
    "tyre_age",
    "fuel_effect",
    "tyre_degradation_effect",
    "traffic_ahead",
    "traffic_behind",
    "position_change",
    "rainfall",
    "humidity",
    "air_temperature",
    "track_temperature",
    "wind_speed",
    "is_pit_out_lap",
]

available_columns = [
    col for col in pace_check_columns if col in sim_state.columns
]

print("SIMULATION DATA")
print("=" * 60)
print("Rows:", len(sim_state))
print("Unique drivers:", sim_state["driver_number"].nunique())
print("Lap range:", sim_state["lap_number"].min(), "to", sim_state["lap_number"].max())
print("Available pace features:", available_columns)

# Keep only rows with a known lap time and compound for this assessment
pace_data = sim_state.loc[
    sim_state["lap_duration"].notna()
    & sim_state["compound"].notna()
].copy()

if "is_pit_out_lap" in pace_data.columns:
    pace_data["is_pit_out_lap"] = (
        pace_data["is_pit_out_lap"].fillna(False).astype(bool)
    )
else:
    pace_data["is_pit_out_lap"] = False

pace_data["compound"] = pace_data["compound"].astype(str).str.upper()

print("\nDATA COUNTS BY COMPOUND")
print("=" * 60)

compound_summary = (
    pace_data.groupby("compound")
    .agg(
        total_laps=("lap_duration", "size"),
        drivers=("driver_number", "nunique"),
        pit_out_laps=("is_pit_out_lap", "sum"),
        median_lap_time=("lap_duration", "median"),
        fastest_lap=("lap_duration", "min"),
        slowest_lap=("lap_duration", "max"),
    )
    .round(2)
)

display(compound_summary)

# Assess missingness separately for each compound
feature_columns = [
    col for col in available_columns
    if col not in ["lap_duration", "compound", "is_pit_out_lap"]
]

missingness = (
    pace_data.groupby("compound")[feature_columns]
    .apply(lambda group: (group.isna().mean() * 100).round(1))
)

print("\nMISSING FEATURE VALUES BY COMPOUND (%)")
print("=" * 60)
display(missingness)

# Compare normal racing laps with pit-out laps
pace_data["lap_type"] = np.where(
    pace_data["is_pit_out_lap"],
    "Pit-out",
    "Normal"
)

print("\nLAP-TIME DISTRIBUTION: NORMAL VS PIT-OUT")
print("=" * 60)

lap_type_summary = (
    pace_data.groupby(["compound", "lap_type"])["lap_duration"]
    .agg(["count", "median", "mean"])
    .round(2)
)

display(lap_type_summary)

SIMULATION DATA
============================================================
Rows: 962
Unique drivers: 20
Lap range: 1 to 52
Available pace features: ['lap_duration', 'compound', 'tyre_age', 'fuel_effect', 'tyre_degradation_effect', 'traffic_ahead', 'traffic_behind', 'position_change', 'rainfall', 'humidity', 'air_temperature', 'track_temperature', 'wind_speed', 'is_pit_out_lap']

DATA COUNTS BY COMPOUND
============================================================

,total_laps,drivers,pit_out_laps,median_lap_time,fastest_lap,slowest_lap
compound,,,,,,
HARD,43,3,2,90.06,88.95,118.31
INTERMEDIATE,234,19,23,103.22,95.96,128.46
MEDIUM,508,19,8,92.77,88.75,120.17
SOFT,174,13,12,91.32,88.29,126.73

MISSING FEATURE VALUES BY COMPOUND (%)
============================================================

,tyre_age,fuel_effect,tyre_degradation_effect,traffic_ahead,traffic_behind,position_change,rainfall,humidity,air_temperature,track_temperature,wind_speed
compound,,,,,,,,,,,
HARD,0.0,4.7,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
INTERMEDIATE,0.0,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MEDIUM,0.0,3.7,11.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SOFT,0.0,6.9,8.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

LAP-TIME DISTRIBUTION: NORMAL VS PIT-OUT
============================================================

                       count  median    mean
compound     lap_type
HARD         Normal       41   89.87   91.29
             Pit-out       2  117.53  117.53
INTERMEDIATE Normal      211  103.03  103.02
             Pit-out      23  122.79  123.02
MEDIUM       Normal      500   92.76   94.11
             Pit-out       8  116.85  117.27
SOFT         Normal      162   91.20   91.89
             Pit-out      12  118.22  119.94

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Exclude pit-out laps so the model learns racing pace, not pit-exit delays
model_data = pace_data.loc[
    ~pace_data["is_pit_out_lap"]
    & pace_data["lap_duration"].notna()
    & pace_data["compound"].notna()
].copy()

# Keep only features available in the current simulation dataset
numeric_features = [
    "lap_number",
    "tyre_age",
    "rainfall",
    "humidity",
    "air_temperature",
    "track_temperature",
    "wind_speed",
    "traffic_ahead",
    "traffic_behind",
    "position_change",
]

categorical_features = ["compound", "driver_number"]

numeric_features = [
    col for col in numeric_features if col in model_data.columns
]
categorical_features = [
    col for col in categorical_features if col in model_data.columns
]

feature_columns = numeric_features + categorical_features

# Time-ordered split: earlier laps train, later laps test
split_lap = 35

train_data = model_data.loc[
    model_data["lap_number"] <= split_lap
].copy()

test_data = model_data.loc[
    model_data["lap_number"] > split_lap
].copy()

if train_data.empty or test_data.empty:
    raise ValueError("The temporal train/test split produced an empty dataset.")

X_train = train_data[feature_columns]
y_train = train_data["lap_duration"]

X_test = test_data[feature_columns]
y_test = test_data["lap_duration"]

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore")),
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features),
])

pace_baseline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=300,
        min_samples_leaf=5,
        random_state=42,
        n_jobs=-1,
    )),
])

pace_baseline.fit(X_train, y_train)
test_predictions = pace_baseline.predict(X_test)

mae = mean_absolute_error(y_test, test_predictions)
rmse = np.sqrt(mean_squared_error(y_test, test_predictions))
r2 = r2_score(y_test, test_predictions)

# Simple reference baseline: always predict the training-set median
median_baseline_prediction = np.full(
    len(y_test), y_train.median()
)
median_baseline_mae = mean_absolute_error(
    y_test, median_baseline_prediction
)

print("TIME-ORDERED PACE VALIDATION")
print("=" * 55)
print(f"Training laps: 1 to {split_lap}")
print(f"Test laps: {split_lap + 1} to {int(test_data['lap_number'].max())}")
print(f"Training rows: {len(train_data)}")
print(f"Test rows: {len(test_data)}")
print(f"Model MAE: {mae:.3f} seconds")
print(f"Model RMSE: {rmse:.3f} seconds")
print(f"Model R²: {r2:.3f}")
print(f"Median-baseline MAE: {median_baseline_mae:.3f} seconds")

# Check performance separately for each compound in the test period
evaluation = test_data[
    ["driver_number", "lap_number", "compound", "lap_duration"]
].copy()

evaluation["predicted_lap_duration"] = test_predictions
evaluation["absolute_error"] = (
    evaluation["lap_duration"]
    - evaluation["predicted_lap_duration"]
).abs()

print("\nTEST PERFORMANCE BY COMPOUND")
print("=" * 55)

compound_evaluation = (
    evaluation.groupby("compound")
    .agg(
        test_laps=("lap_duration", "size"),
        MAE=("absolute_error", "mean"),
        actual_median=("lap_duration", "median"),
        predicted_median=("predicted_lap_duration", "median"),
    )
    .round(3)
)

display(compound_evaluation)

TIME-ORDERED PACE VALIDATION
=======================================================
Training laps: 1 to 35
Test laps: 36 to 52
Training rows: 637
Test rows: 277
Model MAE: 9.314 seconds
Model RMSE: 9.786 seconds
Model R²: -4.830
Median-baseline MAE: 3.984 seconds

TEST PERFORMANCE BY COMPOUND
=======================================================

              test_laps     MAE  actual_median  predicted_median
compound
HARD                 23  11.713         89.472           101.081
INTERMEDIATE         52   3.911        100.458           104.160
MEDIUM               71  10.702         90.148           100.996
SOFT                131  10.285         90.929           101.208

In [28]:

# Cell 25: Diagnose prediction errors across the race

# Overall error by lap
evaluation["error"] = (
    evaluation["predicted_lap_duration"]
    - evaluation["lap_duration"]
)

lap_diagnostics = (
    evaluation.groupby("lap_number")
    .agg(
        drivers=("driver_number", "nunique"),
        actual_median=("lap_duration", "median"),
        predicted_median=("predicted_lap_duration", "median"),
        MAE=("absolute_error", "mean"),
        mean_error=("error", "mean"),
    )
    .round(2)
)

print("TEST-PERIOD ERRORS BY LAP")
display(lap_diagnostics)

# Join the observed weather state for the same lap
weather_columns = [
    col for col in [
        "lap_number", "rainfall", "grip_condition",
        "track_temperature", "air_temperature"
    ]
    if col in sim_state.columns
]

lap_weather = (
    sim_state[weather_columns]
    .groupby("lap_number")
    .agg({
        col: "first"
        for col in weather_columns
        if col != "lap_number"
    })
    .reset_index()
)

lap_diagnostics_weather = (
    lap_diagnostics.reset_index()
    .merge(lap_weather, on="lap_number", how="left")
)

print("\nERRORS WITH WEATHER CONTEXT")
display(lap_diagnostics_weather.round(2))

# Check whether the training and test periods have different conditions
print("\nTRAIN VS TEST CONDITIONS")
condition_summary = (
    model_data.assign(
        period=np.where(
            model_data["lap_number"] <= split_lap,
            "Train",
            "Test"
        )
    )
    .groupby("period")
    .agg(
        rows=("lap_duration", "size"),
        median_lap_time=("lap_duration", "median"),
        wet_laps=("rainfall", lambda s: (s.fillna(0) > 0).sum()),
        median_tyre_age=("tyre_age", "median"),
    )
    .round(2)
)

display(condition_summary)

TEST-PERIOD ERRORS BY LAP

            drivers  actual_median  predicted_median    MAE  mean_error
lap_number
36               18         102.74            104.06   1.53        1.50
37               18         100.46            104.81   4.06        4.06
38               12          98.52            104.42   6.24        6.24
39               10          94.98            103.15   8.16        8.16
40               14          91.71            101.99  10.04       10.04
41               18          90.65            101.03  10.46       10.46
42               18          90.16            100.88  10.54       10.54
43               18          90.14            101.29  11.06       11.06
44               18          90.21            101.62  11.21       11.21
45               18          90.23            101.68  11.13       11.13
46               18          90.16            101.17  10.79       10.79
47               18          90.22            101.01  10.56       10.56
48               17          90.36            101.07  10.30       10.30
49               18          90.75            101.06   9.97        9.97
50               18          90.52            101.05  10.34       10.34
51               14          90.73            101.04  10.30       10.30
52               12          90.50            101.79  11.18       11.18

ERRORS WITH WEATHER CONTEXT

,lap_number,drivers,actual_median,predicted_median,MAE,mean_error,rainfall,grip_condition,track_temperature,air_temperature
0,36,18,102.74,104.06,1.53,1.50,1.0,LOW,21.2,14.5
1,37,18,100.46,104.81,4.06,4.06,1.0,LOW,21.4,14.5
2,38,12,98.52,104.42,6.24,6.24,1.0,LOW,22.5,14.6
3,39,10,94.98,103.15,8.16,8.16,1.0,LOW,24.2,14.6
4,40,14,91.71,101.99,10.04,10.04,0.0,LOW,24.6,14.8
5,41,18,90.65,101.03,10.46,10.46,0.0,LOW,24.4,15.1
6,42,18,90.16,100.88,10.54,10.54,0.0,NORMAL,24.2,15.3
7,43,18,90.14,101.29,11.06,11.06,0.0,NORMAL,24.7,15.3
8,44,18,90.21,101.62,11.21,11.21,0.0,NORMAL,24.9,15.3
9,45,18,90.23,101.68,11.13,11.13,1.0,NORMAL,24.5,15.4
10,46,18,90.16,101.17,10.79,10.79,0.0,NORMAL,25.0,15.5
11,47,18,90.22,101.01,10.56,10.56,0.0,NORMAL,25.0,15.5
12,48,17,90.36,101.07,10.30,10.30,0.0,NORMAL,24.9,15.6
13,49,18,90.75,101.06,9.97,9.97,0.0,NORMAL,25.2,15.7
14,50,18,90.52,101.05,10.34,10.34,0.0,NORMAL,25.2,15.8
15,51,14,90.73,101.04,10.30,10.30,0.0,NORMAL,25.4,15.8
16,52,12,90.50,101.79,11.18,11.18,0.0,NORMAL,25.3,15.9

TRAIN VS TEST CONDITIONS

        rows  median_lap_time  wet_laps  median_tyre_age
period
Test     277            90.85        76              8.0
Train    637            94.08       299              8.0

In [29]:

# Cell 26: Compare Linear Regression, Random Forest, and XGBoost

import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from xgboost import XGBRegressor

# ---------------------------------------------------------
# 1. Build a clean dataset without pit-out laps
# ---------------------------------------------------------
model_data = sim_state.loc[
    sim_state["lap_duration"].notna()
    & sim_state["compound"].notna()
].copy()

model_data["compound"] = model_data["compound"].astype(str).str.upper()
model_data["driver_number"] = model_data["driver_number"].astype(str)

model_data["is_pit_out_lap"] = (
    model_data["is_pit_out_lap"].fillna(False).astype(bool)
)

model_data = model_data.loc[
    ~model_data["is_pit_out_lap"]
].copy()

model_data = model_data.sort_values(
    ["lap_number", "driver_number"]
).reset_index(drop=True)

# ---------------------------------------------------------
# 2. Create track evolution using weather data only
# ---------------------------------------------------------
# One weather record per lap. These are observed conditions,
# not lap-time outcomes.
weather_by_lap = (
    model_data.groupby("lap_number")
    .agg(
        rainfall=("rainfall", "median"),
        track_temperature=("track_temperature", "median"),
        air_temperature=("air_temperature", "median"),
        humidity=("humidity", "median"),
    )
    .sort_index()
)

# Rolling change over the previous 3 lap observations.
# shift(1) ensures the trend feature does not use the
# current lap's weather or any future observations.
for col in [
    "rainfall",
    "track_temperature",
    "air_temperature",
    "humidity",
]:
    previous_weather = weather_by_lap[col].shift(1)

    weather_by_lap[f"{col}_change_3lap"] = (
        previous_weather - previous_weather.shift(3)
    ) / 3

weather_features = [
    "rainfall_change_3lap",
    "track_temperature_change_3lap",
    "air_temperature_change_3lap",
    "humidity_change_3lap",
]

weather_by_lap = weather_by_lap.rename(columns={
    "rainfall_change_3lap": "rainfall_trend",
    "track_temperature_change_3lap": "track_temp_trend",
    "air_temperature_change_3lap": "air_temp_trend",
    "humidity_change_3lap": "humidity_trend",
})

weather_features = [
    "rainfall_trend",
    "track_temp_trend",
    "air_temp_trend",
    "humidity_trend",
]

model_data = model_data.merge(
    weather_by_lap[weather_features],
    left_on="lap_number",
    right_index=True,
    how="left",
    validate="many_to_one",
)

# ---------------------------------------------------------
# 3. Define shared features for a fair comparison
# ---------------------------------------------------------
numeric_features = [
    "lap_number",
    "tyre_age",
    "rainfall",
    "humidity",
    "air_temperature",
    "track_temperature",
    "wind_speed",
    "traffic_ahead",
    "traffic_behind",
    "position_change",
    "rainfall_trend",
    "track_temp_trend",
    "air_temp_trend",
    "humidity_trend",
]

categorical_features = [
    "compound",
    "driver_number",
]

numeric_features = [
    col for col in numeric_features if col in model_data.columns
]

feature_columns = numeric_features + categorical_features

# Chronological split, matching Cell 24
split_lap = 35

train_data = model_data.loc[
    model_data["lap_number"] <= split_lap
].copy()

test_data = model_data.loc[
    model_data["lap_number"] > split_lap
].copy()

X_train = train_data[feature_columns]
y_train = train_data["lap_duration"]

X_test = test_data[feature_columns]
y_test = test_data["lap_duration"]

# ---------------------------------------------------------
# 4. Shared preprocessing
# ---------------------------------------------------------
def make_preprocessor(scale_numeric=False):
    numeric_steps = [
        ("imputer", SimpleImputer(strategy="median")),
    ]

    if scale_numeric:
        numeric_steps.append(("scaler", StandardScaler()))

    numeric_pipeline = Pipeline(numeric_steps)

    categorical_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore")),
    ])

    return ColumnTransformer([
        ("numeric", numeric_pipeline, numeric_features),
        ("categorical", categorical_pipeline, categorical_features),
    ])

# ---------------------------------------------------------
# 5. Define models
# ---------------------------------------------------------
models = {
    "Linear Regression": Pipeline([
        ("preprocessor", make_preprocessor(scale_numeric=True)),
        ("model", LinearRegression()),
    ]),

    "Random Forest": Pipeline([
        ("preprocessor", make_preprocessor()),
        ("model", RandomForestRegressor(
            n_estimators=300,
            min_samples_leaf=5,
            random_state=42,
            n_jobs=-1,
        )),
    ]),

    "XGBoost": Pipeline([
        ("preprocessor", make_preprocessor()),
        ("model", XGBRegressor(
            n_estimators=300,
            max_depth=4,
            learning_rate=0.03,
            subsample=0.8,
            colsample_bytree=0.8,
            objective="reg:squarederror",
            random_state=42,
            n_jobs=-1,
        )),
    ]),
}

# ---------------------------------------------------------
# 6. Train and evaluate on exactly the same rows
# ---------------------------------------------------------
results = []
predictions_by_model = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    predictions_by_model[name] = predictions

    results.append({
        "model": name,
        "MAE": mean_absolute_error(y_test, predictions),
        "RMSE": np.sqrt(mean_squared_error(y_test, predictions)),
        "R2": r2_score(y_test, predictions),
    })

results_df = (
    pd.DataFrame(results)
    .sort_values("MAE")
    .reset_index(drop=True)
    .round(3)
)

print("MODEL COMPARISON: CHRONOLOGICAL TEST")
print("=" * 60)
print("Training laps: 1 to", split_lap)
print(
    "Test laps:",
    split_lap + 1,
    "to",
    int(test_data["lap_number"].max()),
)
print("Training rows:", len(train_data))
print("Test rows:", len(test_data))
display(results_df)

# ---------------------------------------------------------
# 7. Inspect best model by compound and lap
# ---------------------------------------------------------
best_model_name = results_df.iloc[0]["model"]
best_predictions = predictions_by_model[best_model_name]

diagnostics = test_data[
    ["lap_number", "compound", "lap_duration"]
].copy()

diagnostics["prediction"] = best_predictions
diagnostics["absolute_error"] = (
    diagnostics["lap_duration"] - diagnostics["prediction"]
).abs()

print(f"\nBEST MODEL BY MAE: {best_model_name}")

print("\nERROR BY COMPOUND")
display(
    diagnostics.groupby("compound")
    .agg(
        test_laps=("lap_duration", "size"),
        MAE=("absolute_error", "mean"),
        actual_median=("lap_duration", "median"),
        predicted_median=("prediction", "median"),
    )
    .round(3)
)

print("\nERROR BY LAP")
display(
    diagnostics.groupby("lap_number")
    .agg(
        actual_median=("lap_duration", "median"),
        predicted_median=("prediction", "median"),
        MAE=("absolute_error", "mean"),
    )
    .round(3)
)

MODEL COMPARISON: CHRONOLOGICAL TEST
============================================================
Training laps: 1 to 35
Test laps: 36 to 52
Training rows: 637
Test rows: 277

               model     MAE    RMSE     R2
0  Linear Regression   5.572   6.304 -1.420
1            XGBoost   9.939  10.442 -5.637
2      Random Forest  11.647  12.318 -8.237

BEST MODEL BY MAE: Linear Regression

ERROR BY COMPOUND

              test_laps    MAE  actual_median  predicted_median
compound
HARD                 23  4.063         89.472            93.612
INTERMEDIATE         52  4.595        100.458           104.867
MEDIUM               71  7.397         90.148            97.820
SOFT                131  5.235         90.929            96.451

ERROR BY LAP

            actual_median  predicted_median    MAE
lap_number
36                102.737           104.317  2.126
37                100.458           105.099  4.846
38                 98.520           104.993  6.574
39                 94.979            93.985  4.707
40                 91.712            95.790  4.064
41                 90.649            97.420  6.864
42                 90.164            99.137  8.349
43                 90.144            95.322  6.412
44                 90.211           100.733  6.805
45                 90.227            96.802  5.829
46                 90.160            91.041  1.786
47                 90.218            96.734  5.916
48                 90.365            98.418  7.540
49                 90.752            98.925  7.676
50                 90.516            95.199  4.340
51                 90.732            96.433  4.922
52                 90.496            96.583  5.527

In [30]:
best_model_name = results_df.iloc[0]["model"]
best_predictions = predictions_by_model[best_model_name]

diagnostics = test_data[
    [
        "driver_number",
        "lap_number",
        "compound",
        "lap_duration",
        "rainfall",
        "grip_condition",
        "tyre_age",
        "track_temperature",
    ]
].copy()

diagnostics["predicted_lap_duration"] = best_predictions
diagnostics["error"] = (
    diagnostics["predicted_lap_duration"]
    - diagnostics["lap_duration"]
)
diagnostics["absolute_error"] = diagnostics["error"].abs()

print("ERROR DISTRIBUTION")
print("=" * 55)
display(
    diagnostics["error"]
    .describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9])
    .to_frame("prediction_error_seconds")
    .round(3)
)

print("\nBIAS BY COMPOUND")
print("=" * 55)
display(
    diagnostics.groupby("compound")
    .agg(
        laps=("error", "size"),
        mean_error=("error", "mean"),
        median_error=("error", "median"),
        MAE=("absolute_error", "mean"),
    )
    .round(3)
)

print("\nBIAS BY WEATHER STATE")
print("=" * 55)
display(
    diagnostics.groupby(["rainfall", "grip_condition"], dropna=False)
    .agg(
        laps=("error", "size"),
        actual_median=("lap_duration", "median"),
        predicted_median=("predicted_lap_duration", "median"),
        mean_error=("error", "mean"),
        MAE=("absolute_error", "mean"),
    )
    .round(3)
)

print("\nLARGEST PREDICTION ERRORS")
print("=" * 55)
display(
    diagnostics.sort_values("absolute_error", ascending=False)
    .head(15)
    .round(3)
)

ERROR DISTRIBUTION
=======================================================

       prediction_error_seconds
count                   277.000
mean                      5.409
std                       3.245
min                      -4.763
10%                       1.128
25%                       3.440
50%                       5.742
75%                       7.347
90%                       9.202
max                      16.481

BIAS BY COMPOUND
=======================================================

              laps  mean_error  median_error    MAE
compound
HARD            23       3.635         4.043  4.063
INTERMEDIATE    52       4.595         4.679  4.595
MEDIUM          71       7.397         7.338  7.397
SOFT           131       4.965         5.199  5.235

BIAS BY WEATHER STATE
=======================================================

                         laps  actual_median  predicted_median  mean_error  \
rainfall grip_condition
0.0      LOW               29         91.097            95.655       3.730
         NORMAL           172         90.423            96.217       5.257
1.0      LOW               51        100.483           104.879       4.662
         NORMAL            25         90.229           100.595       9.921

                           MAE
rainfall grip_condition
0.0      LOW             4.360
         NORMAL          5.414
1.0      LOW             4.662
         NORMAL          9.921

LARGEST PREDICTION ERRORS
=======================================================

,driver_number,lap_number,compound,lap_duration,rainfall,grip_condition,tyre_age,track_temperature,predicted_lap_duration,error,absolute_error
746,11,43,MEDIUM,90.229,1.0,NORMAL,5.0,24.5,106.710,16.481,16.481
757,31,43,MEDIUM,91.084,1.0,NORMAL,4.0,24.5,107.034,15.950,15.950
754,24,43,SOFT,91.014,1.0,NORMAL,5.0,24.5,105.492,14.478,14.478
764,11,44,MEDIUM,90.518,1.0,NORMAL,6.0,24.5,103.789,13.271,13.271
765,14,44,MEDIUM,89.930,1.0,NORMAL,5.0,24.5,101.672,11.742,11.742
728,11,42,MEDIUM,90.542,0.0,NORMAL,4.0,25.0,101.976,11.434,11.434
767,18,44,MEDIUM,90.030,1.0,NORMAL,4.0,24.5,101.399,11.369,11.369
771,23,44,MEDIUM,90.740,1.0,NORMAL,5.0,24.5,102.090,11.350,11.350
766,16,44,SOFT,89.933,1.0,NORMAL,6.0,24.5,101.255,11.322,11.322
864,31,49,MEDIUM,91.060,0.0,NORMAL,10.0,25.4,102.370,11.310,11.310
768,2,44,SOFT,90.003,1.0,NORMAL,5.0,24.5,100.871,10.868,10.868
739,31,42,MEDIUM,91.187,0.0,NORMAL,3.0,24.9,101.874,10.687,10.687
710,11,41,MEDIUM,90.689,0.0,NORMAL,3.0,24.7,100.957,10.268,10.268
774,3,44,SOFT,91.080,1.0,NORMAL,6.0,24.5,101.286,10.206,10.206
721,31,41,MEDIUM,91.114,0.0,NORMAL,2.0,24.7,101.281,10.167,10.167

In [31]:

# Cell 28: Audit rainfall and grip consistency by lap

weather_audit = (
    sim_state.groupby("lap_number")
    .agg(
        rainfall_values=(
            "rainfall",
            lambda s: sorted(s.dropna().unique().tolist())
        ),
        grip_values=(
            "grip_condition",
            lambda s: sorted(s.dropna().astype(str).unique().tolist())
        ),
        median_lap_time=("lap_duration", "median"),
        drivers=("driver_number", "nunique"),
    )
    .reset_index()
)

print("WEATHER TRANSITION AUDIT: LAPS 34-47")
print("=" * 75)

display(
    weather_audit.loc[
        weather_audit["lap_number"].between(34, 47)
    ].reset_index(drop=True)
)

print("\nROW-LEVEL CHECK: LAPS 40-45")
print("=" * 75)

display(
    sim_state.loc[
        sim_state["lap_number"].between(40, 45),
        [
            "driver_number",
            "lap_number",
            "lap_duration",
            "compound",
            "rainfall",
            "grip_condition",
            "track_temperature",
            "air_temperature",
            "date",
        ],
    ]
    .sort_values(["lap_number", "driver_number"])
    .head(50)
    .reset_index(drop=True)
)

WEATHER TRANSITION AUDIT: LAPS 34-47
===========================================================================

    lap_number rainfall_values    grip_values  median_lap_time  drivers
0           34           [1.0]          [LOW]         104.6490       19
1           35           [1.0]          [LOW]         103.8160       18
2           36           [1.0]          [LOW]         102.7370       18
3           37           [1.0]          [LOW]         100.4575       18
4           38      [0.0, 1.0]          [LOW]          98.8325       18
5           39      [0.0, 1.0]          [LOW]          97.5020       18
6           40           [0.0]  [LOW, NORMAL]          92.3730       18
7           41           [0.0]  [LOW, NORMAL]          90.6495       18
8           42           [0.0]       [NORMAL]          90.1640       18
9           43      [0.0, 1.0]       [NORMAL]          90.1440       18
10          44      [0.0, 1.0]       [NORMAL]          90.2110       18
11          45      [0.0, 1.0]       [NORMAL]          90.2270       18
12          46           [0.0]       [NORMAL]          90.1605       18
13          47           [0.0]       [NORMAL]          90.2185       18

ROW-LEVEL CHECK: LAPS 40-45
===========================================================================

,driver_number,lap_number,lap_duration,compound,rainfall,grip_condition,track_temperature,air_temperature,date
0,1,40,90.056,HARD,0.0,LOW,24.6,14.8,NaT
1,2,40,91.353,SOFT,0.0,LOW,24.4,15.1,NaT
2,3,40,92.428,SOFT,0.0,LOW,24.4,15.1,NaT
3,4,40,114.840,SOFT,0.0,LOW,24.6,14.6,NaT
4,11,40,93.219,MEDIUM,0.0,LOW,24.2,15.2,NaT
5,14,40,91.146,MEDIUM,0.0,LOW,24.4,15.1,NaT
6,16,40,90.878,SOFT,0.0,LOW,24.2,15.2,NaT
7,18,40,116.032,MEDIUM,0.0,LOW,24.6,14.8,NaT
8,20,40,92.071,SOFT,0.0,LOW,24.4,15.1,NaT
9,22,40,92.318,SOFT,0.0,LOW,24.4,15.1,NaT
10,23,40,90.889,MEDIUM,0.0,LOW,24.4,15.1,NaT
11,24,40,93.170,SOFT,0.0,NORMAL,24.2,15.3,NaT
12,27,40,115.659,SOFT,0.0,LOW,24.6,14.8,NaT
13,31,40,92.838,MEDIUM,0.0,NORMAL,24.2,15.2,NaT
14,44,40,90.318,SOFT,0.0,LOW,24.6,14.8,NaT
15,55,40,116.753,HARD,0.0,LOW,24.6,14.8,NaT
16,77,40,92.973,SOFT,0.0,LOW,24.4,15.1,NaT
17,81,40,89.913,MEDIUM,0.0,LOW,24.6,14.8,NaT
18,1,41,89.604,HARD,0.0,LOW,24.4,15.1,NaT
19,2,41,90.875,SOFT,0.0,NORMAL,24.2,15.2,NaT
20,3,41,91.289,SOFT,0.0,NORMAL,24.2,15.2,NaT
21,4,41,89.733,SOFT,0.0,LOW,24.4,15.1,NaT
22,11,41,90.689,MEDIUM,0.0,NORMAL,24.7,15.3,NaT
23,14,41,90.594,MEDIUM,0.0,LOW,24.2,15.2,NaT
24,16,41,90.035,SOFT,0.0,NORMAL,24.2,15.3,NaT
25,18,41,90.098,MEDIUM,0.0,LOW,24.2,15.2,NaT
26,20,41,90.610,SOFT,0.0,NORMAL,24.2,15.2,NaT
27,22,41,90.812,SOFT,0.0,LOW,24.2,15.2,NaT
28,23,41,90.715,MEDIUM,0.0,LOW,24.2,15.2,NaT
29,24,41,91.151,SOFT,0.0,NORMAL,25.0,15.2,NaT
30,27,41,91.097,SOFT,0.0,LOW,24.2,15.2,NaT
31,31,41,91.114,MEDIUM,0.0,NORMAL,24.7,15.3,NaT
32,44,41,90.118,SOFT,0.0,LOW,24.4,15.1,NaT
33,55,41,90.475,HARD,0.0,LOW,24.2,15.2,NaT
34,77,41,93.344,SOFT,0.0,NORMAL,24.2,15.3,NaT
35,81,41,89.574,MEDIUM,0.0,LOW,24.4,15.1,NaT
36,1,42,89.472,HARD,0.0,NORMAL,24.2,15.3,NaT
37,2,42,89.972,SOFT,0.0,NORMAL,24.7,15.3,NaT
38,3,42,90.765,SOFT,0.0,NORMAL,24.7,15.3,NaT
39,4,42,90.006,SOFT,0.0,NORMAL,24.2,15.3,NaT
40,11,42,90.542,MEDIUM,0.0,NORMAL,25.0,15.2,NaT
41,14,42,90.167,MEDIUM,0.0,NORMAL,24.7,15.3,NaT
42,16,42,89.832,SOFT,0.0,NORMAL,25.0,15.2,NaT
43,18,42,90.161,MEDIUM,0.0,NORMAL,24.7,15.3,NaT
44,20,42,90.093,SOFT,0.0,NORMAL,24.7,15.3,NaT
45,22,42,90.319,SOFT,0.0,NORMAL,24.7,15.3,NaT
46,23,42,90.458,MEDIUM,0.0,NORMAL,24.7,15.3,NaT
47,24,42,91.121,SOFT,0.0,NORMAL,24.9,15.3,NaT
48,27,42,90.701,SOFT,0.0,NORMAL,24.2,15.3,NaT
49,31,42,91.187,MEDIUM,0.0,NORMAL,24.9,15.3,NaT

In [32]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
DATA_DIR = PROJECT_ROOT / "data" / "processed" / "9558"

weather_path = DATA_DIR / "weather.parquet"

if not weather_path.exists():
    raise FileNotFoundError(f"Weather file not found: {weather_path}")

weather = pd.read_parquet(weather_path)

print("Weather loaded successfully")
print("Shape:", weather.shape)
print("Columns:", weather.columns.tolist())
display(weather.head())

# Ensure both timestamp columns use consistent UTC datetimes
weather["date"] = pd.to_datetime(weather["date"], utc=True)
sim_state["date_start"] = pd.to_datetime(sim_state["date_start"], utc=True)

# Focus on the laps where our pace predictions became unreliable
lap_window = sim_state.loc[
    sim_state["lap_number"].between(38, 45)
].copy()

print("LAP TIMESTAMP RANGE")
print("First:", lap_window["date_start"].min())
print("Last: ", lap_window["date_start"].max())

start_time = lap_window["date_start"].min() - pd.Timedelta(minutes=5)
end_time = lap_window["date_start"].max() + pd.Timedelta(minutes=5)

print("\nRAW WEATHER OBSERVATIONS IN THAT WINDOW")
weather_window = weather.loc[
    weather["date"].between(start_time, end_time)
].sort_values("date")

display(weather_window[
    ["date", "rainfall", "track_temperature",
     "air_temperature", "humidity", "wind_speed"]
].reset_index(drop=True))

print("\nWEATHER VALUES ATTACHED TO EACH LAP")
display(
    lap_window.groupby("lap_number").agg(
        lap_start_min=("date_start", "min"),
        lap_start_max=("date_start", "max"),
        rainfall_values=("rainfall", lambda s: sorted(s.dropna().unique().tolist())),
        grip_values=("grip_condition", lambda s: sorted(s.dropna().astype(str).unique().tolist())),
        track_temp_min=("track_temperature", "min"),
        track_temp_max=("track_temperature", "max"),
        drivers=("driver_number", "nunique"),
    ).reset_index()
)

# Prepare a clean weather reference table
weather_reference = (
    weather[
        ["date", "rainfall", "track_temperature", "air_temperature"]
    ]
    .dropna(subset=["date"])
    .sort_values("date")
    .drop_duplicates(subset=["date"], keep="last")
)

# Keep the original values for comparison
audit_rows = sim_state.loc[
    sim_state["lap_number"].between(38, 45),
    [
        "driver_number",
        "lap_number",
        "date_start",
        "rainfall",
        "track_temperature",
        "air_temperature",
        "grip_condition",
    ],
].copy()

audit_rows = audit_rows.rename(
    columns={
        "rainfall": "rainfall_attached",
        "track_temperature": "track_temp_attached",
        "air_temperature": "air_temp_attached",
    }
)

# Match each lap timestamp to the latest weather observation at or before it
audit_rows = pd.merge_asof(
    audit_rows.sort_values("date_start"),
    weather_reference,
    left_on="date_start",
    right_on="date",
    direction="backward",
)

audit_rows["weather_age_seconds"] = (
    audit_rows["date_start"] - audit_rows["date"]
).dt.total_seconds()

audit_rows["rainfall_matches"] = (
    audit_rows["rainfall_attached"] == audit_rows["rainfall"]
)
audit_rows["track_temp_matches"] = (
    (audit_rows["track_temp_attached"] - audit_rows["track_temperature"]).abs()
    < 0.11
)
audit_rows["air_temp_matches"] = (
    (audit_rows["air_temp_attached"] - audit_rows["air_temperature"]).abs()
    < 0.11
)

print("ROW-LEVEL WEATHER MERGE AUDIT")
display(
    audit_rows[
        [
            "driver_number",
            "lap_number",
            "date_start",
            "date",
            "weather_age_seconds",
            "rainfall_attached",
            "rainfall",
            "rainfall_matches",
            "track_temp_attached",
            "track_temperature",
            "track_temp_matches",
            "air_temp_attached",
            "air_temperature",
            "air_temp_matches",
            "grip_condition",
        ]
    ].head(30)
)

print("\nMATCH RATES")
display(
    audit_rows[
        ["rainfall_matches", "track_temp_matches", "air_temp_matches"]
    ].mean().rename("match_rate").to_frame()
)

print("\nWEATHER OBSERVATION AGE, IN SECONDS")
display(audit_rows["weather_age_seconds"].describe())

Weather loaded successfully
Shape: (147, 10)
Columns: ['date', 'session_key', 'meeting_key', 'track_temperature', 'wind_speed', 'rainfall', 'humidity', 'pressure', 'air_temperature', 'wind_direction']

,date,session_key,meeting_key,track_temperature,wind_speed,rainfall,humidity,pressure,air_temperature,wind_direction
0,2024-07-07 13:05:02.119000+00:00,9558,1240,28.1,2.2,0,67.0,991.8,15.9,226
1,2024-07-07 13:06:02.098000+00:00,9558,1240,27.6,1.5,0,66.0,991.7,15.9,268
2,2024-07-07 13:07:02.122000+00:00,9558,1240,27.0,1.4,0,65.0,991.7,15.9,291
3,2024-07-07 13:08:02.127000+00:00,9558,1240,27.0,1.1,0,66.0,991.8,15.9,195
4,2024-07-07 13:09:02.125000+00:00,9558,1240,31.0,1.9,0,64.0,991.8,15.9,225

LAP TIMESTAMP RANGE
First: 2024-07-07 15:02:36.581000+00:00
Last:  2024-07-07 15:17:24.587000+00:00

RAW WEATHER OBSERVATIONS IN THAT WINDOW

,date,rainfall,track_temperature,air_temperature,humidity,wind_speed
0,2024-07-07 14:58:02.907000+00:00,1,21.3,14.6,76.0,1.5
1,2024-07-07 14:59:02.914000+00:00,1,21.2,14.5,75.0,1.4
2,2024-07-07 15:00:02.913000+00:00,1,21.2,14.6,75.0,1.7
3,2024-07-07 15:01:02.923000+00:00,1,21.4,14.5,76.0,1.2
4,2024-07-07 15:02:02.923000+00:00,1,22.5,14.6,78.0,1.3
5,2024-07-07 15:03:02.935000+00:00,1,23.8,14.6,77.0,1.8
6,2024-07-07 15:04:02.949000+00:00,1,24.2,14.6,76.0,1.9
7,2024-07-07 15:05:02.943000+00:00,0,24.6,14.6,78.0,1.4
8,2024-07-07 15:06:02.948000+00:00,0,24.6,14.8,75.0,1.2
9,2024-07-07 15:07:02.959000+00:00,0,24.4,15.1,74.0,0.8
10,2024-07-07 15:08:02.987000+00:00,0,24.2,15.2,73.0,2.2
11,2024-07-07 15:09:02.978000+00:00,0,24.2,15.3,76.0,1.1
12,2024-07-07 15:10:02.983000+00:00,0,24.7,15.3,75.0,0.8
13,2024-07-07 15:11:02.996000+00:00,0,25.0,15.2,75.0,1.4
14,2024-07-07 15:12:03.040000+00:00,0,24.9,15.3,75.0,1.6
15,2024-07-07 15:13:03.028000+00:00,1,24.5,15.4,72.0,2.0
16,2024-07-07 15:14:03.040000+00:00,1,24.5,15.4,73.0,2.0
17,2024-07-07 15:15:03.048000+00:00,0,25.0,15.5,73.0,2.0
18,2024-07-07 15:16:03.049000+00:00,0,25.0,15.5,71.0,2.0
19,2024-07-07 15:17:03.029000+00:00,0,24.9,15.6,69.0,0.9
20,2024-07-07 15:18:03.054000+00:00,0,24.9,15.6,71.0,1.1
21,2024-07-07 15:19:03.080000+00:00,0,25.2,15.7,71.0,1.2
22,2024-07-07 15:20:03.083000+00:00,0,25.2,15.7,72.0,1.5
23,2024-07-07 15:21:03.104000+00:00,0,25.2,15.8,69.0,1.8
24,2024-07-07 15:22:03.113000+00:00,0,25.4,15.8,69.0,1.7

WEATHER VALUES ATTACHED TO EACH LAP

,lap_number,lap_start_min,lap_start_max,rainfall_values,grip_values,track_temp_min,track_temp_max,drivers
0,38,2024-07-07 15:02:36.581000+00:00,2024-07-07 15:06:07.310000+00:00,"[0.0, 1.0]",[LOW],22.5,24.6,18
1,39,2024-07-07 15:04:14.487000+00:00,2024-07-07 15:08:14.014000+00:00,"[0.0, 1.0]",[LOW],24.2,24.6,18
2,40,2024-07-07 15:05:51.295000+00:00,2024-07-07 15:09:46.808000+00:00,[0.0],"[LOW, NORMAL]",24.2,24.6,18
3,41,2024-07-07 15:07:43.491000+00:00,2024-07-07 15:11:20.006000+00:00,[0.0],"[LOW, NORMAL]",24.2,25.0,18
4,42,2024-07-07 15:09:13.478000+00:00,2024-07-07 15:12:51.169000+00:00,[0.0],[NORMAL],24.2,25.0,18
5,43,2024-07-07 15:10:43.050000+00:00,2024-07-07 15:14:22.188000+00:00,"[0.0, 1.0]",[NORMAL],24.5,25.0,18
6,44,2024-07-07 15:12:12.874000+00:00,2024-07-07 15:15:53.256000+00:00,"[0.0, 1.0]",[NORMAL],24.5,25.0,18
7,45,2024-07-07 15:13:42.570000+00:00,2024-07-07 15:17:24.587000+00:00,"[0.0, 1.0]",[NORMAL],24.5,25.0,18

ROW-LEVEL WEATHER MERGE AUDIT

,driver_number,lap_number,date_start,date,weather_age_seconds,rainfall_attached,rainfall,rainfall_matches,track_temp_attached,track_temperature,track_temp_matches,air_temp_attached,air_temperature,air_temp_matches,grip_condition
0,4,38,2024-07-07 15:02:36.581000+00:00,2024-07-07 15:02:02.923000+00:00,33.658,1.0,1,True,22.5,22.5,True,14.6,14.6,True,LOW
1,44,38,2024-07-07 15:02:38.413000+00:00,2024-07-07 15:02:02.923000+00:00,35.490,1.0,1,True,22.5,22.5,True,14.6,14.6,True,LOW
2,1,38,2024-07-07 15:02:45.144000+00:00,2024-07-07 15:02:02.923000+00:00,42.221,1.0,1,True,22.5,22.5,True,14.6,14.6,True,LOW
3,55,38,2024-07-07 15:02:57.635000+00:00,2024-07-07 15:02:02.923000+00:00,54.712,1.0,1,True,22.5,22.5,True,14.6,14.6,True,LOW
4,81,38,2024-07-07 15:02:58.606000+00:00,2024-07-07 15:02:02.923000+00:00,55.683,1.0,1,True,22.5,22.5,True,14.6,14.6,True,LOW
5,27,38,2024-07-07 15:03:19.171000+00:00,2024-07-07 15:03:02.935000+00:00,16.236,1.0,1,True,23.8,23.8,True,14.6,14.6,True,LOW
6,18,38,2024-07-07 15:03:22.731000+00:00,2024-07-07 15:03:02.935000+00:00,19.796,1.0,1,True,23.8,23.8,True,14.6,14.6,True,LOW
7,14,38,2024-07-07 15:03:30.826000+00:00,2024-07-07 15:03:02.935000+00:00,27.891,1.0,1,True,23.8,23.8,True,14.6,14.6,True,LOW
8,22,38,2024-07-07 15:03:35.861000+00:00,2024-07-07 15:03:02.935000+00:00,32.926,1.0,1,True,23.8,23.8,True,14.6,14.6,True,LOW
9,23,38,2024-07-07 15:03:39.706000+00:00,2024-07-07 15:03:02.935000+00:00,36.771,1.0,1,True,23.8,23.8,True,14.6,14.6,True,LOW
10,20,38,2024-07-07 15:03:48.146000+00:00,2024-07-07 15:03:02.935000+00:00,45.211,1.0,1,True,23.8,23.8,True,14.6,14.6,True,LOW
11,3,38,2024-07-07 15:03:51.209000+00:00,2024-07-07 15:03:02.935000+00:00,48.274,1.0,1,True,23.8,23.8,True,14.6,14.6,True,LOW
12,2,38,2024-07-07 15:03:51.556000+00:00,2024-07-07 15:03:02.935000+00:00,48.621,1.0,1,True,23.8,23.8,True,14.6,14.6,True,LOW
13,77,38,2024-07-07 15:04:12.228000+00:00,2024-07-07 15:04:02.949000+00:00,9.279,1.0,1,True,24.2,24.2,True,14.6,14.6,True,LOW
14,4,39,2024-07-07 15:04:14.487000+00:00,2024-07-07 15:04:02.949000+00:00,11.538,1.0,1,True,24.2,24.2,True,14.6,14.6,True,LOW
15,44,39,2024-07-07 15:04:15.601000+00:00,2024-07-07 15:04:02.949000+00:00,12.652,1.0,1,True,24.2,24.2,True,14.6,14.6,True,LOW
16,1,39,2024-07-07 15:04:21.179000+00:00,2024-07-07 15:04:02.949000+00:00,18.230,1.0,1,True,24.2,24.2,True,14.6,14.6,True,LOW
17,81,39,2024-07-07 15:04:35.625000+00:00,2024-07-07 15:04:02.949000+00:00,32.676,1.0,1,True,24.2,24.2,True,14.6,14.6,True,LOW
18,55,39,2024-07-07 15:04:36.091000+00:00,2024-07-07 15:04:02.949000+00:00,33.142,1.0,1,True,24.2,24.2,True,14.6,14.6,True,LOW
19,16,38,2024-07-07 15:04:47.211000+00:00,2024-07-07 15:04:02.949000+00:00,44.262,1.0,1,True,24.2,24.2,True,14.6,14.6,True,LOW
20,27,39,2024-07-07 15:04:57.989000+00:00,2024-07-07 15:04:02.949000+00:00,55.040,1.0,1,True,24.2,24.2,True,14.6,14.6,True,LOW
21,18,39,2024-07-07 15:05:02.181000+00:00,2024-07-07 15:04:02.949000+00:00,59.232,1.0,1,True,24.2,24.2,True,14.6,14.6,True,LOW
22,11,38,2024-07-07 15:05:05.883000+00:00,2024-07-07 15:05:02.943000+00:00,2.940,0.0,0,True,24.6,24.6,True,14.6,14.6,True,LOW
23,14,39,2024-07-07 15:05:09.518000+00:00,2024-07-07 15:05:02.943000+00:00,6.575,0.0,0,True,24.6,24.6,True,14.6,14.6,True,LOW
24,22,39,2024-07-07 15:05:14.516000+00:00,2024-07-07 15:05:02.943000+00:00,11.573,0.0,0,True,24.6,24.6,True,14.6,14.6,True,LOW
25,23,39,2024-07-07 15:05:17.442000+00:00,2024-07-07 15:05:02.943000+00:00,14.499,0.0,0,True,24.6,24.6,True,14.6,14.6,True,LOW
26,31,38,2024-07-07 15:05:19.925000+00:00,2024-07-07 15:05:02.943000+00:00,16.982,0.0,0,True,24.6,24.6,True,14.6,14.6,True,LOW
27,2,39,2024-07-07 15:05:30.301000+00:00,2024-07-07 15:05:02.943000+00:00,27.358,0.0,0,True,24.6,24.6,True,14.6,14.6,True,LOW
28,4,40,2024-07-07 15:05:51.295000+00:00,2024-07-07 15:05:02.943000+00:00,48.352,0.0,0,True,24.6,24.6,True,14.6,14.6,True,LOW
29,20,39,2024-07-07 15:05:52.100000+00:00,2024-07-07 15:05:02.943000+00:00,49.157,0.0,0,True,24.6,24.6,True,14.6,14.6,True,LOW

MATCH RATES

                    match_rate
rainfall_matches           1.0
track_temp_matches         1.0
air_temp_matches           1.0

WEATHER OBSERVATION AGE, IN SECONDS

count    144.000000
mean      30.529257
std       17.285580
min        0.473000
25%       14.018750
50%       31.953000
75%       44.272250
max       59.488000
Name: weather_age_seconds, dtype: float64

In [33]:
# Use the same chronological test period as our previous model evaluation
test_audit = model_data.loc[
    model_data["lap_number"].between(36, 52)
].copy()

print("TEST DATA SHAPE:", test_audit.shape)

print("\nACTUAL LAP-TIME MEDIAN BY LAP")
display(
    test_audit.groupby("lap_number")["lap_duration"]
    .agg(["count", "median", "mean", "std"])
    .round(3)
)

print("\nACTUAL LAP-TIME MEDIAN BY LAP AND COMPOUND")
display(
    test_audit.groupby(["lap_number", "compound"])["lap_duration"]
    .agg(["count", "median"])
    .round(3)
)

print("\nFEATURES USED BY THE BEST MODEL")
print("Best model:", best_model_name)
print("Features:", model_data.columns.tolist())

TEST DATA SHAPE: (277, 32)

ACTUAL LAP-TIME MEDIAN BY LAP

            count   median     mean    std
lap_number
36             18  102.737  102.499  0.852
37             18  100.458  100.480  1.089
38             12   98.520   98.194  1.024
39             10   94.979   94.892  2.423
40             14   91.712   91.684  1.177
41             18   90.649   90.663  0.858
42             18   90.164   90.345  0.704
43             18   90.144   90.190  0.703
44             18   90.211   90.345  0.694
45             18   90.227   90.447  1.027
46             18   90.160   90.356  0.739
47             18   90.218   90.469  1.067
48             17   90.365   90.749  1.590
49             18   90.752   91.055  1.863
50             18   90.516   90.766  1.210
51             14   90.732   90.950  1.491
52             12   90.496   90.548  1.225

ACTUAL LAP-TIME MEDIAN BY LAP AND COMPOUND

                         count   median
lap_number compound
36         INTERMEDIATE     18  102.737
37         INTERMEDIATE     18  100.458
38         INTERMEDIATE     12   98.520
39         INTERMEDIATE      4   97.024
           MEDIUM            1   92.722
           SOFT              5   93.138
40         HARD              1   90.056
           MEDIUM            5   91.146
           SOFT              8   92.194
41         HARD              2   90.040
           MEDIUM            6   90.642
           SOFT             10   90.844
42         HARD              2   89.672
           MEDIUM            6   90.312
           SOFT             10   90.206
43         HARD              2   89.488
           MEDIUM            6   90.161
           SOFT             10   90.196
44         HARD              2   89.556
           MEDIUM            6   90.274
           SOFT             10   90.637
45         HARD              2   89.363
           MEDIUM            6   90.216
           SOFT             10   90.784
46         HARD              2   89.566
           MEDIUM            6   90.017
           SOFT             10   90.838
47         HARD              2   89.482
           MEDIUM            6   90.036
           SOFT             10   90.858
48         HARD              2   89.184
           MEDIUM            5   90.114
           SOFT             10   91.031
49         HARD              2   89.500
           MEDIUM            5   89.969
           SOFT             11   91.080
50         HARD              2   89.360
           MEDIUM            5   90.030
           SOFT             11   91.143
51         HARD              1   89.443
           MEDIUM            4   89.971
           SOFT              9   91.529
52         HARD              1   89.089
           MEDIUM            4   89.990
           SOFT              7   90.913

FEATURES USED BY THE BEST MODEL
Best model: Linear Regression
Features: ['driver_number', 'lap_number', 'date_start', 'lap_duration', 'compound', 'tyre_age', 'stint_number', 'is_pit_out_lap', 'position', 'session_key', 'meeting_key', 'track_temperature', 'wind_speed', 'rainfall', 'humidity', 'pressure', 'air_temperature', 'wind_direction', 'weather_age_seconds', 'drs_available', 'grip_condition', 'blue_flag', 'date', 'fuel_effect', 'traffic_ahead', 'traffic_behind', 'position_change', 'tyre_degradation_effect', 'rainfall_trend', 'track_temp_trend', 'air_temp_trend', 'humidity_trend']

In [34]:

print("DIAGNOSTICS")
print("Type:", type(diagnostics))
print("Columns:", getattr(diagnostics, "columns", "No columns attribute"))
display(diagnostics.head())

print("\nPREDICTIONS BY MODEL")
print("Type:", type(predictions_by_model))
print("Keys:", list(predictions_by_model.keys())
      if isinstance(predictions_by_model, dict)
      else "Not a dictionary")

print("\nBEST PREDICTIONS")
print("Type:", type(best_predictions))
print("Shape:", getattr(best_predictions, "shape", "No shape attribute"))
print("First 10 values:", best_predictions[:10]
      if hasattr(best_predictions, "__getitem__")
      else best_predictions)

print("\nMODEL EVALUATION RESULTS")
display(results_df)

print("\nMODEL DATA SHAPE:", model_data.shape)

DIAGNOSTICS
Type: <class 'pandas.DataFrame'>
Columns: Index(['driver_number', 'lap_number', 'compound', 'lap_duration', 'rainfall',
       'grip_condition', 'tyre_age', 'track_temperature',
       'predicted_lap_duration', 'error', 'absolute_error'],
      dtype='str')

,driver_number,lap_number,compound,lap_duration,rainfall,grip_condition,tyre_age,track_temperature,predicted_lap_duration,error,absolute_error
637,1,36,INTERMEDIATE,101.958,1.0,LOW,9.0,21.2,103.430902,1.472902,1.472902
638,11,36,INTERMEDIATE,101.845,1.0,LOW,7.0,21.4,106.703351,4.858351,4.858351
639,14,36,INTERMEDIATE,102.513,1.0,LOW,8.0,21.2,103.950721,1.437721,1.437721
640,16,36,INTERMEDIATE,100.091,1.0,LOW,8.0,21.4,105.524936,5.433936,5.433936
641,18,36,INTERMEDIATE,103.000,1.0,LOW,9.0,21.2,104.264346,1.264346,1.264346

PREDICTIONS BY MODEL
Type: <class 'dict'>
Keys: ['Linear Regression', 'Random Forest', 'XGBoost']

BEST PREDICTIONS
Type: <class 'numpy.ndarray'>
Shape: (277,)
First 10 values: [103.43090178 106.70335096 103.95072115 105.52493567 104.26434555
 104.43917194 104.45172502 104.16338776 104.36932581 106.99548285]

MODEL EVALUATION RESULTS

               model     MAE    RMSE     R2
0  Linear Regression   5.572   6.304 -1.420
1            XGBoost   9.939  10.442 -5.637
2      Random Forest  11.647  12.318 -8.237

MODEL DATA SHAPE: (914, 32)

In [35]:

# 1. Overall error summary
print("OVERALL ERROR SUMMARY")
display(
    diagnostics[["error", "absolute_error"]]
    .agg(["count", "mean", "median", "std", "min", "max"])
    .round(3)
)

# 2. Error by lap: is the model consistently biased on particular laps?
print("\nERROR BY LAP")
display(
    diagnostics.groupby("lap_number")
    .agg(
        drivers=("driver_number", "nunique"),
        actual_median=("lap_duration", "median"),
        predicted_median=("predicted_lap_duration", "median"),
        mean_error=("error", "mean"),
        MAE=("absolute_error", "mean"),
    )
    .round(3)
)

# 3. Error by compound
print("\nERROR BY COMPOUND")
display(
    diagnostics.groupby("compound")
    .agg(
        rows=("error", "size"),
        actual_median=("lap_duration", "median"),
        predicted_median=("predicted_lap_duration", "median"),
        mean_error=("error", "mean"),
        MAE=("absolute_error", "mean"),
    )
    .round(3)
)

# 4. Error by driver
print("\nERROR BY DRIVER")
display(
    diagnostics.groupby("driver_number")
    .agg(
        rows=("error", "size"),
        mean_error=("error", "mean"),
        MAE=("absolute_error", "mean"),
    )
    .sort_values("MAE", ascending=False)
    .round(3)
)

OVERALL ERROR SUMMARY

          error  absolute_error
count   277.000         277.000
mean      5.409           5.572
median    5.742           5.742
std       3.245           2.955
min      -4.763           0.032
max      16.481          16.481

ERROR BY LAP

            drivers  actual_median  predicted_median  mean_error    MAE
lap_number
36               18        102.737           104.317       2.126  2.126
37               18        100.458           105.099       4.846  4.846
38               12         98.520           104.993       6.574  6.574
39               10         94.979            93.985       2.880  4.707
40               14         91.712            95.790       4.064  4.064
41               18         90.649            97.420       6.864  6.864
42               18         90.164            99.137       8.349  8.349
43               18         90.144            95.322       6.412  6.412
44               18         90.211           100.733       6.747  6.805
45               18         90.227            96.802       5.454  5.829
46               18         90.160            91.041       0.724  1.786
47               18         90.218            96.734       5.916  5.916
48               17         90.365            98.418       7.540  7.540
49               18         90.752            98.925       7.676  7.676
50               18         90.516            95.199       4.340  4.340
51               14         90.732            96.433       4.922  4.922
52               12         90.496            96.583       5.527  5.527

ERROR BY COMPOUND

              rows  actual_median  predicted_median  mean_error    MAE
compound
HARD            23         89.472            93.612       3.635  4.063
INTERMEDIATE    52        100.458           104.867       4.595  4.595
MEDIUM          71         90.148            97.820       7.397  7.397
SOFT           131         90.929            96.451       4.965  5.235

ERROR BY DRIVER

               rows  mean_error    MAE
driver_number
11               13       7.575  7.575
23               16       7.091  7.091
31               14       6.965  6.965
18               16       6.721  6.721
14               16       6.604  6.604
81               16       6.223  6.223
24               14       6.194  6.194
16               15       5.989  5.989
2                16       5.436  5.440
22               16       5.086  5.201
20               16       4.758  5.084
77               15       3.946  4.930
27               16       4.799  4.920
4                16       4.243  4.444
44               16       4.245  4.417
55               15       4.008  4.353
3                15       3.971  4.343
1                16       3.967  4.259

In [36]:

import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Recreate the exact chronological split used previously
clean_data = model_data.loc[
    model_data["is_pit_out_lap"].eq(False)
    & model_data["lap_duration"].notna()
].copy()

train_data = clean_data.loc[clean_data["lap_number"] <= 35].copy()
test_data = clean_data.loc[clean_data["lap_number"] >= 36].copy()

# Match the existing diagnostic rows to the test data.
# diagnostics was created from the previous test predictions.
current_mae = mean_absolute_error(
    diagnostics["lap_duration"],
    diagnostics["predicted_lap_duration"]
)
current_rmse = np.sqrt(mean_squared_error(
    diagnostics["lap_duration"],
    diagnostics["predicted_lap_duration"]
))
current_r2 = r2_score(
    diagnostics["lap_duration"],
    diagnostics["predicted_lap_duration"]
)

# Baseline A: global training median
global_median = train_data["lap_duration"].median()
global_predictions = np.full(len(test_data), global_median)

# Baseline B: training median by compound, with global fallback
compound_medians = train_data.groupby("compound")["lap_duration"].median()
compound_predictions = (
    test_data["compound"].map(compound_medians).fillna(global_median)
)

# Evaluate only the same test rows as diagnostics for a fair comparison
test_keys = ["driver_number", "lap_number"]
comparison_test = test_data.merge(
    diagnostics[test_keys],
    on=test_keys,
    how="inner",
    validate="one_to_one"
)

global_test_predictions = np.full(len(comparison_test), global_median)
compound_test_predictions = (
    comparison_test["compound"].map(compound_medians).fillna(global_median)
)

actual = comparison_test["lap_duration"]

comparison = pd.DataFrame([
    {
        "model": "Global training median",
        "MAE": mean_absolute_error(actual, global_test_predictions),
        "RMSE": np.sqrt(mean_squared_error(actual, global_test_predictions)),
        "R2": r2_score(actual, global_test_predictions),
    },
    {
        "model": "Compound training median",
        "MAE": mean_absolute_error(actual, compound_test_predictions),
        "RMSE": np.sqrt(mean_squared_error(actual, compound_test_predictions)),
        "R2": r2_score(actual, compound_test_predictions),
    },
    {
        "model": "Current Linear Regression",
        "MAE": current_mae,
        "RMSE": current_rmse,
        "R2": current_r2,
    },
])

display(comparison.round(3))
print("Training rows:", len(train_data))
print("Test rows evaluated:", len(comparison_test))
print("Diagnostic rows:", len(diagnostics))

                       model    MAE   RMSE     R2
0     Global training median  3.984  4.338 -0.146
1   Compound training median  3.065  3.308  0.334
2  Current Linear Regression  5.572  6.304 -1.420

Training rows: 637
Test rows evaluated: 277
Diagnostic rows: 277

In [37]:

import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Compare actual lap times from both sources
actual_match = np.allclose(
    aligned["lap_duration"].to_numpy(),
    diagnostics.merge(
        aligned[["driver_number", "lap_number"]],
        on=["driver_number", "lap_number"],
        how="inner",
        validate="one_to_one"
    )["lap_duration"].to_numpy(),
    equal_nan=True
)

print("Matched rows:", len(aligned))
print("Actual lap times match diagnostics:", actual_match)

# Recalculate metrics on aligned driver-lap rows
y_true = aligned["lap_duration"].to_numpy()
y_pred = aligned["predicted_lap_duration"].to_numpy()

print("\nAligned Linear Regression metrics")
print(f"MAE:  {mean_absolute_error(y_true, y_pred):.3f} s")
print(f"RMSE: {np.sqrt(mean_squared_error(y_true, y_pred)):.3f} s")
print(f"R2:   {r2_score(y_true, y_pred):.3f}")

display(
    aligned.sort_values(["lap_number", "driver_number"])
    .head(15)
    .round(3)
)

NameError: name 'aligned' is not defined

In [ ]:

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd

# Use the exact same driver-lap rows for every method
evaluation = aligned.copy()

# Calculate compound medians from training data only
training_compound_medians = (
    train_data.groupby("compound")["lap_duration"].median()
)
training_global_median = train_data["lap_duration"].median()

evaluation["baseline_prediction"] = (
    evaluation["compound"]
    .map(training_compound_medians)
    .fillna(training_global_median)
)

y_true = evaluation["lap_duration"].to_numpy()

predictions = {
    "Global median": np.full(
        len(evaluation), training_global_median
    ),
    "Compound median": evaluation["baseline_prediction"].to_numpy(),
    "Linear Regression": evaluation["predicted_lap_duration"].to_numpy(),
}

rows = []

for model_name, y_pred in predictions.items():
    rows.append({
        "model": model_name,
        "MAE": mean_absolute_error(y_true, y_pred),
        "RMSE": np.sqrt(mean_squared_error(y_true, y_pred)),
        "R2": r2_score(y_true, y_pred),
        "mean_error": np.mean(y_pred - y_true),
    })

comparison_aligned = pd.DataFrame(rows).sort_values("MAE")
display(comparison_aligned.round(3))

print("Evaluation rows:", len(evaluation))
print("\nTraining compound medians:")
display(training_compound_medians.round(3))

               model    MAE   RMSE     R2  mean_error
1    Compound median  3.065  3.308  0.334       2.988
0      Global median  3.984  4.338 -0.146       1.547
2  Linear Regression  5.572  6.304 -1.420       5.409

Evaluation rows: 277

Training compound medians:

compound
HARD             92.740
INTERMEDIATE    103.472
MEDIUM           92.956
SOFT             94.235
Name: lap_duration, dtype: float64

In [ ]:

import pandas as pd

coverage = (
    train_data.groupby("lap_number")
    .agg(
        rows=("lap_duration", "size"),
        median_lap_time=("lap_duration", "median"),
        rainfall_rows=("rainfall", "sum"),
        compounds=("compound", "nunique"),
        drivers=("driver_number", "nunique"),
    )
    .reset_index()
)

print("TRAINING LAP COVERAGE")
display(coverage.round(2))

print("\nTRAINING WEATHER AND COMPOUND COVERAGE")
display(
    train_data.groupby(["compound", "rainfall"], dropna=False)
    .agg(
        rows=("lap_duration", "size"),
        first_lap=("lap_number", "min"),
        last_lap=("lap_number", "max"),
        median_lap_time=("lap_duration", "median"),
    )
    .reset_index()
    .round(2)
)

print("\nTEST LAP COVERAGE")
display(
    test_data.groupby("lap_number")
    .agg(
        rows=("lap_duration", "size"),
        median_lap_time=("lap_duration", "median"),
        rainfall_rows=("rainfall", "sum"),
        compounds=("compound", "nunique"),
        drivers=("driver_number", "nunique"),
    )
    .reset_index()
    .round(2)
)

TRAINING LAP COVERAGE

    lap_number  rows  median_lap_time  rainfall_rows  compounds  drivers
0            1    18           100.76            0.0          2       18
1            2    19            92.94            0.0          3       19
2            3    19            92.60            0.0          3       19
3            4    19            92.97            0.0          3       19
4            5    19            92.70            0.0          3       19
5            6    19            92.70            0.0          3       19
6            7    19            92.73            0.0          3       19
7            8    19            92.80            0.0          3       19
8            9    19            92.57            0.0          3       19
9           10    19            92.65            0.0          3       19
10          11    19            92.49            0.0          3       19
11          12    19            92.43            0.0          3       19
12          13    18            92.63            0.0          3       18
13          14    19            92.49            0.0          3       19
14          15    19            92.54            0.0          3       19
15          16    19            93.18            0.0          3       19
16          17    19            95.01            0.0          3       19
17          18    19            95.79            2.0          3       19
18          19    19           104.15           19.0          3       19
19          20    15            97.33           15.0          1       15
20          21    19            93.51           19.0          2       19
21          22    18            92.68           18.0          2       18
22          23    19            93.06           19.0          2       19
23          24    19            94.04           19.0          2       19
24          25    19            95.69           19.0          2       19
25          26    19           103.62           19.0          2       19
26          27    11           108.13           11.0          2       11
27          28    10           102.37           10.0          2       10
28          29    17           102.36           17.0          1       17
29          30    19           102.58           19.0          1       19
30          31    19           103.27           19.0          1       19
31          32    19           104.13           19.0          1       19
32          33    19           104.64           19.0          1       19
33          34    18           104.65           18.0          1       18
34          35    18           103.82           18.0          1       18

TRAINING WEATHER AND COMPOUND COVERAGE

       compound  rainfall  rows  first_lap  last_lap  median_lap_time
0          HARD       0.0    17          2        18            92.71
1          HARD       1.0     1         19        19           101.87
2  INTERMEDIATE       1.0   159         21        35           103.47
3        MEDIUM       0.0   292          1        18            92.71
4        MEDIUM       1.0   137         18        28            95.61
5          SOFT       0.0    29          1        17            94.07
6          SOFT       1.0     2         18        19           100.11

TEST LAP COVERAGE

    lap_number  rows  median_lap_time  rainfall_rows  compounds  drivers
0           36    18           102.74           18.0          1       18
1           37    18           100.46           18.0          1       18
2           38    12            98.52           11.0          1       12
3           39    10            94.98            4.0          3       10
4           40    14            91.71            0.0          3       14
5           41    18            90.65            0.0          3       18
6           42    18            90.16            0.0          3       18
7           43    18            90.14            3.0          3       18
8           44    18            90.21           10.0          3       18
9           45    18            90.23           12.0          3       18
10          46    18            90.16            0.0          3       18
11          47    18            90.22            0.0          3       18
12          48    17            90.36            0.0          3       17
13          49    18            90.75            0.0          3       18
14          50    18            90.52            0.0          3       18
15          51    14            90.73            0.0          3       14
16          52    12            90.50            0.0          3       12

In [ ]:

import pandas as pd

weather_features = [
    "rainfall",
    "rainfall_trend",
    "track_temperature",
    "track_temp_trend",
    "air_temperature",
    "air_temp_trend",
    "humidity",
    "humidity_trend",
]

available_features = [
    col for col in weather_features if col in model_data.columns
]

print("1. AVAILABLE WEATHER FEATURES")
print(available_features)

print("\n2. TRAINING VS TEST FEATURE DISTRIBUTIONS")

train_weather = model_data.loc[
    model_data["lap_number"].between(1, 35),
    available_features
].describe().T

test_weather = model_data.loc[
    model_data["lap_number"].between(36, 52),
    available_features
].describe().T

distribution_comparison = train_weather[
    ["min", "50%", "max"]
].rename(columns={
    "min": "train_min",
    "50%": "train_median",
    "max": "train_max",
}).join(
    test_weather[["min", "50%", "max"]].rename(columns={
        "min": "test_min",
        "50%": "test_median",
        "max": "test_max",
    })
)

display(distribution_comparison.round(3))

print("\n3. WEATHER TRENDS DURING THE TRANSITION")

transition = (
    model_data.loc[model_data["lap_number"].between(16, 46)]
    .groupby("lap_number")
    .agg(
        median_lap_time=("lap_duration", "median"),
        rainfall=("rainfall", "mean"),
        rainfall_trend=("rainfall_trend", "mean"),
        track_temp=("track_temperature", "mean"),
        track_temp_trend=("track_temp_trend", "mean"),
        humidity=("humidity", "mean"),
        humidity_trend=("humidity_trend", "mean"),
    )
    .reset_index()
)

display(transition.round(3))

1. AVAILABLE WEATHER FEATURES
['rainfall', 'rainfall_trend', 'track_temperature', 'track_temp_trend', 'air_temperature', 'air_temp_trend', 'humidity', 'humidity_trend']

2. TRAINING VS TEST FEATURE DISTRIBUTIONS

,train_min,train_median,train_max,test_min,test_median,test_max
rainfall,0.000,0.000,1.000,0.000,0.000,1.000
rainfall_trend,0.000,0.000,0.333,-0.333,0.000,0.333
track_temperature,20.700,24.100,33.000,21.200,24.900,25.500
track_temp_trend,-3.000,-0.200,0.667,-0.067,0.133,1.033
air_temperature,14.500,16.200,16.800,14.500,15.400,15.900
air_temp_trend,-0.333,-0.067,0.167,0.000,0.067,0.233
humidity,59.000,63.000,76.000,68.000,73.000,78.000
humidity_trend,-1.000,0.333,2.000,-1.333,-0.333,1.000

3. WEATHER TRENDS DURING THE TRANSITION

,lap_number,median_lap_time,rainfall,rainfall_trend,track_temp,track_temp_trend,humidity,humidity_trend
0,16,93.178,0.000,0.000,24.395,-0.233,59.053,0.333
1,17,95.014,0.000,0.000,24.300,-0.267,61.158,-0.667
2,18,95.789,0.105,0.000,24.258,-0.167,60.895,1.000
3,19,104.151,1.000,0.000,23.368,-0.100,62.263,0.333
4,20,97.330,1.000,0.333,22.767,-0.400,65.000,1.333
5,21,93.507,1.000,0.333,22.268,-0.467,67.316,0.667
6,22,92.677,1.000,0.333,22.094,-0.667,68.333,2.000
7,23,93.062,1.000,0.000,21.989,-0.367,68.158,1.667
8,24,94.037,1.000,0.000,21.953,-0.300,68.368,1.333
9,25,95.687,1.000,0.000,21.974,-0.100,67.947,0.333
10,26,103.618,1.000,0.000,21.884,-0.033,67.632,0.000
11,27,108.126,1.000,0.000,21.400,0.000,68.000,-0.333
12,28,102.374,1.000,0.000,21.080,-0.200,69.500,0.000
13,29,102.362,1.000,0.000,20.912,-0.300,70.000,0.667
14,30,102.577,1.000,0.000,20.711,-0.367,70.789,1.000
15,31,103.274,1.000,0.000,20.700,-0.233,72.684,0.667
16,32,104.134,1.000,0.000,20.700,-0.133,73.053,1.000
17,33,104.641,1.000,0.000,20.774,-0.067,73.684,1.000
18,34,104.649,1.000,0.000,21.017,0.000,75.056,1.000
19,35,103.816,1.000,0.000,21.244,0.100,75.722,0.667
20,36,102.737,1.000,0.000,21.306,0.167,75.333,1.000
21,37,100.458,1.000,0.000,22.178,0.167,76.500,0.667
22,38,98.520,0.917,0.000,23.325,0.133,77.500,0.333
23,39,94.979,0.400,0.000,24.380,0.867,75.700,0.500
24,40,91.712,0.000,-0.333,24.386,1.033,74.143,0.333
25,41,90.649,0.000,-0.333,24.344,1.000,73.889,-0.667
26,42,90.164,0.000,-0.333,24.589,0.133,75.333,-1.333
27,43,90.144,0.167,0.000,24.839,0.133,74.556,-0.333
28,44,90.211,0.556,0.000,24.689,0.183,73.278,0.333
29,45,90.227,0.667,0.333,24.661,0.100,72.333,-0.167
30,46,90.160,0.000,0.333,24.972,-0.067,71.333,-0.667

In [ ]:

import numpy as np
import pandas as pd

# Work on a copy. Do not modify the shared simulation dataset.
transition_data = model_data.copy()

transition_data = transition_data.loc[
    transition_data["is_pit_out_lap"].fillna(False).eq(False)
].copy()

transition_data = transition_data.sort_values(
    ["driver_number", "lap_number"]
).reset_index(drop=True)

# Race-wide pace trend, calculated using completed laps only.
lap_pace = (
    transition_data.groupby("lap_number")["lap_duration"]
    .median()
    .rename("field_median_pace")
    .reset_index()
)

# Recent pace improvement, using only previous completed laps.
lap_pace["previous_pace"] = lap_pace["field_median_pace"].shift(1)
lap_pace["pace_change_from_previous_lap"] = (
    lap_pace["field_median_pace"] - lap_pace["previous_pace"]
)

transition_data = transition_data.merge(
    lap_pace[
        ["lap_number", "field_median_pace",
         "pace_change_from_previous_lap"]
    ],
    on="lap_number",
    how="left",
    validate="many_to_one"
)

# Inspect the drying transition and early dry running.
diagnostic = (
    transition_data.loc[
        transition_data["lap_number"].between(30, 46)
    ]
    .groupby(["lap_number", "compound"], dropna=False)
    .agg(
        drivers=("driver_number", "nunique"),
        median_lap_time=("lap_duration", "median"),
        median_tyre_age=("tyre_age", "median"),
        rainfall=("rainfall", "median"),
        track_temperature=("track_temperature", "median"),
        humidity=("humidity", "median"),
        grip_condition=("grip_condition", "first"),
    )
    .reset_index()
    .sort_values(["lap_number", "compound"])
)

display(diagnostic.round(3))

print("\nFIELD PACE CHANGE BY LAP")
display(
    lap_pace.loc[lap_pace["lap_number"].between(30, 46)]
    .round(3)
    .reset_index(drop=True)
)

,lap_number,compound,drivers,median_lap_time,median_tyre_age,rainfall,track_temperature,humidity,grip_condition
0,30,INTERMEDIATE,19,102.577,2.0,1.0,20.70,70.0,LOW
1,31,INTERMEDIATE,19,103.274,3.0,1.0,20.70,73.0,LOW
2,32,INTERMEDIATE,19,104.134,4.0,1.0,20.70,73.0,LOW
3,33,INTERMEDIATE,19,104.641,5.0,1.0,20.70,73.0,LOW
4,34,INTERMEDIATE,18,104.649,6.0,1.0,21.00,75.0,LOW
5,35,INTERMEDIATE,18,103.816,7.0,1.0,21.20,76.0,LOW
6,36,INTERMEDIATE,18,102.737,8.0,1.0,21.20,75.0,LOW
7,37,INTERMEDIATE,18,100.458,9.0,1.0,21.40,76.0,LOW
8,38,INTERMEDIATE,12,98.520,10.0,1.0,23.80,77.5,LOW
9,39,INTERMEDIATE,4,97.024,12.0,1.0,24.20,76.0,LOW
10,39,MEDIUM,1,92.722,1.0,0.0,24.40,74.0,LOW
11,39,SOFT,5,93.138,1.0,0.0,24.60,75.0,LOW
12,40,HARD,1,90.056,1.0,0.0,24.60,75.0,LOW
13,40,MEDIUM,5,91.146,1.0,0.0,24.40,74.0,LOW
14,40,SOFT,8,92.194,2.0,0.0,24.40,74.0,LOW
15,41,HARD,2,90.040,1.5,0.0,24.30,73.5,LOW
16,41,MEDIUM,6,90.642,2.0,0.0,24.30,73.5,NORMAL
17,41,SOFT,10,90.844,2.5,0.0,24.20,73.5,NORMAL
18,42,HARD,2,89.672,2.5,0.0,24.20,76.0,NORMAL
19,42,MEDIUM,6,90.312,3.0,0.0,24.70,75.0,NORMAL
20,42,SOFT,10,90.206,3.5,0.0,24.70,75.0,NORMAL
21,43,HARD,2,89.488,3.5,0.0,24.85,75.0,NORMAL
22,43,MEDIUM,6,90.161,4.0,0.0,24.85,75.0,NORMAL
23,43,SOFT,10,90.196,4.5,0.0,24.95,75.0,NORMAL
24,44,HARD,2,89.556,4.5,0.0,24.90,75.0,NORMAL
25,44,MEDIUM,6,90.274,5.0,1.0,24.50,72.5,NORMAL
26,44,SOFT,10,90.637,5.5,1.0,24.50,73.0,NORMAL
27,45,HARD,2,89.363,5.5,1.0,24.50,72.5,NORMAL
28,45,MEDIUM,6,90.216,6.0,1.0,24.50,72.5,NORMAL
29,45,SOFT,10,90.784,6.5,1.0,24.50,73.0,NORMAL
30,46,HARD,2,89.566,6.5,0.0,25.00,73.0,NORMAL
31,46,MEDIUM,6,90.017,7.0,0.0,25.00,71.0,NORMAL
32,46,SOFT,10,90.838,7.5,0.0,25.00,71.0,NORMAL

FIELD PACE CHANGE BY LAP

,lap_number,field_median_pace,previous_pace,pace_change_from_previous_lap
0,30,102.577,102.362,0.215
1,31,103.274,102.577,0.697
2,32,104.134,103.274,0.860
3,33,104.641,104.134,0.507
4,34,104.649,104.641,0.008
5,35,103.816,104.649,-0.833
6,36,102.737,103.816,-1.079
7,37,100.458,102.737,-2.279
8,38,98.520,100.458,-1.938
9,39,94.979,98.520,-3.541
10,40,91.712,94.979,-3.267
11,41,90.649,91.712,-1.062
12,42,90.164,90.649,-0.485
13,43,90.144,90.164,-0.020
14,44,90.211,90.144,0.067
15,45,90.227,90.211,0.016
16,46,90.160,90.227,-0.067

In [ ]:

import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Start from the existing dataset. Exclude pit-out laps from pace training.
pace_data = model_data.copy()

pace_data = pace_data.loc[
    ~pace_data["is_pit_out_lap"].fillna(False)
    & pace_data["lap_duration"].notna()
    & pace_data["compound"].notna()
].copy()

pace_data = pace_data.sort_values(
    ["driver_number", "lap_number"]
).reset_index(drop=True)

# All rolling features are shifted first, so the current lap's pace
# is never used to predict that same lap.
pace_data["previous_lap_time"] = (
    pace_data.groupby("driver_number")["lap_duration"].shift(1)
)

pace_data["previous_tyre_age"] = (
    pace_data.groupby("driver_number")["tyre_age"].shift(1)
)

pace_data["previous_rainfall"] = (
    pace_data.groupby("driver_number")["rainfall"].shift(1)
)

pace_data["previous_track_temperature"] = (
    pace_data.groupby("driver_number")["track_temperature"].shift(1)
)

pace_data["previous_humidity"] = (
    pace_data.groupby("driver_number")["humidity"].shift(1)
)

# Keep only rows with an available prior lap time.
pace_data = pace_data.loc[
    pace_data["previous_lap_time"].notna()
].copy()

numeric_features = [
    "lap_number",
    "tyre_age",
    "previous_tyre_age",
    "previous_lap_time",
    "previous_rainfall",
    "previous_track_temperature",
    "previous_humidity",
    "rainfall",
    "track_temperature",
    "humidity",
    "fuel_effect",
    "traffic_ahead",
    "traffic_behind",
    "tyre_degradation_effect",
]

numeric_features = [
    col for col in numeric_features if col in pace_data.columns
]

categorical_features = ["compound", "driver_number"]

# Chronological split, matching our previous evaluation.
train_mask = pace_data["lap_number"].between(2, 35)
test_mask = pace_data["lap_number"].between(36, 52)

train = pace_data.loc[train_mask].copy()
test = pace_data.loc[test_mask].copy()

X_train = train[numeric_features + categorical_features]
y_train = train["lap_duration"]

X_test = test[numeric_features + categorical_features]
y_test = test["lap_duration"]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numeric",
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
            ]),
            numeric_features,
        ),
        (
            "categorical",
            Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", OneHotEncoder(handle_unknown="ignore")),
            ]),
            categorical_features,
        ),
    ]
)

pace_model_ridge = Pipeline([
    ("preprocessor", preprocessor),
    ("model", Ridge(alpha=10.0)),
])

pace_model_ridge.fit(X_train, y_train)
predictions = pace_model_ridge.predict(X_test)

# Baseline: median training lap time for the compound.
compound_medians = train.groupby("compound")["lap_duration"].median()
baseline_predictions = test["compound"].map(compound_medians)

# Use the same rows for both evaluations.
valid = baseline_predictions.notna().to_numpy()

def evaluate_predictions(y_true, y_pred, label):
    return {
        "model": label,
        "MAE": mean_absolute_error(y_true, y_pred),
        "RMSE": np.sqrt(mean_squared_error(y_true, y_pred)),
        "R2": r2_score(y_true, y_pred),
    }

results = pd.DataFrame([
    evaluate_predictions(y_test.to_numpy()[valid], predictions[valid],
                         "Lagged-feature Ridge"),
    evaluate_predictions(y_test.to_numpy()[valid],
                         baseline_predictions.to_numpy()[valid],
                         "Compound median baseline"),
])

print("Training rows:", len(train))
print("Test rows:", len(test))
print("Numeric features:", numeric_features)
display(results.round(3))

Training rows: 618
Test rows: 277
Numeric features: ['lap_number', 'tyre_age', 'previous_tyre_age', 'previous_lap_time', 'previous_rainfall', 'previous_track_temperature', 'previous_humidity', 'rainfall', 'track_temperature', 'humidity', 'fuel_effect', 'traffic_ahead', 'traffic_behind', 'tyre_degradation_effect']

                      model    MAE   RMSE     R2
0      Lagged-feature Ridge  2.407  3.213  0.371
1  Compound median baseline  2.977  3.222  0.368

In [ ]:

# Compare both methods on identical test rows.
evaluation = test[
    ["driver_number", "lap_number", "compound", "lap_duration"]
].copy()

evaluation["ridge_prediction"] = predictions
evaluation["baseline_prediction"] = baseline_predictions.to_numpy()

evaluation["ridge_abs_error"] = (
    evaluation["lap_duration"] - evaluation["ridge_prediction"]
).abs()

evaluation["baseline_abs_error"] = (
    evaluation["lap_duration"] - evaluation["baseline_prediction"]
).abs()

print("ERROR BY COMPOUND")
by_compound = (
    evaluation.groupby("compound")
    .agg(
        rows=("lap_duration", "size"),
        ridge_MAE=("ridge_abs_error", "mean"),
        baseline_MAE=("baseline_abs_error", "mean"),
        ridge_RMSE=("lap_duration", lambda y: np.sqrt(
            np.mean(
                (
                    y.to_numpy()
                    - evaluation.loc[y.index, "ridge_prediction"].to_numpy()
                ) ** 2
            )
        )),
    )
    .reset_index()
)

by_compound["MAE_improvement_pct"] = (
    100
    * (by_compound["baseline_MAE"] - by_compound["ridge_MAE"])
    / by_compound["baseline_MAE"]
)

display(by_compound.round(3))

print("\nERROR BY RACE PHASE")
evaluation["race_phase"] = pd.cut(
    evaluation["lap_number"],
    bins=[35, 39, 42, 46, 52],
    labels=["Laps 36-39", "Laps 40-42", "Laps 43-46", "Laps 47-52"],
)

by_phase = (
    evaluation.groupby("race_phase", observed=True)
    .agg(
        rows=("lap_duration", "size"),
        ridge_MAE=("ridge_abs_error", "mean"),
        baseline_MAE=("baseline_abs_error", "mean"),
    )
    .reset_index()
)

by_phase["MAE_improvement_pct"] = (
    100
    * (by_phase["baseline_MAE"] - by_phase["ridge_MAE"])
    / by_phase["baseline_MAE"]
)

display(by_phase.round(3))


# Positive error = model predicted a lap that was too slow.
# Negative error = model predicted a lap that was too fast.

evaluation["ridge_error"] = (
    evaluation["ridge_prediction"] - evaluation["lap_duration"]
)

evaluation["baseline_error"] = (
    evaluation["baseline_prediction"] - evaluation["lap_duration"]
)

bias_by_phase = (
    evaluation.groupby("race_phase", observed=True)
    .agg(
        rows=("lap_duration", "size"),
        ridge_mean_error=("ridge_error", "mean"),
        ridge_median_error=("ridge_error", "median"),
        ridge_MAE=("ridge_abs_error", "mean"),
        baseline_mean_error=("baseline_error", "mean"),
        actual_median_lap_time=("lap_duration", "median"),
        predicted_median_lap_time=("ridge_prediction", "median"),
    )
    .reset_index()
)

display(bias_by_phase.round(3))

print("\nDETAIL: TRANSITION LAPS 36-39")
display(
    evaluation.loc[evaluation["lap_number"].between(36, 39)]
    .groupby(["lap_number", "compound"])
    .agg(
        rows=("lap_duration", "size"),
        actual_median=("lap_duration", "median"),
        ridge_median=("ridge_prediction", "median"),
        ridge_MAE=("ridge_abs_error", "mean"),
        ridge_bias=("ridge_error", "mean"),
    )
    .reset_index()
    .round(3)
)

ERROR BY COMPOUND

,compound,rows,ridge_MAE,baseline_MAE,ridge_RMSE,MAE_improvement_pct
0,HARD,23,2.083,3.187,2.947,34.632
1,INTERMEDIATE,52,4.056,3.083,4.296,-31.565
2,MEDIUM,71,2.137,2.576,2.920,17.024
3,SOFT,131,1.956,3.115,2.891,37.195

ERROR BY RACE PHASE

   race_phase  rows  ridge_MAE  baseline_MAE  MAE_improvement_pct
0  Laps 36-39    58      4.066         2.919              -39.313
1  Laps 40-42    50      1.238         2.716               54.428
2  Laps 43-46    72      3.458         3.196               -8.193
3  Laps 47-52    97      1.238         2.982               58.477

,race_phase,rows,ridge_mean_error,ridge_median_error,ridge_MAE,baseline_mean_error,actual_median_lap_time,predicted_median_lap_time
0,Laps 36-39,58,3.186,4.140,4.066,2.809,100.039,104.453
1,Laps 40-42,50,-0.851,-0.532,1.238,2.704,90.649,90.112
2,Laps 43-46,72,1.009,0.126,3.458,3.196,90.149,90.472
3,Laps 47-52,97,1.048,1.129,1.238,2.821,90.556,91.766

DETAIL: TRANSITION LAPS 36-39

,lap_number,compound,rows,actual_median,ridge_median,ridge_MAE,ridge_bias
0,36,INTERMEDIATE,18,102.737,105.399,2.890,2.890
1,37,INTERMEDIATE,18,100.458,104.565,4.179,4.179
2,38,INTERMEDIATE,12,98.520,103.460,4.911,4.813
3,39,INTERMEDIATE,4,97.024,103.406,6.185,6.185
4,39,MEDIUM,1,92.722,90.078,2.644,-2.644
5,39,SOFT,5,93.138,88.733,4.458,-4.458

In [ ]:

# Cell 40: Diagnose pace by observed weather regime and tyre compound.
# This is analysis only. It does not train or modify any model.

import numpy as np
import pandas as pd

regime_data = model_data.copy()

# Exclude pit-out laps because they contain substantial pit-exit time.
regime_data = regime_data.loc[
    ~regime_data["is_pit_out_lap"].fillna(False)
    & regime_data["lap_duration"].notna()
    & regime_data["compound"].notna()
].copy()

# Use observed conditions to classify historical rows.
# These are retrospective diagnostic labels, not future inputs.
def classify_weather_regime(row):
    rainfall = row.get("rainfall", np.nan)
    grip = row.get("grip_condition", None)

    if pd.isna(rainfall):
        return "UNKNOWN"

    if rainfall >= 0.5:
        return "WET"

    if isinstance(grip, str) and grip.upper() == "LOW":
        return "DRYING_OR_LOW_GRIP"

    return "DRY_OR_NORMAL_GRIP"

regime_data["weather_regime"] = regime_data.apply(
    classify_weather_regime,
    axis=1
)

# Show how each compound performs under each observed regime.
regime_summary = (
    regime_data.groupby(
        ["weather_regime", "compound"],
        dropna=False
    )
    .agg(
        rows=("lap_duration", "size"),
        drivers=("driver_number", "nunique"),
        median_lap_time=("lap_duration", "median"),
        mean_lap_time=("lap_duration", "mean"),
        median_tyre_age=("tyre_age", "median"),
    )
    .reset_index()
    .sort_values(["weather_regime", "compound"])
)

display(regime_summary.round(3))

print("\nREGIME COVERAGE")
display(
    regime_data.groupby("weather_regime")
    .agg(
        rows=("lap_duration", "size"),
        drivers=("driver_number", "nunique"),
        first_lap=("lap_number", "min"),
        last_lap=("lap_number", "max"),
    )
    .reset_index()
)

,weather_regime,compound,rows,drivers,median_lap_time,mean_lap_time,median_tyre_age
0,DRYING_OR_LOW_GRIP,HARD,3,2,90.056,90.045,1.0
1,DRYING_OR_LOW_GRIP,INTERMEDIATE,1,1,99.440,99.440,11.0
2,DRYING_OR_LOW_GRIP,MEDIUM,9,5,90.715,90.986,1.0
3,DRYING_OR_LOW_GRIP,SOFT,16,10,91.776,91.984,1.0
4,DRY_OR_NORMAL_GRIP,HARD,35,3,89.872,91.200,8.0
5,DRY_OR_NORMAL_GRIP,MEDIUM,344,19,92.590,92.833,8.0
6,DRY_OR_NORMAL_GRIP,SOFT,131,13,91.198,91.879,8.0
7,WET,HARD,3,3,89.589,93.531,6.0
8,WET,INTERMEDIATE,210,19,103.036,103.039,5.0
9,WET,MEDIUM,147,19,95.181,97.285,21.0
10,WET,SOFT,15,11,91.014,91.910,6.0

REGIME COVERAGE

       weather_regime  rows  drivers  first_lap  last_lap
0  DRYING_OR_LOW_GRIP    29       18         38        41
1  DRY_OR_NORMAL_GRIP   510       19          1        52
2                 WET   375       19         18        45

In [ ]:

# Cell 41: Check tyre and weather-regime coverage by race phase.

phase_data = regime_data.copy()

phase_data["race_phase"] = pd.cut(
    phase_data["lap_number"],
    bins=[0, 18, 27, 39, 52],
    labels=[
        "EARLY_DRY",
        "RAIN_ARRIVAL",
        "WET_TO_DRY_TRANSITION",
        "LATE_RACE"
    ],
    include_lowest=True
)

phase_coverage = (
    phase_data
    .groupby(
        ["race_phase", "weather_regime", "compound"],
        observed=True
    )
    .agg(
        rows=("lap_duration", "size"),
        drivers=("driver_number", "nunique"),
        first_lap=("lap_number", "min"),
        last_lap=("lap_number", "max"),
        median_lap_time=("lap_duration", "median")
    )
    .reset_index()
    .sort_values(["race_phase", "weather_regime", "compound"])
)

display(phase_coverage.round(3))

print("\nTotal observations and drivers by race phase:")
display(
    phase_data
    .groupby("race_phase", observed=True)
    .agg(
        rows=("lap_duration", "size"),
        drivers=("driver_number", "nunique"),
        first_lap=("lap_number", "min"),
        last_lap=("lap_number", "max")
    )
    .reset_index()
)

,race_phase,weather_regime,compound,rows,drivers,first_lap,last_lap,median_lap_time
0,EARLY_DRY,DRY_OR_NORMAL_GRIP,HARD,17,1,2,18,92.709
1,EARLY_DRY,DRY_OR_NORMAL_GRIP,MEDIUM,292,17,1,18,92.709
2,EARLY_DRY,DRY_OR_NORMAL_GRIP,SOFT,29,2,1,17,94.071
3,EARLY_DRY,WET,MEDIUM,1,1,18,18,99.637
4,EARLY_DRY,WET,SOFT,1,1,18,18,98.497
5,RAIN_ARRIVAL,WET,HARD,1,1,19,19,101.868
6,RAIN_ARRIVAL,WET,INTERMEDIATE,21,4,21,27,106.214
7,RAIN_ARRIVAL,WET,MEDIUM,135,18,19,27,95.488
8,RAIN_ARRIVAL,WET,SOFT,1,1,19,19,101.731
9,WET_TO_DRY_TRANSITION,DRYING_OR_LOW_GRIP,INTERMEDIATE,1,1,38,38,99.440
10,WET_TO_DRY_TRANSITION,DRYING_OR_LOW_GRIP,MEDIUM,1,1,39,39,92.722
11,WET_TO_DRY_TRANSITION,DRYING_OR_LOW_GRIP,SOFT,5,5,39,39,93.138
12,WET_TO_DRY_TRANSITION,WET,INTERMEDIATE,189,19,28,39,102.935
13,WET_TO_DRY_TRANSITION,WET,MEDIUM,1,1,28,28,112.976
14,LATE_RACE,DRYING_OR_LOW_GRIP,HARD,3,2,40,41,90.056
15,LATE_RACE,DRYING_OR_LOW_GRIP,MEDIUM,8,5,40,41,90.654
16,LATE_RACE,DRYING_OR_LOW_GRIP,SOFT,11,9,40,41,91.097
17,LATE_RACE,DRY_OR_NORMAL_GRIP,HARD,18,2,42,52,89.441
18,LATE_RACE,DRY_OR_NORMAL_GRIP,MEDIUM,52,6,40,52,90.131
19,LATE_RACE,DRY_OR_NORMAL_GRIP,SOFT,102,12,40,52,90.862
20,LATE_RACE,WET,HARD,2,2,45,45,89.363
21,LATE_RACE,WET,MEDIUM,10,6,43,45,90.130
22,LATE_RACE,WET,SOFT,13,10,43,45,90.882

Total observations and drivers by race phase:

              race_phase  rows  drivers  first_lap  last_lap
0              EARLY_DRY   340       19          1        18
1           RAIN_ARRIVAL   158       19         19        27
2  WET_TO_DRY_TRANSITION   197       19         28        39
3              LATE_RACE   219       18         40        52

In [ ]:

# Cell 42: Compare a weather-aware Ridge model against a compound-median baseline.

import numpy as np
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# --------------------------------------------------
# 1. Prepare data
# --------------------------------------------------
pace_data = model_data.copy()

pace_data = pace_data.loc[
    (~pace_data["is_pit_out_lap"].fillna(False).astype(bool))
    & pace_data["lap_duration"].notna()
    & pace_data["compound"].notna()
    & pace_data["lap_number"].notna()
].copy()

# Keep a chronological split, matching our earlier experiments.
train_data = pace_data.loc[pace_data["lap_number"] <= 35].copy()
test_data = pace_data.loc[pace_data["lap_number"] >= 36].copy()

# Features available at the decision point.
# Trend features must already be lagged in model_data.
numeric_features = [
    "lap_number",
    "tyre_age",
    "fuel_effect",
    "traffic_ahead",
    "traffic_behind",
    "position_change",
    "rainfall",
    "humidity",
    "air_temperature",
    "track_temperature",
    "wind_speed",
    "rainfall_trend",
    "track_temp_trend",
    "air_temp_trend",
    "humidity_trend",
]

categorical_features = [
    "compound",
    "driver_number",
]

numeric_features = [
    c for c in numeric_features
    if c in pace_data.columns
]
categorical_features = [
    c for c in categorical_features
    if c in pace_data.columns
]

feature_columns = numeric_features + categorical_features

X_train = train_data[feature_columns].copy()
y_train = train_data["lap_duration"].copy()

X_test = test_data[feature_columns].copy()
y_test = test_data["lap_duration"].copy()

# --------------------------------------------------
# 2. Build preprocessing and Ridge regression
# --------------------------------------------------
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore")),
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features),
])

ridge_model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", Ridge(alpha=10.0)),
])

ridge_model.fit(X_train, y_train)
ridge_predictions = ridge_model.predict(X_test)

# --------------------------------------------------
# 3. Baseline: median pace by compound from training
# --------------------------------------------------
compound_medians = train_data.groupby("compound")[
    "lap_duration"
].median()

global_median = train_data["lap_duration"].median()

baseline_predictions = (
    test_data["compound"]
    .map(compound_medians)
    .fillna(global_median)
    .to_numpy()
)

# --------------------------------------------------
# 4. Evaluate both models on identical test rows
# --------------------------------------------------
evaluation = test_data[
    ["driver_number", "lap_number", "compound", "lap_duration"]
].copy().reset_index(drop=True)

evaluation["race_phase"] = pd.cut(
    evaluation["lap_number"],
    bins=[35, 39, 42, 46, 52],
    labels=[
        "WET_TO_DRY",
        "EARLY_DRY",
        "MID_LATE_RACE",
        "FINAL_LAPS",
    ],
    include_lowest=True,
)

evaluation["actual"] = evaluation["lap_duration"]
evaluation["ridge_prediction"] = ridge_predictions
evaluation["baseline_prediction"] = baseline_predictions

def calculate_metrics(frame, prediction_column):
    actual = frame["actual"]
    predicted = frame[prediction_column]
    return pd.Series({
        "rows": len(frame),
        "MAE": mean_absolute_error(actual, predicted),
        "RMSE": np.sqrt(mean_squared_error(actual, predicted)),
        "Bias": (predicted - actual).mean(),
        "R2": r2_score(actual, predicted),
    })

overall_results = pd.DataFrame({
    "Ridge": calculate_metrics(
        evaluation, "ridge_prediction"
    ),
    "Compound median": calculate_metrics(
        evaluation, "baseline_prediction"
    ),
}).T

print("OVERALL TEST RESULTS")
display(overall_results.round(3))

# --------------------------------------------------
# 5. Performance by race phase
# --------------------------------------------------
phase_results = []

for phase, group in evaluation.groupby(
    "race_phase", observed=True
):
    for model_name, prediction_column in [
        ("Ridge", "ridge_prediction"),
        ("Compound median", "baseline_prediction"),
    ]:
        result = calculate_metrics(group, prediction_column)
        phase_results.append({
            "race_phase": phase,
            "model": model_name,
            **result.to_dict(),
        })

phase_results = pd.DataFrame(phase_results)

print("\nRESULTS BY RACE PHASE")
display(
    phase_results
    .sort_values(["race_phase", "model"])
    .round(3)
)

# --------------------------------------------------
# 6. Performance by tyre compound
# --------------------------------------------------
compound_results = []

for compound, group in evaluation.groupby("compound"):
    for model_name, prediction_column in [
        ("Ridge", "ridge_prediction"),
        ("Compound median", "baseline_prediction"),
    ]:
        result = calculate_metrics(group, prediction_column)
        compound_results.append({
            "compound": compound,
            "model": model_name,
            **result.to_dict(),
        })

compound_results = pd.DataFrame(compound_results)

print("\nRESULTS BY TYRE COMPOUND")
display(
    compound_results
    .sort_values(["compound", "model"])
    .round(3)
)

# --------------------------------------------------
# 7. Inspect errors over time
# --------------------------------------------------
evaluation["ridge_error"] = (
    evaluation["ridge_prediction"] - evaluation["actual"]
)
evaluation["baseline_error"] = (
    evaluation["baseline_prediction"] - evaluation["actual"]
)

lap_errors = (
    evaluation.groupby("lap_number")
    .agg(
        rows=("actual", "size"),
        actual_median=("actual", "median"),
        ridge_median=("ridge_prediction", "median"),
        ridge_MAE=("ridge_error", lambda s: s.abs().mean()),
        ridge_bias=("ridge_error", "mean"),
        baseline_MAE=("baseline_error", lambda s: s.abs().mean()),
    )
    .reset_index()
)

print("\nERRORS BY LAP")
display(lap_errors.round(3))

print("\nTraining rows:", len(train_data))
print("Test rows:", len(test_data))
print("Features used:", feature_columns)
print("Training lap range:", train_data["lap_number"].min(),
      "to", train_data["lap_number"].max())
print("Test lap range:", test_data["lap_number"].min(),
      "to", test_data["lap_number"].max())

OVERALL TEST RESULTS

                  rows    MAE   RMSE   Bias     R2
Ridge            277.0  2.959  3.760 -0.194  0.139
Compound median  277.0  3.065  3.308  2.988  0.334

RESULTS BY RACE PHASE

      race_phase            model  rows    MAE   RMSE   Bias      R2
3      EARLY_DRY  Compound median  50.0  2.827  3.017  2.816  -7.449
2      EARLY_DRY            Ridge  50.0  1.430  1.654 -0.454  -1.539
7     FINAL_LAPS  Compound median  97.0  3.089  3.219  2.938  -4.200
6     FINAL_LAPS            Ridge  97.0  1.612  2.089 -1.364  -1.190
5  MID_LATE_RACE  Compound median  72.0  3.308  3.400  3.308 -17.742
4  MID_LATE_RACE            Ridge  72.0  4.059  4.428 -1.657 -30.781
1     WET_TO_DRY  Compound median  58.0  2.928  3.567  2.824  -0.455
0     WET_TO_DRY            Ridge  58.0  5.163  5.790  3.804  -2.834

RESULTS BY TYRE COMPOUND

       compound            model   rows    MAE   RMSE   Bias      R2
1          HARD  Compound median   23.0  3.218  3.235  3.218 -96.704
0          HARD            Ridge   23.0  2.360  3.101 -1.957 -88.772
3  INTERMEDIATE  Compound median   52.0  3.083  3.715  3.078  -2.189
2  INTERMEDIATE            Ridge   52.0  5.001  5.650  5.001  -6.377
5        MEDIUM  Compound median   71.0  2.623  2.746  2.514  -5.186
4        MEDIUM            Ridge   71.0  2.310  2.874 -0.631  -5.780
7          SOFT  Compound median  131.0  3.270  3.426  3.169  -5.944
6          SOFT            Ridge  131.0  2.604  3.325 -1.709  -5.543

ERRORS BY LAP

,lap_number,rows,actual_median,ridge_median,ridge_MAE,ridge_bias,baseline_MAE
0,36,18,102.737,104.715,2.417,2.417,0.989
1,37,18,100.458,105.641,5.261,5.261,2.992
2,38,12,98.520,105.799,7.088,7.088,5.278
3,39,10,94.979,87.828,7.621,-0.262,3.486
4,40,14,91.712,89.707,2.231,-2.231,2.025
5,41,18,90.649,89.863,1.189,-0.410,2.980
6,42,18,90.164,91.655,1.048,0.885,3.297
7,43,18,90.144,87.553,3.319,-1.086,3.452
8,44,18,90.211,94.460,4.501,0.362,3.297
9,45,18,90.227,91.581,3.094,-0.583,3.196
10,46,18,90.160,84.719,5.322,-5.322,3.286
11,47,18,90.218,90.053,1.144,-1.120,3.245
12,48,17,90.365,91.021,0.744,0.085,3.284
13,49,18,90.752,90.493,0.821,-0.293,3.006
14,50,18,90.516,87.703,3.009,-3.009,2.948
15,51,14,90.732,88.636,2.352,-2.352,2.896
16,52,12,90.496,89.220,1.768,-1.768,3.136

Training rows: 637
Test rows: 277
Features used: ['lap_number', 'tyre_age', 'fuel_effect', 'traffic_ahead', 'traffic_behind', 'position_change', 'rainfall', 'humidity', 'air_temperature', 'track_temperature', 'wind_speed', 'rainfall_trend', 'track_temp_trend', 'air_temp_trend', 'humidity_trend', 'compound', 'driver_number']
Training lap range: 1 to 35
Test lap range: 36 to 52

In [ ]:

# Cell 43: Diagnose extreme pace predictions and train/test feature shifts.

# --------------------------------------------------
# 1. Find the largest individual Ridge errors
# --------------------------------------------------
diagnostic_rows = evaluation.copy()

diagnostic_rows["absolute_ridge_error"] = (
    diagnostic_rows["ridge_error"].abs()
)

inspect_columns = [
    "driver_number",
    "lap_number",
    "compound",
    "actual",
    "ridge_prediction",
    "baseline_prediction",
    "ridge_error",
    "absolute_ridge_error",
]

display(
    diagnostic_rows
    .sort_values("absolute_ridge_error", ascending=False)
    [inspect_columns]
    .head(20)
    .round(3)
)

# --------------------------------------------------
# 2. Inspect the underlying features for those rows
# --------------------------------------------------
feature_inspection = test_data[
    ["driver_number", "lap_number", "compound"]
    + numeric_features
].copy().reset_index(drop=True)

feature_inspection["actual"] = y_test.reset_index(drop=True)
feature_inspection["ridge_prediction"] = ridge_predictions
feature_inspection["ridge_error"] = (
    feature_inspection["ridge_prediction"]
    - feature_inspection["actual"]
)
feature_inspection["absolute_error"] = (
    feature_inspection["ridge_error"].abs()
)

print("\nFEATURES FOR THE 15 WORST PREDICTIONS")

display(
    feature_inspection
    .sort_values("absolute_error", ascending=False)
    .head(15)
    .round(3)
)

# --------------------------------------------------
# 3. Compare training and test feature distributions
# --------------------------------------------------
distribution_rows = []

for col in numeric_features:
    train_values = pd.to_numeric(train_data[col], errors="coerce")
    test_values = pd.to_numeric(test_data[col], errors="coerce")

    distribution_rows.append({
        "feature": col,
        "train_missing_pct": train_values.isna().mean() * 100,
        "test_missing_pct": test_values.isna().mean() * 100,
        "train_min": train_values.min(),
        "train_median": train_values.median(),
        "train_max": train_values.max(),
        "test_min": test_values.min(),
        "test_median": test_values.median(),
        "test_max": test_values.max(),
    })

distribution_comparison = pd.DataFrame(distribution_rows)

print("\nTRAIN VS TEST FEATURE DISTRIBUTIONS")

display(distribution_comparison.round(3))

# --------------------------------------------------
# 4. Check whether test compounds were represented
#    in the training data
# --------------------------------------------------
train_compounds = set(train_data["compound"].dropna().unique())

compound_support = (
    test_data.groupby("compound")
    .agg(
        test_rows=("lap_duration", "size"),
        test_drivers=("driver_number", "nunique"),
    )
    .reset_index()
)

compound_support["present_in_training"] = (
    compound_support["compound"].isin(train_compounds)
)

compound_support["training_rows"] = (
    compound_support["compound"]
    .map(train_data["compound"].value_counts())
    .fillna(0)
    .astype(int)
)

print("\nCOMPOUND SUPPORT")

display(compound_support)

,driver_number,lap_number,compound,actual,ridge_prediction,baseline_prediction,ridge_error,absolute_ridge_error
57,77,39,SOFT,97.114,87.011,94.235,-10.103,10.103
36,1,38,INTERMEDIATE,95.963,105.561,103.472,9.598,9.598
56,55,39,INTERMEDIATE,96.802,106.395,103.472,9.593,9.593
53,27,39,INTERMEDIATE,97.245,106.709,103.472,9.464,9.464
50,18,39,INTERMEDIATE,97.759,106.789,103.472,9.030,9.030
41,23,38,INTERMEDIATE,97.843,106.618,103.472,8.775,8.775
55,4,39,INTERMEDIATE,96.746,105.451,103.472,8.705,8.705
160,77,45,SOFT,93.159,84.677,94.235,-8.482,8.482
47,81,38,INTERMEDIATE,97.106,105.341,103.472,8.235,8.235
21,16,37,INTERMEDIATE,98.357,106.516,103.472,8.159,8.159
45,44,38,INTERMEDIATE,97.220,105.220,103.472,8.000,8.000
51,20,39,SOFT,93.212,85.479,94.235,-7.733,7.733
40,22,38,INTERMEDIATE,98.670,106.242,103.472,7.572,7.572
37,14,38,INTERMEDIATE,98.684,106.052,103.472,7.368,7.368
39,2,38,INTERMEDIATE,98.811,106.117,103.472,7.306,7.306
176,44,46,SOFT,89.641,82.380,94.235,-7.261,7.261
54,3,39,SOFT,93.138,85.910,94.235,-7.228,7.228
42,27,38,INTERMEDIATE,98.854,106.037,103.472,7.183,7.183
46,55,38,INTERMEDIATE,98.370,105.529,103.472,7.159,7.159
109,11,43,MEDIUM,90.229,97.138,92.956,6.909,6.909

FEATURES FOR THE 15 WORST PREDICTIONS

,driver_number,lap_number,compound,lap_number,tyre_age,fuel_effect,traffic_ahead,traffic_behind,position_change,rainfall,...,track_temperature,wind_speed,rainfall_trend,track_temp_trend,air_temp_trend,humidity_trend,actual,ridge_prediction,ridge_error,absolute_error
57,77,39,SOFT,39,1.0,-3.197,1.0,0.0,0.0,0.0,...,24.6,1.2,0.000,0.867,0.000,0.500,97.114,87.011,-10.103,10.103
36,1,38,INTERMEDIATE,38,11.0,NaN,1.0,1.0,0.0,1.0,...,22.5,1.3,0.000,0.133,0.000,0.333,95.963,105.561,9.598,9.598
56,55,39,INTERMEDIATE,39,12.0,NaN,1.0,0.0,1.0,1.0,...,24.2,1.9,0.000,0.867,0.000,0.500,96.802,106.395,9.593,9.593
53,27,39,INTERMEDIATE,39,12.0,NaN,1.0,0.0,0.0,1.0,...,24.2,1.9,0.000,0.867,0.000,0.500,97.245,106.709,9.464,9.464
50,18,39,INTERMEDIATE,39,12.0,NaN,1.0,0.0,0.0,1.0,...,24.2,1.9,0.000,0.867,0.000,0.500,97.759,106.789,9.030,9.030
41,23,38,INTERMEDIATE,38,10.0,NaN,1.0,1.0,0.0,1.0,...,23.8,1.8,0.000,0.133,0.000,0.333,97.843,106.618,8.775,8.775
55,4,39,INTERMEDIATE,39,11.0,NaN,0.0,1.0,0.0,1.0,...,24.2,1.9,0.000,0.867,0.000,0.500,96.746,105.451,8.705,8.705
160,77,45,SOFT,45,7.0,-3.701,1.0,0.0,0.0,0.0,...,25.0,2.0,0.333,0.100,0.067,-0.167,93.159,84.677,-8.482,8.482
47,81,38,INTERMEDIATE,38,9.0,NaN,1.0,0.0,0.0,1.0,...,22.5,1.3,0.000,0.133,0.000,0.333,97.106,105.341,8.235,8.235
21,16,37,INTERMEDIATE,37,9.0,NaN,1.0,1.0,0.0,1.0,...,23.8,1.8,0.000,0.167,0.000,0.667,98.357,106.516,8.159,8.159
45,44,38,INTERMEDIATE,38,10.0,NaN,1.0,1.0,0.0,1.0,...,22.5,1.3,0.000,0.133,0.000,0.333,97.220,105.220,8.000,8.000
51,20,39,SOFT,39,1.0,-3.197,1.0,0.0,1.0,0.0,...,24.6,1.4,0.000,0.867,0.000,0.500,93.212,85.479,-7.733,7.733
40,22,38,INTERMEDIATE,38,10.0,NaN,1.0,0.0,0.0,1.0,...,23.8,1.8,0.000,0.133,0.000,0.333,98.670,106.242,7.572,7.572
37,14,38,INTERMEDIATE,38,10.0,NaN,1.0,0.0,0.0,1.0,...,23.8,1.8,0.000,0.133,0.000,0.333,98.684,106.052,7.368,7.368
39,2,38,INTERMEDIATE,38,10.0,NaN,0.0,1.0,1.0,1.0,...,23.8,1.8,0.000,0.133,0.000,0.333,98.811,106.117,7.306,7.306

TRAIN VS TEST FEATURE DISTRIBUTIONS

,feature,train_missing_pct,test_missing_pct,train_min,train_median,train_max,test_min,test_median,test_max
0,lap_number,0.000,0.000,1.000,17.000,35.000,36.000,44.000,52.000
1,tyre_age,0.000,0.000,0.000,8.000,27.000,1.000,8.000,14.000
2,fuel_effect,26.688,18.773,-2.103,-1.009,-0.000,-4.290,-3.785,-3.197
3,traffic_ahead,0.000,0.000,0.000,1.000,1.000,0.000,1.000,1.000
4,traffic_behind,0.000,0.000,0.000,0.000,1.000,0.000,0.000,1.000
5,position_change,0.000,0.000,-5.000,0.000,8.000,-2.000,0.000,3.000
6,rainfall,0.000,0.000,0.000,0.000,1.000,0.000,0.000,1.000
7,humidity,0.000,0.000,59.000,63.000,76.000,68.000,73.000,78.000
8,air_temperature,0.000,0.000,14.500,16.200,16.800,14.500,15.400,15.900
9,track_temperature,0.000,0.000,20.700,24.100,33.000,21.200,24.900,25.500
10,wind_speed,0.000,0.000,0.500,1.600,2.500,0.700,1.400,2.200
11,rainfall_trend,11.774,0.000,0.000,0.000,0.333,-0.333,0.000,0.333
12,track_temp_trend,11.774,0.000,-3.000,-0.200,0.667,-0.067,0.133,1.033
13,air_temp_trend,11.774,0.000,-0.333,-0.067,0.167,0.000,0.067,0.233
14,humidity_trend,11.774,0.000,-1.000,0.333,2.000,-1.333,-0.333,1.000

COMPOUND SUPPORT

       compound  test_rows  test_drivers  present_in_training  training_rows
0          HARD         23             2                 True             18
1  INTERMEDIATE         52            18                 True            159
2        MEDIUM         71             6                 True            429
3          SOFT        131            12                 True             31

In [ ]:

# Cell 44: Audit extreme prediction errors and fuel-feature coverage.

# --------------------------------------------------
# 1. Inspect the exact rows with the largest errors
# --------------------------------------------------
worst_keys = (
    diagnostic_rows
    .nlargest(15, "absolute_ridge_error")
    [["driver_number", "lap_number"]]
    .drop_duplicates()
)

context_columns = [
    "driver_number",
    "lap_number",
    "date_start",
    "compound",
    "lap_duration",
    "is_pit_out_lap",
    "stint_number",
    "tyre_age",
    "position",
    "fuel_effect",
    "tyre_degradation_effect",
    "rainfall",
    "grip_condition",
    "weather_age_seconds",
    "track_temperature",
    "air_temperature",
    "rainfall_trend",
    "track_temp_trend",
    "traffic_ahead",
    "traffic_behind",
    "position_change",
]

context_columns = [
    c for c in context_columns if c in model_data.columns
]

worst_context = (
    model_data
    .merge(
        worst_keys,
        on=["driver_number", "lap_number"],
        how="inner",
        validate="many_to_one",
    )
    [context_columns]
    .sort_values(["lap_number", "driver_number"])
)

print("RAW CONTEXT FOR WORST PREDICTIONS")
display(worst_context.round(3))

# --------------------------------------------------
# 2. Measure missing fuel-effect coverage
# --------------------------------------------------
fuel_coverage = (
    model_data
    .assign(fuel_missing=model_data["fuel_effect"].isna())
    .groupby("compound", dropna=False)
    .agg(
        rows=("lap_duration", "size"),
        missing_fuel_rows=("fuel_missing", "sum"),
        unique_drivers=("driver_number", "nunique"),
        first_lap=("lap_number", "min"),
        last_lap=("lap_number", "max"),
    )
    .reset_index()
)

fuel_coverage["missing_fuel_pct"] = (
    100 * fuel_coverage["missing_fuel_rows"]
    / fuel_coverage["rows"]
)

print("\nFUEL COVERAGE BY COMPOUND")
display(fuel_coverage.round(2))

# --------------------------------------------------
# 3. Check whether fuel missingness is concentrated
#    in particular laps
# --------------------------------------------------
fuel_missing_by_lap = (
    model_data
    .groupby("lap_number")
    .agg(
        rows=("driver_number", "size"),
        missing_fuel=("fuel_effect", lambda s: s.isna().sum()),
        compounds=("compound", "nunique"),
    )
    .reset_index()
)

fuel_missing_by_lap["missing_fuel_pct"] = (
    100 * fuel_missing_by_lap["missing_fuel"]
    / fuel_missing_by_lap["rows"]
)

print("\nLAPS WITH THE MOST MISSING FUEL DATA")
display(
    fuel_missing_by_lap
    .sort_values("missing_fuel_pct", ascending=False)
    .head(20)
    .round(2)
)

# --------------------------------------------------
# 4. Check if suspicious laps were pit-out laps
# --------------------------------------------------
print("\nPIT-OUT FLAG COUNTS IN THE WORST ROWS")

if "is_pit_out_lap" in worst_context.columns:
    display(
        worst_context["is_pit_out_lap"]
        .value_counts(dropna=False)
        .rename_axis("is_pit_out_lap")
        .reset_index(name="rows")
    )

# --------------------------------------------------
# 5. Verify compound coverage in training
# --------------------------------------------------
print("\nTRAINING COMPOUND COUNTS")
display(
    train_data["compound"]
    .value_counts(dropna=False)
    .rename_axis("compound")
    .reset_index(name="training_rows")
)

RAW CONTEXT FOR WORST PREDICTIONS

C:\Users\Nihan\AppData\Local\Temp\ipykernel_3544\353108106.py:54: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  display(worst_context.round(3))

,driver_number,lap_number,date_start,compound,lap_duration,is_pit_out_lap,stint_number,tyre_age,position,fuel_effect,...,rainfall,grip_condition,weather_age_seconds,track_temperature,air_temperature,rainfall_trend,track_temp_trend,traffic_ahead,traffic_behind,position_change
0,16,37,2024-07-07 15:03:08.926000+00:00,INTERMEDIATE,98.357,False,3.0,9.0,15.0,NaN,...,1.0,LOW,5.991,23.8,14.6,0.000,0.167,1.0,1.0,0.0
1,1,38,2024-07-07 15:02:45.144000+00:00,INTERMEDIATE,95.963,False,2.0,11.0,3.0,NaN,...,1.0,LOW,42.221,22.5,14.6,0.000,0.133,1.0,1.0,0.0
2,14,38,2024-07-07 15:03:30.826000+00:00,INTERMEDIATE,98.684,False,2.0,10.0,8.0,NaN,...,1.0,LOW,27.891,23.8,14.6,0.000,0.133,1.0,0.0,0.0
3,2,38,2024-07-07 15:03:51.556000+00:00,INTERMEDIATE,98.811,False,2.0,10.0,13.0,NaN,...,1.0,LOW,48.621,23.8,14.6,0.000,0.133,0.0,1.0,1.0
4,22,38,2024-07-07 15:03:35.861000+00:00,INTERMEDIATE,98.670,False,2.0,10.0,9.0,NaN,...,1.0,LOW,32.926,23.8,14.6,0.000,0.133,1.0,0.0,0.0
5,23,38,2024-07-07 15:03:39.706000+00:00,INTERMEDIATE,97.843,False,2.0,10.0,10.0,NaN,...,1.0,LOW,36.771,23.8,14.6,0.000,0.133,1.0,1.0,0.0
6,44,38,2024-07-07 15:02:38.413000+00:00,INTERMEDIATE,97.220,False,2.0,10.0,2.0,NaN,...,1.0,LOW,35.490,22.5,14.6,0.000,0.133,1.0,1.0,0.0
7,81,38,2024-07-07 15:02:58.606000+00:00,INTERMEDIATE,97.106,False,2.0,9.0,5.0,NaN,...,1.0,LOW,55.683,22.5,14.6,0.000,0.133,1.0,0.0,0.0
8,18,39,2024-07-07 15:05:02.181000+00:00,INTERMEDIATE,97.759,False,2.0,12.0,7.0,NaN,...,1.0,LOW,59.232,24.2,14.6,0.000,0.867,1.0,0.0,0.0
9,20,39,2024-07-07 15:05:52.100000+00:00,SOFT,93.212,False,3.0,1.0,12.0,-3.197,...,0.0,LOW,49.157,24.6,14.6,0.000,0.867,1.0,0.0,1.0
10,27,39,2024-07-07 15:04:57.989000+00:00,INTERMEDIATE,97.245,False,2.0,12.0,6.0,NaN,...,1.0,LOW,55.040,24.2,14.6,0.000,0.867,1.0,0.0,0.0
11,4,39,2024-07-07 15:04:14.487000+00:00,INTERMEDIATE,96.746,False,2.0,11.0,1.0,NaN,...,1.0,LOW,11.538,24.2,14.6,0.000,0.867,0.0,1.0,0.0
12,55,39,2024-07-07 15:04:36.091000+00:00,INTERMEDIATE,96.802,False,2.0,12.0,5.0,NaN,...,1.0,LOW,33.142,24.2,14.6,0.000,0.867,1.0,0.0,1.0
13,77,39,2024-07-07 15:06:18.865000+00:00,SOFT,97.114,False,3.0,1.0,14.0,-3.197,...,0.0,LOW,15.917,24.6,14.8,0.000,0.867,1.0,0.0,0.0
14,77,45,2024-07-07 15:15:37.622000+00:00,SOFT,93.159,False,3.0,7.0,14.0,-3.701,...,0.0,NORMAL,34.574,25.0,15.5,0.333,0.100,1.0,0.0,0.0

FUEL COVERAGE BY COMPOUND

,compound,rows,missing_fuel_rows,unique_drivers,first_lap,last_lap,missing_fuel_pct
0,HARD,41,0,3,2,52,0.0
1,INTERMEDIATE,211,211,19,21,39,100.0
2,MEDIUM,500,11,19,1,52,2.2
3,SOFT,162,0,13,1,52,0.0

LAPS WITH THE MOST MISSING FUEL DATA

    lap_number  rows  missing_fuel  compounds  missing_fuel_pct
32          33    19            19          1            100.00
33          34    18            18          1            100.00
27          28    10            10          2            100.00
26          27    11            11          2            100.00
28          29    17            17          1            100.00
29          30    19            19          1            100.00
30          31    19            19          1            100.00
31          32    19            19          1            100.00
36          37    18            18          1            100.00
37          38    12            12          1            100.00
35          36    18            18          1            100.00
34          35    18            18          1            100.00
38          39    10             4          3             40.00
25          26    19             4          2             21.05
20          21    19             4          2             21.05
21          22    18             3          2             16.67
22          23    19             3          2             15.79
24          25    19             3          2             15.79
23          24    19             3          2             15.79
0            1    18             0          2              0.00

PIT-OUT FLAG COUNTS IN THE WORST ROWS

   is_pit_out_lap  rows
0           False    15

TRAINING COMPOUND COUNTS

       compound  training_rows
0        MEDIUM            429
1  INTERMEDIATE            159
2          SOFT             31
3          HARD             18

In [ ]:

# Cell 44: Establish the first PITWALL strategy decision.
# Handles target_state as either a Series or a DataFrame.

TARGET_DRIVER = 63
DECISION_LAP = 26

decision = build_decision_state(
    sim_state=sim_state,
    driver_number=TARGET_DRIVER,
    decision_lap=DECISION_LAP,
)

field = decision["field_state"].copy()
target = decision["target_state"]

# Normalize the target to a one-row DataFrame for display.
if isinstance(target, pd.Series):
    target_row = target.to_frame().T
else:
    target_row = target.copy()

print("PITWALL STRATEGY DECISION")
print("=" * 45)
print(f"Driver: #{TARGET_DRIVER}")
print(f"Decision after lap: {DECISION_LAP}")
print(f"Next lap: {decision['next_lap']}")
print(f"Last lap in dataset: {decision['race_laps_in_dataset']}")
print(
    "Laps remaining:",
    max(0, decision["race_laps_in_dataset"] - DECISION_LAP)
)

# Target driver state
target_columns = [
    "driver_number",
    "lap_number",
    "position",
    "compound",
    "tyre_age",
    "fuel_effect",
    "rainfall",
    "grip_condition",
]

target_columns = [
    c for c in target_columns if c in target_row.columns
]

print("\nTARGET DRIVER STATE")
display(target_row[target_columns])

# Current field
field_columns = [
    "driver_number",
    "lap_number",
    "position",
    "compound",
    "tyre_age",
    "rainfall",
    "grip_condition",
]

field_columns = [
    c for c in field_columns if c in field.columns
]

print("\nCURRENT FIELD")
display(
    field[field_columns].sort_values(
        "position", na_position="last"
    )
)

# Candidate actions only. Not ranked or evaluated yet.
current_compound = target_row.iloc[0].get("compound")

candidate_actions = pd.DataFrame([
    {
        "action": "HOLD",
        "pit_lap": None,
        "new_compound": None,
    },
    {
        "action": "PIT_NEXT_LAP",
        "pit_lap": DECISION_LAP + 1,
        "new_compound": "INTERMEDIATE",
    },
    {
        "action": "PIT_IN_2_LAPS",
        "pit_lap": DECISION_LAP + 2,
        "new_compound": "INTERMEDIATE",
    },
    {
        "action": "PIT_IN_3_LAPS",
        "pit_lap": DECISION_LAP + 3,
        "new_compound": "INTERMEDIATE",
    },
])

print("\nCURRENT COMPOUND:", current_compound)
print("\nCANDIDATE STRATEGIES")
display(candidate_actions)

print(
    "\nStatus: decision state and candidate actions created. "
    "No strategy has been declared optimal."
)

PITWALL STRATEGY DECISION
=============================================
Driver: #63
Decision after lap: 26
Next lap: 27
Last lap in dataset: 52
Laps remaining: 26

TARGET DRIVER STATE

,driver_number,lap_number,position,compound,tyre_age,fuel_effect,rainfall,grip_condition
3,63,26,4.0,MEDIUM,25.0,-2.103049,1.0,LOW

CURRENT FIELD

,driver_number,lap_number,position,compound,tyre_age,rainfall,grip_condition
0,4,26,1.0,MEDIUM,25.0,1.0,LOW
1,81,26,2.0,MEDIUM,25.0,1.0,LOW
2,44,26,3.0,MEDIUM,25.0,1.0,LOW
3,63,26,4.0,MEDIUM,25.0,1.0,LOW
4,1,26,5.0,MEDIUM,25.0,1.0,LOW
5,55,26,6.0,MEDIUM,25.0,1.0,LOW
6,27,26,7.0,MEDIUM,25.0,1.0,LOW
7,14,26,8.0,MEDIUM,25.0,1.0,LOW
8,18,26,9.0,MEDIUM,25.0,1.0,LOW
9,22,26,10.0,MEDIUM,25.0,1.0,LOW
10,23,26,11.0,MEDIUM,25.0,1.0,LOW
11,20,26,12.0,MEDIUM,25.0,1.0,LOW
12,2,26,13.0,MEDIUM,25.0,1.0,LOW
13,3,26,14.0,MEDIUM,25.0,1.0,LOW
14,77,26,15.0,MEDIUM,25.0,1.0,LOW
15,16,26,16.0,INTERMEDIATE,6.0,1.0,LOW
16,11,26,17.0,INTERMEDIATE,6.0,1.0,LOW
17,31,26,18.0,MEDIUM,4.0,1.0,LOW
18,24,26,19.0,INTERMEDIATE,6.0,1.0,LOW

CURRENT COMPOUND: MEDIUM

CANDIDATE STRATEGIES

          action  pit_lap  new_compound
0           HOLD      NaN           NaN
1   PIT_NEXT_LAP     27.0  INTERMEDIATE
2  PIT_IN_2_LAPS     28.0  INTERMEDIATE
3  PIT_IN_3_LAPS     29.0  INTERMEDIATE

Status: decision state and candidate actions created. No strategy has been declared optimal.

In [ ]:
# Cell 45: Build a transparent strategy comparison table

import pandas as pd

TOTAL_LAPS = int(sim_state["lap_number"].max())

decision_lap = int(decision["decision_lap"])
next_lap = decision_lap + 1
laps_remaining = TOTAL_LAPS - decision_lap

target = decision["target_state"]

if isinstance(target, pd.Series):
    target_row = target
else:
    target_row = target.iloc[0]

current_compound = target_row["compound"]
current_tyre_age = int(target_row["tyre_age"])

strategies = pd.DataFrame([
    {
        "strategy": "Stay out",
        "pit_lap": None,
        "planned_compound": current_compound,
        "decision": "Continue on current tyres",
    },
    {
        "strategy": "Pit next lap",
        "pit_lap": next_lap,
        "planned_compound": "INTERMEDIATE",
        "decision": "Switch to Intermediates",
    },
    {
        "strategy": "Pit in 2 laps",
        "pit_lap": next_lap + 1,
        "planned_compound": "INTERMEDIATE",
        "decision": "Delay the stop by 1 lap",
    },
    {
        "strategy": "Pit in 3 laps",
        "pit_lap": next_lap + 2,
        "planned_compound": "INTERMEDIATE",
        "decision": "Delay the stop by 2 laps",
    },
])

strategies["decision_after_lap"] = decision_lap
strategies["laps_remaining_at_decision"] = laps_remaining
strategies["current_compound"] = current_compound
strategies["current_tyre_age"] = current_tyre_age

print(f"Driver: #{int(target_row['driver_number'])}")
print(f"Position: P{int(target_row['position'])}")
print(f"Decision after lap: {decision_lap}")
print(f"Laps remaining: {laps_remaining}")
print(f"Current tyres: {current_compound}, age {current_tyre_age}")
print("\nCandidate strategies:")

display(strategies)

Driver: #63
Position: P4
Decision after lap: 26
Laps remaining: 26
Current tyres: MEDIUM, age 25

Candidate strategies:

,strategy,pit_lap,planned_compound,decision,decision_after_lap,laps_remaining_at_decision,current_compound,current_tyre_age
0,Stay out,NaN,MEDIUM,Continue on current tyres,26,26,MEDIUM,25
1,Pit next lap,27.0,INTERMEDIATE,Switch to Intermediates,26,26,MEDIUM,25
2,Pit in 2 laps,28.0,INTERMEDIATE,Delay the stop by 1 lap,26,26,MEDIUM,25
3,Pit in 3 laps,29.0,INTERMEDIATE,Delay the stop by 2 laps,26,26,MEDIUM,25

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

# ==========================================
# PITWALL: CANDIDATE STRATEGY EVALUATION
# ==========================================

DRIVER_NUMBER = 63
CURRENT_LAP = 26
TOTAL_LAPS = 52
CURRENT_POSITION = 4

CURRENT_COMPOUND = "MEDIUM"
CURRENT_TYRE_AGE = 25

# Candidate strategies
candidates = pd.DataFrame([
    {
        "strategy": "Stay out",
        "pit_lap": None,
        "planned_compound": "MEDIUM",
    },
    {
        "strategy": "Pit next lap",
        "pit_lap": 27,
        "planned_compound": "INTERMEDIATE",
    },
    {
        "strategy": "Pit in 2 laps",
        "pit_lap": 28,
        "planned_compound": "INTERMEDIATE",
    },
    {
        "strategy": "Pit in 3 laps",
        "pit_lap": 29,
        "planned_compound": "INTERMEDIATE",
    },
])

candidates["decision_after_lap"] = CURRENT_LAP
candidates["laps_remaining"] = TOTAL_LAPS - CURRENT_LAP
candidates["current_compound"] = CURRENT_COMPOUND
candidates["current_tyre_age"] = CURRENT_TYRE_AGE

# ==========================================
# 1. Load the race-state dataset
# ==========================================

DATA_PATH = Path("../data/processed/9558/lap_performance.parquet")

if not DATA_PATH.exists():
    raise FileNotFoundError(
        f"Dataset not found: {DATA_PATH.resolve()}\n"
        "Update DATA_PATH to your actual processed dataset."
    )

df = pd.read_parquet(DATA_PATH)

# Inspect available columns before proceeding
print("Dataset shape:", df.shape)
print("Available columns:", df.columns.tolist())

# ==========================================
# 2. Extract the current driver's race state
# ==========================================

# ==========================================
# 2. EXTRACT THE CURRENT DRIVER'S LAP STATE
# ==========================================

required_columns = [
    "driver_number",
    "lap_number",
    "compound",
    "tyre_age",
    "lap_duration",
]

missing = [
    col for col in required_columns
    if col not in df.columns
]

if missing:
    raise KeyError(f"Missing columns: {missing}")

state = df[
    (df["driver_number"] == DRIVER_NUMBER)
    & (df["lap_number"] == CURRENT_LAP)
].copy()

if state.empty:
    raise ValueError(
        f"No record found for driver #{DRIVER_NUMBER} "
        f"on lap {CURRENT_LAP}."
    )

state = state.iloc[-1]

print("\nCURRENT DRIVER LAP STATE")
print(state.to_string())

print("\nRace position: P4 (provided by strategy decision)")
print("Current compound:", state["compound"])
print("Current tyre age:", state["tyre_age"])
print("Lap duration:", state["lap_duration"])


# ==========================================
# 3. Validate the candidate strategies
# ==========================================

def validate_strategy(row):
    pit_lap = row["pit_lap"]

    if pd.isna(pit_lap):
        return "Continue on current tyres"

    if pit_lap <= CURRENT_LAP:
        return "Invalid: pit lap must be in the future"

    if pit_lap > TOTAL_LAPS:
        return "Invalid: pit lap exceeds race distance"

    return "Valid candidate; check weather and tyre rules"

candidates["validation"] = candidates.apply(
    validate_strategy, axis=1
)

# ==========================================
# 4. Display the comparison table
# ==========================================

print("\nCANDIDATE STRATEGIES")
display(candidates)

print(
    "\nNext step: score each candidate using the trained "
    "lap-time model, weather forecasts, pit-loss estimates, "
    "traffic, and competitor race states."
)

Dataset shape: (962, 19)
Available columns: ['meeting_key', 'session_key', 'driver_number', 'lap_number', 'date_start', 'duration_sector_1', 'duration_sector_2', 'duration_sector_3', 'i1_speed', 'i2_speed', 'is_pit_out_lap', 'lap_duration', 'segments_sector_1', 'segments_sector_2', 'segments_sector_3', 'st_speed', 'stint_number', 'compound', 'tyre_age']

CURRENT DRIVER LAP STATE
meeting_key                                                       1240
session_key                                                       9558
driver_number                                                       63
lap_number                                                          26
date_start                            2024-07-07 14:41:59.699000+00:00
duration_sector_1                                               30.082
duration_sector_2                                               41.323
duration_sector_3                                               28.544
i1_speed                                                           NaN
i2_speed                                                         252.0
is_pit_out_lap                                                   False
lap_duration                                                    99.949
segments_sector_1    [nan, 2048.0, 2048.0, 2048.0, 2048.0, 2048.0, ...
segments_sector_2    [2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...
segments_sector_3     [2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]
st_speed                                                         304.0
stint_number                                                       1.0
compound                                                        MEDIUM
tyre_age                                                          25.0

Race position: P4 (provided by strategy decision)
Current compound: MEDIUM
Current tyre age: 25.0
Lap duration: 99.949

CANDIDATE STRATEGIES

,strategy,pit_lap,planned_compound,decision_after_lap,laps_remaining,current_compound,current_tyre_age,validation
0,Stay out,NaN,MEDIUM,26,26,MEDIUM,25,Continue on current tyres
1,Pit next lap,27.0,INTERMEDIATE,26,26,MEDIUM,25,Valid candidate; check weather and tyre rules
2,Pit in 2 laps,28.0,INTERMEDIATE,26,26,MEDIUM,25,Valid candidate; check weather and tyre rules
3,Pit in 3 laps,29.0,INTERMEDIATE,26,26,MEDIUM,25,Valid candidate; check weather and tyre rules

Next step: score each candidate using the trained lap-time model, weather forecasts, pit-loss estimates, traffic, and competitor race states.

In [ ]:

from pathlib import Path

for root in [Path("../data"), Path("data"), Path("..")]:
    if root.exists():
        print(f"\nSearching: {root.resolve()}")
        for path in root.rglob("*"):
            if path.is_file() and path.suffix.lower() in {
                ".parquet", ".csv", ".pkl", ".joblib"
            }:
                print(path)

Searching: C:\Users\Nihan\.vscode\pitwall\data
..\data\processed\9558\fuel_features.parquet
..\data\processed\9558\laps.parquet
..\data\processed\9558\lap_performance.parquet
..\data\processed\9558\position.parquet
..\data\processed\9558\race_control.parquet
..\data\processed\9558\race_state.parquet
..\data\processed\9558\stints.parquet
..\data\processed\9558\traffic_features.parquet
..\data\processed\9558\tyre_features.parquet
..\data\processed\9558\weather.parquet
..\data\processed\9558\car_data\1.parquet
..\data\processed\9558\car_data\10.parquet
..\data\processed\9558\car_data\11.parquet
..\data\processed\9558\car_data\14.parquet
..\data\processed\9558\car_data\16.parquet
..\data\processed\9558\car_data\18.parquet
..\data\processed\9558\car_data\2.parquet
..\data\processed\9558\car_data\20.parquet
..\data\processed\9558\car_data\22.parquet
..\data\processed\9558\car_data\23.parquet
..\data\processed\9558\car_data\24.parquet
..\data\processed\9558\car_data\27.parquet
..\data\processed\9558\car_data\3.parquet
..\data\processed\9558\car_data\31.parquet
..\data\processed\9558\car_data\4.parquet
..\data\processed\9558\car_data\44.parquet
..\data\processed\9558\car_data\55.parquet
..\data\processed\9558\car_data\63.parquet
..\data\processed\9558\car_data\77.parquet
..\data\processed\9558\car_data\81.parquet

Searching: C:\Users\Nihan\.vscode\pitwall
..\models\pace_xgb_weather.joblib
..\models\pace_xgb_weather_features.joblib
..\data\processed\9558\fuel_features.parquet
..\data\processed\9558\laps.parquet
..\data\processed\9558\lap_performance.parquet
..\data\processed\9558\position.parquet
..\data\processed\9558\race_control.parquet
..\data\processed\9558\race_state.parquet
..\data\processed\9558\stints.parquet
..\data\processed\9558\traffic_features.parquet
..\data\processed\9558\tyre_features.parquet
..\data\processed\9558\weather.parquet
..\data\processed\9558\car_data\1.parquet
..\data\processed\9558\car_data\10.parquet
..\data\processed\9558\car_data\11.parquet
..\data\processed\9558\car_data\14.parquet
..\data\processed\9558\car_data\16.parquet
..\data\processed\9558\car_data\18.parquet
..\data\processed\9558\car_data\2.parquet
..\data\processed\9558\car_data\20.parquet
..\data\processed\9558\car_data\22.parquet
..\data\processed\9558\car_data\23.parquet
..\data\processed\9558\car_data\24.parquet
..\data\processed\9558\car_data\27.parquet
..\data\processed\9558\car_data\3.parquet
..\data\processed\9558\car_data\31.parquet
..\data\processed\9558\car_data\4.parquet
..\data\processed\9558\car_data\44.parquet
..\data\processed\9558\car_data\55.parquet
..\data\processed\9558\car_data\63.parquet
..\data\processed\9558\car_data\77.parquet
..\data\processed\9558\car_data\81.parquet

In [ ]:

from pathlib import Path
import pandas as pd

# ==========================================
# PITWALL: INSPECT STRATEGY INPUT ASSETS
# ==========================================

DATA_DIR = Path("../data/processed/9558")

assets = [
    "position.parquet",
    "race_state.parquet",
    "weather.parquet",
    "tyre_features.parquet",
    "traffic_features.parquet",
    "fuel_features.parquet",
    "race_control.parquet",
    "stints.parquet",
]

for filename in assets:
    path = DATA_DIR / filename

    print("\n" + "=" * 75)
    print(filename)

    if not path.exists():
        print("FILE NOT FOUND")
        continue

    temp = pd.read_parquet(path)

    print("Shape:", temp.shape)
    print("Columns:", temp.columns.tolist())

    # Show the current driver's lap 26 record where possible
    if {"driver_number", "lap_number"}.issubset(temp.columns):
        sample = temp[
            (temp["driver_number"] == 63)
            & (temp["lap_number"] == 26)
        ]
        print("Driver 63, lap 26:")
        print(sample.head(2).to_string(index=False))

    else:
        print("Sample rows:")
        print(temp.head(2).to_string(index=False))

# ==========================================
# FIND SAVED MODEL FILES
# ==========================================

print("\n" + "=" * 75)
print("MODEL AND ARTIFACT FILES")

PROJECT_DIR = Path("..")

for folder in ["models", "artifacts", "backend"]:
    root = PROJECT_DIR / folder

    if root.exists():
        print(f"\n{root.resolve()}")

        for path in root.rglob("*"):
            if path.is_file() and path.suffix.lower() in {
                ".pkl", ".joblib", ".json", ".ubj", ".model"
            }:
                print(path)

===========================================================================
position.parquet
Shape: (252, 5)
Columns: ['date', 'session_key', 'driver_number', 'position', 'meeting_key']
Sample rows:
                            date  session_key  driver_number  position  meeting_key
2024-07-07 13:05:02.926000+00:00         9558              1         4         1240
2024-07-07 13:05:02.926000+00:00         9558              2        12         1240

===========================================================================
race_state.parquet
Shape: (962, 23)
Columns: ['driver_number', 'lap_number', 'date_start', 'lap_duration', 'compound', 'tyre_age', 'stint_number', 'is_pit_out_lap', 'position', 'session_key', 'meeting_key', 'track_temperature', 'wind_speed', 'rainfall', 'humidity', 'pressure', 'air_temperature', 'wind_direction', 'weather_age_seconds', 'drs_available', 'grip_condition', 'blue_flag', 'date']
Driver 63, lap 26:
 driver_number  lap_number                       date_start  lap_duration compound  tyre_age  stint_number  is_pit_out_lap  position  session_key  meeting_key  track_temperature  wind_speed  rainfall  humidity  pressure  air_temperature  wind_direction  weather_age_seconds drs_available grip_condition blue_flag date
            63          26 2024-07-07 14:41:59.699000+00:00        99.949   MEDIUM      25.0           1.0           False       4.0       9558.0       1240.0               22.0         0.8       1.0      69.0     992.2             15.1           267.0               56.971         False            LOW     False  NaT

===========================================================================
weather.parquet
Shape: (147, 10)
Columns: ['date', 'session_key', 'meeting_key', 'track_temperature', 'wind_speed', 'rainfall', 'humidity', 'pressure', 'air_temperature', 'wind_direction']
Sample rows:
                            date  session_key  meeting_key  track_temperature  wind_speed  rainfall  humidity  pressure  air_temperature  wind_direction
2024-07-07 13:05:02.119000+00:00         9558         1240               28.1         2.2         0      67.0     991.8             15.9             226
2024-07-07 13:06:02.098000+00:00         9558         1240               27.6         1.5         0      66.0     991.7             15.9             268

===========================================================================
tyre_features.parquet
Shape: (650, 4)
Columns: ['driver_number', 'lap_number', 'tyre_age', 'tyre_degradation_effect']
Driver 63, lap 26:
 driver_number  lap_number  tyre_age  tyre_degradation_effect
            63          26      25.0                  5.38111

===========================================================================
traffic_features.parquet
Shape: (962, 6)
Columns: ['driver_number', 'lap_number', 'position', 'traffic_ahead', 'traffic_behind', 'position_change']
Driver 63, lap 26:
 driver_number  lap_number  position  traffic_ahead  traffic_behind  position_change
            63          26         4              1               0              0.0

===========================================================================
fuel_features.parquet
Shape: (692, 3)
Columns: ['driver_number', 'lap_number', 'fuel_effect']
Driver 63, lap 26:
 driver_number  lap_number  fuel_effect
            63          26    -2.103049

===========================================================================
race_control.parquet
Shape: (110, 11)
Columns: ['meeting_key', 'session_key', 'date', 'driver_number', 'lap_number', 'category', 'flag', 'scope', 'sector', 'qualifying_phase', 'message']
Driver 63, lap 26:
Empty DataFrame
Columns: [meeting_key, session_key, date, driver_number, lap_number, category, flag, scope, sector, qualifying_phase, message]
Index: []

===========================================================================
stints.parquet
Shape: (65, 8)
Columns: ['meeting_key', 'session_key', 'stint_number', 'driver_number', 'lap_start', 'lap_end', 'compound', 'tyre_age_at_start']
Sample rows:
 meeting_key  session_key  stint_number  driver_number  lap_start  lap_end     compound  tyre_age_at_start
        1240         9558             1              1        1.0     26.0       MEDIUM                  0
        1240         9558             2              1       27.0     38.0 INTERMEDIATE                  0

===========================================================================
MODEL AND ARTIFACT FILES

C:\Users\Nihan\.vscode\pitwall\models
..\models\pace_xgb_weather.joblib
..\models\pace_xgb_weather_features.joblib

C:\Users\Nihan\.vscode\pitwall\backend

In [ ]:

# CELL 56 — PITWALL STRATEGY SIMULATOR
# Compare candidate pit timings over the remaining race.

from pathlib import Path
import numpy as np
import pandas as pd

# ------------------------------------------
# 1. Race decision state
# ------------------------------------------

DATA_DIR = Path("../data/processed/9558")

DRIVER = 63
CURRENT_LAP = 26
TOTAL_LAPS = 52
CURRENT_POSITION = 4

CURRENT_COMPOUND = "MEDIUM"
CURRENT_TYRE_AGE = 25

CANDIDATES = [
    {"strategy": "Stay out", "pit_lap": None,
     "compound": "MEDIUM"},
    {"strategy": "Pit lap 27", "pit_lap": 27,
     "compound": "INTERMEDIATE"},
    {"strategy": "Pit lap 28", "pit_lap": 28,
     "compound": "INTERMEDIATE"},
    {"strategy": "Pit lap 29", "pit_lap": 29,
     "compound": "INTERMEDIATE"},
]

# Replace this with your measured pit-lane loss if available.
# It must represent the additional time lost versus staying
# on track, not the entire pit-lap duration.
PIT_LOSS_SECONDS = 22.0

# ------------------------------------------
# 2. Load the frozen race-state assets
# ------------------------------------------

race = pd.read_parquet(DATA_DIR / "race_state.parquet")
tyres = pd.read_parquet(DATA_DIR / "tyre_features.parquet")

race = race[
    (race["session_key"] == 9558)
    & (race["lap_number"] > CURRENT_LAP)
    & (race["lap_number"] <= TOTAL_LAPS)
].copy()

# Use historical observed conditions as a provisional
# scenario, not as a claim about future weather.
driver_future = race[
    race["driver_number"] == DRIVER
].copy()

if driver_future.empty:
    raise ValueError("No future race-state rows for Driver 63.")

# ------------------------------------------
# 3. Build provisional lap-time scenarios
# ------------------------------------------

# The validated compound-median baseline has lower MAE
# than Ridge for INTERMEDIATE tyres in your evaluation.
# Use historical compound/tyre-age medians as a transparent
# fallback, rather than extrapolating Ridge to unsupported
# compound conditions.

historical = pd.read_parquet(DATA_DIR / "race_state.parquet")

# Exclude pit-out laps from ordinary running-lap baselines.
historical = historical[
    historical["lap_duration"].notna()
    & (~historical["is_pit_out_lap"].fillna(False))
].copy()

compound_age_baseline = (
    historical.groupby(
        ["compound", "tyre_age"], dropna=True
    )["lap_duration"]
    .median()
)

compound_baseline = (
    historical.groupby("compound")["lap_duration"]
    .median()
)

def baseline_lap_time(compound, tyre_age):
    key = (compound, tyre_age)

    if key in compound_age_baseline.index:
        return float(compound_age_baseline.loc[key])

    if compound in compound_baseline.index:
        return float(compound_baseline.loc[compound])

    raise ValueError(
        f"No historical baseline for compound {compound}"
    )

# ------------------------------------------
# 4. Simulate each candidate
# ------------------------------------------

results = []

for candidate in CANDIDATES:
    pit_lap = candidate["pit_lap"]
    compound_after_stop = candidate["compound"]

    projected_time = 0.0
    tyre_age = CURRENT_TYRE_AGE
    current_compound = CURRENT_COMPOUND
    pit_loss_added = False
    simulated_laps = []

    for lap in range(CURRENT_LAP + 1, TOTAL_LAPS + 1):

        # A pit on lap N means the driver runs that lap on
        # the old tyres, then changes compound for lap N+1.
        if pit_lap is not None and lap > pit_lap:
            current_compound = compound_after_stop
            if not pit_loss_added:
                projected_time += PIT_LOSS_SECONDS
                pit_loss_added = True
                tyre_age = 0

        tyre_age += 1

        lap_time = baseline_lap_time(
            current_compound, tyre_age
        )

        projected_time += lap_time

        simulated_laps.append({
            "lap": lap,
            "compound": current_compound,
            "tyre_age": tyre_age,
            "baseline_lap_time": lap_time,
        })

    results.append({
        "strategy": candidate["strategy"],
        "pit_lap": pit_lap,
        "planned_compound": compound_after_stop,
        "projected_remaining_time_s": projected_time,
        "pit_loss_s": (
            PIT_LOSS_SECONDS if pit_lap is not None else 0.0
        ),
        "simulated_laps": simulated_laps,
    })

# ------------------------------------------
# 5. Compare strategies
# ------------------------------------------

comparison = pd.DataFrame([
    {k: v for k, v in row.items()
     if k != "simulated_laps"}
    for row in results
])

comparison["difference_vs_best_s"] = (
    comparison["projected_remaining_time_s"]
    - comparison["projected_remaining_time_s"].min()
)

comparison = comparison.sort_values(
    "projected_remaining_time_s"
).reset_index(drop=True)

display(comparison)

print(
    "IMPORTANT: These are provisional compound/age baseline "
    "scenarios, not calibrated forecasts or win probabilities. "
    "The fixed pit loss and historical weather assumptions "
    "must be replaced with the existing strategy inputs before "
    "using this ranking as a race recommendation."
)

,strategy,pit_lap,planned_compound,projected_remaining_time_s,pit_loss_s,difference_vs_best_s
0,Stay out,NaN,MEDIUM,2447.2580,0.0,0.0000
1,Pit lap 29,29.0,INTERMEDIATE,2695.1675,22.0,247.9095
2,Pit lap 27,27.0,INTERMEDIATE,2695.4930,22.0,248.2350
3,Pit lap 28,28.0,INTERMEDIATE,2705.4400,22.0,258.1820

IMPORTANT: These are provisional compound/age baseline scenarios, not calibrated forecasts or win probabilities. The fixed pit loss and historical weather assumptions must be replaced with the existing strategy inputs before using this ranking as a race recommendation.

In [ ]:

# CELL 57 — WEATHER-AWARE LAP-TIME BASELINE

historical = pd.read_parquet(DATA_DIR / "race_state.parquet")

historical = historical[
    historical["lap_duration"].notna()
    & (~historical["is_pit_out_lap"].fillna(False))
].copy()

# Normalize categorical weather conditions
historical["compound"] = historical["compound"].str.upper()
historical["grip_condition"] = (
    historical["grip_condition"].fillna("UNKNOWN").astype(str)
)

# Keep exact age only when sufficiently supported
MIN_GROUP_ROWS = 5

weather_baseline = (
    historical.groupby(
        ["compound", "rainfall", "grip_condition"],
        dropna=False
    )["lap_duration"]
    .agg(["median", "count"])
    .reset_index()
)

print("WEATHER-AWARE BASELINE COVERAGE")
display(
    weather_baseline.sort_values(
        ["compound", "rainfall", "grip_condition"]
    )
)

def weather_aware_baseline(compound, rainfall, grip):
    subset = historical[
        (historical["compound"] == compound)
        & (historical["rainfall"] == rainfall)
        & (historical["grip_condition"] == grip)
    ]

    if len(subset) >= MIN_GROUP_ROWS:
        return float(subset["lap_duration"].median()), "compound+weather+grip"

    subset = historical[
        (historical["compound"] == compound)
        & (historical["rainfall"] == rainfall)
    ]

    if len(subset) >= MIN_GROUP_ROWS:
        return float(subset["lap_duration"].median()), "compound+weather"

    subset = historical[
        historical["compound"] == compound
    ]

    if len(subset) >= MIN_GROUP_ROWS:
        return float(subset["lap_duration"].median()), "compound-only fallback"

    return np.nan, "insufficient data"

# Inspect the current decision-state conditions
current = pd.read_parquet(DATA_DIR / "race_state.parquet")

current = current[
    (current["driver_number"] == DRIVER)
    & (current["lap_number"] == CURRENT_LAP)
    & (current["session_key"] == 9558)
]

if current.empty:
    raise ValueError("Current decision state not found.")

current = current.iloc[0]

for compound in ["MEDIUM", "INTERMEDIATE"]:
    estimate, method = weather_aware_baseline(
        compound,
        current["rainfall"],
        current["grip_condition"]
    )

    print(
        f"{compound}: {estimate:.3f}s | method={method}"
        if pd.notna(estimate)
        else f"{compound}: unavailable | method={method}"
    )

WEATHER-AWARE BASELINE COVERAGE

        compound  rainfall grip_condition    median  count
0           HARD       0.0            LOW   90.0560      3
1           HARD       0.0         NORMAL   89.4410     18
2           HARD       0.0        UNKNOWN   92.7090     17
3           HARD       1.0            LOW  101.8680      1
4           HARD       1.0         NORMAL   89.3630      2
5   INTERMEDIATE       0.0            LOW   99.4400      1
6   INTERMEDIATE       1.0            LOW  103.0035    206
7   INTERMEDIATE       1.0         NORMAL  110.4050      4
8         MEDIUM       0.0            LOW   90.7150      9
9         MEDIUM       0.0         NORMAL   90.1310     52
10        MEDIUM       0.0        UNKNOWN   92.7090    292
11        MEDIUM       1.0            LOW   94.4940     97
12        MEDIUM       1.0         NORMAL   94.3070     35
13        MEDIUM       1.0        UNKNOWN  104.0900     15
14          SOFT       0.0            LOW   91.7760     16
15          SOFT       0.0         NORMAL   90.8620    102
16          SOFT       0.0        UNKNOWN   94.0710     29
17          SOFT       1.0            LOW  101.7310      1
18          SOFT       1.0         NORMAL   90.8820     13
19          SOFT       1.0        UNKNOWN   98.4970      1

MEDIUM: 94.494s | method=compound+weather+grip
INTERMEDIATE: 103.004s | method=compound+weather+grip

In [ ]:
# Cell 58: Compare compound pace by tyre age in current conditions

historical = pd.read_parquet(DATA_DIR / "race_state.parquet")

historical = historical[
    (historical["session_key"] == 9558)
    & historical["lap_duration"].notna()
    & (~historical["is_pit_out_lap"].fillna(False))
    & (historical["rainfall"] == 1.0)
    & (historical["grip_condition"] == "LOW")
].copy()

historical["compound"] = historical["compound"].str.upper()

historical["tyre_age_band"] = pd.cut(
    historical["tyre_age"],
    bins=[-1, 5, 10, 15, 20, 30, 100],
    labels=["0-5", "6-10", "11-15", "16-20", "21-30", "31+"]
)

pace_by_age = (
    historical.groupby(
        ["compound", "tyre_age_band"],
        observed=True
    )["lap_duration"]
    .agg(["median", "count"])
    .reset_index()
)

display(
    pace_by_age.pivot(
        index="tyre_age_band",
        columns="compound",
        values="median"
    )
)

display(
    pace_by_age.pivot(
        index="tyre_age_band",
        columns="compound",
        values="count"
    ).fillna(0).astype(int)
)

compound          HARD  INTERMEDIATE    MEDIUM     SOFT
tyre_age_band
16-20          101.868           NaN   95.6755  101.731
0-5                NaN       103.157  107.4320      NaN
6-10               NaN       102.995  106.3130      NaN
11-15              NaN        97.502       NaN      NaN
21-30              NaN           NaN   93.1060      NaN

compound       HARD  INTERMEDIATE  MEDIUM  SOFT
tyre_age_band
16-20             1             0      32     1
0-5               0           107       3     0
6-10              0            91       1     0
11-15             0             8       0     0
21-30             0             0      61     0

In [39]:

# Cell 59: PITWALL strategy simulator v1
# Purpose: compare candidate strategies using historical wet/low-grip pace.
# This is a scenario model, not yet a calibrated race-outcome predictor.

import numpy as np
import pandas as pd
from pathlib import Path

DATA_DIR = Path("../data/processed/9558")

DRIVER = 63
SESSION = 9558
CURRENT_LAP = 26
TOTAL_LAPS = 52
CURRENT_POSITION = 4
CURRENT_COMPOUND = "MEDIUM"
CURRENT_TYRE_AGE = 25

# Explicit assumptions: test several pit-loss values rather than hiding uncertainty.
PIT_LOSS_SCENARIOS = [18.0, 22.0, 26.0]

CANDIDATES = [
    {"strategy": "Stay out", "pit_lap": None, "compound": "MEDIUM"},
    {"strategy": "Pit lap 27", "pit_lap": 27, "compound": "INTERMEDIATE"},
    {"strategy": "Pit lap 28", "pit_lap": 28, "compound": "INTERMEDIATE"},
    {"strategy": "Pit lap 29", "pit_lap": 29, "compound": "INTERMEDIATE"},
]

race = pd.read_parquet(DATA_DIR / "race_state.parquet")

# Use historical observations from this session in wet, low-grip conditions.
hist = race[
    (race["session_key"] == SESSION)
    & race["lap_duration"].notna()
    & (~race["is_pit_out_lap"].fillna(False))
    & (race["rainfall"] == 1.0)
    & (race["grip_condition"] == "LOW")
].copy()

hist["compound"] = hist["compound"].str.upper()
hist = hist[hist["tyre_age"].notna() & (hist["tyre_age"] >= 0)]

# Use tyre-age bands to avoid pretending every exact age has enough observations.
AGE_BINS = [-1, 5, 10, 15, 20, 30, 100]
AGE_LABELS = ["0-5", "6-10", "11-15", "16-20", "21-30", "31+"]

hist["age_band"] = pd.cut(
    hist["tyre_age"],
    bins=AGE_BINS,
    labels=AGE_LABELS
)

pace_table = (
    hist.groupby(["compound", "age_band"], observed=True)["lap_duration"]
    .agg(["median", "count"])
    .reset_index()
)

# Anchor the current compound's age band to the actual decision-point lap time.
current_row = race[
    (race["session_key"] == SESSION)
    & (race["driver_number"] == DRIVER)
    & (race["lap_number"] == CURRENT_LAP)
]

if current_row.empty:
    raise ValueError("Could not find driver #63 at the decision lap.")

current_row = current_row.iloc[0]
CURRENT_LAP_TIME = float(current_row["lap_duration"])

def age_band(age):
    for upper, label in zip([5, 10, 15, 20, 30, 100], AGE_LABELS):
        if age <= upper:
            return label
    return "31+"

def empirical_pace(compound, age):
    """Return the historical median for compound/age band.
    Fall back to the nearest available age band for that compound.
    """
    band = age_band(age)
    rows = pace_table[
        (pace_table["compound"] == compound)
        & (pace_table["age_band"] == band)
    ]

    if not rows.empty:
        row = rows.iloc[0]
        return float(row["median"]), int(row["count"]), band

    available = pace_table[
        (pace_table["compound"] == compound)
        & (pace_table["count"] >= 5)
    ].copy()

    if available.empty:
        raise ValueError(
            f"No usable historical pace observations for {compound}."
        )

    # Find the closest available tyre-age band.
    band_midpoint = {
        "0-5": 2.5, "6-10": 8, "11-15": 13,
        "16-20": 18, "21-30": 25.5, "31+": 35
    }
    available["distance"] = available["age_band"].astype(str).map(
        lambda x: abs(band_midpoint[x] - age)
    )
    row = available.sort_values("distance").iloc[0]
    return float(row["median"]), int(row["count"]), str(row["age_band"])

# Align the Medium historical pace curve to the actual observed lap at lap 26.
medium_hist, _, _ = empirical_pace("MEDIUM", CURRENT_TYRE_AGE)
medium_anchor_adjustment = CURRENT_LAP_TIME - medium_hist

def projected_lap_time(compound, age):
    pace, count, source_band = empirical_pace(compound, age)

    # Preserve the target driver's current pace level for the Medium curve.
    # Intermediate pace remains a historical estimate, not an XGBoost prediction.
    if compound == "MEDIUM":
        pace += medium_anchor_adjustment

    return pace, count, source_band

def simulate(candidate, pit_loss):
    pit_lap = candidate["pit_lap"]
    new_compound = candidate["compound"]

    compound = CURRENT_COMPOUND
    tyre_age = CURRENT_TYRE_AGE
    total_time = 0.0
    pit_loss_added = False
    lap_records = []

    for lap in range(CURRENT_LAP + 1, TOTAL_LAPS + 1):

        # The driver completes the pit-in lap on the current tyres.
        if pit_lap is not None and lap == pit_lap:
            tyre_age += 1
            lap_time, n, band = projected_lap_time(compound, tyre_age)
            total_time += lap_time + pit_loss
            pit_loss_added = True

            lap_records.append({
                "lap": lap,
                "compound": compound,
                "tyre_age": tyre_age,
                "estimated_lap_time": lap_time,
                "pit_loss": pit_loss,
                "pace_sample_count": n,
                "pace_age_band": band
            })

            # New tyres are fitted after the pit-in lap.
            compound = new_compound
            tyre_age = 0
            continue

        tyre_age += 1
        lap_time, n, band = projected_lap_time(compound, tyre_age)
        total_time += lap_time

        lap_records.append({
            "lap": lap,
            "compound": compound,
            "tyre_age": tyre_age,
            "estimated_lap_time": lap_time,
            "pit_loss": 0.0,
            "pace_sample_count": n,
            "pace_age_band": band
        })

    return total_time, lap_records

results = []
details = {}

for pit_loss in PIT_LOSS_SCENARIOS:
    scenario_results = []

    for candidate in CANDIDATES:
        total, laps = simulate(candidate, pit_loss)
        scenario_results.append({
            "pit_loss_assumption_s": pit_loss,
            "strategy": candidate["strategy"],
            "pit_lap": candidate["pit_lap"],
            "new_compound": candidate["compound"],
            "projected_remaining_time_s": round(total, 2),
        })
        details[(pit_loss, candidate["strategy"])] = pd.DataFrame(laps)

    best_time = min(x["projected_remaining_time_s"] for x in scenario_results)

    for result in scenario_results:
        result["gap_to_best_s"] = round(
            result["projected_remaining_time_s"] - best_time, 2
        )
        results.append(result)

comparison = pd.DataFrame(results)

display(
    comparison.sort_values(
        ["pit_loss_assumption_s", "projected_remaining_time_s"]
    ).reset_index(drop=True)
)

print(
    f"Decision: after lap {CURRENT_LAP}, driver #{DRIVER}, "
    f"P{CURRENT_POSITION}, current lap time {CURRENT_LAP_TIME:.3f}s."
)
print(
    "Important: these are conditional scenario estimates. "
    "They do not yet simulate rival strategies or predict a finishing position."
)

,pit_loss_assumption_s,strategy,pit_lap,new_compound,projected_remaining_time_s,gap_to_best_s
0,18.0,Stay out,NaN,MEDIUM,2598.67,0.00
1,18.0,Pit lap 27,27.0,INTERMEDIATE,2611.24,12.57
2,18.0,Pit lap 28,28.0,INTERMEDIATE,2613.69,15.02
3,18.0,Pit lap 29,29.0,INTERMEDIATE,2616.13,17.46
4,22.0,Stay out,NaN,MEDIUM,2598.67,0.00
5,22.0,Pit lap 27,27.0,INTERMEDIATE,2615.24,16.57
6,22.0,Pit lap 28,28.0,INTERMEDIATE,2617.69,19.02
7,22.0,Pit lap 29,29.0,INTERMEDIATE,2620.13,21.46
8,26.0,Stay out,NaN,MEDIUM,2598.67,0.00
9,26.0,Pit lap 27,27.0,INTERMEDIATE,2619.24,20.57
10,26.0,Pit lap 28,28.0,INTERMEDIATE,2621.69,23.02
11,26.0,Pit lap 29,29.0,INTERMEDIATE,2624.13,25.46

Decision: after lap 26, driver #63, P4, current lap time 99.949s.
Important: these are conditional scenario estimates. They do not yet simulate rival strategies or predict a finishing position.

In [40]:

# Cell 60: Full-field strategy comparison
# Baseline assumption: rivals continue on their current compounds.
# Target driver #63 is evaluated under each candidate strategy.

PIT_LOSS = 22.0  # Assumption in seconds; change for sensitivity testing.

field = race[
    (race["session_key"] == SESSION)
    & (race["lap_number"] == CURRENT_LAP)
].copy()

field = field[
    field["position"].notna()
    & field["compound"].notna()
    & field["tyre_age"].notna()
].copy()

field["compound"] = field["compound"].str.upper()

# Elapsed time through the decision lap, using observed lap times.
elapsed = (
    race[
        (race["session_key"] == SESSION)
        & (race["lap_number"] <= CURRENT_LAP)
        & race["lap_duration"].notna()
    ]
    .groupby("driver_number")["lap_duration"]
    .sum()
    .rename("elapsed_time_s")
)

field = field.merge(elapsed, on="driver_number", how="left")
field = field.dropna(subset=["elapsed_time_s"])

def project_driver_remaining(compound, tyre_age, driver_number,
                             strategy_compound=None, pit_lap=None):
    total = 0.0
    age = int(tyre_age)
    active_compound = str(compound).upper()

    for lap in range(CURRENT_LAP + 1, TOTAL_LAPS + 1):
        if pit_lap is not None and lap == pit_lap:
            # Complete pit-in lap on the old tyres, then add pit loss.
            age += 1
            lap_time, _, _ = projected_lap_time(active_compound, age)
            total += lap_time + PIT_LOSS

            active_compound = strategy_compound
            age = 0
            continue

        age += 1
        lap_time, _, _ = projected_lap_time(active_compound, age)
        total += lap_time

    return total

# Project every rival under the baseline of no further pit stops.
baseline_remaining = {}

for _, row in field.iterrows():
    number = int(row["driver_number"])
    baseline_remaining[number] = project_driver_remaining(
        compound=row["compound"],
        tyre_age=row["tyre_age"],
        driver_number=number
    )

# Replace driver #63's baseline with each candidate strategy.
strategy_rows = []

for candidate in CANDIDATES:
    target_number = DRIVER
    target_row = field[field["driver_number"] == target_number]

    if target_row.empty:
        raise ValueError("Driver #63 is missing from the lap-26 field.")

    target_row = target_row.iloc[0]

    target_remaining = project_driver_remaining(
        compound=target_row["compound"],
        tyre_age=target_row["tyre_age"],
        driver_number=target_number,
        strategy_compound=candidate["compound"],
        pit_lap=candidate["pit_lap"]
    )

    projected = []

    for _, row in field.iterrows():
        number = int(row["driver_number"])
        remaining = (
            target_remaining
            if number == target_number
            else baseline_remaining[number]
        )

        projected.append({
            "driver_number": number,
            "current_position": int(row["position"]),
            "projected_total_time_s": (
                float(row["elapsed_time_s"]) + remaining
            )
        })

    ranked = pd.DataFrame(projected).sort_values(
        "projected_total_time_s"
    ).reset_index(drop=True)

    ranked["projected_position"] = np.arange(1, len(ranked) + 1)

    target_result = ranked[ranked["driver_number"] == DRIVER].iloc[0]

    strategy_rows.append({
        "strategy": candidate["strategy"],
        "pit_lap": candidate["pit_lap"],
        "projected_position": int(target_result["projected_position"]),
        "current_position": CURRENT_POSITION,
        "position_change": (
            CURRENT_POSITION - int(target_result["projected_position"])
        ),
        "projected_total_time_s": round(
            float(target_result["projected_total_time_s"]), 2
        ),
        "gap_to_projected_leader_s": round(
            float(target_result["projected_total_time_s"])
            - float(ranked.iloc[0]["projected_total_time_s"]),
            2
        )
    })

    print(f"\n{candidate['strategy']} | Projected field order:")
    display(
        ranked[["projected_position", "driver_number",
                "current_position", "projected_total_time_s"]]
    )

field_comparison = pd.DataFrame(strategy_rows).sort_values(
    ["projected_position", "projected_total_time_s"]
)

print("\nPITWALL: strategy impact on projected finishing position")
display(field_comparison.reset_index(drop=True))

Stay out | Projected field order:

,projected_position,driver_number,current_position,projected_total_time_s
0,1,11,17,4996.829
1,2,4,1,5021.607
2,3,81,2,5022.189
3,4,44,3,5024.468
4,5,63,4,5025.810
5,6,1,5,5033.946
6,7,55,6,5035.129
7,8,27,7,5052.017
8,9,18,9,5054.105
9,10,14,8,5055.846
10,11,22,10,5057.308
11,12,23,11,5058.297
12,13,20,12,5061.021
13,14,2,13,5062.253
14,15,3,14,5076.600
15,16,77,15,5094.781
16,17,16,16,5103.232
17,18,24,19,5170.471
18,19,31,18,5276.145

Pit lap 27 | Projected field order:

,projected_position,driver_number,current_position,projected_total_time_s
0,1,11,17,4996.829
1,2,4,1,5021.607
2,3,81,2,5022.189
3,4,44,3,5024.468
4,5,1,5,5033.946
5,6,55,6,5035.129
6,7,63,4,5042.375
7,8,27,7,5052.017
8,9,18,9,5054.105
9,10,14,8,5055.846
10,11,22,10,5057.308
11,12,23,11,5058.297
12,13,20,12,5061.021
13,14,2,13,5062.253
14,15,3,14,5076.600
15,16,77,15,5094.781
16,17,16,16,5103.232
17,18,24,19,5170.471
18,19,31,18,5276.145

Pit lap 28 | Projected field order:

,projected_position,driver_number,current_position,projected_total_time_s
0,1,11,17,4996.829
1,2,4,1,5021.607
2,3,81,2,5022.189
3,4,44,3,5024.468
4,5,1,5,5033.946
5,6,55,6,5035.129
6,7,63,4,5044.822
7,8,27,7,5052.017
8,9,18,9,5054.105
9,10,14,8,5055.846
10,11,22,10,5057.308
11,12,23,11,5058.297
12,13,20,12,5061.021
13,14,2,13,5062.253
14,15,3,14,5076.600
15,16,77,15,5094.781
16,17,16,16,5103.232
17,18,24,19,5170.471
18,19,31,18,5276.145

Pit lap 29 | Projected field order:

,projected_position,driver_number,current_position,projected_total_time_s
0,1,11,17,4996.829
1,2,4,1,5021.607
2,3,81,2,5022.189
3,4,44,3,5024.468
4,5,1,5,5033.946
5,6,55,6,5035.129
6,7,63,4,5047.269
7,8,27,7,5052.017
8,9,18,9,5054.105
9,10,14,8,5055.846
10,11,22,10,5057.308
11,12,23,11,5058.297
12,13,20,12,5061.021
13,14,2,13,5062.253
14,15,3,14,5076.600
15,16,77,15,5094.781
16,17,16,16,5103.232
17,18,24,19,5170.471
18,19,31,18,5276.145

PITWALL: strategy impact on projected finishing position

,strategy,pit_lap,projected_position,current_position,position_change,projected_total_time_s,gap_to_projected_leader_s
0,Stay out,NaN,5,4,-1,5025.81,28.98
1,Pit lap 27,27.0,7,4,-3,5042.37,45.55
2,Pit lap 28,28.0,7,4,-3,5044.82,47.99
3,Pit lap 29,29.0,7,4,-3,5047.27,50.44

In [41]:

# Cell 61: Driver-specific pace anchoring
# Reuse the existing variables from Cells 59-60.

def project_driver_remaining_v2(
    driver_number,
    compound,
    tyre_age,
    strategy_compound=None,
    pit_lap=None
):
    # Get this driver's own observed lap time at the decision point.
    observed = race[
        (race["session_key"] == SESSION)
        & (race["driver_number"] == driver_number)
        & (race["lap_number"] == CURRENT_LAP)
    ]

    if observed.empty:
        raise ValueError(f"No decision-lap observation for driver {driver_number}")

    observed_time = float(observed.iloc[0]["lap_duration"])
    compound = str(compound).upper()

    # Anchor this driver's starting compound curve to their observed pace.
    hist_pace, _, _ = empirical_pace(compound, int(tyre_age))
    driver_adjustment = observed_time - hist_pace

    total = 0.0
    age = int(tyre_age)
    active_compound = compound

    for lap in range(CURRENT_LAP + 1, TOTAL_LAPS + 1):
        if pit_lap is not None and lap == pit_lap:
            age += 1
            pace, _, _ = empirical_pace(active_compound, age)
            total += pace + driver_adjustment + PIT_LOSS

            active_compound = str(strategy_compound).upper()
            age = 0

            # For the new compound, use the historical pace curve without
            # pretending that the old-compound adjustment is transferable.
            driver_adjustment = 0.0
            continue

        age += 1
        pace, _, _ = empirical_pace(active_compound, age)
        total += pace + driver_adjustment

    return total


# Recalculate each rival's baseline with their own pace anchor.
baseline_remaining_v2 = {}

for _, row in field.iterrows():
    number = int(row["driver_number"])
    baseline_remaining_v2[number] = project_driver_remaining_v2(
        driver_number=number,
        compound=row["compound"],
        tyre_age=row["tyre_age"]
    )

# Re-evaluate each target strategy against the driver-specific field baseline.
results_v2 = []

for candidate in CANDIDATES:
    target_row = field[field["driver_number"] == DRIVER].iloc[0]

    target_remaining = project_driver_remaining_v2(
        driver_number=DRIVER,
        compound=target_row["compound"],
        tyre_age=target_row["tyre_age"],
        strategy_compound=candidate["compound"],
        pit_lap=candidate["pit_lap"]
    )

    projected = []

    for _, row in field.iterrows():
        number = int(row["driver_number"])
        remaining = (
            target_remaining
            if number == DRIVER
            else baseline_remaining_v2[number]
        )

        projected.append({
            "driver_number": number,
            "current_position": int(row["position"]),
            "projected_total_time_s": float(row["elapsed_time_s"]) + remaining
        })

    ranked = pd.DataFrame(projected).sort_values(
        "projected_total_time_s"
    ).reset_index(drop=True)

    ranked["projected_position"] = np.arange(1, len(ranked) + 1)
    target_result = ranked[ranked["driver_number"] == DRIVER].iloc[0]

    results_v2.append({
        "strategy": candidate["strategy"],
        "pit_lap": candidate["pit_lap"],
        "projected_position": int(target_result["projected_position"]),
        "position_change": CURRENT_POSITION - int(target_result["projected_position"]),
        "projected_total_time_s": round(float(target_result["projected_total_time_s"]), 2),
        "gap_to_projected_leader_s": round(
            float(target_result["projected_total_time_s"])
            - float(ranked.iloc[0]["projected_total_time_s"]), 2
        )
    })

field_comparison_v2 = pd.DataFrame(results_v2).sort_values(
    ["projected_position", "projected_total_time_s"]
)

display(field_comparison_v2.reset_index(drop=True))

,strategy,pit_lap,projected_position,position_change,projected_total_time_s,gap_to_projected_leader_s
0,Stay out,NaN,1,3,5025.81,0.00
1,Pit lap 27,27.0,2,2,5042.37,2.69
2,Pit lap 28,28.0,2,2,5044.82,5.13
3,Pit lap 29,29.0,3,1,5047.27,7.58

In [42]:

# Cell 62: Consistent driver pace + tyre-relative strategy simulation
# All drivers are projected over the same remaining laps.
# Driver pace adjustment stays constant across compound changes.

PIT_LOSS = 22.0  # Assumption in seconds; test sensitivity later.

# Keep only drivers with a decision-lap observation and usable elapsed time.
field62 = field.copy()
field62["driver_number"] = field62["driver_number"].astype(int)
field62["compound"] = field62["compound"].str.upper()

# Historical median pace for each compound and tyre-age band.
# Require at least 5 observations; fallback to the nearest supported age band.
def robust_empirical_pace(compound, age):
    band = age_band(age)

    rows = pace_table[
        (pace_table["compound"] == compound)
        & (pace_table["age_band"].astype(str) == band)
        & (pace_table["count"] >= 5)
    ]

    if not rows.empty:
        row = rows.iloc[0]
        return float(row["median"]), int(row["count"]), str(row["age_band"])

    available = pace_table[
        (pace_table["compound"] == compound)
        & (pace_table["count"] >= 5)
    ].copy()

    if available.empty:
        raise ValueError(
            f"No supported historical pace data for compound={compound}"
        )

    band_midpoint = {
        "0-5": 2.5, "6-10": 8, "11-15": 13,
        "16-20": 18, "21-30": 25.5, "31+": 35
    }

    available["distance"] = available["age_band"].astype(str).map(
        lambda x: abs(band_midpoint[x] - age)
    )

    row = available.sort_values("distance").iloc[0]
    return float(row["median"]), int(row["count"]), str(row["age_band"])


def simulate_driver62(
    driver_number,
    starting_compound,
    starting_age,
    observed_lap_time,
    pit_lap=None,
    new_compound=None,
    pit_loss=PIT_LOSS
):
    starting_compound = str(starting_compound).upper()

    # Driver-specific pace level, estimated at the decision point.
    reference_pace, _, _ = robust_empirical_pace(
        starting_compound, int(starting_age)
    )
    driver_offset = float(observed_lap_time) - reference_pace

    total_lap_time = 0.0
    total_pit_loss = 0.0
    age = int(starting_age)
    compound = starting_compound
    rows = []

    for lap in range(CURRENT_LAP + 1, TOTAL_LAPS + 1):

        # Pit-in lap is completed on the old tyres.
        if pit_lap is not None and lap == pit_lap:
            age += 1
            pace, n, used_band = robust_empirical_pace(compound, age)
            projected_lap = pace + driver_offset

            total_lap_time += projected_lap
            total_pit_loss += pit_loss

            rows.append({
                "driver_number": driver_number,
                "lap": lap,
                "compound": compound,
                "tyre_age": age,
                "projected_lap_time_s": projected_lap,
                "pit_loss_s": pit_loss,
                "pace_sample_count": n,
                "pace_age_band": used_band
            })

            compound = str(new_compound).upper()
            age = 0
            continue

        age += 1
        pace, n, used_band = robust_empirical_pace(compound, age)
        projected_lap = pace + driver_offset

        total_lap_time += projected_lap

        rows.append({
            "driver_number": driver_number,
            "lap": lap,
            "compound": compound,
            "tyre_age": age,
            "projected_lap_time_s": projected_lap,
            "pit_loss_s": 0.0,
            "pace_sample_count": n,
            "pace_age_band": used_band
        })

    return total_lap_time, total_pit_loss, pd.DataFrame(rows)


# Build one consistent baseline for every driver.
driver_models62 = {}

for _, row in field62.iterrows():
    number = int(row["driver_number"])

    observed = race[
        (race["session_key"] == SESSION)
        & (race["driver_number"] == number)
        & (race["lap_number"] == CURRENT_LAP)
    ]

    if observed.empty or pd.isna(observed.iloc[0]["lap_duration"]):
        continue

    row_time = float(observed.iloc[0]["lap_duration"])

    remaining, pit_cost, lap_detail = simulate_driver62(
        driver_number=number,
        starting_compound=row["compound"],
        starting_age=int(row["tyre_age"]),
        observed_lap_time=row_time
    )

    driver_models62[number] = {
        "remaining_time_s": remaining + pit_cost,
        "elapsed_time_s": float(row["elapsed_time_s"]),
        "current_position": int(row["position"]),
        "lap_detail": lap_detail
    }


# Evaluate #63's strategies against the same baseline for all rivals.
strategy_results62 = []
rankings62 = {}

for candidate in CANDIDATES:
    target = field62[field62["driver_number"] == DRIVER]

    if target.empty or DRIVER not in driver_models62:
        raise ValueError("Driver #63 is missing from the usable field.")

    target = target.iloc[0]

    target_remaining, target_pit_loss, target_laps = simulate_driver62(
        driver_number=DRIVER,
        starting_compound=target["compound"],
        starting_age=int(target["tyre_age"]),
        observed_lap_time=float(
            race[
                (race["session_key"] == SESSION)
                & (race["driver_number"] == DRIVER)
                & (race["lap_number"] == CURRENT_LAP)
            ].iloc[0]["lap_duration"]
        ),
        pit_lap=candidate["pit_lap"],
        new_compound=candidate["compound"],
        pit_loss=PIT_LOSS
    )

    projected_rows = []

    for number, model in driver_models62.items():
        remaining = (
            target_remaining + target_pit_loss
            if number == DRIVER
            else model["remaining_time_s"]
        )

        projected_rows.append({
            "driver_number": number,
            "current_position": model["current_position"],
            "elapsed_time_s": model["elapsed_time_s"],
            "remaining_time_s": remaining,
            "projected_total_time_s": (
                model["elapsed_time_s"] + remaining
            )
        })

    ranking = pd.DataFrame(projected_rows).sort_values(
        "projected_total_time_s"
    ).reset_index(drop=True)

    ranking["projected_position"] = np.arange(1, len(ranking) + 1)
    rankings62[candidate["strategy"]] = ranking

    target_result = ranking[
        ranking["driver_number"] == DRIVER
    ].iloc[0]

    leader_time = float(ranking.iloc[0]["projected_total_time_s"])

    strategy_results62.append({
        "strategy": candidate["strategy"],
        "pit_lap": candidate["pit_lap"],
        "projected_position": int(target_result["projected_position"]),
        "position_change": (
            CURRENT_POSITION - int(target_result["projected_position"])
        ),
        "projected_remaining_lap_time_s": round(target_remaining, 2),
        "pit_loss_s": round(target_pit_loss, 2),
        "projected_total_time_s": round(
            float(target_result["projected_total_time_s"]), 2
        ),
        "gap_to_projected_leader_s": round(
            float(target_result["projected_total_time_s"]) - leader_time, 2
        )
    })

comparison62 = pd.DataFrame(strategy_results62).sort_values(
    "projected_total_time_s"
).reset_index(drop=True)

display(comparison62)

# Consistency check: every rival uses the same baseline across strategies.
print(
    "Drivers included:", len(driver_models62),
    "| Laps simulated per strategy:", TOTAL_LAPS - CURRENT_LAP
)
print("Pit-loss assumption:", PIT_LOSS, "seconds")
print(
    "Reminder: this is a simplified scenario model. "
    "It assumes wet/low-grip pace persists and rivals do not pit."
)

,strategy,pit_lap,projected_position,position_change,projected_remaining_lap_time_s,pit_loss_s,projected_total_time_s,gap_to_projected_leader_s
0,Stay out,NaN,1,3,2598.67,0.0,5025.81,0.00
1,Pit lap 29,29.0,16,-12,2755.52,22.0,5204.66,164.97
2,Pit lap 28,28.0,16,-12,2759.92,22.0,5209.05,169.37
3,Pit lap 27,27.0,16,-12,2764.31,22.0,5213.45,173.76

Drivers included: 19 | Laps simulated per strategy: 26
Pit-loss assumption: 22.0 seconds
Reminder: this is a simplified scenario model. It assumes wet/low-grip pace persists and rivals do not pit.

In [ ]:

# PITWALL — Weather timeline audit for strategy scenarios
# Purpose: identify observed lap-by-lap weather changes and coverage.
# This is a diagnostic cell, not a forecast of future weather.

import pandas as pd
import numpy as np

SESSION = 9558

weather = pd.read_parquet(DATA_DIR / "weather.parquet")
race_weather = pd.read_parquet(DATA_DIR / "race_state.parquet")

race_weather = race_weather[
    race_weather["session_key"] == SESSION
].copy()

print("WEATHER DATASET")
print("Shape:", weather.shape)
print("Columns:", weather.columns.tolist())
print("\nMissing values:")
display(weather.isna().sum().sort_values(ascending=False).to_frame(
    "missing_count"
))

# Summarise race-state weather once per lap, rather than counting
# every driver's row as an independent weather observation.
weather_columns = [
    c for c in [
        "rainfall",
        "grip_condition",
        "weather_state",
        "track_temperature",
        "air_temperature",
    ]
    if c in race_weather.columns
]

lap_weather = (
    race_weather.groupby("lap_number")[weather_columns]
    .agg(lambda s: s.dropna().iloc[0] if s.notna().any() else np.nan)
    .reset_index()
)

missing_by_lap = (
    race_weather.groupby("lap_number")[weather_columns]
    .agg(lambda s: s.isna().sum())
    .reset_index()
)

missing_by_lap = missing_by_lap.rename(
    columns={c: f"{c}_missing_rows" for c in weather_columns}
)

lap_weather = lap_weather.merge(
    missing_by_lap, on="lap_number", how="left"
)

print("\nOBSERVED WEATHER TIMELINE")
display(lap_weather.to_string(index=False) if False else lap_weather)

print("\nWEATHER STATE COUNTS")
for col in ["rainfall", "grip_condition", "weather_state"]:
    if col in race_weather.columns:
        print(f"\n{col}:")
        print(race_weather.groupby("lap_number")[col].first()
              .value_counts(dropna=False).to_string())

print(
    "\nImportant: these are observed race conditions, not information "
    "available to a strategist at lap 26. We will use them to design "
    "plausible scenarios, not assume the historical future is known."
)

WEATHER DATASET
Shape: (147, 10)
Columns: ['date', 'session_key', 'meeting_key', 'track_temperature', 'wind_speed', 'rainfall', 'humidity', 'pressure', 'air_temperature', 'wind_direction']

Missing values:

                   missing_count
date                           0
session_key                    0
meeting_key                    0
track_temperature              0
wind_speed                     0
rainfall                       0
humidity                       0
pressure                       0
air_temperature                0
wind_direction                 0

OBSERVED WEATHER TIMELINE

,lap_number,rainfall,grip_condition,track_temperature,air_temperature,rainfall_missing_rows,grip_condition_missing_rows,track_temperature_missing_rows,air_temperature_missing_rows
0,1,0.0,NaN,33.0,16.1,0,19,0,0
1,2,0.0,NaN,33.0,16.2,0,19,0,0
2,3,0.0,NaN,33.0,16.3,0,19,0,0
3,4,0.0,NaN,24.3,16.3,0,19,0,0
4,5,0.0,NaN,24.0,16.2,0,19,0,0
5,6,0.0,NaN,24.2,16.3,0,19,0,0
6,7,0.0,NaN,25.4,16.3,0,19,0,0
7,8,0.0,NaN,25.8,16.4,0,19,0,0
8,9,0.0,NaN,26.1,16.5,0,19,0,0
9,10,0.0,NaN,25.7,16.8,0,19,0,0
10,11,0.0,NaN,25.6,16.8,0,19,0,0
11,12,0.0,NaN,25.3,16.7,0,19,0,0
12,13,0.0,NaN,25.2,16.7,0,19,0,0
13,14,0.0,NaN,24.8,16.6,0,19,0,0
14,15,0.0,NaN,24.6,16.5,0,19,0,0
15,16,0.0,NaN,24.4,16.5,0,19,0,0
16,17,0.0,NaN,24.3,16.5,0,19,0,0
17,18,0.0,NaN,24.3,16.5,0,19,0,0
18,19,1.0,LOW,23.9,16.6,0,14,0,0
19,20,1.0,LOW,22.9,16.2,0,0,0,0
20,21,1.0,LOW,22.3,15.9,0,0,0,0
21,22,1.0,LOW,22.1,15.6,0,0,0,0
22,23,1.0,LOW,22.0,15.2,0,0,0,0
23,24,1.0,LOW,22.0,15.2,0,0,0,0
24,25,1.0,NORMAL,22.0,15.1,0,0,0,0
25,26,1.0,LOW,22.0,15.1,0,0,0,0
26,27,1.0,LOW,21.5,15.1,0,0,0,0
27,28,1.0,LOW,21.2,15.1,0,0,0,0
28,29,1.0,LOW,21.0,15.0,0,0,0,0
29,30,1.0,LOW,20.7,14.9,0,0,0,0
30,31,1.0,LOW,20.7,14.9,0,0,0,0
31,32,1.0,LOW,20.7,14.7,0,0,0,0
32,33,1.0,LOW,20.7,14.5,0,0,0,0
33,34,1.0,LOW,20.7,14.5,0,0,0,0
34,35,1.0,LOW,21.2,14.6,0,0,0,0
35,36,1.0,LOW,21.2,14.5,0,0,0,0
36,37,1.0,LOW,21.4,14.5,0,0,0,0
37,38,1.0,LOW,22.5,14.6,0,0,0,0
38,39,1.0,LOW,24.2,14.6,0,0,0,0
39,40,0.0,LOW,24.6,14.8,0,0,0,0
40,41,0.0,LOW,24.4,15.1,0,0,0,0
41,42,0.0,NORMAL,24.2,15.3,0,0,0,0
42,43,0.0,NORMAL,24.7,15.3,0,0,0,0
43,44,0.0,NORMAL,24.9,15.3,0,0,0,0
44,45,1.0,NORMAL,24.5,15.4,0,0,0,0
45,46,0.0,NORMAL,25.0,15.5,0,0,0,0
46,47,0.0,NORMAL,25.0,15.5,0,0,0,0
47,48,0.0,NORMAL,24.9,15.6,0,0,0,0
48,49,0.0,NORMAL,25.2,15.7,0,0,0,0
49,50,0.0,NORMAL,25.2,15.8,0,0,0,0
50,51,0.0,NORMAL,25.4,15.8,0,0,0,0
51,52,0.0,NORMAL,25.3,15.9,0,0,0,0

WEATHER STATE COUNTS

rainfall:
rainfall
0.0    30
1.0    22

grip_condition:
grip_condition
LOW       22
NaN       18
NORMAL    12

Important: these are observed race conditions, not information available to a strategist at lap 26. We will use them to design plausible scenarios, not assume the historical future is known.

In [ ]:

# PITWALL — Audit weather-to-lap alignment
# Diagnostic only: does not modify existing simulator functions.

weather = pd.read_parquet(DATA_DIR / "weather.parquet")
race = pd.read_parquet(DATA_DIR / "race_state.parquet")

weather = weather[weather["session_key"] == SESSION].copy()
race_session = race[race["session_key"] == SESSION].copy()

weather["date"] = pd.to_datetime(weather["date"], utc=True)

print("RAW WEATHER TIME COVERAGE")
print("Records:", len(weather))
print("First observation:", weather["date"].min())
print("Last observation:", weather["date"].max())

intervals = (
    weather.sort_values("date")["date"]
    .diff()
    .dt.total_seconds()
    .dropna()
)

print("\nWeather sampling interval (seconds)")
display(intervals.describe().to_frame("seconds"))

print("\nRACE-STATE TIME AND LAP COLUMNS")
print([
    c for c in race_session.columns
    if any(term in c.lower() for term in
           ["date", "time", "lap", "rainfall", "temperature", "grip"])
])

print("\nRACE-STATE TIMESTAMP COVERAGE")
for col in ["date", "timestamp", "session_time"]:
    if col in race_session.columns:
        values = pd.to_datetime(race_session[col], errors="coerce", utc=True)
        print(f"{col}: {values.min()} to {values.max()}")

print("\nLAP AND WEATHER COVERAGE")
print("Race-state laps:",
      race_session["lap_number"].min(),
      "to", race_session["lap_number"].max())
print("Weather records:", len(weather))

print(
    "\nDo not merge weather to laps by row order. "
    "We need a validated timestamp relationship before using weather "
    "scenarios in the simulator."
)

RAW WEATHER TIME COVERAGE
Records: 147
First observation: 2024-07-07 13:05:02.119000+00:00
Last observation: 2024-07-07 15:31:03.204000+00:00

Weather sampling interval (seconds)

          seconds
count  146.000000
mean    60.007432
std      0.016544
min     59.953000
25%     59.997000
50%     60.007000
75%     60.017000
max     60.063000

RACE-STATE TIME AND LAP COLUMNS
['lap_number', 'date_start', 'lap_duration', 'is_pit_out_lap', 'track_temperature', 'rainfall', 'air_temperature', 'grip_condition', 'date']

RACE-STATE TIMESTAMP COVERAGE
date: NaT to NaT

LAP AND WEATHER COVERAGE
Race-state laps: 1 to 52
Weather records: 147

Do not merge weather to laps by row order. We need a validated timestamp relationship before using weather scenarios in the simulator.

In [ ]:

# PITWALL — Inspect raw timestamps before designing the weather join
# Read-only diagnostic. Does not change the simulator.

weather = pd.read_parquet(DATA_DIR / "weather.parquet")
race = pd.read_parquet(DATA_DIR / "race_state.parquet")

weather = weather[weather["session_key"] == SESSION].copy()
race = race[race["session_key"] == SESSION].copy()

print("WEATHER TIMESTAMP")
print("dtype:", weather["date"].dtype)
print("Examples:")
print(weather["date"].head(3).map(repr).to_string(index=False))

print("\nRACE-STATE TIMESTAMP COLUMNS")
for col in ["date_start", "date"]:
    if col in race.columns:
        print(f"\n{col} | dtype: {race[col].dtype}")
        print("Examples:")
        print(race[col].head(5).map(repr).to_string(index=False))

        parsed = pd.to_datetime(race[col], errors="coerce", utc=True)
        print("Successfully parsed:", int(parsed.notna().sum()), "/", len(parsed))
        print("Parsed range:", parsed.min(), "to", parsed.max())

print("\nRACE-STATE TIMESTAMP UNIQUENESS")
if "date_start" in race.columns:
    print("Unique date_start values:", race["date_start"].nunique())
    print("Missing date_start:", race["date_start"].isna().sum())

print(
    "\nNext: determine the correct time representation and alignment. "
    "Do not merge yet."
)

WEATHER TIMESTAMP
dtype: datetime64[us, UTC]
Examples:
Timestamp('2024-07-07 13:05:02.119000+0000', tz...
Timestamp('2024-07-07 13:06:02.098000+0000', tz...
Timestamp('2024-07-07 13:07:02.122000+0000', tz...

RACE-STATE TIMESTAMP COLUMNS

date_start | dtype: datetime64[us, UTC]
Examples:
Timestamp('2024-07-07 14:03:12.540000+0000', tz...
Timestamp('2024-07-07 14:04:49.750000+0000', tz...
Timestamp('2024-07-07 14:06:21.461000+0000', tz...
Timestamp('2024-07-07 14:07:53.675000+0000', tz...
Timestamp('2024-07-07 14:09:25.527000+0000', tz...
Successfully parsed: 961 / 961
Parsed range: 2024-07-07 14:03:12.540000+00:00 to 2024-07-07 15:25:38.167000+00:00

date | dtype: datetime64[us, UTC]
Examples:
NaT
NaT
NaT
NaT
NaT
Successfully parsed: 0 / 961
Parsed range: NaT to NaT

RACE-STATE TIMESTAMP UNIQUENESS
Unique date_start values: 943
Missing date_start: 0

Next: determine the correct time representation and alignment. Do not merge yet.

In [ ]:

# PITWALL — Validate causal weather alignment
# Uses the latest weather observation available at each lap start.
# Does not modify race_state or the simulator.

weather_check = pd.read_parquet(DATA_DIR / "weather.parquet")
race_check = pd.read_parquet(DATA_DIR / "race_state.parquet")

weather_check = weather_check.loc[
    weather_check["session_key"] == SESSION
].copy()

race_check = race_check.loc[
    race_check["session_key"] == SESSION
].copy()

weather_check["date"] = pd.to_datetime(
    weather_check["date"], utc=True
)
race_check["date_start"] = pd.to_datetime(
    race_check["date_start"], utc=True
)

weather_check = weather_check.sort_values("date")
race_check = race_check.sort_values("date_start")

aligned = pd.merge_asof(
    race_check[["driver_number", "lap_number", "date_start"]],
    weather_check[[
        "date", "rainfall", "track_temperature",
        "air_temperature", "humidity"
    ]],
    left_on="date_start",
    right_on="date",
    direction="backward",
    tolerance=pd.Timedelta(seconds=65)
)

aligned["weather_age_seconds"] = (
    aligned["date_start"] - aligned["date"]
).dt.total_seconds()

print("CAUSAL WEATHER ALIGNMENT")
print("Race-state rows:", len(aligned))
print("Rows with matched weather:", int(aligned["date"].notna().sum()))
print("Match rate:", round(aligned["date"].notna().mean() * 100, 2), "%")

print("\nWeather observation age (seconds)")
display(aligned["weather_age_seconds"].describe().to_frame())

print("\nMatched weather coverage by lap")
display(
    aligned.groupby("lap_number")
    .agg(
        drivers=("driver_number", "nunique"),
        matched_rows=("date", "count"),
        rainfall_values=("rainfall", "nunique"),
        median_weather_age_s=("weather_age_seconds", "median")
    )
    .reset_index()
    .head(15)
)

print("\nMissing matched weather values")
display(aligned[["rainfall", "track_temperature",
                 "air_temperature", "humidity"]].isna().sum().to_frame(
    "missing_count"
))

CAUSAL WEATHER ALIGNMENT
Race-state rows: 961
Rows with matched weather: 961
Match rate: 100.0 %

Weather observation age (seconds)

       weather_age_seconds
count           961.000000
mean             29.377612
std              17.568594
min               0.019000
25%              13.337000
50%              29.296000
75%              44.449000
max              59.981000

Matched weather coverage by lap

    lap_number  drivers  matched_rows  rainfall_values  median_weather_age_s
0            1       19            19                1                10.044
1            2       19            19                1                51.018
2            3       19            19                1                24.070
3            4       19            19                1                52.796
4            5       19            19                1                30.264
5            6       19            19                1                 7.273
6            7       19            19                1                35.470
7            8       19            19                1                13.396
8            9       19            19                1                40.678
9           10       19            19                1                14.221
10          11       19            19                1                43.716
11          12       19            19                1                18.591
12          13       19            19                1                47.859
13          14       19            19                1                21.624
14          15       19            19                1                41.110

Missing matched weather values

                   missing_count
rainfall                       0
track_temperature              0
air_temperature                0
humidity                       0

In [46]:
# PITWALL — Check existing weather integration

print("WEATHER-RELATED DATASETS")
for name in [
    "race_state",
    "weather",
    "lap_performance",
    "pace_table",
    "comparison62"
]:
    obj = globals().get(name)
    if obj is not None:
        print(f"\n{name}: {type(obj).__name__}")
        if hasattr(obj, "columns"):
            print("Columns:", obj.columns.tolist())

print("\nWEATHER REFERENCES IN SIMULATOR SOURCE")
import inspect

simulator_source = inspect.getsource(simulate_driver62)
weather_terms = [
    "rainfall", "track_temperature", "air_temperature",
    "humidity", "weather", "grip_condition"
]

for term in weather_terms:
    print(f"{term}: {term.lower() in simulator_source.lower()}")

print("\nEXISTING WEATHER-RELATED NOTEBOOK CELLS")
for i, cell in enumerate(In):
    source = str(cell)
    if (
        "weather_state" in source
        or "track_temperature" in source
        or "grip_condition" in source
    ):
        print(f"Cell {i}: {source.splitlines()[0][:120]}")

WEATHER-RELATED DATASETS

race_state: DataFrame
Columns: ['driver_number', 'lap_number', 'date_start', 'lap_duration', 'compound', 'tyre_age', 'stint_number', 'is_pit_out_lap', 'position', 'session_key', 'meeting_key', 'track_temperature', 'wind_speed', 'rainfall', 'humidity', 'pressure', 'air_temperature', 'wind_direction', 'weather_age_seconds', 'drs_available', 'grip_condition', 'blue_flag', 'date']

weather: DataFrame
Columns: ['date', 'session_key', 'meeting_key', 'track_temperature', 'wind_speed', 'rainfall', 'humidity', 'pressure', 'air_temperature', 'wind_direction']

pace_table: DataFrame
Columns: ['compound', 'age_band', 'median', 'count']

comparison62: DataFrame
Columns: ['strategy', 'pit_lap', 'projected_position', 'position_change', 'projected_remaining_lap_time_s', 'pit_loss_s', 'projected_total_time_s', 'gap_to_projected_leader_s']

WEATHER REFERENCES IN SIMULATOR SOURCE
rainfall: False
track_temperature: False
air_temperature: False
humidity: False
weather: False
grip_condition: False

EXISTING WEATHER-RELATED NOTEBOOK CELLS
Cell 4: race_state = pd.read_parquet(DATA_DIR / "race_state.parquet")
Cell 12: TARGET_DRIVER = 63  # George Russell
Cell 14: # Cell 11: Reconstruct observed strategy timelines (fixed)
Cell 15: drivers_to_compare = {
Cell 17: # Cell 14: Define candidate strategies for George Russell
Cell 24: def build_decision_state(sim_state, driver_number, decision_lap):
Cell 25: def generate_strategy_candidates(
Cell 26: pace_check_columns = [
Cell 27: from sklearn.compose import ColumnTransformer
Cell 28: # Cell 25: Diagnose prediction errors across the race
Cell 29: # Cell 26: Compare Linear Regression, Random Forest, and XGBoost
Cell 30: best_model_name = results_df.iloc[0]["model"]
Cell 31: # Cell 28: Audit rainfall and grip consistency by lap
Cell 32: from pathlib import Path
Cell 39: # Cell 59: PITWALL strategy simulator v1
Cell 46: # PITWALL — Check existing weather integration

In [47]:
# PITWALL — Diagnose weather signal in observed lap times

weather_diag = race_state.copy()

# Exclude pit-out laps from this first comparison.
weather_diag = weather_diag.loc[
    ~weather_diag["is_pit_out_lap"].fillna(False)
].copy()

print("Rows:", len(weather_diag))
print("Unique laps:", weather_diag["lap_number"].nunique())

print("\nWeather and grip coverage")
display(
    weather_diag[
        ["rainfall", "track_temperature", "grip_condition",
         "compound", "tyre_age", "lap_duration"]
    ].isna().sum().to_frame("missing_count")
)

print("\nLap time by compound and grip condition")
display(
    weather_diag.groupby(
        ["compound", "grip_condition"], dropna=False
    ).agg(
        rows=("lap_duration", "size"),
        median_lap_time=("lap_duration", "median"),
        median_tyre_age=("tyre_age", "median"),
        median_rainfall=("rainfall", "median"),
        median_track_temp=("track_temperature", "median")
    ).reset_index().sort_values(["compound", "grip_condition"])
)

print("\nLap time by rainfall")
display(
    weather_diag.groupby("rainfall", dropna=False).agg(
        rows=("lap_duration", "size"),
        median_lap_time=("lap_duration", "median"),
        median_tyre_age=("tyre_age", "median"),
        median_track_temp=("track_temperature", "median")
    ).reset_index()
)

Rows: 917
Unique laps: 52

Weather and grip coverage

                   missing_count
rainfall                       1
track_temperature              1
grip_condition               356
compound                       2
tyre_age                       2
lap_duration                   3

Lap time by compound and grip condition

,compound,grip_condition,rows,median_lap_time,median_tyre_age,median_rainfall,median_track_temp
0,HARD,LOW,4,90.2655,1.5,0.0,24.30
1,HARD,NORMAL,20,89.4410,7.0,0.0,24.95
2,HARD,NaN,18,92.7090,8.5,0.0,25.20
3,INTERMEDIATE,LOW,207,103.0000,5.0,1.0,21.00
4,INTERMEDIATE,NORMAL,4,110.4050,4.0,1.0,22.00
5,MEDIUM,LOW,106,93.6850,21.0,1.0,22.10
6,MEDIUM,NORMAL,87,90.5650,9.0,0.0,24.90
7,MEDIUM,NaN,307,92.7480,9.0,0.0,25.20
8,SOFT,LOW,17,92.0710,1.0,0.0,24.40
9,SOFT,NORMAL,115,90.8750,8.0,0.0,25.00
10,SOFT,NaN,30,94.1530,7.0,0.0,25.40
11,NaN,LOW,1,NaN,NaN,1.0,21.00
12,NaN,NaN,1,NaN,NaN,0.0,33.00

Lap time by rainfall

   rainfall  rows  median_lap_time  median_tyre_age  median_track_temp
0       0.0   540           92.320              8.0               25.0
1       1.0   376          102.025              8.0               21.9
2       NaN     1              NaN              0.0                NaN

In [48]:
# PITWALL — Inspect existing model validation and feature setup

print("RACE STATE COLUMNS")
print(race_state.columns.tolist())

print("\nEXISTING VALIDATION CELLS")
for i, cell in enumerate(In):
    source = str(cell)
    terms = [
        "TimeSeriesSplit",
        "ExpandingWindow",
        "train_laps",
        "test_laps",
        "chronological",
        "rolling validation",
        "XGBRegressor",
        "RandomForestRegressor"
    ]
    if any(term.lower() in source.lower() for term in terms):
        print(f"\n{'=' * 18} INPUT CELL {i} {'=' * 18}")
        print(source[:3500])

RACE STATE COLUMNS
['driver_number', 'lap_number', 'date_start', 'lap_duration', 'compound', 'tyre_age', 'stint_number', 'is_pit_out_lap', 'position', 'session_key', 'meeting_key', 'track_temperature', 'wind_speed', 'rainfall', 'humidity', 'pressure', 'air_temperature', 'wind_direction', 'weather_age_seconds', 'drs_available', 'grip_condition', 'blue_flag', 'date']

EXISTING VALIDATION CELLS

================== INPUT CELL 27 ==================
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Exclude pit-out laps so the model learns racing pace, not pit-exit delays
model_data = pace_data.loc[
    ~pace_data["is_pit_out_lap"]
    & pace_data["lap_duration"].notna()
    & pace_data["compound"].notna()
].copy()

# Keep only features available in the current simulation dataset
numeric_features = [
    "lap_number",
    "tyre_age",
    "rainfall",
    "humidity",
    "air_temperature",
    "track_temperature",
    "wind_speed",
    "traffic_ahead",
    "traffic_behind",
    "position_change",
]

categorical_features = ["compound", "driver_number"]

numeric_features = [
    col for col in numeric_features if col in model_data.columns
]
categorical_features = [
    col for col in categorical_features if col in model_data.columns
]

feature_columns = numeric_features + categorical_features

# Time-ordered split: earlier laps train, later laps test
split_lap = 35

train_data = model_data.loc[
    model_data["lap_number"] <= split_lap
].copy()

test_data = model_data.loc[
    model_data["lap_number"] > split_lap
].copy()

if train_data.empty or test_data.empty:
    raise ValueError("The temporal train/test split produced an empty dataset.")

X_train = train_data[feature_columns]
y_train = train_data["lap_duration"]

X_test = test_data[feature_columns]
y_test = test_data["lap_duration"]

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore")),
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features),
])

pace_baseline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=300,
        min_samples_leaf=5,
        random_state=42,
        n_jobs=-1,
    )),
])

pace_baseline.fit(X_train, y_train)
test_predictions = pace_baseline.predict(X_test)

mae = mean_absolute_error(y_test, test_predictions)
rmse = np.sqrt(mean_squared_error(y_test, test_predictions))
r2 = r2_score(y_test, test_predictions)

# Simple reference baseline: always predict the training-set median
median_baseline_prediction = np.full(
    len(y_test), y_train.median()
)
median_baseline_mae = mean_absolute_error(
    y_test, median_baseline_prediction
)

print("TIME-ORDERED PACE VALIDATION")
print("=" * 55)
print(f"Training laps: 1 to {split_lap}")
print(f"Test laps: {split_lap + 1} to {int(test_data['lap_number'].max())}")
print(f"Training rows: {len(train_data)}")
print(f"Test rows: {len(test_data)}")
print(f"Model MAE: {mae:.3f} seconds")
print(f"Model RMSE: {rmse:.3f} seconds")
print(f"Model R²: {r2:.3f}")
print(f"Median-baseline MAE: {median_baseline_mae:.3f} seconds")

# Check performance separately for each compound in the test period
evaluation = test_data[
    ["driver_number", "lap_number", "compound", "lap_duration"]
].copy()

evaluation["predicted_lap_duration"] = test_predictions
evaluation["absolute_error"] = (
    evaluation["lap_duration"]
    - evaluation["predicted_lap_duration"]
).abs()

print("\nTEST PERFORMANCE BY COMPOUND")
print(

================== INPUT CELL 29 ==================
# Cell 26: Compare Linear Regression, Random Forest, and XGBoost

import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from xgboost import XGBRegressor

# ---------------------------------------------------------
# 1. Build a clean dataset without pit-out laps
# ---------------------------------------------------------
model_data = sim_state.loc[
    sim_state["lap_duration"].notna()
    & sim_state["compound"].notna()
].copy()

model_data["compound"] = model_data["compound"].astype(str).str.upper()
model_data["driver_number"] = model_data["driver_number"].astype(str)

model_data["is_pit_out_lap"] = (
    model_data["is_pit_out_lap"].fillna(False).astype(bool)
)

model_data = model_data.loc[
    ~model_data["is_pit_out_lap"]
].copy()

model_data = model_data.sort_values(
    ["lap_number", "driver_number"]
).reset_index(drop=True)

# ---------------------------------------------------------
# 2. Create track evolution using weather data only
# ---------------------------------------------------------
# One weather record per lap. These are observed conditions,
# not lap-time outcomes.
weather_by_lap = (
    model_data.groupby("lap_number")
    .agg(
        rainfall=("rainfall", "median"),
        track_temperature=("track_temperature", "median"),
        air_temperature=("air_temperature", "median"),
        humidity=("humidity", "median"),
    )
    .sort_index()
)

# Rolling change over the previous 3 lap observations.
# shift(1) ensures the trend feature does not use the
# current lap's weather or any future observations.
for col in [
    "rainfall",
    "track_temperature",
    "air_temperature",
    "humidity",
]:
    previous_weather = weather_by_lap[col].shift(1)

    weather_by_lap[f"{col}_change_3lap"] = (
        previous_weather - previous_weather.shift(3)
    ) / 3

weather_features = [
    "rainfall_change_3lap",
    "track_temperature_change_3lap",
    "air_temperature_change_3lap",
    "humidity_change_3lap",
]

weather_by_lap = weather_by_lap.rename(columns={
    "rainfall_change_3lap": "rainfall_trend",
    "track_temperature_change_3lap": "track_temp_trend",
    "air_temperature_change_3lap": "air_temp_trend",
    "humidity_change_3lap": "humidity_trend",
})

weather_features = [
    "rainfall_trend",
    "track_temp_trend",
    "air_temp_trend",
    "humidity_trend",
]

model_data = model_data.merge(
    weather_by_lap[weather_features],
    left_on="lap_number",
    right_index=True,
    how="left",
    validate="many_to_one",
)

# ---------------------------------------------------------
# 3. Define shared features for a fair comparison
# ---------------------------------------------------------
numeric_features = [
    "lap_number",
    "tyre_age",
    "rainfall",
    "humidity",
    "air_temperature",
    "track_temperature",
    "wind_speed",
    "traffic_ahead",
    "traffic_behind",
    "position_change",
    "rainfall_trend",
    "track_temp_trend",
    "air_temp_trend",
    "humidity_trend",
]

categorical_features = [
    "compound",
    "driver_number",
]

numeric_features = [
    col for col in numeric_features if col in model_data.columns
]

feature_colum

================== INPUT CELL 33 ==================
# Use the same chronological test period as our previous model evaluation
test_audit = model_data.loc[
    model_data["lap_number"].between(36, 52)
].copy()

print("TEST DATA SHAPE:", test_audit.shape)

print("\nACTUAL LAP-TIME MEDIAN BY LAP")
display(
    test_audit.groupby("lap_number")["lap_duration"]
    .agg(["count", "median", "mean", "std"])
    .round(3)
)

print("\nACTUAL LAP-TIME MEDIAN BY LAP AND COMPOUND")
display(
    test_audit.groupby(["lap_number", "compound"])["lap_duration"]
    .agg(["count", "median"])
    .round(3)
)

print("\nFEATURES USED BY THE BEST MODEL")
print("Best model:", best_model_name)
print("Features:", model_data.columns.tolist())

================== INPUT CELL 36 ==================
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Recreate the exact chronological split used previously
clean_data = model_data.loc[
    model_data["is_pit_out_lap"].eq(False)
    & model_data["lap_duration"].notna()
].copy()

train_data = clean_data.loc[clean_data["lap_number"] <= 35].copy()
test_data = clean_data.loc[clean_data["lap_number"] >= 36].copy()

# Match the existing diagnostic rows to the test data.
# diagnostics was created from the previous test predictions.
current_mae = mean_absolute_error(
    diagnostics["lap_duration"],
    diagnostics["predicted_lap_duration"]
)
current_rmse = np.sqrt(mean_squared_error(
    diagnostics["lap_duration"],
    diagnostics["predicted_lap_duration"]
))
current_r2 = r2_score(
    diagnostics["lap_duration"],
    diagnostics["predicted_lap_duration"]
)

# Baseline A: global training median
global_median = train_data["lap_duration"].median()
global_predictions = np.full(len(test_data), global_median)

# Baseline B: training median by compound, with global fallback
compound_medians = train_data.groupby("compound")["lap_duration"].median()
compound_predictions = (
    test_data["compound"].map(compound_medians).fillna(global_median)
)

# Evaluate only the same test rows as diagnostics for a fair comparison
test_keys = ["driver_number", "lap_number"]
comparison_test = test_data.merge(
    diagnostics[test_keys],
    on=test_keys,
    how="inner",
    validate="one_to_one"
)

global_test_predictions = np.full(len(comparison_test), global_median)
compound_test_predictions = (
    comparison_test["compound"].map(compound_medians).fillna(global_median)
)

actual = comparison_test["lap_duration"]

comparison = pd.DataFrame([
    {
        "model": "Global training median",
        "MAE": mean_absolute_error(actual, global_test_predictions),
        "RMSE": np.sqrt(mean_squared_error(actual, global_test_predictions)),
        "R2": r2_score(actual, global_test_predictions),
    },
    {
        "model": "Compound training median",
        "MAE": mean_absolute_error(actual, compound_test_predictions),
        "RMSE": np.sqrt(mean_squared_error(actual, compound_test_predictions)),
        "R2": r2_score(actual, compound_test_predictions),
    },
    {
        "model": "Current Linear Regression",
        "MAE": current_mae,
        "RMSE": current_rmse,
        "R2": current_r2,
    },
])

display(comparison.round(3))
print("Training rows:", len(train_data))
print("Test rows evaluated:", len(comparison_test))
print("Diagnostic rows:", len(diagnostics))

================== INPUT CELL 48 ==================
# PITWALL — Inspect existing model validation and feature setup

print("RACE STATE COLUMNS")
print(race_state.columns.tolist())

print("\nEXISTING VALIDATION CELLS")
for i, cell in enumerate(In):
    source = str(cell)
    terms = [
        "TimeSeriesSplit",
        "ExpandingWindow",
        "train_laps",
        "test_laps",
        "chronological",
        "rolling validation",
        "XGBRegressor",
        "RandomForestRegressor"
    ]
    if any(term.lower() in source.lower() for term in terms):
        print(f"\n{'=' * 18} INPUT CELL {i} {'=' * 18}")
        print(source[:3500])

In [49]:
# PITWALL — Baseline vs weather-enhanced pace prediction
# Diagnostic only: does adding weather improve chronological test performance?

import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

weather_test_data = race_state.loc[
    race_state["lap_duration"].notna()
    & race_state["compound"].notna()
    & ~race_state["is_pit_out_lap"].fillna(False).astype(bool)
].copy()

weather_test_data["compound"] = (
    weather_test_data["compound"].astype(str).str.upper()
)
weather_test_data["driver_number"] = (
    weather_test_data["driver_number"].astype(str)
)

baseline_numeric = ["lap_number", "tyre_age"]
weather_numeric = [
    "lap_number", "tyre_age",
    "rainfall", "track_temperature",
    "air_temperature", "humidity", "wind_speed"
]
categorical = ["compound", "driver_number"]

train = weather_test_data.loc[
    weather_test_data["lap_number"] <= 35
].copy()

test = weather_test_data.loc[
    weather_test_data["lap_number"].between(36, 52)
].copy()

def evaluate_weather_model(numeric_features, model_name):
    preprocessor = ColumnTransformer([
        ("numeric", Pipeline([
            ("imputer", SimpleImputer(strategy="median"))
        ]), numeric_features),
        ("categorical", Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("encoder", OneHotEncoder(handle_unknown="ignore"))
        ]), categorical)
    ])

    model = Pipeline([
        ("preprocessor", preprocessor),
        ("model", RandomForestRegressor(
            n_estimators=300,
            min_samples_leaf=5,
            random_state=42,
            n_jobs=-1
        ))
    ])

    features = numeric_features + categorical
    model.fit(train[features], train["lap_duration"])
    predictions = model.predict(test[features])

    return {
        "model": model_name,
        "train_rows": len(train),
        "test_rows": len(test),
        "MAE_s": mean_absolute_error(test["lap_duration"], predictions),
        "RMSE_s": np.sqrt(
            mean_squared_error(test["lap_duration"], predictions)
        ),
        "R2": r2_score(test["lap_duration"], predictions)
    }

results_weather = pd.DataFrame([
    evaluate_weather_model(baseline_numeric, "Baseline"),
    evaluate_weather_model(weather_numeric, "Baseline + weather")
])

print("CHRONOLOGICAL VALIDATION: TRAIN LAPS 1–35, TEST LAPS 36–52")
display(results_weather.round(4))

print("Weather test-period coverage:")
display(
    test[weather_numeric[2:]]
    .isna()
    .sum()
    .to_frame("missing_test_values")
)

CHRONOLOGICAL VALIDATION: TRAIN LAPS 1–35, TEST LAPS 36–52

                model  train_rows  test_rows    MAE_s   RMSE_s      R2
0            Baseline         637        277  11.1873  11.8786 -7.5900
1  Baseline + weather         637        277   9.5186  10.0115 -5.1018

Weather test-period coverage:

                   missing_test_values
rainfall                             0
track_temperature                    0
air_temperature                      0
humidity                             0
wind_speed                           0

In [50]:
# PITWALL — Diagnose chronological distribution shift

for period_name, period_data in [
    ("TRAIN: laps 1–35", train),
    ("TEST: laps 36–52", test)
]:
    print(f"\n{period_name}")
    print("Rows:", len(period_data))

    display(
        period_data.agg({
            "lap_duration": ["median", "mean", "std"],
            "rainfall": ["mean"],
            "track_temperature": ["median", "mean"],
            "tyre_age": ["median"]
        }).round(3)
    )

    print("Compound distribution:")
    display(
        period_data["compound"]
        .value_counts(normalize=True)
        .mul(100)
        .round(1)
        .rename("percent")
        .to_frame()
    )

print("\nWEATHER AND LAP-TIME MEDIANS BY LAP")
display(
    weather_test_data.groupby("lap_number").agg(
        rows=("lap_duration", "count"),
        median_lap_time=("lap_duration", "median"),
        rainfall=("rainfall", "median"),
        track_temperature=("track_temperature", "median")
    ).round(3).tail(20)
)

TRAIN: laps 1–35
Rows: 637

        lap_duration  rainfall  track_temperature  tyre_age
median        94.076       NaN             24.100       8.0
mean          97.003     0.469             24.085       NaN
std            5.466       NaN                NaN       NaN

Compound distribution:

              percent
compound
MEDIUM           67.3
INTERMEDIATE     25.0
SOFT              4.9
HARD              2.8

TEST: laps 36–52
Rows: 277

        lap_duration  rainfall  track_temperature  tyre_age
median        90.849       NaN             24.900       8.0
mean          92.529     0.274             24.399       NaN
std            4.060       NaN                NaN       NaN

Compound distribution:

              percent
compound
SOFT             47.3
MEDIUM           25.6
INTERMEDIATE     18.8
HARD              8.3

WEATHER AND LAP-TIME MEDIANS BY LAP

            rows  median_lap_time  rainfall  track_temperature
lap_number
33            19          104.641       1.0              20.70
34            18          104.649       1.0              21.00
35            18          103.816       1.0              21.20
36            18          102.737       1.0              21.20
37            18          100.458       1.0              21.40
38            12           98.520       1.0              23.80
39            10           94.979       0.0              24.30
40            14           91.712       0.0              24.40
41            18           90.649       0.0              24.20
42            18           90.164       0.0              24.70
43            18           90.144       0.0              24.95
44            18           90.211       1.0              24.50
45            18           90.227       1.0              24.50
46            18           90.160       0.0              25.00
47            18           90.218       0.0              24.90
48            17           90.365       0.0              25.20
49            18           90.752       0.0              25.20
50            18           90.516       0.0              25.40
51            14           90.732       0.0              25.40
52            12           90.496       0.0              25.20

In [38]:

# PITWALL — Check simulator dependencies without assuming they exist

required = [
    "DATA_DIR",
    "SESSION",
    "DRIVER",
    "CURRENT_LAP",
    "TOTAL_LAPS",
    "CURRENT_POSITION",
    "PIT_LOSS",
    "CANDIDATES",
    "field",
    "race",
    "pace_table",
    "age_band",
    "robust_empirical_pace",
    "simulate_driver62",
    "driver_models62",
    "comparison62",
]

available = globals()

dependency_check = pd.DataFrame([
    {
        "name": name,
        "available": name in available,
        "type": type(available[name]).__name__
                if name in available else "NOT DEFINED",
    }
    for name in required
])

display(dependency_check)

missing = dependency_check.loc[
    ~dependency_check["available"], "name"
].tolist()

if missing:
    print("\nMissing dependencies:", missing)
    print(
        "\nDo not run the simulator continuation yet. "
        "The notebook's setup cells must execute in dependency order."
    )
else:
    print("\nAll checked simulator dependencies are available.")
    print("Decision lap:", CURRENT_LAP)
    print("Race distance:", TOTAL_LAPS)
    print("Target driver:", DRIVER)
    print("Pit-loss assumption:", PIT_LOSS, "seconds")
    print("\nExisting strategy comparison:")
    display(comparison62)

                     name  available         type
0                DATA_DIR       True  WindowsPath
1                 SESSION      False  NOT DEFINED
2                  DRIVER      False  NOT DEFINED
3             CURRENT_LAP      False  NOT DEFINED
4              TOTAL_LAPS      False  NOT DEFINED
5        CURRENT_POSITION      False  NOT DEFINED
6                PIT_LOSS      False  NOT DEFINED
7              CANDIDATES      False  NOT DEFINED
8                   field      False  NOT DEFINED
9                    race      False  NOT DEFINED
10             pace_table      False  NOT DEFINED
11               age_band      False  NOT DEFINED
12  robust_empirical_pace      False  NOT DEFINED
13      simulate_driver62      False  NOT DEFINED
14        driver_models62      False  NOT DEFINED
15           comparison62      False  NOT DEFINED

Missing dependencies: ['SESSION', 'DRIVER', 'CURRENT_LAP', 'TOTAL_LAPS', 'CURRENT_POSITION', 'PIT_LOSS', 'CANDIDATES', 'field', 'race', 'pace_table', 'age_band', 'robust_empirical_pace', 'simulate_driver62', 'driver_models62', 'comparison62']

Do not run the simulator continuation yet. The notebook's setup cells must execute in dependency order.

In [ ]:

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from xgboost import XGBRegressor

# ============================================================
# CELL 63: TEMPORAL PACE-MODEL BACKTEST
# ============================================================

DATA_DIR = Path("../data/processed/9558")
SESSION = 9558

# ------------------------------------------------------------
# 1. Load existing processed datasets
# ------------------------------------------------------------

state = pd.read_parquet(DATA_DIR / "race_state.parquet")
fuel = pd.read_parquet(DATA_DIR / "fuel_features.parquet")
traffic = pd.read_parquet(DATA_DIR / "traffic_features.parquet")
tyres = pd.read_parquet(DATA_DIR / "tyre_features.parquet")

# Keep only the features required from each asset
fuel = fuel[
    ["driver_number", "lap_number", "fuel_effect"]
].drop_duplicates(["driver_number", "lap_number"])

traffic = traffic[
    [
        "driver_number",
        "lap_number",
        "traffic_ahead",
        "traffic_behind",
        "position_change",
    ]
].drop_duplicates(["driver_number", "lap_number"])

tyres = tyres[
    ["driver_number", "lap_number", "tyre_degradation_effect"]
].drop_duplicates(["driver_number", "lap_number"])

# ------------------------------------------------------------
# 2. Filter session and merge features
# ------------------------------------------------------------

df = state[state["session_key"] == SESSION].copy()

df = df.merge(
    fuel,
    on=["driver_number", "lap_number"],
    how="left",
    validate="many_to_one",
)

df = df.merge(
    traffic,
    on=["driver_number", "lap_number"],
    how="left",
    validate="many_to_one",
)

df = df.merge(
    tyres,
    on=["driver_number", "lap_number"],
    how="left",
    validate="many_to_one",
)

# ------------------------------------------------------------
# 3. Create lagged track-evolution feature
# ------------------------------------------------------------

df["lap_duration"] = pd.to_numeric(
    df["lap_duration"], errors="coerce"
)

field_median = (
    df.groupby("lap_number")["lap_duration"]
    .median()
    .sort_index()
)

previous_field_median = field_median.shift(1)

df["track_evolution"] = df["lap_number"].map(
    previous_field_median
)

first_available = previous_field_median.dropna()

if first_available.empty:
    raise ValueError(
        "Cannot calculate track evolution: no previous-lap median available."
    )

df["track_evolution"] = df["track_evolution"].fillna(
    float(first_available.iloc[0])
)

# ------------------------------------------------------------
# 4. Clean target and filter compounds
# ------------------------------------------------------------

df["compound"] = (
    df["compound"].astype("string").str.upper()
)

df = df[
    df["lap_duration"].notna()
    & np.isfinite(df["lap_duration"])
    & (df["lap_duration"] > 0)
    & (~df["is_pit_out_lap"].fillna(False).astype(bool))
    & df["compound"].isin(["MEDIUM", "SOFT"])
].copy()

df = df.reset_index(drop=True)

if df.empty:
    raise ValueError(
        "No valid MEDIUM/SOFT laps remain after filtering."
    )

print("Valid rows after cleaning:", len(df))
print("Invalid lap durations remaining:", (
    df["lap_duration"].isna()
    | ~np.isfinite(df["lap_duration"])
).sum())

# ------------------------------------------------------------
# 5. Build features
# ------------------------------------------------------------

numeric_features = [
    "tyre_age",
    "fuel_effect",
    "traffic_ahead",
    "traffic_behind",
    "position_change",
    "track_evolution",
    "rainfall",
    "humidity",
    "air_temperature",
    "wind_speed",
]

missing_features = [
    col for col in numeric_features if col not in df.columns
]

if missing_features:
    raise KeyError(f"Missing feature columns: {missing_features}")

numeric_X = df[numeric_features].apply(
    pd.to_numeric, errors="coerce"
)

driver_dummies = pd.get_dummies(
    df["driver_number"].astype(str),
    prefix="driver",
    dtype=int,
)

compound_dummies = pd.get_dummies(
    df["compound"],
    prefix="compound",
    dtype=int,
)

X = pd.concat(
    [
        numeric_X.reset_index(drop=True),
        driver_dummies.reset_index(drop=True),
        compound_dummies.reset_index(drop=True),
    ],
    axis=1,
)

y = df["lap_duration"].reset_index(drop=True)
laps = pd.to_numeric(
    df["lap_number"], errors="coerce"
).reset_index(drop=True)
compounds = df["compound"].reset_index(drop=True)

# Remove any rows with invalid lap numbers, keeping all arrays aligned
valid_lap_mask = laps.notna().to_numpy()

X = X.iloc[np.flatnonzero(valid_lap_mask)].reset_index(drop=True)
y = y.iloc[np.flatnonzero(valid_lap_mask)].reset_index(drop=True)
laps = laps.iloc[np.flatnonzero(valid_lap_mask)].reset_index(drop=True)
compounds = compounds.iloc[
    np.flatnonzero(valid_lap_mask)
].reset_index(drop=True)

# ------------------------------------------------------------
# 6. Temporal train/test split
#    Train on earlier laps, test on later laps
# ------------------------------------------------------------

split_lap = int(laps.quantile(0.70))

train_idx = np.flatnonzero((laps <= split_lap).to_numpy())
test_idx = np.flatnonzero((laps > split_lap).to_numpy())

if len(train_idx) == 0 or len(test_idx) == 0:
    raise ValueError(
        f"Empty temporal split. Split lap: {split_lap}"
    )

X_train = X.iloc[train_idx].copy()
X_test = X.iloc[test_idx].copy()

y_train = y.iloc[train_idx].copy()
y_test = y.iloc[test_idx].copy()

train_compounds = compounds.iloc[train_idx].reset_index(drop=True)
test_compounds = compounds.iloc[test_idx].reset_index(drop=True)

# ------------------------------------------------------------
# 7. Handle missing feature values using training data only
# ------------------------------------------------------------

X_train = X_train.replace([np.inf, -np.inf], np.nan)
X_test = X_test.replace([np.inf, -np.inf], np.nan)

train_medians = X_train.median(numeric_only=True)

X_train = X_train.fillna(train_medians).fillna(0)
X_test = X_test.fillna(train_medians).fillna(0)

# Final target safety checks
assert np.isfinite(y_train.to_numpy(dtype=float)).all(), (
    "Invalid values remain in y_train."
)
assert np.isfinite(y_test.to_numpy(dtype=float)).all(), (
    "Invalid values remain in y_test."
)

print(f"\nTemporal split lap: {split_lap}")
print(f"Training rows: {len(X_train)}")
print(f"Testing rows: {len(X_test)}")
print(f"Training lap range: {laps.iloc[train_idx].min()}–"
      f"{laps.iloc[train_idx].max()}")
print(f"Testing lap range: {laps.iloc[test_idx].min()}–"
      f"{laps.iloc[test_idx].max()}")

# ------------------------------------------------------------
# 8. Train XGBoost pace model
# ------------------------------------------------------------

model = XGBRegressor(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.04,
    subsample=0.85,
    colsample_bytree=0.85,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1,
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

# ------------------------------------------------------------
# 9. Baseline: training-set median lap time by compound
# ------------------------------------------------------------

compound_medians = (
    pd.DataFrame({
        "compound": train_compounds,
        "lap_time": y_train.reset_index(drop=True),
    })
    .groupby("compound")["lap_time"]
    .median()
)

baseline_pred = test_compounds.map(
    compound_medians
).to_numpy(dtype=float)

# A test compound absent from training cannot use this baseline.
baseline_valid = np.isfinite(baseline_pred)

# ------------------------------------------------------------
# 10. Evaluate both approaches
# ------------------------------------------------------------

def metrics(name, actual, predicted):
    actual = np.asarray(actual, dtype=float)
    predicted = np.asarray(predicted, dtype=float)

    return {
        "model": name,
        "n": len(actual),
        "MAE_seconds": mean_absolute_error(actual, predicted),
        "RMSE_seconds": np.sqrt(
            mean_squared_error(actual, predicted)
        ),
        "Bias_seconds": float(np.mean(predicted - actual)),
        "R2": r2_score(actual, predicted),
    }

results = [
    metrics("Temporal XGBoost", y_test, pred)
]

if baseline_valid.any():
    results.append(
        metrics(
            "Training compound median",
            y_test.to_numpy()[baseline_valid],
            baseline_pred[baseline_valid],
        )
    )

results_df = pd.DataFrame(results)

print("\n========== TEMPORAL BACKTEST RESULTS ==========")
print(results_df.round(4).to_string(index=False))

# ------------------------------------------------------------
# 11. Inspect prediction errors
# ------------------------------------------------------------

predictions = pd.DataFrame({
    "lap_number": laps.iloc[test_idx].to_numpy(),
    "driver_number": df.loc[
        valid_lap_mask, "driver_number"
    ].to_numpy()[test_idx],
    "compound": test_compounds.to_numpy(),
    "actual_lap_time": y_test.to_numpy(),
    "predicted_lap_time": pred,
})

predictions["error_seconds"] = (
    predictions["predicted_lap_time"]
    - predictions["actual_lap_time"]
)

print("\n========== SAMPLE TEST PREDICTIONS ==========")
print(predictions.head(10).round(3).to_string(index=False))

print("\nMean absolute prediction error:",
      round(predictions["error_seconds"].abs().mean(), 3),
      "seconds")

Valid rows after cleaning: 662
Invalid lap durations remaining: 0

Temporal split lap: 39
Training rows: 466
Testing rows: 196
Training lap range: 1–39
Testing lap range: 40–52

========== TEMPORAL BACKTEST RESULTS ==========
                   model   n  MAE_seconds  RMSE_seconds  Bias_seconds      R2
        Temporal XGBoost 196       2.9537        3.0690        2.8985 -5.9105
Training compound median 196       2.9324        3.0748        2.8482 -5.9369

========== SAMPLE TEST PREDICTIONS ==========
 lap_number  driver_number compound  actual_lap_time  predicted_lap_time  error_seconds
         40              2     SOFT           91.353           93.339996          1.987
         41              2     SOFT           90.875           94.156998          3.282
         42              2     SOFT           89.972           93.988998          4.017
         43              2     SOFT           90.162           93.941002          3.779
         44              2     SOFT           90.003           94.039001          4.036
         45              2     SOFT           90.613           94.370003          3.757
         46              2     SOFT           90.826           94.383003          3.557
         47              2     SOFT           91.250           94.313004          3.063
         48              2     SOFT           91.201           94.318001          3.117
         49              2     SOFT           91.175           94.389000          3.214

Mean absolute prediction error: 2.954 seconds

In [ ]:

from pathlib import Path
import numpy as np
import pandas as pd

DATA_DIR = Path("../data/processed/9558")
SESSION = 9558

state = pd.read_parquet(DATA_DIR / "race_state.parquet")
df_diag = state[state["session_key"] == SESSION].copy()

df_diag["lap_duration"] = pd.to_numeric(
    df_diag["lap_duration"], errors="coerce"
)
df_diag["compound"] = (
    df_diag["compound"].astype("string").str.upper()
)

df_diag = df_diag[
    df_diag["lap_duration"].notna()
    & np.isfinite(df_diag["lap_duration"])
    & (df_diag["lap_duration"] > 0)
    & (~df_diag["is_pit_out_lap"].fillna(False).astype(bool))
    & df_diag["compound"].notna()
].copy()

split_lap = int(df_diag["lap_number"].quantile(0.70))
df_diag["period"] = np.where(
    df_diag["lap_number"] <= split_lap, "Train", "Test"
)

print(f"Temporal split: lap {split_lap}")
print(f"Compounds included: {sorted(df_diag['compound'].unique())}")

print("\n--- Compound distribution by period (%) ---")
print(pd.crosstab(
    df_diag["period"], df_diag["compound"], normalize="index"
).mul(100).round(1))

for col in ["rainfall", "grip_condition"]:
    if col in df_diag.columns:
        print(f"\n--- {col}: row counts by period ---")
        print(pd.crosstab(
            df_diag["period"], df_diag[col].fillna("UNKNOWN")
        ))

print("\n--- Lap-time and tyre-age summary ---")
summary_cols = ["lap_duration", "tyre_age"]
available = [c for c in summary_cols if c in df_diag.columns]

print(df_diag.groupby("period")[available].agg(
    ["count", "mean", "median", "std"]
).round(2))

print("\n--- Lap-time summary by compound and period ---")
print(df_diag.groupby(
    ["period", "compound"]
)["lap_duration"].agg(
    ["count", "mean", "median", "std"]
).round(2))

Temporal split: lap 36
Compounds included: ['HARD', 'INTERMEDIATE', 'MEDIUM', 'SOFT']

--- Compound distribution by period (%) ---
compound  HARD  INTERMEDIATE  MEDIUM  SOFT
period
Test       8.9          13.1    27.4  50.6
Train      2.7          27.0    65.5   4.7

--- rainfall: row counts by period ---
rainfall  0.0  1.0
period
Test      201   58
Train     338  317

--- grip_condition: row counts by period ---
grip_condition  LOW  NORMAL  UNKNOWN
period
Test             62     197        0
Train           272      29      354

--- Lap-time and tyre-age summary ---
       lap_duration                     tyre_age
              count   mean median   std    count   mean median   std
period
Test            259  91.84  90.74  3.19      259   7.09    8.0  3.62
Train           655  97.15  94.27  5.47      655  10.00    8.0  7.40

--- Lap-time summary by compound and period ---
                     count    mean  median   std
period compound
Test   HARD             23   89.52   89.47  0.33
       INTERMEDIATE     34   99.28   99.41  1.66
       MEDIUM           71   90.44   90.15  1.11
       SOFT            131   91.07   90.93  1.30
Train  HARD             18   93.54   92.74  2.26
       INTERMEDIATE    177  103.74  103.30  2.06
       MEDIUM          429   94.72   92.96  4.30
       SOFT             31   95.39   94.24  2.79

In [ ]:

from pathlib import Path
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from xgboost import XGBRegressor

DATA_DIR = Path("../data/processed/9558")
SESSION = 9558

# 1. Load and merge existing assets
state = pd.read_parquet(DATA_DIR / "race_state.parquet")
fuel = pd.read_parquet(DATA_DIR / "fuel_features.parquet")
traffic = pd.read_parquet(DATA_DIR / "traffic_features.parquet")
tyres = pd.read_parquet(DATA_DIR / "tyre_features.parquet")

fuel = fuel[
    ["driver_number", "lap_number", "fuel_effect"]
].drop_duplicates(["driver_number", "lap_number"])

traffic = traffic[
    ["driver_number", "lap_number", "traffic_ahead",
     "traffic_behind", "position_change"]
].drop_duplicates(["driver_number", "lap_number"])

tyres = tyres[
    ["driver_number", "lap_number", "tyre_degradation_effect"]
].drop_duplicates(["driver_number", "lap_number"])

df = state[state["session_key"] == SESSION].copy()

for asset in [fuel, traffic, tyres]:
    df = df.merge(
        asset,
        on=["driver_number", "lap_number"],
        how="left",
        validate="many_to_one",
    )

# 2. Clean target, but keep ALL tyre compounds
df["lap_duration"] = pd.to_numeric(df["lap_duration"], errors="coerce")
df["compound"] = df["compound"].astype("string").str.upper()

df = df[
    df["lap_duration"].notna()
    & np.isfinite(df["lap_duration"])
    & (df["lap_duration"] > 0)
    & (~df["is_pit_out_lap"].fillna(False).astype(bool))
    & df["compound"].notna()
].copy()

df = df.reset_index(drop=True)

# 3. Build track evolution from the previous completed lap only
field_median = df.groupby("lap_number")["lap_duration"].median().sort_index()
previous_field_median = field_median.shift(1)
df["track_evolution"] = df["lap_number"].map(previous_field_median)

# 4. Create shared features for all models
numeric_features = [
    "tyre_age",
    "tyre_degradation_effect",
    "fuel_effect",
    "traffic_ahead",
    "traffic_behind",
    "position_change",
    "track_evolution",
    "rainfall",
    "humidity",
    "air_temperature",
    "wind_speed",
]

missing = [c for c in numeric_features if c not in df.columns]
if missing:
    raise KeyError(f"Missing expected features: {missing}")

X_num = df[numeric_features].apply(pd.to_numeric, errors="coerce")
X_num = X_num.replace([np.inf, -np.inf], np.nan)

# Include compound and driver categories
compound_dummies = pd.get_dummies(
    df["compound"], prefix="compound", dtype=int
)
driver_dummies = pd.get_dummies(
    df["driver_number"].astype(str), prefix="driver", dtype=int
)

if "grip_condition" in df.columns:
    grip = df["grip_condition"].fillna("UNKNOWN").astype(str)
    grip_dummies = pd.get_dummies(grip, prefix="grip", dtype=int)
else:
    grip_dummies = pd.DataFrame(index=df.index)

X = pd.concat(
    [X_num, compound_dummies, driver_dummies, grip_dummies], axis=1
)
y = df["lap_duration"].reset_index(drop=True)
laps = pd.to_numeric(df["lap_number"], errors="coerce").reset_index(drop=True)

# 5. Temporal split: earlier laps train, later laps test
valid_lap = laps.notna().to_numpy()
X = X.iloc[np.flatnonzero(valid_lap)].reset_index(drop=True)
y = y.iloc[np.flatnonzero(valid_lap)].reset_index(drop=True)
laps = laps.iloc[np.flatnonzero(valid_lap)].reset_index(drop=True)
df = df.iloc[np.flatnonzero(valid_lap)].reset_index(drop=True)

split_lap = int(laps.quantile(0.70))
train_idx = np.flatnonzero((laps <= split_lap).to_numpy())
test_idx = np.flatnonzero((laps > split_lap).to_numpy())

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

print(f"Rows: {len(df)} | Train: {len(train_idx)} | Test: {len(test_idx)}")
print(f"Train laps: {laps.iloc[train_idx].min()}–{laps.iloc[train_idx].max()}")
print(f"Test laps: {laps.iloc[test_idx].min()}–{laps.iloc[test_idx].max()}")
print("Compounds:", sorted(df["compound"].unique()))

# 6. Models
models = {
    "Linear Regression": make_pipeline(
        SimpleImputer(strategy="median"),
        StandardScaler(),
        LinearRegression(),
    ),
    "Ridge Regression": make_pipeline(
        SimpleImputer(strategy="median"),
        StandardScaler(),
        Ridge(alpha=10.0),
    ),
    "Random Forest": make_pipeline(
        SimpleImputer(strategy="median"),
        RandomForestRegressor(
            n_estimators=400,
            min_samples_leaf=4,
            random_state=42,
            n_jobs=-1,
        ),
    ),
    "XGBoost": make_pipeline(
        SimpleImputer(strategy="median"),
        XGBRegressor(
            n_estimators=300,
            max_depth=4,
            learning_rate=0.04,
            subsample=0.85,
            colsample_bytree=0.85,
            objective="reg:squarederror",
            random_state=42,
            n_jobs=-1,
        ),
    ),
}

# Baseline: median training lap time
baseline = np.full(len(y_test), y_train.median())

results = []
predictions = pd.DataFrame({
    "lap_number": laps.iloc[test_idx].to_numpy(),
    "driver_number": df.iloc[test_idx]["driver_number"].to_numpy(),
    "compound": df.iloc[test_idx]["compound"].to_numpy(),
    "actual": y_test.to_numpy(),
})

for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    predictions[name] = pred
    results.append({
        "model": name,
        "MAE": mean_absolute_error(y_test, pred),
        "RMSE": np.sqrt(mean_squared_error(y_test, pred)),
        "Bias": np.mean(pred - y_test.to_numpy()),
        "R2": r2_score(y_test, pred),
    })

results.append({
    "model": "Training median baseline",
    "MAE": mean_absolute_error(y_test, baseline),
    "RMSE": np.sqrt(mean_squared_error(y_test, baseline)),
    "Bias": np.mean(baseline - y_test.to_numpy()),
    "R2": r2_score(y_test, baseline),
})

results_df = pd.DataFrame(results).sort_values("MAE")

print("\n===== FAIR TEMPORAL MODEL COMPARISON =====")
print(results_df.round(4).to_string(index=False))

# Keep predictions and models available for Cells 3 and 4
backtest_predictions = predictions.copy()
backtest_models = models
backtest_split_lap = split_lap
backtest_train_idx = train_idx
backtest_test_idx = test_idx

Rows: 914 | Train: 655 | Test: 259
Train laps: 1–36
Test laps: 37–52
Compounds: ['HARD', 'INTERMEDIATE', 'MEDIUM', 'SOFT']

===== FAIR TEMPORAL MODEL COMPARISON =====
                   model     MAE    RMSE     Bias       R2
Training median baseline  3.8116  4.0064   2.4330  -0.5842
           Random Forest  4.8035  5.1254   4.7707  -1.5927
                 XGBoost  4.9112  5.1935   4.8842  -1.6621
        Ridge Regression 15.3100 16.3662 -14.5800 -25.4363
       Linear Regression 20.9200 22.4471 -20.2482 -48.7311

In [ ]:

import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error

pred_df = backtest_predictions.copy()

model_names = [
    "Linear Regression",
    "Ridge Regression",
    "Random Forest",
    "XGBoost",
]

# Add conditions for the held-out rows
pred_df["rainfall"] = df.iloc[test_idx]["rainfall"].to_numpy()

if "grip_condition" in df.columns:
    pred_df["grip_condition"] = (
        df.iloc[test_idx]["grip_condition"].fillna("UNKNOWN").to_numpy()
    )
else:
    pred_df["grip_condition"] = "UNKNOWN"

pred_df["weather_group"] = np.where(
    pred_df["rainfall"].fillna(0).astype(float) > 0,
    "Rain",
    "No rain",
)

def summarize_errors(group, model_name):
    actual = group["actual"].to_numpy(dtype=float)
    predicted = group[model_name].to_numpy(dtype=float)
    return pd.Series({
        "n": len(group),
        "MAE": mean_absolute_error(actual, predicted),
        "RMSE": np.sqrt(mean_squared_error(actual, predicted)),
        "Bias": np.mean(predicted - actual),
    })

for model_name in model_names:
    print(f"\n===== {model_name}: ERROR BY COMPOUND =====")
    rows = []
    for compound, group in pred_df.groupby("compound"):
        row = summarize_errors(group, model_name)
        row["compound"] = compound
        rows.append(row)

    print(
        pd.DataFrame(rows)
        .set_index("compound")
        .sort_values("MAE")
        .round(3)
        .to_string()
    )

print("\n===== RIDGE: ERROR BY RAIN CONDITION =====")
print(
    pred_df.groupby("weather_group")
    .apply(lambda g: summarize_errors(g, "Ridge Regression"),
           include_groups=False)
    .round(3)
    .to_string()
)

print("\n===== RIDGE: ERROR BY COMPOUND AND GRIP =====")
print(
    pred_df.groupby(["compound", "grip_condition"])
    .apply(lambda g: summarize_errors(g, "Ridge Regression"),
           include_groups=False)
    .round(3)
    .to_string()
)

# Inspect the largest Ridge errors
pred_df["ridge_error"] = (
    pred_df["Ridge Regression"] - pred_df["actual"]
)

print("\n===== 15 LARGEST ABSOLUTE RIDGE ERRORS =====")
print(
    pred_df.assign(abs_error=pred_df["ridge_error"].abs())
    .sort_values("abs_error", ascending=False)
    [[
        "lap_number", "driver_number", "compound", "rainfall",
        "grip_condition", "actual", "Ridge Regression", "ridge_error"
    ]]
    .head(15)
    .round(3)
    .to_string(index=False)
)

===== Linear Regression: ERROR BY COMPOUND =====
                  n     MAE    RMSE    Bias
compound
INTERMEDIATE   34.0   2.735   2.970   2.382
MEDIUM         71.0  21.231  21.664 -21.231
HARD           23.0  24.783  25.015 -24.783
SOFT          131.0  24.793  25.094 -24.793

===== Ridge Regression: ERROR BY COMPOUND =====
                  n     MAE    RMSE    Bias
compound
INTERMEDIATE   34.0   2.877   3.046   2.685
MEDIUM         71.0  15.170  15.531 -15.170
SOFT          131.0  18.069  18.324 -18.069
HARD           23.0  18.406  18.588 -18.406

===== Random Forest: ERROR BY COMPOUND =====
                  n    MAE   RMSE   Bias
compound
INTERMEDIATE   34.0  3.530  3.948  3.530
MEDIUM         71.0  3.817  4.138  3.762
SOFT          131.0  5.461  5.650  5.426
HARD           23.0  5.986  6.174  5.986

===== XGBoost: ERROR BY COMPOUND =====
                  n    MAE   RMSE   Bias
compound
INTERMEDIATE   34.0  3.268  3.641  3.268
MEDIUM         71.0  4.456  4.662  4.423
HARD           23.0  5.059  5.244  5.059
SOFT          131.0  5.559  5.769  5.523

===== RIDGE: ERROR BY RAIN CONDITION =====
                   n     MAE    RMSE    Bias
weather_group
No rain        201.0  18.118  18.244 -18.118
Rain            58.0   5.578   6.525  -2.318

===== RIDGE: ERROR BY COMPOUND AND GRIP =====
                                 n     MAE    RMSE    Bias
compound     grip_condition
HARD         LOW               3.0  19.438  19.481 -19.438
             NORMAL           20.0  18.252  18.451 -18.252
INTERMEDIATE LOW              34.0   2.877   3.046   2.685
MEDIUM       LOW               9.0  17.131  17.188 -17.131
             NORMAL           62.0  14.885  15.275 -14.885
SOFT         LOW              16.0  19.153  19.200 -19.153
             NORMAL          115.0  17.919  18.199 -17.919

===== 15 LARGEST ABSOLUTE RIDGE ERRORS =====
 lap_number  driver_number compound  rainfall grip_condition  actual  Ridge Regression  ridge_error
         49             11     SOFT       0.0         NORMAL  97.360            70.586      -26.774
         39             77     SOFT       0.0            LOW  97.114            74.993      -22.121
         41             27     SOFT       0.0            LOW  91.097            69.443      -21.654
         50              3     SOFT       0.0         NORMAL  94.150            72.579      -21.571
         51              3     SOFT       0.0         NORMAL  94.814            73.301      -21.513
         41             55     HARD       0.0            LOW  90.475            69.199      -21.276
         52             55     SOFT       0.0         NORMAL  88.293            67.211      -21.082
         45             77     SOFT       0.0         NORMAL  93.159            72.108      -21.051
         51              4     SOFT       0.0         NORMAL  90.769            69.735      -21.034
         46              4     SOFT       0.0         NORMAL  89.960            68.937      -21.023
         50              4     SOFT       0.0         NORMAL  90.544            69.643      -20.901
         46             44     SOFT       0.0         NORMAL  89.641            69.008      -20.633
         41             22     SOFT       0.0            LOW  90.812            70.211      -20.601
         49              3     SOFT       0.0         NORMAL  92.926            72.354      -20.572
         47              4     SOFT       0.0         NORMAL  89.838            69.340      -20.498

In [ ]:

import numpy as np
import pandas as pd
from pathlib import Path

DATA_DIR = Path("../data/processed/9558")
SESSION = 9558

state = pd.read_parquet(DATA_DIR / "race_state.parquet")
race = state[state["session_key"] == SESSION].copy()

race["compound"] = race["compound"].astype("string").str.upper()
race["lap_number"] = pd.to_numeric(race["lap_number"], errors="coerce")
race["tyre_age"] = pd.to_numeric(race["tyre_age"], errors="coerce")
race["position"] = pd.to_numeric(race["position"], errors="coerce")

race = race.sort_values(
    ["driver_number", "lap_number"]
).reset_index(drop=True)

# Next recorded state for each driver
by_driver = race.groupby("driver_number", sort=False)

race["next_lap"] = by_driver["lap_number"].shift(-1)
race["next_compound"] = by_driver["compound"].shift(-1)
race["next_tyre_age"] = by_driver["tyre_age"].shift(-1)
race["next_position"] = by_driver["position"].shift(-1)
race["next_is_pit_out"] = (
    by_driver["is_pit_out_lap"].shift(-1).fillna(False).astype(bool)
)

# Flag a likely stop between this row and the next recorded row.
# A gap in recorded laps alone is not enough to prove a pit stop.
age_reset = (
    race["next_tyre_age"].notna()
    & race["tyre_age"].notna()
    & (race["next_tyre_age"] < race["tyre_age"])
)

compound_change = (
    race["next_compound"].notna()
    & race["compound"].notna()
    & (race["next_compound"] != race["compound"])
)

pit_event_mask = (
    race["next_is_pit_out"]
    | age_reset
    | compound_change
)

pit_events = race.loc[pit_event_mask, [
    "driver_number",
    "lap_number",
    "position",
    "compound",
    "tyre_age",
    "rainfall",
    "grip_condition",
    "next_lap",
    "next_position",
    "next_compound",
    "next_tyre_age",
    "next_is_pit_out",
]].copy()

pit_events = pit_events.rename(columns={
    "lap_number": "decision_lap",
    "position": "position_before",
    "compound": "compound_before",
    "tyre_age": "tyre_age_before",
    "next_lap": "next_recorded_lap",
    "next_position": "position_next_recorded_lap",
    "next_compound": "compound_after",
    "next_tyre_age": "tyre_age_after",
})

pit_events["position_change_next_recorded_lap"] = (
    pit_events["position_before"]
    - pit_events["position_next_recorded_lap"]
)

print("===== OBSERVED PIT-EVENT CANDIDATES =====")
print("Events found:", len(pit_events))

print(pit_events.head(25).round(2).to_string(index=False))

print("\n===== EVENTS BY COMPOUND TRANSITION =====")
if not pit_events.empty:
    print(
        pit_events.groupby(
            ["compound_before", "compound_after"],
            dropna=False,
        ).size().sort_values(ascending=False).to_string()
    )

# Save for the next strategy-replay stage
output_path = DATA_DIR / "historical_pit_events.parquet"
pit_events.to_parquet(output_path, index=False)

print(f"\nSaved event candidates to: {output_path}")

===== OBSERVED PIT-EVENT CANDIDATES =====
Events found: 45
 driver_number  decision_lap  position_before compound_before  tyre_age_before  rainfall grip_condition  next_recorded_lap  position_next_recorded_lap compound_after  tyre_age_after  next_is_pit_out  position_change_next_recorded_lap
             1            26              5.0          MEDIUM             25.0       1.0            LOW               27.0                         5.0   INTERMEDIATE             0.0             True                                0.0
             1            38              3.0    INTERMEDIATE             11.0       1.0            LOW               39.0                         3.0           HARD             0.0             True                                0.0
             2            27             13.0          MEDIUM             26.0       1.0            LOW               28.0                        11.0   INTERMEDIATE             0.0             True                                2.0
             2            38             13.0    INTERMEDIATE             10.0       1.0            LOW               39.0                        11.0           SOFT             0.0             True                                2.0
             3            26             14.0          MEDIUM             25.0       1.0            LOW               27.0                        14.0   INTERMEDIATE             0.0             True                                0.0
             3            37             13.0    INTERMEDIATE             10.0       1.0            LOW               38.0                        13.0           SOFT             0.0             True                                0.0
             4            27              1.0          MEDIUM             26.0       1.0            LOW               28.0                         1.0   INTERMEDIATE             0.0             True                                0.0
             4            39              1.0    INTERMEDIATE             11.0       1.0            LOW               40.0                         1.0           SOFT             0.0             True                                0.0
            11            19             15.0            HARD             18.0       1.0            LOW               20.0                        15.0   INTERMEDIATE             0.0             True                                0.0
            11            28             17.0    INTERMEDIATE              8.0       1.0            LOW               29.0                        16.0   INTERMEDIATE             0.0             True                                1.0
            11            37             16.0    INTERMEDIATE              8.0       1.0            LOW               38.0                        16.0         MEDIUM             0.0             True                                0.0
            11            47             16.0          MEDIUM              9.0       0.0         NORMAL               48.0                        16.0           SOFT             0.0             True                                0.0
            14            27              9.0          MEDIUM             26.0       1.0            LOW               28.0                         7.0   INTERMEDIATE             0.0             True                                2.0
            14            38              8.0    INTERMEDIATE             10.0       1.0            LOW               39.0                         8.0         MEDIUM             0.0             True                                0.0
            16            19              7.0          MEDIUM             18.0       1.0            NaN               20.0                         7.0   INTERMEDIATE             0.0             True                                0.0
            16            27             16.0    INTERMEDIATE              7.0       1.0            LOW               28.0                        16.0   INTERMEDIATE             0.0             True                                0.0
            16            37             15.0    INTERMEDIATE              9.0       1.0            LOW               38.0                        15.0           SOFT             0.0             True                                0.0
            18            26              9.0          MEDIUM             25.0       1.0            LOW               27.0                         8.0   INTERMEDIATE             0.0             True                                1.0
            18            39              7.0    INTERMEDIATE             12.0       1.0            LOW               40.0                         7.0         MEDIUM             0.0             True                                0.0
            20            27             12.0          MEDIUM             26.0       1.0            LOW               28.0                        10.0   INTERMEDIATE             0.0             True                                2.0
            20            37             11.0    INTERMEDIATE              9.0       1.0            LOW               38.0                        11.0           SOFT             0.0             True                                0.0
            22            27             10.0          MEDIUM             26.0       1.0            LOW               28.0                         8.0   INTERMEDIATE             0.0             True                                2.0
            22            38              9.0    INTERMEDIATE             10.0       1.0            LOW               39.0                         9.0           SOFT             0.0             True                                0.0
            23            27             11.0          MEDIUM             26.0       1.0            LOW               28.0                         9.0   INTERMEDIATE             0.0             True                                2.0
            23            38             10.0    INTERMEDIATE             10.0       1.0            LOW               39.0                        10.0         MEDIUM             0.0             True                                0.0

===== EVENTS BY COMPOUND TRANSITION =====
compound_before  compound_after
MEDIUM           INTERMEDIATE      18
INTERMEDIATE     SOFT              10
                 MEDIUM             7
                 INTERMEDIATE       3
                 HARD               2
HARD             INTERMEDIATE       1
                 SOFT               1
MEDIUM           SOFT               1
SOFT             INTERMEDIATE       1
                 MEDIUM             1

Saved event candidates to: ..\data\processed\9558\historical_pit_events.parquet

In [ ]:

import numpy as np
import pandas as pd

ridge_model = backtest_models["Ridge Regression"]
ridge_estimator = ridge_model[-1]

# Check target and prediction distributions
ridge_train_pred = ridge_model.predict(X_train)
ridge_test_pred = ridge_model.predict(X_test)

distribution = pd.DataFrame({
    "Actual train": pd.Series(y_train).describe(),
    "Predicted train": pd.Series(ridge_train_pred).describe(),
    "Actual test": pd.Series(y_test).describe(),
    "Predicted test": pd.Series(ridge_test_pred).describe(),
})

print("===== TARGET VS PREDICTION DISTRIBUTIONS =====")
print(distribution.round(3).to_string())

print("\n===== TRAINING ERROR =====")
print("Train MAE:", round(
    np.mean(np.abs(ridge_train_pred - y_train.to_numpy())), 3
))
print("Test MAE:", round(
    np.mean(np.abs(ridge_test_pred - y_test.to_numpy())), 3
))

# Inspect coefficients from the fitted Ridge pipeline
feature_names = X_train.columns
coefficients = pd.Series(
    ridge_estimator.coef_,
    index=feature_names,
)

print("\n===== 15 LARGEST POSITIVE COEFFICIENTS =====")
print(coefficients.sort_values(ascending=False).head(15).round(3))

print("\n===== 15 LARGEST NEGATIVE COEFFICIENTS =====")
print(coefficients.sort_values().head(15).round(3))

# Verify row alignment and compound-wise prediction ranges
check = pd.DataFrame({
    "lap_number": laps.iloc[test_idx].to_numpy(),
    "driver_number": df.iloc[test_idx]["driver_number"].to_numpy(),
    "compound": df.iloc[test_idx]["compound"].to_numpy(),
    "actual": y_test.to_numpy(),
    "ridge_pred": ridge_test_pred,
})

print("\n===== RIDGE PREDICTIONS BY COMPOUND =====")
print(check.groupby("compound").agg(
    n=("actual", "size"),
    actual_mean=("actual", "mean"),
    predicted_mean=("ridge_pred", "mean"),
    actual_min=("actual", "min"),
    predicted_min=("ridge_pred", "min"),
    actual_max=("actual", "max"),
    predicted_max=("ridge_pred", "max"),
).round(3).to_string())

===== TARGET VS PREDICTION DISTRIBUTIONS =====
       Actual train  Predicted train  Actual test  Predicted test
count       655.000          655.000      259.000         259.000
mean         97.154           97.154       91.836          77.256
std           5.466            4.678        3.189          10.145
min          90.860           90.909       88.293          67.211
25%          92.648           93.289       89.946          71.537
50%          94.269           95.226       90.735          73.111
75%         102.594          102.147       91.705          77.059
max         118.710          107.779      102.235         105.513

===== TRAINING ERROR =====
Train MAE: 1.725
Test MAE: 15.31

===== 15 LARGEST POSITIVE COEFFICIENTS =====
rainfall                   4.649
fuel_effect                2.100
grip_UNKNOWN               1.898
tyre_degradation_effect    1.551
compound_INTERMEDIATE      1.494
track_evolution            1.033
driver_31                  0.693
driver_24                  0.678
tyre_age                   0.486
driver_11                  0.405
driver_77                  0.238
driver_3                   0.120
driver_16                  0.117
traffic_behind             0.070
position_change            0.067
dtype: float64

===== 15 LARGEST NEGATIVE COEFFICIENTS =====
grip_LOW          -1.700
air_temperature   -1.371
humidity          -1.132
compound_MEDIUM   -0.850
compound_SOFT     -0.767
wind_speed        -0.702
compound_HARD     -0.591
grip_NORMAL       -0.525
driver_44         -0.375
driver_4          -0.357
driver_1          -0.314
driver_63         -0.285
driver_81         -0.255
driver_55         -0.254
driver_27         -0.138
dtype: float64

===== RIDGE PREDICTIONS BY COMPOUND =====
                n  actual_mean  predicted_mean  actual_min  predicted_min  actual_max  predicted_max
compound
HARD           23       89.522          71.116      88.952         69.199      90.475         79.150
INTERMEDIATE   34       99.280         101.965      95.963         96.176     102.235        105.513
MEDIUM         71       90.442          75.273      88.748         71.380      95.931         85.543
SOFT          131       91.066          72.996      88.293         67.211      97.360         83.627

In [ ]:

import numpy as np
import pandas as pd

# Compare numeric feature distributions between train and test
numeric_cols = X_train.select_dtypes(include=np.number).columns

shift_rows = []

for col in numeric_cols:
    train_values = X_train[col].replace([np.inf, -np.inf], np.nan).dropna()
    test_values = X_test[col].replace([np.inf, -np.inf], np.nan).dropna()

    if len(train_values) == 0 or len(test_values) == 0:
        continue

    train_std = train_values.std()
    test_std = test_values.std()

    shift_rows.append({
        "feature": col,
        "train_mean": train_values.mean(),
        "test_mean": test_values.mean(),
        "train_std": train_std,
        "test_std": test_std,
        "mean_shift_in_train_sd": (
            (test_values.mean() - train_values.mean()) / train_std
            if pd.notna(train_std) and train_std > 1e-9
            else np.nan
        ),
    })

shift_df = pd.DataFrame(shift_rows)

print("===== LARGEST NUMERIC FEATURE SHIFTS =====")
print(
    shift_df.assign(
        abs_shift=lambda d: d["mean_shift_in_train_sd"].abs()
    )
    .sort_values("abs_shift", ascending=False)
    .drop(columns="abs_shift")
    .head(20)
    .round(3)
    .to_string(index=False)
)

# Check whether the target range differs by compound and period
target_check = df[["lap_number", "compound", "lap_duration"]].copy()
target_check["period"] = np.where(
    target_check["lap_number"] <= backtest_split_lap,
    "Train",
    "Test",
)

print("\n===== TARGET BY COMPOUND AND PERIOD =====")
print(
    target_check.groupby(["period", "compound"])["lap_duration"]
    .agg(["count", "mean", "median", "std"])
    .round(3)
    .to_string()
)

===== LARGEST NUMERIC FEATURE SHIFTS =====
                feature  train_mean  test_mean  train_std  test_std  mean_shift_in_train_sd
            fuel_effect      -1.012     -3.757      0.619     0.312                  -4.436
            grip_NORMAL       0.044      0.761      0.206     0.428                   3.480
          compound_SOFT       0.047      0.506      0.213     0.501                   2.157
               humidity      65.249     72.575      5.357     2.858                   1.368
           grip_UNKNOWN       0.540      0.000      0.499     0.000                  -1.084
        track_evolution      96.586     92.349      4.917     3.920                  -0.862
        compound_MEDIUM       0.655      0.274      0.476     0.447                  -0.800
tyre_degradation_effect       2.559      1.432      1.552     0.791                  -0.726
        air_temperature      15.803     15.372      0.786     0.403                  -0.549
               rainfall       0.484      0.224      0.500     0.418                  -0.520
               tyre_age      10.002      7.089      7.399     3.623                  -0.394
          compound_HARD       0.027      0.089      0.164     0.285                   0.375
               grip_LOW       0.415      0.239      0.493     0.428                  -0.357
  compound_INTERMEDIATE       0.270      0.131      0.444     0.338                  -0.313
              driver_63       0.049      0.000      0.216     0.000                  -0.226
             wind_speed       1.515      1.465      0.474     0.442                  -0.105
         traffic_behind       0.423      0.382      0.494     0.487                  -0.082
          traffic_ahead       0.948      0.938      0.222     0.241                  -0.044
        position_change       0.000      0.027      0.738     0.378                   0.037
               driver_1       0.053      0.058      0.225     0.234                   0.020

===== TARGET BY COMPOUND AND PERIOD =====
                     count     mean   median    std
period compound
Test   HARD             23   89.522   89.472  0.335
       INTERMEDIATE     34   99.280   99.406  1.659
       MEDIUM           71   90.442   90.148  1.112
       SOFT            131   91.066   90.929  1.305
Train  HARD             18   93.540   92.740  2.265
       INTERMEDIATE    177  103.741  103.302  2.065
       MEDIUM          429   94.715   92.956  4.299
       SOFT             31   95.386   94.235  2.790

In [ ]:

import numpy as np
import pandas as pd

fuel_path = DATA_DIR / "fuel_features.parquet"
fuel_raw = pd.read_parquet(fuel_path)

print("===== RAW FUEL FEATURE DATA =====")
print("Shape:", fuel_raw.shape)
print("Columns:", fuel_raw.columns.tolist())
print(fuel_raw.head(10).to_string(index=False))

print("\n===== FUEL EFFECT DISTRIBUTION BY LAP =====")
if {"lap_number", "fuel_effect"}.issubset(fuel_raw.columns):
    print(
        fuel_raw.groupby("lap_number")["fuel_effect"]
        .agg(["count", "mean", "median", "min", "max", "std"])
        .loc[lambda x: x.index.isin([1, 5, 10, 15, 20, 25, 30, 35, 36, 40, 45, 50, 52])]
        .round(3)
        .to_string()
    )

print("\n===== FUEL EFFECT BY TEMPORAL SPLIT =====")
if {"lap_number", "fuel_effect"}.issubset(fuel_raw.columns):
    fuel_raw = fuel_raw.copy()
    fuel_raw["period"] = np.where(
        fuel_raw["lap_number"] <= backtest_split_lap, "Train", "Test"
    )
    print(
        fuel_raw.groupby("period")["fuel_effect"]
        .agg(["count", "mean", "median", "std", "min", "max"])
        .round(3)
        .to_string()
    )

print("\n===== FUEL EFFECT VARIATION WITHIN EACH LAP =====")
if {"lap_number", "fuel_effect"}.issubset(fuel_raw.columns):
    per_lap = fuel_raw.groupby("lap_number")["fuel_effect"].agg(
        ["mean", "std", "min", "max", "count"]
    )
    print(per_lap.loc[per_lap["std"].fillna(0) > 0.05].head(20).round(3).to_string())

print("\n===== MERGED MODEL DATA: FUEL EFFECT BY LAP =====")
if {"lap_number", "fuel_effect"}.issubset(df.columns):
    print(
        df.groupby("lap_number")["fuel_effect"]
        .agg(["mean", "median", "min", "max", "count"])
        .loc[lambda x: x.index.isin([1, 5, 10, 15, 20, 25, 30, 35, 36, 37, 40, 45, 50, 52])]
        .round(3)
        .to_string()
    )
else:
    print("The merged df does not contain both lap_number and fuel_effect.")

===== RAW FUEL FEATURE DATA =====
Shape: (692, 3)
Columns: ['driver_number', 'lap_number', 'fuel_effect']
 driver_number  lap_number  fuel_effect
             1           1    -0.000000
             1           2    -0.084122
             1           3    -0.168244
             1           4    -0.252366
             1           5    -0.336488
             1           6    -0.420610
             1           7    -0.504732
             1           8    -0.588854
             1           9    -0.672976
             1          10    -0.757098

===== FUEL EFFECT DISTRIBUTION BY LAP =====
            count   mean  median    min    max  std
lap_number
1              18  0.000  -0.000 -0.000 -0.000  0.0
5              19 -0.336  -0.336 -0.336 -0.336  0.0
10             19 -0.757  -0.757 -0.757 -0.757  0.0
15             19 -1.178  -1.178 -1.178 -1.178  0.0
20             15 -1.598  -1.598 -1.598 -1.598  0.0
25             16 -2.019  -2.019 -2.019 -2.019  0.0
40             14 -3.281  -3.281 -3.281 -3.281  0.0
45             18 -3.701  -3.701 -3.701 -3.701  0.0
50             18 -4.122  -4.122 -4.122 -4.122  0.0
52             12 -4.290  -4.290 -4.290 -4.290  0.0

===== FUEL EFFECT BY TEMPORAL SPLIT =====
        count   mean  median    std    min    max
period
Test      225 -3.757  -3.785  0.312 -4.290 -3.197
Train     467 -1.012  -1.009  0.619 -2.103 -0.000

===== FUEL EFFECT VARIATION WITHIN EACH LAP =====
Empty DataFrame
Columns: [mean, std, min, max, count]
Index: []

===== MERGED MODEL DATA: FUEL EFFECT BY LAP =====
             mean  median    min    max  count
lap_number
1           0.000  -0.000 -0.000 -0.000     18
5          -0.336  -0.336 -0.336 -0.336     19
10         -0.757  -0.757 -0.757 -0.757     19
15         -1.178  -1.178 -1.178 -1.178     19
20         -1.598  -1.598 -1.598 -1.598     15
25         -2.019  -2.019 -2.019 -2.019     16
30            NaN     NaN    NaN    NaN      0
35            NaN     NaN    NaN    NaN      0
36            NaN     NaN    NaN    NaN      0
37            NaN     NaN    NaN    NaN      0
40         -3.281  -3.281 -3.281 -3.281     14
45         -3.701  -3.701 -3.701 -3.701     18
50         -4.122  -4.122 -4.122 -4.122     18
52         -4.290  -4.290 -4.290 -4.290     12

In [ ]:

import numpy as np
import pandas as pd

fuel_raw = pd.read_parquet(DATA_DIR / "fuel_features.parquet")

print("===== FUEL EFFECT FORMULA CHECK =====")
fuel_lap = (
    fuel_raw.groupby("lap_number")["fuel_effect"]
    .agg(["mean", "min", "max", "count"])
    .reset_index()
    .sort_values("lap_number")
)

fuel_lap["change_from_previous_lap"] = fuel_lap["mean"].diff()
print(fuel_lap.head(12).round(4).to_string(index=False))
print("\nLast 12 laps:")
print(fuel_lap.tail(12).round(4).to_string(index=False))

print("\n===== CORRELATION WITH LAP NUMBER =====")
print(
    fuel_raw[["lap_number", "fuel_effect"]]
    .corr()
    .round(4)
    .to_string()
)

print("\n===== FUEL EFFECT COVERAGE BY LAP =====")
coverage = fuel_raw.groupby("lap_number")["driver_number"].nunique()
print("First available lap:", coverage.index.min())
print("Last available lap:", coverage.index.max())
print("Number of laps:", len(coverage))
print("Laps with no fuel records in 1..52:",
      sorted(set(range(1, 53)) - set(coverage.index)))
print("Driver counts per lap:")
print(coverage.value_counts().sort_index().to_string())

print("\n===== JOIN COVERAGE =====")
lap_keys = pd.read_parquet(DATA_DIR / "lap_performance.parquet")
print("lap_performance columns:", lap_keys.columns.tolist())
print("lap_performance shape:", lap_keys.shape)

if {"driver_number", "lap_number"}.issubset(lap_keys.columns):
    perf_keys = lap_keys[["driver_number", "lap_number"]].drop_duplicates()
    fuel_keys = fuel_raw[["driver_number", "lap_number"]].drop_duplicates()

    overlap = perf_keys.merge(
        fuel_keys,
        on=["driver_number", "lap_number"],
        how="inner"
    )

    print("Unique lap-performance keys:", len(perf_keys))
    print("Unique fuel keys:", len(fuel_keys))
    print("Overlapping keys:", len(overlap))
    print("Performance keys without fuel:",
          len(perf_keys.merge(
              fuel_keys,
              on=["driver_number", "lap_number"],
              how="left",
              indicator=True
          ).query("_merge == 'left_only'")))

===== FUEL EFFECT FORMULA CHECK =====
 lap_number    mean     min     max  count  change_from_previous_lap
          1  0.0000 -0.0000 -0.0000     18                       NaN
          2 -0.0841 -0.0841 -0.0841     19                   -0.0841
          3 -0.1682 -0.1682 -0.1682     19                   -0.0841
          4 -0.2524 -0.2524 -0.2524     19                   -0.0841
          5 -0.3365 -0.3365 -0.3365     19                   -0.0841
          6 -0.4206 -0.4206 -0.4206     19                   -0.0841
          7 -0.5047 -0.5047 -0.5047     19                   -0.0841
          8 -0.5889 -0.5889 -0.5889     19                   -0.0841
          9 -0.6730 -0.6730 -0.6730     19                   -0.0841
         10 -0.7571 -0.7571 -0.7571     19                   -0.0841
         11 -0.8412 -0.8412 -0.8412     19                   -0.0841
         12 -0.9253 -0.9253 -0.9253     19                   -0.0841

Last 12 laps:
 lap_number    mean     min     max  count  change_from_previous_lap
         41 -3.3649 -3.3649 -3.3649     18                   -0.0841
         42 -3.4490 -3.4490 -3.4490     18                   -0.0841
         43 -3.5331 -3.5331 -3.5331     18                   -0.0841
         44 -3.6172 -3.6172 -3.6172     18                   -0.0841
         45 -3.7014 -3.7014 -3.7014     18                   -0.0841
         46 -3.7855 -3.7855 -3.7855     18                   -0.0841
         47 -3.8696 -3.8696 -3.8696     18                   -0.0841
         48 -3.9537 -3.9537 -3.9537     17                   -0.0841
         49 -4.0379 -4.0379 -4.0379     18                   -0.0841
         50 -4.1220 -4.1220 -4.1220     18                   -0.0841
         51 -4.2061 -4.2061 -4.2061     14                   -0.0841
         52 -4.2902 -4.2902 -4.2902     12                   -0.0841

===== CORRELATION WITH LAP NUMBER =====
             lap_number  fuel_effect
lap_number          1.0         -1.0
fuel_effect        -1.0          1.0

===== FUEL EFFECT COVERAGE BY LAP =====
First available lap: 1
Last available lap: 52
Number of laps: 40
Laps with no fuel records in 1..52: [27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]
Driver counts per lap:
driver_number
6      1
12     1
14     2
15     4
16     3
17     1
18    11
19    17

===== JOIN COVERAGE =====
lap_performance columns: ['meeting_key', 'session_key', 'driver_number', 'lap_number', 'date_start', 'duration_sector_1', 'duration_sector_2', 'duration_sector_3', 'i1_speed', 'i2_speed', 'is_pit_out_lap', 'lap_duration', 'segments_sector_1', 'segments_sector_2', 'segments_sector_3', 'st_speed', 'stint_number', 'compound', 'tyre_age']
lap_performance shape: (962, 19)
Unique lap-performance keys: 962
Unique fuel keys: 692
Overlapping keys: 692
Performance keys without fuel: 270

In [ ]:

import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.metrics import mean_absolute_error, mean_squared_error

# ============================================================
# CELL 7: ROLLING-ORIGIN TEMPORAL BACKTEST
# ============================================================

# Reuse the feature matrix and target from Cell 2.
# X and y should have the same row order as df.
assert len(X) == len(y) == len(df), (
    f"Length mismatch: X={len(X)}, y={len(y)}, df={len(df)}"
)

backtest_df = df[["lap_number", "compound", "rainfall", "lap_duration"]].copy()
backtest_df = backtest_df.reset_index(drop=True)

X_bt = X.reset_index(drop=True).copy()
y_bt = pd.Series(np.asarray(y), name="lap_duration")

# Keep rows with finite target values.
valid = np.isfinite(pd.to_numeric(y_bt, errors="coerce"))
backtest_df = backtest_df.loc[valid].reset_index(drop=True)
X_bt = X_bt.loc[valid].reset_index(drop=True)
y_bt = y_bt.loc[valid].reset_index(drop=True)

# Chronological validation windows.
# Each fold trains only on earlier laps and predicts a later block.
folds = [
    (15, 16, 24),
    (24, 25, 32),
    (32, 33, 40),
    (40, 41, 46),
    (46, 47, 52),
]

# Reuse the pipelines from Cell 2.
models_bt = {
    name: clone(model)
    for name, model in backtest_models.items()
    if name in ["Linear Regression", "Ridge Regression",
                "Random Forest", "XGBoost"]
}

prediction_rows = []

for train_end, test_start, test_end in folds:
    train_mask = backtest_df["lap_number"] <= train_end
    test_mask = (
        (backtest_df["lap_number"] >= test_start)
        & (backtest_df["lap_number"] <= test_end)
    )

    X_train_fold = X_bt.loc[train_mask]
    y_train_fold = y_bt.loc[train_mask]
    X_test_fold = X_bt.loc[test_mask]
    y_test_fold = y_bt.loc[test_mask]

    if len(X_train_fold) == 0 or len(X_test_fold) == 0:
        print(f"Skipping fold {train_end}->{test_start}-{test_end}: empty split")
        continue

    print(
        f"Fold train laps <= {train_end}, "
        f"test laps {test_start}-{test_end}: "
        f"{len(X_train_fold)} train rows, {len(X_test_fold)} test rows"
    )

    # Baseline: median lap time from the training period.
    baseline_pred = np.full(
        len(y_test_fold),
        float(y_train_fold.median())
    )

    for actual_idx, prediction in zip(y_test_fold.index, baseline_pred):
        prediction_rows.append({
            "fold": f"{test_start}-{test_end}",
            "model": "Training median baseline",
            "row_idx": actual_idx,
            "actual": float(y_bt.loc[actual_idx]),
            "predicted": float(prediction),
        })

    # Fit and evaluate each model.
    for model_name, model in models_bt.items():
        model.fit(X_train_fold, y_train_fold)
        predictions = model.predict(X_test_fold)

        for actual_idx, prediction in zip(y_test_fold.index, predictions):
            prediction_rows.append({
                "fold": f"{test_start}-{test_end}",
                "model": model_name,
                "row_idx": actual_idx,
                "actual": float(y_bt.loc[actual_idx]),
                "predicted": float(prediction),
            })

rolling_predictions = pd.DataFrame(prediction_rows)

rolling_predictions = rolling_predictions.merge(
    backtest_df[["lap_number", "compound", "rainfall"]],
    left_on="row_idx",
    right_index=True,
    how="left",
    validate="many_to_one"
)

rolling_predictions["error"] = (
    rolling_predictions["predicted"] - rolling_predictions["actual"]
)
rolling_predictions["abs_error"] = rolling_predictions["error"].abs()
rolling_predictions["squared_error"] = rolling_predictions["error"] ** 2

# ============================================================
# OVERALL ROLLING BACKTEST RESULTS
# ============================================================

overall_results = (
    rolling_predictions.groupby("model")
    .apply(
        lambda g: pd.Series({
            "n": len(g),
            "MAE": mean_absolute_error(g["actual"], g["predicted"]),
            "RMSE": np.sqrt(mean_squared_error(g["actual"], g["predicted"])),
            "Bias": g["error"].mean(),
        }),
        include_groups=False
    )
    .sort_values("MAE")
)

print("\n===== OVERALL ROLLING TEMPORAL BACKTEST =====")
print(overall_results.round(3).to_string())

# ============================================================
# PERFORMANCE BY TEST WINDOW
# ============================================================

fold_results = (
    rolling_predictions.groupby(["fold", "model"])
    .apply(
        lambda g: pd.Series({
            "n": len(g),
            "MAE": mean_absolute_error(g["actual"], g["predicted"]),
            "RMSE": np.sqrt(mean_squared_error(g["actual"], g["predicted"])),
            "Bias": g["error"].mean(),
        }),
        include_groups=False
    )
    .reset_index()
)

print("\n===== PERFORMANCE BY TEMPORAL FOLD =====")
print(
    fold_results.sort_values(["fold", "MAE"])
    .round(3)
    .to_string(index=False)
)

# ============================================================
# PERFORMANCE BY COMPOUND
# ============================================================

compound_results = (
    rolling_predictions.groupby(["model", "compound"])
    .apply(
        lambda g: pd.Series({
            "n": len(g),
            "MAE": mean_absolute_error(g["actual"], g["predicted"]),
            "RMSE": np.sqrt(mean_squared_error(g["actual"], g["predicted"])),
            "Bias": g["error"].mean(),
        }),
        include_groups=False
    )
    .reset_index()
)

print("\n===== PERFORMANCE BY COMPOUND =====")
print(
    compound_results.sort_values(["compound", "MAE"])
    .round(3)
    .to_string(index=False)
)

# ============================================================
# PERFORMANCE BY WEATHER
# ============================================================

rolling_predictions["weather_regime"] = np.where(
    rolling_predictions["rainfall"].fillna(0).astype(float) > 0,
    "Rain",
    "No rain"
)

weather_results = (
    rolling_predictions.groupby(["model", "weather_regime"])
    .apply(
        lambda g: pd.Series({
            "n": len(g),
            "MAE": mean_absolute_error(g["actual"], g["predicted"]),
            "RMSE": np.sqrt(mean_squared_error(g["actual"], g["predicted"])),
            "Bias": g["error"].mean(),
        }),
        include_groups=False
    )
    .reset_index()
)

print("\n===== PERFORMANCE BY RAINFALL FLAG =====")
print(
    weather_results.sort_values(["weather_regime", "MAE"])
    .round(3)
    .to_string(index=False)
)

# Save predictions and summary tables for the strategy work.
rolling_predictions.to_parquet(
    DATA_DIR / "rolling_temporal_predictions.parquet",
    index=False
)
fold_results.to_csv(DATA_DIR / "rolling_temporal_fold_results.csv", index=False)
compound_results.to_csv(DATA_DIR / "rolling_temporal_compound_results.csv", index=False)
weather_results.to_csv(DATA_DIR / "rolling_temporal_weather_results.csv", index=False)

print("\nSaved rolling temporal backtest outputs to:", DATA_DIR)

Fold train laps <= 15, test laps 16-24: 283 train rows, 166 test rows
Fold train laps <= 24, test laps 25-32: 449 train rows, 133 test rows
Fold train laps <= 32, test laps 33-40: 582 train rows, 127 test rows
Fold train laps <= 40, test laps 41-46: 709 train rows, 108 test rows
Fold train laps <= 46, test laps 47-52: 817 train rows, 97 test rows

===== OVERALL ROLLING TEMPORAL BACKTEST =====
                              n    MAE   RMSE   Bias
model
XGBoost                   631.0  3.191  4.694  0.046
Random Forest             631.0  3.241  4.401  0.717
Ridge Regression          631.0  3.955  6.062 -1.528
Linear Regression         631.0  4.329  7.537 -2.969
Training median baseline  631.0  5.848  7.247 -3.399

===== PERFORMANCE BY TEMPORAL FOLD =====
 fold                    model     n    MAE   RMSE    Bias
16-24                  XGBoost 166.0  3.831  5.938  -3.691
16-24 Training median baseline 166.0  3.958  6.010  -3.641
16-24            Random Forest 166.0  4.334  5.620  -1.789
16-24        Linear Regression 166.0  4.851  8.605  -4.742
16-24         Ridge Regression 166.0  5.451  7.331  -0.833
25-32            Random Forest 133.0  3.436  4.810   0.026
25-32         Ridge Regression 133.0  4.265  5.888  -1.703
25-32                  XGBoost 133.0  4.267  5.842  -0.135
25-32        Linear Regression 133.0  5.091  6.729  -2.202
25-32 Training median baseline 133.0 10.004 10.693 -10.004
33-40                  XGBoost 127.0  2.735  3.655   2.392
33-40            Random Forest 127.0  3.165  4.132   2.866
33-40         Ridge Regression 127.0  4.713  8.104  -2.830
33-40        Linear Regression 127.0  6.018 11.164  -4.345
33-40 Training median baseline 127.0  7.708  8.484  -7.214
41-46         Ridge Regression 108.0  2.765  3.095  -1.191
41-46        Linear Regression 108.0  3.268  3.614  -1.153
41-46                  XGBoost 108.0  3.647  3.935   3.647
41-46            Random Forest 108.0  3.719  3.840   3.719
41-46 Training median baseline 108.0  4.100  4.175   4.100
47-52            Random Forest  97.0  0.669  1.210  -0.203
47-52                  XGBoost  97.0  0.707  1.213  -0.396
47-52         Ridge Regression  97.0  1.303  1.696  -1.151
47-52        Linear Regression  97.0  1.359  1.739  -1.205
47-52 Training median baseline  97.0  2.892  3.063   2.718

===== PERFORMANCE BY COMPOUND =====
                   model     compound     n   MAE   RMSE   Bias
                 XGBoost         HARD  27.0 2.418  3.393  1.260
           Random Forest         HARD  27.0 2.788  3.765  1.628
        Ridge Regression         HARD  27.0 3.798  5.781 -3.610
Training median baseline         HARD  27.0 4.400  4.586  3.250
       Linear Regression         HARD  27.0 4.676  7.618 -4.322
        Ridge Regression INTERMEDIATE 211.0 2.281  2.902  0.483
       Linear Regression INTERMEDIATE 211.0 2.749  3.734  0.085
           Random Forest INTERMEDIATE 211.0 3.026  4.008  1.533
                 XGBoost INTERMEDIATE 211.0 3.096  4.414  1.184
Training median baseline INTERMEDIATE 211.0 9.762 10.129 -9.762
                 XGBoost       MEDIUM 258.0 3.565  5.470 -1.985
           Random Forest       MEDIUM 258.0 3.707  5.096 -0.757
Training median baseline       MEDIUM 258.0 4.222  6.024 -2.040
       Linear Regression       MEDIUM 258.0 5.229  8.602 -4.750
        Ridge Regression       MEDIUM 258.0 5.354  7.360 -2.068
           Random Forest         SOFT 135.0 2.776  3.601  2.077
                 XGBoost         SOFT 135.0 2.777  3.613  1.904
Training median baseline         SOFT 135.0 3.125  3.399  2.619
        Ridge Regression         SOFT 135.0 3.929  6.954 -3.225
       Linear Regression         SOFT 135.0 5.009  9.526 -4.066

===== PERFORMANCE BY RAINFALL FLAG =====
                   model weather_regime     n   MAE  RMSE   Bias
                 XGBoost        No rain 256.0 2.199 2.901  0.852
           Random Forest        No rain 256.0 2.316 3.103  1.069
Training median baseline        No rain 256.0 3.029 3.309  2.027
        Ridge Regression        No rain 256.0 3.189 5.926 -3.112
       Linear Regression        No rain 256.0 4.075 8.095 -4.011
                 XGBoost           Rain 375.0 3.868 5.598 -0.505
           Random Forest           Rain 375.0 3.872 5.101  0.476
        Ridge Regression           Rain 375.0 4.478 6.152 -0.448
       Linear Regression           Rain 375.0 4.502 7.131 -2.257
Training median baseline           Rain 375.0 7.772 8.994 -7.103

Saved rolling temporal backtest outputs to: ..\data\processed\9558

In [ ]:

# ============================================================
# CELL 8: ERROR BREAKDOWN BY FOLD x WEATHER x COMPOUND
# ============================================================

pred = rolling_predictions.copy()

pred["weather_regime"] = np.where(
    pd.to_numeric(pred["rainfall"], errors="coerce").fillna(0) > 0,
    "Rain",
    "No rain"
)

pred["error"] = pred["predicted"] - pred["actual"]
pred["abs_error"] = pred["error"].abs()
pred["squared_error"] = pred["error"] ** 2

# Combined breakdown
combined = (
    pred.groupby(["fold", "model", "weather_regime", "compound"])
    .agg(
        n=("error", "size"),
        MAE=("abs_error", "mean"),
        RMSE=("squared_error", lambda s: np.sqrt(s.mean())),
        Bias=("error", "mean"),
    )
    .reset_index()
)

print("===== FOLD x WEATHER x COMPOUND =====")
print(
    combined.sort_values(
        ["fold", "weather_regime", "compound", "MAE"]
    ).round(3).to_string(index=False)
)

# Focus on XGBoost and Random Forest for a readable comparison
tree_models = combined[
    combined["model"].isin(["XGBoost", "Random Forest"])
].copy()

print("\n===== TREE MODELS: RAIN PERFORMANCE BY FOLD =====")
rain_table = tree_models[
    tree_models["weather_regime"] == "Rain"
].sort_values(["fold", "compound", "MAE"])

print(rain_table.round(3).to_string(index=False))

print("\n===== TREE MODELS: NO-RAIN PERFORMANCE BY FOLD =====")
dry_table = tree_models[
    tree_models["weather_regime"] == "No rain"
].sort_values(["fold", "compound", "MAE"])

print(dry_table.round(3).to_string(index=False))

# Identify combinations with enough samples to interpret cautiously
print("\n===== COMBINATIONS WITH AT LEAST 10 PREDICTIONS =====")
print(
    combined[combined["n"] >= 10]
    .sort_values(["MAE"])
    .round(3)
    .to_string(index=False)
)

combined.to_csv(
    DATA_DIR / "rolling_temporal_weather_compound_results.csv",
    index=False
)

print("\nSaved:", DATA_DIR / "rolling_temporal_weather_compound_results.csv")

===== FOLD x WEATHER x COMPOUND =====
 fold                    model weather_regime     compound   n    MAE   RMSE    Bias
16-24         Ridge Regression        No rain         HARD   3  1.394  1.490  -1.394
16-24                  XGBoost        No rain         HARD   3  2.114  2.161  -2.114
16-24 Training median baseline        No rain         HARD   3  2.118  2.169  -2.118
16-24            Random Forest        No rain         HARD   3  2.182  2.230  -2.182
16-24        Linear Regression        No rain         HARD   3  2.209  2.252  -2.209
16-24         Ridge Regression        No rain       MEDIUM  50  1.417  1.865  -1.379
16-24 Training median baseline        No rain       MEDIUM  50  1.965  2.285  -1.807
16-24        Linear Regression        No rain       MEDIUM  50  2.070  2.471  -2.068
16-24            Random Forest        No rain       MEDIUM  50  2.094  2.465  -2.094
16-24                  XGBoost        No rain       MEDIUM  50  2.130  2.483  -2.130
16-24         Ridge Regression        No rain         SOFT   2  2.722  2.746  -2.722
16-24            Random Forest        No rain         SOFT   2  3.041  3.245  -3.041
16-24                  XGBoost        No rain         SOFT   2  3.059  3.285  -3.059
16-24        Linear Regression        No rain         SOFT   2  3.600  3.760  -3.600
16-24 Training median baseline        No rain         SOFT   2  4.932  5.054  -4.932
16-24            Random Forest           Rain         HARD   1  9.113  9.113  -9.113
16-24                  XGBoost           Rain         HARD   1  9.142  9.142  -9.142
16-24 Training median baseline           Rain         HARD   1  9.171  9.171  -9.171
16-24         Ridge Regression           Rain         HARD   1 14.288 14.288 -14.288
16-24        Linear Regression           Rain         HARD   1 20.984 20.984 -20.984
16-24         Ridge Regression           Rain INTERMEDIATE  13  5.473  6.210  -5.205
16-24        Linear Regression           Rain INTERMEDIATE  13  9.162 10.237  -9.085
16-24            Random Forest           Rain INTERMEDIATE  13  9.837 10.479  -9.837
16-24                  XGBoost           Rain INTERMEDIATE  13 13.124 13.624 -13.124
16-24 Training median baseline           Rain INTERMEDIATE  13 13.679 14.143 -13.679
16-24                  XGBoost           Rain       MEDIUM  95  3.434  5.569  -3.188
16-24 Training median baseline           Rain       MEDIUM  95  3.587  5.496  -3.116
16-24            Random Forest           Rain       MEDIUM  95  4.780  5.917  -0.333
16-24        Linear Regression           Rain       MEDIUM  95  5.513 10.124  -5.334
16-24         Ridge Regression           Rain       MEDIUM  95  7.597  9.081   0.415
16-24                  XGBoost           Rain         SOFT   2  5.533  5.801  -5.533
16-24            Random Forest           Rain         SOFT   2  5.543  5.781  -5.543
16-24 Training median baseline           Rain         SOFT   2  7.417  7.591  -7.417
16-24         Ridge Regression           Rain         SOFT   2  8.618  9.618  -8.618
16-24        Linear Regression           Rain         SOFT   2 12.035 14.212 -12.035
25-32         Ridge Regression           Rain INTERMEDIATE  91  2.237  2.804   1.508
25-32            Random Forest           Rain INTERMEDIATE  91  2.600  2.929   2.365
25-32        Linear Regression           Rain INTERMEDIATE  91  2.702  3.295   1.520
25-32                  XGBoost           Rain INTERMEDIATE  91  2.906  3.150   2.700
25-32 Training median baseline           Rain INTERMEDIATE  91 10.308 10.479 -10.308
25-32            Random Forest           Rain       MEDIUM  42  5.247  7.395  -5.042
25-32                  XGBoost           Rain       MEDIUM  42  7.217  9.304  -6.276
25-32         Ridge Regression           Rain       MEDIUM  42  8.660  9.630  -8.660
25-32 Training median baseline           Rain       MEDIUM  42  9.346 11.142  -9.346
25-32        Linear Regression           Rain       MEDIUM  42 10.266 10.948 -10.266
33-40 Training median baseline        No rain         HARD   1  3.534  3.534   3.534
33-40                  XGBoost        No rain         HARD   1  7.609  7.609   7.609
33-40            Random Forest        No rain         HARD   1 10.108 10.108  10.108
33-40         Ridge Regression        No rain         HARD   1 20.537 20.537 -20.537
33-40        Linear Regression        No rain         HARD   1 28.075 28.075 -28.075
33-40         Ridge Regression        No rain INTERMEDIATE   1  2.519  2.519  -2.519
33-40                  XGBoost        No rain INTERMEDIATE   1  3.044  3.044   3.044
33-40            Random Forest        No rain INTERMEDIATE   1  4.500  4.500   4.500
33-40        Linear Regression        No rain INTERMEDIATE   1  5.205  5.205  -5.205
33-40 Training median baseline        No rain INTERMEDIATE   1  5.850  5.850  -5.850
33-40 Training median baseline        No rain       MEDIUM   6  1.802  2.169   1.802
33-40                  XGBoost        No rain       MEDIUM   6  5.673  5.963   5.673
33-40            Random Forest        No rain       MEDIUM   6  6.135  7.026   6.135
33-40         Ridge Regression        No rain       MEDIUM   6 16.877 16.931 -16.877
33-40        Linear Regression        No rain       MEDIUM   6 24.150 24.200 -24.150
33-40 Training median baseline        No rain         SOFT  13  1.582  1.899   1.040
33-40            Random Forest        No rain         SOFT  13  6.230  6.723   6.230
33-40                  XGBoost        No rain         SOFT  13  6.726  6.963   6.726
33-40         Ridge Regression        No rain         SOFT  13 20.771 20.826 -20.771
33-40        Linear Regression        No rain         SOFT  13 28.959 29.005 -28.959
33-40         Ridge Regression           Rain INTERMEDIATE 106  1.926  2.286   0.330
33-40        Linear Regression           Rain INTERMEDIATE 106  1.978  2.306   0.027
33-40                  XGBoost           Rain INTERMEDIATE 106  2.031  2.722   1.619
33-40            Random Forest           Rain INTERMEDIATE 106  2.542  3.311   2.184
33-40 Training median baseline           Rain INTERMEDIATE 106  8.851  9.224  -8.851
41-46                  XGBoost        No rain         HARD  10  2.699  2.740   2.699
41-46            Random Forest        No rain         HARD  10  3.443  3.483   3.443
41-46 Training median baseline        No rain         HARD  10  4.827  4.839   4.827
41-46         Ridge Regression        No rain         HARD  10  4.889  4.968  -4.889
41-46        Linear Regression        No rain         HARD  10  5.332  5.395  -5.332
41-46         Ridge Regression        No rain       MEDIUM  26  2.098  2.345  -1.990
41-46        Linear Regression        No rain       MEDIUM  26  2.413  2.651  -2.357
41-46                  XGBoost        No rain       MEDIUM  26  2.855  2.975   2.855
41-46            Random Forest        No rain       MEDIUM  26  2.865  2.880   2.865
41-46 Training median baseline        No rain       MEDIUM  26  4.246  4.282   4.246
41-46         Ridge Regression        No rain         SOFT  47  2.377  2.690  -2.370
41-46        Linear Regression        No rain         SOFT  47  2.625  2.899  -2.625
41-46                  XGBoost        No rain         SOFT  47  3.023  3.099   3.023
41-46            Random Forest        No rain         SOFT  47  3.604  3.689   3.604
41-46 Training median baseline        No rain         SOFT  47  3.852  3.951   3.852
41-46         Ridge Regression           Rain         HARD   2  1.265  1.299   1.265
41-46        Linear Regression           Rain         HARD   2  2.371  2.390   2.371
41-46 Training median baseline           Rain         HARD   2  5.128  5.133   5.128
41-46            Random Forest           Rain         HARD   2  5.433  5.436   5.433
41-46                  XGBoost           Rain         HARD   2  6.304  6.304   6.304
41-46         Ridge Regression           Rain       MEDIUM  10  3.762  3.861   3.762
41-46 Training median baseline           Rain       MEDIUM  10  4.285  4.314   4.285
41-46            Random Forest           Rain       MEDIUM  10  4.682  4.690   4.682
41-46        Linear Regression           Rain       MEDIUM  10  4.919  5.000   4.919
41-46                  XGBoost           Rain       MEDIUM  10  5.922  5.947   5.922
41-46         Ridge Regression           Rain         SOFT  13  3.331  3.423   3.331
41-46 Training median baseline           Rain         SOFT  13  3.843  3.910   3.843
41-46        Linear Regression           Rain         SOFT  13  4.579  4.645   4.579
41-46            Random Forest           Rain         SOFT  13  5.053  5.092   5.053
41-46                  XGBoost           Rain         SOFT  13  6.061  6.091   6.061
47-52                  XGBoost        No rain         HARD  10  0.260  0.292   0.229
47-52            Random Forest        No rain         HARD  10  0.422  0.478   0.422
47-52         Ridge Regression        No rain         HARD  10  1.211  1.402  -1.211
47-52        Linear Regression        No rain         HARD  10  1.249  1.439  -1.244
47-52 Training median baseline        No rain         HARD  10  4.121  4.125   4.121
47-52                  XGBoost        No rain       MEDIUM  29  0.569  1.051  -0.231
47-52            Random Forest        No rain       MEDIUM  29  0.663  1.196  -0.182
47-52         Ridge Regression        No rain       MEDIUM  29  1.090  1.458  -0.862
47-52        Linear Regression        No rain       MEDIUM  29  1.165  1.521  -0.938
47-52 Training median baseline        No rain       MEDIUM  29  3.235  3.352   3.057
47-52            Random Forest        No rain         SOFT  58  0.715  1.301  -0.320
47-52                  XGBoost        No rain         SOFT  58  0.852  1.376  -0.587
47-52         Ridge Regression        No rain         SOFT  58  1.425  1.846  -1.285
47-52        Linear Regression        No rain         SOFT  58  1.475  1.882  -1.332
47-52 Training median baseline        No rain         SOFT  58  2.510  2.671   2.307

===== TREE MODELS: RAIN PERFORMANCE BY FOLD =====
 fold         model weather_regime     compound   n    MAE   RMSE    Bias
16-24 Random Forest           Rain         HARD   1  9.113  9.113  -9.113
16-24       XGBoost           Rain         HARD   1  9.142  9.142  -9.142
16-24 Random Forest           Rain INTERMEDIATE  13  9.837 10.479  -9.837
16-24       XGBoost           Rain INTERMEDIATE  13 13.124 13.624 -13.124
16-24       XGBoost           Rain       MEDIUM  95  3.434  5.569  -3.188
16-24 Random Forest           Rain       MEDIUM  95  4.780  5.917  -0.333
16-24       XGBoost           Rain         SOFT   2  5.533  5.801  -5.533
16-24 Random Forest           Rain         SOFT   2  5.543  5.781  -5.543
25-32 Random Forest           Rain INTERMEDIATE  91  2.600  2.929   2.365
25-32       XGBoost           Rain INTERMEDIATE  91  2.906  3.150   2.700
25-32 Random Forest           Rain       MEDIUM  42  5.247  7.395  -5.042
25-32       XGBoost           Rain       MEDIUM  42  7.217  9.304  -6.276
33-40       XGBoost           Rain INTERMEDIATE 106  2.031  2.722   1.619
33-40 Random Forest           Rain INTERMEDIATE 106  2.542  3.311   2.184
41-46 Random Forest           Rain         HARD   2  5.433  5.436   5.433
41-46       XGBoost           Rain         HARD   2  6.304  6.304   6.304
41-46 Random Forest           Rain       MEDIUM  10  4.682  4.690   4.682
41-46       XGBoost           Rain       MEDIUM  10  5.922  5.947   5.922
41-46 Random Forest           Rain         SOFT  13  5.053  5.092   5.053
41-46       XGBoost           Rain         SOFT  13  6.061  6.091   6.061

===== TREE MODELS: NO-RAIN PERFORMANCE BY FOLD =====
 fold         model weather_regime     compound  n    MAE   RMSE   Bias
16-24       XGBoost        No rain         HARD  3  2.114  2.161 -2.114
16-24 Random Forest        No rain         HARD  3  2.182  2.230 -2.182
16-24 Random Forest        No rain       MEDIUM 50  2.094  2.465 -2.094
16-24       XGBoost        No rain       MEDIUM 50  2.130  2.483 -2.130
16-24 Random Forest        No rain         SOFT  2  3.041  3.245 -3.041
16-24       XGBoost        No rain         SOFT  2  3.059  3.285 -3.059
33-40       XGBoost        No rain         HARD  1  7.609  7.609  7.609
33-40 Random Forest        No rain         HARD  1 10.108 10.108 10.108
33-40       XGBoost        No rain INTERMEDIATE  1  3.044  3.044  3.044
33-40 Random Forest        No rain INTERMEDIATE  1  4.500  4.500  4.500
33-40       XGBoost        No rain       MEDIUM  6  5.673  5.963  5.673
33-40 Random Forest        No rain       MEDIUM  6  6.135  7.026  6.135
33-40 Random Forest        No rain         SOFT 13  6.230  6.723  6.230
33-40       XGBoost        No rain         SOFT 13  6.726  6.963  6.726
41-46       XGBoost        No rain         HARD 10  2.699  2.740  2.699
41-46 Random Forest        No rain         HARD 10  3.443  3.483  3.443
41-46       XGBoost        No rain       MEDIUM 26  2.855  2.975  2.855
41-46 Random Forest        No rain       MEDIUM 26  2.865  2.880  2.865
41-46       XGBoost        No rain         SOFT 47  3.023  3.099  3.023
41-46 Random Forest        No rain         SOFT 47  3.604  3.689  3.604
47-52       XGBoost        No rain         HARD 10  0.260  0.292  0.229
47-52 Random Forest        No rain         HARD 10  0.422  0.478  0.422
47-52       XGBoost        No rain       MEDIUM 29  0.569  1.051 -0.231
47-52 Random Forest        No rain       MEDIUM 29  0.663  1.196 -0.182
47-52 Random Forest        No rain         SOFT 58  0.715  1.301 -0.320
47-52       XGBoost        No rain         SOFT 58  0.852  1.376 -0.587

===== COMBINATIONS WITH AT LEAST 10 PREDICTIONS =====
 fold                    model weather_regime     compound   n    MAE   RMSE    Bias
47-52                  XGBoost        No rain         HARD  10  0.260  0.292   0.229
47-52            Random Forest        No rain         HARD  10  0.422  0.478   0.422
47-52                  XGBoost        No rain       MEDIUM  29  0.569  1.051  -0.231
47-52            Random Forest        No rain       MEDIUM  29  0.663  1.196  -0.182
47-52            Random Forest        No rain         SOFT  58  0.715  1.301  -0.320
47-52                  XGBoost        No rain         SOFT  58  0.852  1.376  -0.587
47-52         Ridge Regression        No rain       MEDIUM  29  1.090  1.458  -0.862
47-52        Linear Regression        No rain       MEDIUM  29  1.165  1.521  -0.938
47-52         Ridge Regression        No rain         HARD  10  1.211  1.402  -1.211
47-52        Linear Regression        No rain         HARD  10  1.249  1.439  -1.244
16-24         Ridge Regression        No rain       MEDIUM  50  1.417  1.865  -1.379
47-52         Ridge Regression        No rain         SOFT  58  1.425  1.846  -1.285
47-52        Linear Regression        No rain         SOFT  58  1.475  1.882  -1.332
33-40 Training median baseline        No rain         SOFT  13  1.582  1.899   1.040
33-40         Ridge Regression           Rain INTERMEDIATE 106  1.926  2.286   0.330
16-24 Training median baseline        No rain       MEDIUM  50  1.965  2.285  -1.807
33-40        Linear Regression           Rain INTERMEDIATE 106  1.978  2.306   0.027
33-40                  XGBoost           Rain INTERMEDIATE 106  2.031  2.722   1.619
16-24        Linear Regression        No rain       MEDIUM  50  2.070  2.471  -2.068
16-24            Random Forest        No rain       MEDIUM  50  2.094  2.465  -2.094
41-46         Ridge Regression        No rain       MEDIUM  26  2.098  2.345  -1.990
16-24                  XGBoost        No rain       MEDIUM  50  2.130  2.483  -2.130
25-32         Ridge Regression           Rain INTERMEDIATE  91  2.237  2.804   1.508
41-46         Ridge Regression        No rain         SOFT  47  2.377  2.690  -2.370
41-46        Linear Regression        No rain       MEDIUM  26  2.413  2.651  -2.357
47-52 Training median baseline        No rain         SOFT  58  2.510  2.671   2.307
33-40            Random Forest           Rain INTERMEDIATE 106  2.542  3.311   2.184
25-32            Random Forest           Rain INTERMEDIATE  91  2.600  2.929   2.365
41-46        Linear Regression        No rain         SOFT  47  2.625  2.899  -2.625
41-46                  XGBoost        No rain         HARD  10  2.699  2.740   2.699
25-32        Linear Regression           Rain INTERMEDIATE  91  2.702  3.295   1.520
41-46                  XGBoost        No rain       MEDIUM  26  2.855  2.975   2.855
41-46            Random Forest        No rain       MEDIUM  26  2.865  2.880   2.865
25-32                  XGBoost           Rain INTERMEDIATE  91  2.906  3.150   2.700
41-46                  XGBoost        No rain         SOFT  47  3.023  3.099   3.023
47-52 Training median baseline        No rain       MEDIUM  29  3.235  3.352   3.057
41-46         Ridge Regression           Rain         SOFT  13  3.331  3.423   3.331
16-24                  XGBoost           Rain       MEDIUM  95  3.434  5.569  -3.188
41-46            Random Forest        No rain         HARD  10  3.443  3.483   3.443
16-24 Training median baseline           Rain       MEDIUM  95  3.587  5.496  -3.116
41-46            Random Forest        No rain         SOFT  47  3.604  3.689   3.604
41-46         Ridge Regression           Rain       MEDIUM  10  3.762  3.861   3.762
41-46 Training median baseline           Rain         SOFT  13  3.843  3.910   3.843
41-46 Training median baseline        No rain         SOFT  47  3.852  3.951   3.852
47-52 Training median baseline        No rain         HARD  10  4.121  4.125   4.121
41-46 Training median baseline        No rain       MEDIUM  26  4.246  4.282   4.246
41-46 Training median baseline           Rain       MEDIUM  10  4.285  4.314   4.285
41-46        Linear Regression           Rain         SOFT  13  4.579  4.645   4.579
41-46            Random Forest           Rain       MEDIUM  10  4.682  4.690   4.682
16-24            Random Forest           Rain       MEDIUM  95  4.780  5.917  -0.333
41-46 Training median baseline        No rain         HARD  10  4.827  4.839   4.827
41-46         Ridge Regression        No rain         HARD  10  4.889  4.968  -4.889
41-46        Linear Regression           Rain       MEDIUM  10  4.919  5.000   4.919
41-46            Random Forest           Rain         SOFT  13  5.053  5.092   5.053
25-32            Random Forest           Rain       MEDIUM  42  5.247  7.395  -5.042
41-46        Linear Regression        No rain         HARD  10  5.332  5.395  -5.332
16-24         Ridge Regression           Rain INTERMEDIATE  13  5.473  6.210  -5.205
16-24        Linear Regression           Rain       MEDIUM  95  5.513 10.124  -5.334
41-46                  XGBoost           Rain       MEDIUM  10  5.922  5.947   5.922
41-46                  XGBoost           Rain         SOFT  13  6.061  6.091   6.061
33-40            Random Forest        No rain         SOFT  13  6.230  6.723   6.230
33-40                  XGBoost        No rain         SOFT  13  6.726  6.963   6.726
25-32                  XGBoost           Rain       MEDIUM  42  7.217  9.304  -6.276
16-24         Ridge Regression           Rain       MEDIUM  95  7.597  9.081   0.415
25-32         Ridge Regression           Rain       MEDIUM  42  8.660  9.630  -8.660
33-40 Training median baseline           Rain INTERMEDIATE 106  8.851  9.224  -8.851
16-24        Linear Regression           Rain INTERMEDIATE  13  9.162 10.237  -9.085
25-32 Training median baseline           Rain       MEDIUM  42  9.346 11.142  -9.346
16-24            Random Forest           Rain INTERMEDIATE  13  9.837 10.479  -9.837
25-32        Linear Regression           Rain       MEDIUM  42 10.266 10.948 -10.266
25-32 Training median baseline           Rain INTERMEDIATE  91 10.308 10.479 -10.308
16-24                  XGBoost           Rain INTERMEDIATE  13 13.124 13.624 -13.124
16-24 Training median baseline           Rain INTERMEDIATE  13 13.679 14.143 -13.679
33-40         Ridge Regression        No rain         SOFT  13 20.771 20.826 -20.771